### ISSUE TITLE
Can't install nativescript-cli on Windows 8.1

### ISSUE THREAD

**Issue by dajk** [NativeScript/nativescript-cli#1051]
```
C:\Users\Radovan\Desktop>npm i -g nativescript
npm WARN excluding symbolic link docs\stylesheets\hightlight.css -> ../../node_m
odules/highlight.js/src/styles/solarized_light.css
-


> bufferutil@1.0.1 install C:\Users\Radovan\AppData\Roaming\npm\node_modules\nat
ivescript\node_modules\bufferutil
> node ./build.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\Radovan\Desktop\build.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
\


> utf-8-validate@1.0.1 install C:\Users\Radovan\AppData\Roaming\npm\node_modules
\nativescript\node_modules\utf-8-validate
> node ./build.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\Radovan\Desktop\build.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm WARN excluding symbolic link docs\assets\ir_black.css -> ../../node_modules/
highlight.js/src/styles/ir_black.css
npm WARN excluding symbolic link docs\stylesheets\hightlight.css -> ../../node_m
odules/highlight.js/src/styles/solarized_light.css
npm WARN excluding symbolic link docs\stylesheets\hightlight.css -> ../../node_m
odules/highlight.js/src/styles/solarized_light.css
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {
"node":"0.12.6","npm":"2.11.2"})
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework
\Resources -> Versions/Current/Resources
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework
\Test Framework -> Versions/Current/Test Framework
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework
\Versions\Current -> A
-


> ref@0.3.5 install C:\Users\Radovan\AppData\Roaming\npm\node_modules\nativescri
pt\node_modules\ref
> node ./build.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\Radovan\Desktop\build.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
\


> fibers@1.0.6 install C:\Users\Radovan\AppData\Roaming\npm\node_modules\natives
cript\node_modules\fibers
> node build.js || nodejs build.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\Radovan\Desktop\build.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
npm WARN excluding symbolic link docs\assets\ir_black.css -> ../../node_modules/
highlight.js/src/styles/ir_black.css
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework
\Resources -> Versions/Current/Resources
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework
\Test Framework -> Versions/Current/Test Framework
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework
\Versions\Current -> A
npm WARN excluding symbolic link docs\stylesheets\hightlight.css -> ../../node_m
odules/highlight.js/src/styles/solarized_light.css
-


> ws@0.4.32 install C:\Users\Radovan\AppData\Roaming\npm\node_modules\nativescri
pt\node_modules\node-inspector\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

\
C:\Users\Radovan\Desktop>if not defined npm_config_node_gyp (node "C:\Program Fi
les\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\no
de-gyp.js" rebuild )  else (node  rebuild )
npm WARN excluding symbolic link docs\stylesheets\hightlight.css -> ../../node_m
odules/highlight.js/src/styles/solarized_light.css
npm WARN excluding symbolic link docs\stylesheets\hightlight.css -> ../../node_m
odules/highlight.js/src/styles/solarized_light.css
|
> ref@1.1.0 install C:\Users\Radovan\AppData\Roaming\npm\node_modules\nativescri
pt\node_modules\ios-sim-portable\node_modules\NodObjC\node_modules\ref
> node ./build.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\Radovan\Desktop\build.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

> ffi@1.2.7 install C:\Users\Radovan\AppData\Roaming\npm\node_modules\nativescri
pt\node_modules\ffi
> node ./build.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\Radovan\Desktop\build.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm WARN excluding symbolic link docs\stylesheets\hightlight.css -> ../../node_m
odules/highlight.js/src/styles/solarized_light.css
/
> ffi@1.3.2 install C:\Users\Radovan\AppData\Roaming\npm\node_modules\nativescri
pt\node_modules\ios-sim-portable\node_modules\NodObjC\node_modules\ffi
> node ./build.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\Radovan\Desktop\build.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "nativescript"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! bufferutil@1.0.1 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@1.0.1 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

> nativescript@1.4.1 preuninstall C:\Users\Radovan\AppData\Roaming\npm\node_modu
les\nativescript
> node preuninstall.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\Radovan\Desktop\preuninstall.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm WARN continuing anyway nativescript@1.4.1 preuninstall: `node preuninstall.j
s`
npm WARN continuing anyway Exit status 1

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Radovan\Desktop\npm-debug.log
```

Any solution how to fix it?

**Comment by rosen-vladimirov** [comment]
Hi @dajk 
I'm not sure what could cause such behavior. It looks like nodejs is confused about your working directory and searches the files on incorrect place. May I ask you to try installing nodejs 0.12.7 - you can find the installers [here](https://nodejs.org/en/blog/release/v0.12.7/)
After that please try `npm i -g nativescript`
If this doesn't help, can you try installing node-gyp: `npm i -g node-gyp` and install nativescript after that.

Hope this helps. I'm looking forward to hearing from you.

**Comment by dajk** [comment]
Hello @rosen-vladimirov 
Thank you for your response. Yes, looks strange..I checked nodejs' path but it's correct. I think that I tried almost everything but nothing helps :) I had that version of nodejs and I uninstalled, clear cache and install again older one, I also tried to install older node-gyp@2.0.0, but the same.

These are current versions: 
```
C:\Users\Radovan\Desktop>node -v
v0.12.7
C:\Users\Radovan\Desktop>npm -v
2.11.3
C:\Users\Radovan\Desktop>node-gyp -v
v3.0.3
```

And this is the builderror:
```
gyp: binding.gyp not found (cwd: C:\Users\Radovan\Desktop) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Radovan\Desktop
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
```

**Comment by rosen-vladimirov** [comment]
Hi @dajk ,
Have you tried removing .node-gyp folder. It should be under:
```
C:\Users\<USERNAME>\.node-gyp\
```
It definitely looks like something's wrong with node and/or node-gyp as the working directory is incorrect.
I'll try to find some more info on this case, but meanwhile could you try deleting the `.node-gyp` directory and try again.
I'm looking forward to hearing from you.

**Comment by dajk** [comment]
Hi @rosen-vladimirov 
I removed `.node-gyp` and  after that `npm i -g nativescript` but nothing happened, the same error.

**Comment by gabrielbiga** [comment]
I'm having the same problem in Windows 10.

**Comment by rosen-vladimirov** [comment]
Hi @gabrielbiga , what is the output of the following commands:
```
$ node --version
$ npm --version
```
Also can you send us the installation log (the same that @dajk  had sent)

**Comment by ligaz** [comment]
Hey @dajk and @gabrielbiga,

I'm going to close this issue. Please feel free to reopen it and provide the requested information. Thanks.
