### ISSUE TITLE
Steps required for nativescript mac install?

### ISSUE THREAD

**Issue by cleechtech** [NativeScript/nativescript-cli#1064]
I am trying to install nativescript-cli but get an error about not having android installed. I ran `tns doctor` as suggested in the readme and got similar output to the error below.

```
$ npm install nativescript -g
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
npm WARN excluding symbolic link docs/assets/ir_black.css -> ../../node_modules/highlight.js/src/styles/ir_black.css
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Resources -> Versions/Current/Resources
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Test Framework -> Versions/Current/Test Framework
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Versions/Current -> A
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.2.1","npm":"3.3.6"})
/usr/local/bin/tns -> /usr/local/lib/node_modules/nativescript/bin/nativescript.js
/usr/local/bin/nativescript -> /usr/local/lib/node_modules/nativescript/bin/nativescript.js

> nativescript@1.4.1 postinstall /usr/local/lib/node_modules/nativescript
> node postinstall.js

WARNING: adb from the Android SDK is not installed or is not configured properly.
For Android-related operations, the NativeScript CLI will use a built-in version of adb.
To avoid possible issues with the native Android emulator, Genymotion or connected
Android devices, verify that you have installed the latest Android SDK and
its dependencies as described in http://developer.android.com/sdk/index.html#Requirements

TIP: To avoid setting up the necessary environment variables, you can use the Homebrew package manager to install the Android SDK and its dependencies.

WARNING: The Android SDK is not installed or is not configured properly.
You will not be able to build your projects for Android and run them in the native emulator.
To be able to build for Android and run apps in the native emulator, verify that you have
installed the latest Android SDK and its dependencies as described in http://developer.android.com/sdk/index.html#Requirements

TIP: To avoid setting up the necessary environment variables, you can use the Homebrew package manager to install the Android SDK and its dependencies.

WARNING: Gradle is not installed or is not configured properly.
You will not be able to build your projects for Android or run them in the emulator or on a connected device.
To be able to build for Android and run apps in the emulator or on a connected device, verify that you have installed Gradle.
WARNING: CocoaPod is not installed or is not configured properly.
You will not be able to build your projects for iOS if they contain plugin with CocoaPod file.
To be able to build such projects, verify that you have installed CocoaPod.
Command failed: /bin/sh -c android list targets
/bin/sh: android: command not found

Error: Unknown command 'dev-post-install'. Try '$ tns help' for a full list of supported commands.
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:7:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:6:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
/usr/local/lib
└── nativescript@1.4.1 
```

What more do I need to do on OSX 10.11 to get nativescript-cli working? Where are those instructions?

**Comment by teobugslayer** [comment]
Hi,

the setup guide is [here](http://docs.nativescript.org/setup/ns-cli-setup/ns-setup-os-x). A known issue is that NativeScript CLI does not support XCode 7 iOS Simulator, which we will fix in an upcoming release. Otherwise, I am using it on El Capitan at the moment without issues.

**Comment by teobugslayer** [comment]
I am closing this issue for now. If you need more help, feel free to reopen it.

**Comment by cleechtech** [comment]
Ok rad. Thanks for support, great project

**Comment by 5hay** [comment]
So I can't build iOS apps with XCode 7 right now?

**Comment by ligaz** [comment]
Just the opposite you can safely use Xcode 7 and El Capitan to build NativeScript apps. There is a corner case (that probably will not bite you) when the Xcode 7 iOS Simulator might not work correctly. We hope to address this next week.

**Comment by aditiphadnis** [comment]
I am facing the same issue. WARNING: Xcode is not installed or is not configured properly.
Can anyone tell me how to resolve it?

**Comment by vikasgupta-iphone** [comment]
Xcode 8.2 continuously getting "WARNING: Xcode is not installed or is not configured properly. "

**Comment by Delivrator** [comment]
Same problem here :( (xcode 8.2)

**Comment by thowerton** [comment]
Same issue here with Xcode 8.2.1

**Comment by Delivrator** [comment]
Indeed, i have this error, but your fix doesn't work :(
I'll try to fix this by an other way.

**Comment by tolerious** [comment]
@thowerton   your   answer is really help me,  thank you.

**Comment by tolerious** [comment]
but the  `WARNING: CocoaPods is not installed or is not configured properly.` . warning still there.
