### ISSUE TITLE
[Unit Testing] Console lists my failing tests and shows their "describe" text but does not list my passing tests

### ISSUE THREAD

**Issue by ikoevska** [NativeScript/nativescript-cli#1127]
This is the output of my unit tests when both fail:
```
NativeScript / 21 (5.0; Google Nexus 9 - 5.0.0 - API 21 - 2048x1536) My Suite: Check convert FAILED
	TypeError: Convert is not a function
	    at Object.<anonymous> (/data/data/org.nativescript.jasmine/files/app/tests/example.js:10:12)
	    at attemptSync (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1789:24)
	    at QueueRunner.run (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1777:9)
	    at QueueRunner.execute (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1762:10)
	    at Spec.Env.queueRunnerFactory (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:627:35)
	    at Spec.execute (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:353:10)
	    at Object.fn (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:2360:37)
	    at attemptAsync (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1819:24)
	    at QueueRunner.run (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1774:9)
	    at QueueRunner.execute (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1762:10)
NativeScript / 21 (5.0; Google Nexus 9 - 5.0.0 - API 21 - 2048x1536) My Suite: Check counter FAILED
	TypeError: Cannot read property 'HelloWorldModel' of undefined
	    at Object.<anonymous> (/data/data/org.nativescript.jasmine/files/app/tests/example.js:14:39)
	    at attemptSync (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1789:24)
	    at QueueRunner.run (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1777:9)
	    at QueueRunner.execute (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1762:10)
	    at Spec.Env.queueRunnerFactory (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:627:35)
	    at Spec.execute (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:353:10)
	    at Object.fn (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:2360:37)
	    at attemptAsync (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1819:24)
	    at QueueRunner.run (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1774:9)
	    at eval (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1801:16)
NativeScript / 21 (5.0; Google Nexus 9 - 5.0.0 - API 21 - 2048x1536): Executed 2 of 2 (2 FAILED) ERROR (0.03 secs / 0.005 secs)
```

This is the output for my tests when both succeed:
```
30 10 2015 16:06:38.183:INFO [NativeScript / 21 (5.0; Google Nexus 9 - 5.0.0 - API 21 - 2048x1536)]: Connected on socket Szt0fzKkE2n_yQslAAAA with id NativeScriptUnit-9999
NativeScript / 21 (5.0; Google Nexus 9 - 5.0.0 - API 21 - 2048x1536): Executed 2 of 2 SUCCESS (0.023 secs / 0.005 secs)
```

And this is the output when one passes and one fails:
```
30 10 2015 16:06:06.827:INFO [NativeScript / 21 (5.0; Google Nexus 9 - 5.0.0 - API 21 - 2048x1536)]: Connected on socket RxDUkFZZ-LtsLMjlAAAA with id NativeScriptUnit-4687
NativeScript / 21 (5.0; Google Nexus 9 - 5.0.0 - API 21 - 2048x1536) A suite is just a function Check counter FAILED
	TypeError: Cannot read property 'HelloWorldModel' of undefined
	    at Object.<anonymous> (/data/data/org.nativescript.jasmine/files/app/tests/example.js:14:55)
	    at attemptSync (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1789:24)
	    at QueueRunner.run (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1777:9)
	    at QueueRunner.execute (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1762:10)
	    at Spec.Env.queueRunnerFactory (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:627:35)
	    at Spec.execute (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:353:10)
	    at Object.fn (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:2360:37)
	    at attemptAsync (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1819:24)
	    at QueueRunner.run (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1774:9)
	    at eval (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1801:16)
NativeScript / 21 (5.0; Google Nexus 9 - 5.0.0 - API 21 - 2048x1536): Executed 2 of 2 (1 FAILED) (0.037 secs / 0.008 secs)
```

Ultimately, the console should say which test fail and which succeeded, not just the failing tests. The output should be something like:
```
NativeScript / 21 (5.0; Google Nexus 9 - 5.0.0 - API 21 - 2048x1536) A suite is just a function Check counter FAILED
NativeScript / 21 (5.0; Google Nexus 9 - 5.0.0 - API 21 - 2048x1536) A suite is just a function Check convert SUCCESS
NativeScript / 21 (5.0; Google Nexus 9 - 5.0.0 - API 21 - 2048x1536): Executed 2 of 2 (1 FAILED)
```

**Comment by tailsu** [comment]
Suppose you have 500 tests in your project and you do a change that makes one of them to fail. The failure details will drown in the avalanche of success messages, yesno?

Anyway, the test run report format can be configured by changing the `reporters` property in the `karma.conf.js`. We currently use the karma default reporter. We can always change the default to something else. Suggestions?

**Comment by dtopuzov** [comment]
Changing reporters is fine :+1:
