### ISSUE TITLE
Unable to install nativescript cli

### ISSUE THREAD

**Issue by sharath28** [NativeScript/nativescript-cli#1175]
I am not able to install {N}.
android and adb are installed and are in the path. 
This is the output of the npm install command.
```
sharath@sharath-Lenovo-G50-80:~$ sudo npm install nativescript -g --unsafe-perm 
-
> nativescript@1.4.3 preuninstall /home/sharath/npm-global/lib/node_modules/nativescript
> node preuninstall.js

Trying to kill adb server. Some running Android related operations may fail.
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
npm WARN excluding symbolic link docs/assets/ir_black.css -> ../../node_modules/highlight.js/src/styles/ir_black.css
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Resources -> Versions/Current/Resources
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Test Framework -> Versions/Current/Test Framework
 
> bufferutil@1.0.1 install /home/sharath/npm-global/lib/node_modules/nativescript/node_modules/bufferutil
> node ./build.js

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/sharath/npm-global/lib/node_modules/nativescript/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory `/home/sharath/npm-global/lib/node_modules/nativescript/node_modules/bufferutil/build'
Installed in `/home/sharath/npm-global/lib/node_modules/nativescript/node_modules/bufferutil/bin/linux-x64-v8-3.28/bufferutil.node`
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Versions/Current -> A
npm WARN excluding symbolic link docs/assets/ir_black.css -> ../../node_modules/highlight.js/src/styles/ir_black.css
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Resources -> Versions/Current/Resources
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Test Framework -> Versions/Current/Test Framework
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Versions/Current -> A
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css

> utf-8-validate@1.0.1 install /home/sharath/npm-global/lib/node_modules/nativescript/node_modules/utf-8-validate
> node ./build.js

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/sharath/npm-global/lib/node_modules/nativescript/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory `/home/sharath/npm-global/lib/node_modules/nativescript/node_modules/utf-8-validate/build'
Installed in `/home/sharath/npm-global/lib/node_modules/nativescript/node_modules/utf-8-validate/bin/linux-x64-v8-3.28/validation.node`

> fibers@1.0.6 install /home/sharath/npm-global/lib/node_modules/nativescript/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-v8-3.28` exists; testing
Binary is fine; exiting

> ref@1.1.3 install /home/sharath/npm-global/lib/node_modules/nativescript/node_modules/ref
> node ./build.js

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/sharath/npm-global/lib/node_modules/nativescript/node_modules/ref/build'
  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
make: Leaving directory `/home/sharath/npm-global/lib/node_modules/nativescript/node_modules/ref/build'
Installed in `/home/sharath/npm-global/lib/node_modules/nativescript/node_modules/ref/bin/linux-x64-v8-3.28/binding.node`

> ffi@2.0.0 install /home/sharath/npm-global/lib/node_modules/nativescript/node_modules/ffi
> node ./build.js

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/sharath/npm-global/lib/node_modules/nativescript/node_modules/ffi/build'
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
../deps/libffi/src/closures.c: In function ‘dlmmap_locked’:
../deps/libffi/src/closures.c:421:17: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
       ftruncate (execfd, offset);
                 ^
../deps/libffi/src/closures.c:433:17: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
       ftruncate (execfd, offset);
                 ^
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
../deps/libffi/src/x86/ffi64.c: In function ‘classify_argument’:
../deps/libffi/src/x86/ffi64.c:181:18: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
    FFI_ASSERT (0);
                  ^
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/unix64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/sysv.o
  AR(target) Release/obj.target/deps/libffi/libffi.a
  COPY Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
  CXX(target) Release/obj.target/ffi_bindings/src/callback_info.o
  CXX(target) Release/obj.target/ffi_bindings/src/threaded_callback_invokation.o
  SOLINK_MODULE(target) Release/obj.target/ffi_bindings.node
  COPY Release/ffi_bindings.node
make: Leaving directory `/home/sharath/npm-global/lib/node_modules/nativescript/node_modules/ffi/build'
Installed in `/home/sharath/npm-global/lib/node_modules/nativescript/node_modules/ffi/bin/linux-x64-v8-3.28/ffi_bindings.node`

> ws@0.4.32 install /home/sharath/npm-global/lib/node_modules/nativescript/node_modules/node-inspector/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

/home/sharath/npm-global/bin/tns -> /home/sharath/npm-global/lib/node_modules/nativescript/bin/nativescript.js
/home/sharath/npm-global/bin/nativescript -> /home/sharath/npm-global/lib/node_modules/nativescript/bin/nativescript.js

> nativescript@1.4.3 postinstall /home/sharath/npm-global/lib/node_modules/nativescript
> node postinstall.js

WARNING: adb from the Android SDK is not installed or is not configured properly.
For Android-related operations, the NativeScript CLI will use a built-in version of adb.
To avoid possible issues with the native Android emulator, Genymotion or connected
Android devices, verify that you have installed the latest Android SDK and
its dependencies as described in http://developer.android.com/sdk/index.html#Requirements

WARNING: The Android SDK is not installed or is not configured properly.
You will not be able to build your projects for Android and run them in the native emulator.
To be able to build for Android and run apps in the native emulator, verify that you have
installed the latest Android SDK and its dependencies as described in http://developer.android.com/sdk/index.html#Requirements

WARNING: You can work with iOS only on Mac OS X systems.
To be able to work with iOS devices and projects, you need Mac OS X Mavericks or later.

WARNING: CocoaPod is not installed or is not configured properly.
You will not be able to build your projects for iOS if they contain plugin with CocoaPod file.
To be able to build such projects, verify that you have installed CocoaPod.
Command failed: /bin/sh -c android list targets
/bin/sh: 1: android: not found

Error: Unknown command 'dev-post-install'. Try '$ tns help' for a full list of supported commands.
    at Object.<anonymous> (/home/sharath/npm-global/lib/node_modules/nativescript/lib/common/errors.js:7:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/sharath/npm-global/lib/node_modules/nativescript/lib/nativescript-cli.js:6:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
nativescript@1.4.3 /home/sharath/npm-global/lib/node_modules/nativescript
├── bufferpack@0.0.6
├── mute-stream@0.0.5
├── winreg@0.0.12
├── open@0.0.5
├── properties-parser@0.2.3
├── lockfile@1.0.1
├── tabtab@0.0.3
├── bplist-parser@0.1.0
├── colors@1.1.2
├── xmldom@0.1.19
├── node-uuid@1.4.3
├── xmlhttprequest@1.5.1
├── filesize@3.1.2
├── marked@0.3.3
├── semver@5.0.1
├── osenv@0.1.3 (os-homedir@1.0.1, os-tmpdir@1.0.1)
├── temp@0.8.3 (os-tmpdir@1.0.1, rimraf@2.2.8)
├── shelljs@0.5.1
├── mkdirp@0.5.1 (minimist@0.0.8)
├── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── ws@0.7.1 (options@0.0.6, ultron@1.0.2)
├── minimatch@2.0.10 (brace-expansion@1.1.1)
├── iconv-lite@0.4.11
├── through2@2.0.0 (xtend@4.0.1, readable-stream@2.0.4)
├── vinyl-filter-since@2.0.2 (readable-stream@2.0.4)
├── rimraf@2.4.2 (glob@5.0.15)
├── progress-stream@1.1.1 (single-line-log@0.3.1, speedometer@0.1.4, through2@0.2.3)
├── bluebird@2.9.34
├── inquirer@0.9.0 (strip-ansi@3.0.0, ansi-regex@2.0.0, figures@1.4.0, cli-width@1.1.0, through@2.3.8, run-async@0.1.0, readline2@0.1.1, rx-lite@2.5.2)
├── yargs@3.15.0 (decamelize@1.1.1, camelcase@1.2.1, window-size@0.1.2, cliui@2.1.0)
├── gaze@0.5.1 (globule@0.1.0)
├── xcode@0.8.0 (node-uuid@1.3.3, pegjs@0.6.2)
├── prompt@0.2.12 (read@1.0.7, revalidator@0.1.8, pkginfo@0.3.1, utile@0.2.1, winston@0.6.2)
├── byline@4.2.1
├── gulp@3.9.0 (interpret@0.6.6, pretty-hrtime@1.0.1, deprecated@0.0.1, archy@1.0.0, tildify@1.1.2, minimist@1.2.0, v8flags@2.0.10, semver@4.3.6, orchestrator@0.3.7, vinyl-fs@0.3.14, liftoff@2.2.0, gulp-util@3.0.7)
├── marked-terminal@1.5.0 (node-emoji@0.1.0, lodash.assign@3.2.0, cardinal@0.5.0)
├── ref-struct@1.0.2 (debug@2.2.0)
├── lodash@3.10.0
├── cli-table@0.3.1 (colors@1.0.3, wcwidth@1.0.0, lodash@3.6.0)
├── broccoli@0.16.4 (broccoli-slow-trees@1.1.0, copy-dereference@1.0.0, promise-map-series@0.2.2, mime@1.3.4, commander@2.9.0, broccoli-kitchen-sink-helpers@0.2.9, rsvp@3.1.0, findup-sync@0.2.1, connect@3.4.0, quick-temp@0.1.3, handlebars@3.0.3)
├── plistlib@0.2.1 (node-xml@1.0.2, xml@0.0.12, underscore@1.5.2, async@0.2.10, moment@2.4.0)
├── broccoli-funnel@0.2.3 (walk-sync@0.1.3, symlink-or-copy@1.0.1, broccoli-read-compat@0.1.3, core-object@0.0.2)
├── plist@1.1.0 (util-deprecate@1.0.0, base64-js@0.0.6, xmlbuilder@2.2.1)
├── xmlmerge-js@0.2.4 (pretty-data@0.40.0, heyutils@0.5.12)
├── log4js@0.6.26 (async@0.2.10, underscore@1.8.2, semver@4.3.6, readable-stream@1.0.33)
├── npm@2.6.1
├── ios-sim-portable@1.0.9-beta (colors@0.6.2, yargs@1.2.2, lodash@3.2.0, nodobjc@2.0.0)
├── bufferutil@1.0.1 (prebuilt@0.1.0, bindings@1.2.1, nan@2.1.0)
├── utf-8-validate@1.0.1 (prebuilt@0.1.0, bindings@1.2.1, nan@2.1.0)
├── fibers@1.0.6
├── ref@1.1.3 (bindings@1.2.1, prebuilt@0.1.0, debug@2.2.0, nan@2.1.0)
├── ffi@2.0.0 (bindings@1.2.1, prebuilt@0.1.0, debug@2.2.0, nan@2.1.0)
└── node-inspector@0.7.4 (opener@1.3.0, debug@0.8.1, which@1.0.9, async@0.8.0, yargs@1.2.6, rc@0.3.5, strong-data-uri@0.1.1, glob@3.2.11, express@4.0.0, ws@0.4.32)
```

**Comment by rosen-vladimirov** [comment]
Hi @sharath28 ,
NativeScript CLI is installed on your machine, only the post-install script had failed, but you should be able to use NativeScriptCLI without issues. However I've noticed some warnings, which could be caused by some incorrect configuration on your machine. Have you set **ANDROID_HOME** environment variable?
Can you send us the output of the following commands:
1) `adb -h`
2) `android --help`
3) `tns doctor --log trace`

**Comment by sharath28** [comment]
Hi @rosen-vladimirov 
ya the $ANDROID_HOME variable is set.
But when I run the tns command I am getting an tns command no found error.
I think there is some issue with the installation itself.
```sharath@sharath-Lenovo-G50-80:~$ adb -h
Android Debug Bridge version 1.0.32
Revision eac51f2bb6a8-android

 -a                            - directs adb to listen on all interfaces for a connection
 -d                            - directs command to the only connected USB device
                                 returns an error if more than one USB device is present.
 -e                            - directs command to the only running emulator.
                                 returns an error if more than one emulator is running.
 -s <specific device>          - directs command to the device or emulator with the given
                                 serial number or qualifier. Overrides ANDROID_SERIAL
                                 environment variable.
 -p <product name or path>     - simple product name like 'sooner', or
                                 a relative/absolute path to a product
                                 out directory like 'out/target/product/sooner'.
                                 If -p is not specified, the ANDROID_PRODUCT_OUT
                                 environment variable is used, which must
                                 be an absolute path.
 -H                            - Name of adb server host (default: localhost)
 -P                            - Port of adb server (default: 5037)
 devices [-l]                  - list all connected devices
                                 ('-l' will also list device qualifiers)
 connect <host>[:<port>]       - connect to a device via TCP/IP
                                 Port 5555 is used by default if no port number is specified.
 disconnect [<host>[:<port>]]  - disconnect from a TCP/IP device.
                                 Port 5555 is used by default if no port number is specified.
                                 Using this command with no additional arguments
                                 will disconnect from all connected TCP/IP devices.

device commands:
  adb push [-p] <local> <remote>
                               - copy file/dir to device
                                 ('-p' to display the transfer progress)
  adb pull [-p] [-a] <remote> [<local>]
                               - copy file/dir from device
                                 ('-p' to display the transfer progress)
                                 ('-a' means copy timestamp and mode)
  adb sync [ <directory> ]     - copy host->device only if changed
                                 (-l means list but don't copy)
                                 (see 'adb help all')
  adb shell                    - run remote shell interactively
  adb shell <command>          - run remote shell command
  adb emu <command>            - run emulator console command
  adb logcat [ <filter-spec> ] - View device log
  adb forward --list           - list all forward socket connections.
                                 the format is a list of lines with the following format:
                                    <serial> " " <local> " " <remote> "\n"
  adb forward <local> <remote> - forward socket connections
                                 forward specs are one of: 
                                   tcp:<port>
                                   localabstract:<unix domain socket name>
                                   localreserved:<unix domain socket name>
                                   localfilesystem:<unix domain socket name>
                                   dev:<character device name>
                                   jdwp:<process pid> (remote only)
  adb forward --no-rebind <local> <remote>
                               - same as 'adb forward <local> <remote>' but fails
                                 if <local> is already forwarded
  adb forward --remove <local> - remove a specific forward socket connection
  adb forward --remove-all     - remove all forward socket connections
  adb reverse --list           - list all reverse socket connections from device
  adb reverse <remote> <local> - reverse socket connections
                                 reverse specs are one of:
                                   tcp:<port>
                                   localabstract:<unix domain socket name>
                                   localreserved:<unix domain socket name>
                                   localfilesystem:<unix domain socket name>
  adb reverse --norebind <remote> <local>
                               - same as 'adb reverse <remote> <local>' but fails
                                 if <remote> is already reversed.
  adb reverse --remove <remote>
                               - remove a specific reversed socket connection
  adb reverse --remove-all     - remove all reversed socket connections from device
  adb jdwp                     - list PIDs of processes hosting a JDWP transport
  adb install [-lrtsdg] <file>
                               - push this package file to the device and install it
                                 (-l: forward lock application)
                                 (-r: replace existing application)
                                 (-t: allow test packages)
                                 (-s: install application on sdcard)
                                 (-d: allow version code downgrade)
                                 (-g: grant all runtime permissions)
  adb install-multiple [-lrtsdpg] <file...>
                               - push this package file to the device and install it
                                 (-l: forward lock application)
                                 (-r: replace existing application)
                                 (-t: allow test packages)
                                 (-s: install application on sdcard)
                                 (-d: allow version code downgrade)
                                 (-p: partial application install)
                                 (-g: grant all runtime permissions)
  adb uninstall [-k] <package> - remove this app package from the device
                                 ('-k' means keep the data and cache directories)
  adb bugreport                - return all information from the device
                                 that should be included in a bug report.

  adb backup [-f <file>] [-apk|-noapk] [-obb|-noobb] [-shared|-noshared] [-all] [-system|-nosystem] [<packages...>]
                               - write an archive of the device's data to <file>.
                                 If no -f option is supplied then the data is written
                                 to "backup.ab" in the current directory.
                                 (-apk|-noapk enable/disable backup of the .apks themselves
                                    in the archive; the default is noapk.)
                                 (-obb|-noobb enable/disable backup of any installed apk expansion
                                    (aka .obb) files associated with each application; the default
                                    is noobb.)
                                 (-shared|-noshared enable/disable backup of the device's
                                    shared storage / SD card contents; the default is noshared.)
                                 (-all means to back up all installed applications)
                                 (-system|-nosystem toggles whether -all automatically includes
                                    system applications; the default is to include system apps)
                                 (<packages...> is the list of applications to be backed up.  If
                                    the -all or -shared flags are passed, then the package
                                    list is optional.  Applications explicitly given on the
                                    command line will be included even if -nosystem would
                                    ordinarily cause them to be omitted.)

  adb restore <file>           - restore device contents from the <file> backup archive

  adb disable-verity           - disable dm-verity checking on USERDEBUG builds
  adb enable-verity            - re-enable dm-verity checking on USERDEBUG builds
  adb keygen <file>            - generate adb public/private key. The private key is stored in <file>,
                                 and the public key is stored in <file>.pub. Any existing files
                                 are overwritten.
  adb help                     - show this help message
  adb version                  - show version num

scripting:
  adb wait-for-device          - block until device is online
  adb start-server             - ensure that there is a server running
  adb kill-server              - kill the server if it is running
  adb get-state                - prints: offline | bootloader | device
  adb get-serialno             - prints: <serial-number>
  adb get-devpath              - prints: <device-path>
  adb remount                  - remounts the /system, /vendor (if present) and /oem (if present) partitions on the device read-write
  adb reboot [bootloader|recovery]
                               - reboots the device, optionally into the bootloader or recovery program.
  adb reboot sideload          - reboots the device into the sideload mode in recovery program (adb root required).
  adb reboot sideload-auto-reboot
                               - reboots into the sideload mode, then reboots automatically after the sideload regardless of the result.
  adb reboot-bootloader        - reboots the device into the bootloader
  adb root                     - restarts the adbd daemon with root permissions
  adb unroot                   - restarts the adbd daemon without root permissions
  adb usb                      - restarts the adbd daemon listening on USB
  adb tcpip <port>             - restarts the adbd daemon listening on TCP on the specified port
networking:
  adb ppp <tty> [parameters]   - Run PPP over USB.
 Note: you should not automatically start a PPP connection.
 <tty> refers to the tty for PPP stream. Eg. dev:/dev/omap_csmi_tty1
 [parameters] - Eg. defaultroute debug dump local notty usepeerdns

adb sync notes: adb sync [ <directory> ]
  <localdir> can be interpreted in several ways:

  - If <directory> is not specified, /system, /vendor (if present), /oem (if present) and /data partitions will be updated.

  - If it is "system", "vendor", "oem" or "data", only the corresponding partition
    is updated.

environmental variables:
  ADB_TRACE                    - Print debug information. A comma separated list of the following values
                                 1 or all, adb, sockets, packets, rwx, usb, sync, sysdeps, transport, jdwp
  ANDROID_SERIAL               - The serial number to connect to. -s takes priority over this if given.
  ANDROID_LOG_TAGS             - When used with the logcat option, only these debug tags are printed.
sharath@sharath-Lenovo-G50-80:~$ android --help

       Usage:
       android [global options] action [action options]
       Global options:
  -s --silent     : Silent mode, shows errors only.
  -v --verbose    : Verbose mode, shows errors, warnings and all messages.
     --clear-cache: Clear the SDK Manager repository manifest cache.
  -h --help       : Help on a specific command.

                                                                    Valid
                                                                    actions
                                                                    are
                                                                    composed
                                                                    of a verb
                                                                    and an
                                                                    optional
                                                                    direct
                                                                    object:
-    sdk              : Displays the SDK Manager window.
-    avd              : Displays the AVD Manager window.
-   list              : Lists existing targets or virtual devices.
-   list avd          : Lists existing Android Virtual Devices.
-   list target       : Lists existing targets.
-   list device       : Lists existing devices.
-   list sdk          : Lists remote SDK repository.
- create avd          : Creates a new Android Virtual Device.
-   move avd          : Moves or renames an Android Virtual Device.
- delete avd          : Deletes an Android Virtual Device.
- update avd          : Updates an Android Virtual Device to match the folders
                        of a new SDK.
- create project      : Creates a new Android project.
- update project      : Updates an Android project (must already have an
                        AndroidManifest.xml).
- create test-project : Creates a new Android project for a test package.
- update test-project : Updates the Android project for a test package (must
                        already have an AndroidManifest.xml).
- create lib-project  : Creates a new Android library project.
- update lib-project  : Updates an Android library project (must already have
                        an AndroidManifest.xml).
- create uitest-project: Creates a new UI test project.
- update adb          : Updates adb to support the USB devices declared in the
                        SDK add-ons.
- update sdk          : Updates the SDK by suggesting new platforms to install
                        if available.
sharath@sharath-Lenovo-G50-80:~$ tns doctor --log trace
No command 'tns' found, did you mean:
 Command 'tnb' from package 'pvm-examples' (universe)
 Command 'trs' from package 'konwert' (main)
 Command 'tls' from package 'python-tlslite' (universe)
 Command 'ns' from package 'ns2' (universe)
 Command 'nns' from package 'tcllib' (universe)
 Command 'tcs' from package 'tcs' (universe)
 Command 'tqs' from package 'ssake' (universe)
 Command 'ts' from package 'moreutils' (universe)
tns: command not found
```

**Comment by rosen-vladimirov** [comment]
hm, something's definitely not correct, can you try 
`sudo tns doctor --log trace`
Maybe the ownership is not correct, but let's verify it :)

**Comment by sharath28** [comment]
@rosen-vladimirov 
same

```
sharath@sharath-Lenovo-G50-80:~$ sudo tns doctor --log trace
sudo: tns: command not found
```

**Comment by teobugslayer** [comment]
Can you try `sudo npm ls -g` and post the results (perhaps as a gist)?

**Comment by sharath28** [comment]
@teobugslayer 
here is the link to the gist file
https://gist.github.com/sharath28/b228a97bf4f9bd80b159

**Comment by rosen-vladimirov** [comment]
Hi @sharath28 
It looks like nativescript is installed, but I'm not sure why you are not able to use it. Can you try installing some other package globally and see if you are able to use it, for example `rimraf`.

**Comment by rosen-vladimirov** [comment]
Hi @sharath28 
As we have not heard back from you for a week, I'm closing this issue. Feel free to contact us in case you have any problems or concerns.

**Comment by Sean-Sekora** [comment]
I'm having the same issue on os X. I've gone through the process and is works but tns doctor gives the following error

-bash: tns: command not found

**Comment by brendalynharper34** [comment]
I am currently having the same issue on my Macbook and this is driving me insane!!

-bash: tns: command not found

Any suggestions?
