### ISSUE TITLE
LiveSync watch option stops working

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#1210]
Tested with 1.5 RC.

Steps to reproduce:
- `tns livesync ios --watch` stops working when:
- create new .xml or .css file,
- delete this new file.

Output:
```
Transferring project files...
PlistService sending: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Command</key>
	<string>VendContainer</string>
	<key>Identifier</key>
	<string>org.nativescript.appGroceries</string>
</dict>
</plist>

Error: ENOENT: no such file or directory, stat '/Work/GitHub/nativescript-cli-tests/appGroceries/platforms/ios/appGroceries/app/test.xml'
    at FiberFuture.Future.wait (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:535:15)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/common/errors.js:109:33
    at Function.settle (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:534:10)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/common/services/commands-service.js:87:106
    at Function.settle (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:534:10)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/common/dispatchers.js:38:85
    at Function.settle (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:534:10)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/nativescript-cli.js:18:45
    - - - - -
    at Error (native)
Analytics statuses: 
{ TrackFeatureUsage: 0, TrackExceptions: 1 }
Trying to track feature 'CLI' with value 'help'.
List of registered commands: /?, autocomplete, autocomplete|disable, autocomplete|enable, autocomplete|status, build, build|android, build|ios, create, debug, debug|android, debug|ios, deploy, dev-post-install, dev-preuninstall, dev-test, dev-test|android, dev-test|ios, device, device|android, device|get-file, device|ios, device|list-applications, device|list-files, device|log, device|put-file, device|run, device|stop, device|uninstall, doctor, emulate, emulate|android, emulate|ios, error-reporting, help, init, install, library, library|add, livesync, platform, platform|add, platform|remove, platform|update, plugin, plugin|add, plugin|remove, prepare, run, run|android, run|ios, test, test|android, test|init, test|ios, usage-reporting
Reading help for command 'livesync'. FileName is 'livesync.md'.
# livesync
┌─────────┬───────────────────────────┐
│ Usage   │ Synopsis                  │
│ General │ $ tns livesync <Platform> │
└─────────┴───────────────────────────┘

Synchronizes the latest changes in your project to devices.

### Attributes
<Platform> is the target mobile platform to which you want to synchronize your changes. You can set the following target platforms.


    * android - Synchronizes the latest changes in your project to connected Android devices. 
    * ios - Synchronizes the latest changes in your project to connected iOS devices.

VCHIMEVMAC:nativescript-cli-tests vchimev$ 
```

**Comment by vchimev** [comment]
Tested with CLI-release build 333.

**Comment by vchimev** [comment]
Still an issue on iOS simulator.

Preconditions:
- started iOS simulator;
- app installed;

Execute:
node_modules/.bin/tns livesync ios --emulator --watch --path myGroceries --log trace

Steps to reproduce:
VCHIMEVMAC:app vchimev$ touch asdf.xml
VCHIMEVMAC:app vchimev$ rm -rf asdf.xml

```
Successfully synced application org.nativescript.myGroceries.
AssertionError: Devices services not initialized!
    at FiberFuture.Future.wait (/Users/vchimev/Work/release/node_modules/fibers/future.js:535:15)
    at /Users/vchimev/Work/release/node_modules/nativescript/lib/common/errors.js:109:33
    at Function.settle (/Users/vchimev/Work/release/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/vchimev/Work/release/node_modules/fibers/future.js:534:10)
    at /Users/vchimev/Work/release/node_modules/nativescript/lib/common/services/commands-service.js:87:106
    at Function.settle (/Users/vchimev/Work/release/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/vchimev/Work/release/node_modules/fibers/future.js:534:10)
    at /Users/vchimev/Work/release/node_modules/nativescript/lib/common/dispatchers.js:38:85
    at Function.settle (/Users/vchimev/Work/release/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/vchimev/Work/release/node_modules/fibers/future.js:534:10)
    at /Users/vchimev/Work/release/node_modules/nativescript/lib/nativescript-cli.js:20:45
    - - - - -
    at /Users/vchimev/Work/release/node_modules/nativescript/lib/common/mobile/mobile-core/devices-service.js:174:20
    at Function.settle (/Users/vchimev/Work/release/node_modules/ios-sim-portable/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/vchimev/Work/release/node_modules/ios-sim-portable/node_modules/fibers/future.js:534:10)
    at /Users/vchimev/Work/release/node_modules/nativescript/lib/common/services/usb-livesync-service-base.js:168:51
    at Function.settle (/Users/vchimev/Work/release/node_modules/ios-sim-portable/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/vchimev/Work/release/node_modules/ios-sim-portable/node_modules/fibers/future.js:534:10)
    at FutureDispatcher.run (/Users/vchimev/Work/release/node_modules/nativescript/lib/common/dispatchers.js:75:22)
    at /Users/vchimev/Work/release/node_modules/nativescript/lib/common/services/usb-livesync-service-base.js:115:35
    at Function.settle (/Users/vchimev/Work/release/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/vchimev/Work/release/node_modules/fibers/future.js:534:10)
    at /Users/vchimev/Work/release/node_modules/nativescript/lib/services/usb-livesync-service.js:130:38
    at Function.settle (/Users/vchimev/Work/release/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/vchimev/Work/release/node_modules/fibers/future.js:534:10)
    at /Users/vchimev/Work/release/node_modules/nativescript/lib/common/services/commands-service.js:54:55
    at Function.settle (/Users/vchimev/Work/release/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/vchimev/Work/release/node_modules/fibers/future.js:534:10)
```

**Comment by vchimev** [comment]
Tested with 1.5.1 RC - the same steps to reproduce.

Output:
```
Successfully synced application org.nativescript.TNSApp.
startLookingForDevices; platform is iOS
Error: Cannot find connected devices. Reconnect any connected devices, verify that your system recognizes them, and run this command again.
    at Object.<anonymous> (/Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/common/errors.js:7:23)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/nativescript-cli.js:9:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
VCHIMEVMAC:nativescript-cli-tests vchimev$ 
```
