### ISSUE TITLE
LiveSync doesn't work when both iOS device and simulator are available

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#1224]
Preconditions:
- attached iOS device;
- started iOS simulator;
- apps installed on both;

Execute:
node_modules/.bin/tns livesync ios --watch --path myGroceries --log trace

```
stderr: 
Error: [object Object] is not a future
    at FiberFuture.Future.wait (/Users/vchimev/Work/release/node_modules/fibers/future.js:535:15)
    at /Users/vchimev/Work/release/node_modules/nativescript/lib/common/errors.js:109:33
    at Function.settle (/Users/vchimev/Work/release/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/vchimev/Work/release/node_modules/fibers/future.js:534:10)
    at /Users/vchimev/Work/release/node_modules/nativescript/lib/common/services/commands-service.js:87:106
    at Function.settle (/Users/vchimev/Work/release/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/vchimev/Work/release/node_modules/fibers/future.js:534:10)
    at /Users/vchimev/Work/release/node_modules/nativescript/lib/common/dispatchers.js:38:85
    at Function.settle (/Users/vchimev/Work/release/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/vchimev/Work/release/node_modules/fibers/future.js:534:10)
    at /Users/vchimev/Work/release/node_modules/nativescript/lib/nativescript-cli.js:20:45
    - - - - -
    at getFutures (/Users/vchimev/Work/release/node_modules/fibers/future.js:202:10)
    at Function.settle (/Users/vchimev/Work/release/node_modules/fibers/future.js:214:16)
    at /Users/vchimev/Work/release/node_modules/nativescript/lib/common/mobile/mobile-core/devices-service.js:156:28
    at arrayMap (/Users/vchimev/Work/release/node_modules/ios-sim-portable/node_modules/lodash/index.js:1378:25)
    at Function.map (/Users/vchimev/Work/release/node_modules/ios-sim-portable/node_modules/lodash/index.js:6154:14)
    at /Users/vchimev/Work/release/node_modules/nativescript/lib/common/mobile/mobile-core/devices-service.js:153:29
    at Function.settle (/Users/vchimev/Work/release/node_modules/ios-sim-portable/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/vchimev/Work/release/node_modules/ios-sim-portable/node_modules/fibers/future.js:534:10)
    at /Users/vchimev/Work/release/node_modules/nativescript/lib/common/mobile/mobile-core/devices-service.js:180:76
    at Function.settle (/Users/vchimev/Work/release/node_modules/ios-sim-portable/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/vchimev/Work/release/node_modules/ios-sim-portable/node_modules/fibers/future.js:534:10)
    at /Users/vchimev/Work/release/node_modules/nativescript/lib/common/services/usb-livesync-service-base.js:197:51
    at Function.settle (/Users/vchimev/Work/release/node_modules/ios-sim-portable/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/vchimev/Work/release/node_modules/ios-sim-portable/node_modules/fibers/future.js:534:10)
    at /Users/vchimev/Work/release/node_modules/nativescript/lib/common/services/usb-livesync-service-base.js:89:59
    at Function.settle (/Users/vchimev/Work/release/node_modules/fibers/future.js:249:26)
```

**Comment by Fatme** [comment]
The problem can be reproduced only when `node_modules/ios-sim-portable/node_modules/fibers` exists. The fix is to delete it.

**Comment by vchimev** [comment]
@Fatme, what could be the reason for `node_modules/ios-sim-portable/node_modules/fibers` to exists?

**Comment by rvanzon** [comment]
Does this bug still exist? I am using a clean install. 

1. tns create test1
2. cd test1
3. tns livesync ios --emulator --watch
4. I get ``[object Object] is not a future``

There is no ``node_modules/ios-sim-portable/node_modules/fibers``

**Comment by rvanzon** [comment]
I just found out that ``tns device`` also gives ``[object Object] is not a future`` in red, above the help lines.

**Comment by nikolal** [comment]
I solved `[object Object] is not a future` by restarting terminal and just running `tns run --emulator ios`.
