### ISSUE TITLE
LiveSync doesn't work when the app is not installed on the iOS simulator

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#1225]
Preconditions:
- started iOS simulator;
- app not installed on the simulator;

Execute:
node_modules/.bin/tns livesync ios --emulator --path myGroceries --log trace

```
stderr: 
Error: Command xcrun with arguments simctl get_app_container 4DF4BF74-B903-4072-95A8-C4F1A9B373D0 org.nativescript.myGroceries failed with exit code 2. Error output:
 An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
The operation couldn’t be completed. No such file or directory
No such file or directory
: Command xcrun with arguments simctl get_app_container 4DF4BF74-B903-4072-95A8-C4F1A9B373D0 org.nativescript.myGroceries failed with exit code 2. Error output:
    at FiberFuture.Future.wait (/Users/vchimev/Work/release/node_modules/fibers/future.js:535:15)
    at /Users/vchimev/Work/release/node_modules/nativescript/lib/common/errors.js:109:33
    at Function.settle (/Users/vchimev/Work/release/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/vchimev/Work/release/node_modules/fibers/future.js:534:10)
    at /Users/vchimev/Work/release/node_modules/nativescript/lib/common/services/commands-service.js:87:106
    at Function.settle (/Users/vchimev/Work/release/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/vchimev/Work/release/node_modules/fibers/future.js:534:10)
    at /Users/vchimev/Work/release/node_modules/nativescript/lib/common/dispatchers.js:38:85
    at Function.settle (/Users/vchimev/Work/release/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/vchimev/Work/release/node_modules/fibers/future.js:534:10)
    at /Users/vchimev/Work/release/node_modules/nativescript/lib/nativescript-cli.js:20:45
    - - - - -
 An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
The operation couldn’t be completed. No such file or directory
No such file or directory

    at ChildProcess.<anonymous> (/Users/vchimev/Work/release/node_modules/ios-sim-portable/lib/child-process.js:40:26)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

**Comment by vchimev** [comment]
Tested with 1.5.1 RC.

If I execute the following commands when the app is not installed on the simulaotr:
- `tns livesync ios --emulator` - installs an older version of the app, which is not correct
- `tns run ios --emulator` - installs the latest version of the app

**Comment by vchimev** [comment]
Update:

the exact workflow for the issue described in the previous comment is:
1. `tns create testApp`
2. `cd testApp`
3. `tns platform add ios`
4. `tns build ios`
5. make a change
6. `tns livesync ios --emulator`

As a result, the app built at step 4 get deployed on the simulator which is **correct** because the `livesync` command does not rebuild the app,.
