### ISSUE TITLE
"ANDROID_HOME environment variable is not set correctly" error is thrown then `tns run ios --log trace` command is executed

### ISSUE THREAD

**Issue by Fatme** [NativeScript/nativescript-cli#1242]
The ANDROID_HOME environment variable is not set or it points to a non-existent directory. You will not be able to perform any build-related operations for Android.
To be able to perform Android build-related operations, set the ANDROID_HOME variable to point to the root of your Android SDK installation directory.

ANDROID_HOME environment variable is not set correctly.
error is thrown when ios related command is executed with --log trace option.

**Comment by vchimev** [comment]
```
VCHIMEVMAC:nativescript-cli-tests vchimev$ node_modules/.bin/tns doctor
The ANDROID_HOME environment variable is not set or it points to a non-existent directory. You will not be able to perform any build-related operations for Android.
To be able to perform Android build-related operations, set the ANDROID_HOME variable to point to the root of your Android SDK installation directory.

ANDROID_HOME environment variable is not set correctly.
WARNING: adb from the Android SDK is not installed or is not configured properly.
For Android-related operations, the NativeScript CLI will use a built-in version of adb.
To avoid possible issues with the native Android emulator, Genymotion or connected
Android devices, verify that you have installed the latest Android SDK and
its dependencies as described in http://developer.android.com/sdk/index.html#Requirements

TIP: To avoid setting up the necessary environment variables, you can use the Homebrew package manager to install the Android SDK and its dependencies.

WARNING: The Android SDK is not installed or is not configured properly.
You will not be able to build your projects for Android and run them in the native emulator.
To be able to build for Android and run apps in the native emulator, verify that you have
installed the latest Android SDK and its dependencies as described in http://developer.android.com/sdk/index.html#Requirements

TIP: To avoid setting up the necessary environment variables, you can use the Homebrew package manager to install the Android SDK and its dependencies.

WARNING: CocoaPod is not installed or is not configured properly.
You will not be able to build your projects for iOS if they contain plugin with CocoaPod file.
To be able to build such projects, verify that you have installed CocoaPod.
ANDROID_HOME environment variable is not set correctly.
ANDROID_HOME environment variable is not set correctly.
ANDROID_HOME environment variable is not set correctly.
Cannot find a compatible Android SDK for compilation. To be able to build for Android, install Android SDK 22 or later.
Run $ android to manage your Android SDK versions.

You need to have the Android SDK Build-tools installed on your system. You can install any version in the following range: '>=22 <=23'.
Run android from your command-line to install required Android Build Tools. In case you already have them installed, make sure ANDROID_HOME environment variable is set correctly.

You need to have Android SDK 22 or later and the latest Android Support Repository installed on your system.
Run $ android  to manage the Android Support Repository. In case you already have it installed, make sure ANDROID_HOME environment variable is set correctly.

These warnings are just used to help the NativeScript maintainers with debugging if you file an issue.
Please ignore them if everything you use NativeScript for is working fine.

Error: There are outstanding futures. Construction call stacks:
#1
    at ChildProcess.spawnFromEvent (/Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/common/child-process.js:53:22)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/common/sys-info-base.js:88:63
    at Function.settle (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:534:10)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/common/sys-info-base.js:56:74
    at Function.settle (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:534:10)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/sys-info.js:28:170
    at Function.settle (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:534:10)
    at DoctorService.printWarnings (/Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/services/doctor-service.js:15:98)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/common/commands/doctor.js:18:56
    at Function.settle (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:534:10)
#2
    at ChildProcess.spawnFromEvent (/Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/common/child-process.js:53:22)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/android-tools-info.js:300:54
    at Function.settle (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:534:10)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/android-tools-info.js:288:64
    at Function.settle (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:534:10)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/android-tools-info.js:201:88
    at Function.settle (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:534:10)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/android-tools-info.js:76:68
    at Function.settle (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:534:10)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/android-tools-info.js:90:54
#3
    at ChildProcess.spawnFromEvent (/Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/common/child-process.js:53:22)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/android-tools-info.js:300:54
    at Function.settle (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:534:10)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/android-tools-info.js:288:64
    at Function.settle (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:534:10)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/android-tools-info.js:201:88
    at Function.settle (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:534:10)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/android-tools-info.js:216:103
    at Function.settle (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:534:10)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/android-tools-info.js:78:66
#4
    at ChildProcess.spawnFromEvent (/Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/common/child-process.js:53:22)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/android-tools-info.js:300:54
    at Function.settle (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:534:10)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/android-tools-info.js:288:64
    at Function.settle (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:534:10)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/android-tools-info.js:201:88
    at Function.settle (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:534:10)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/android-tools-info.js:264:59
    at Function.settle (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:534:10)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/android-tools-info.js:276:68
    at Function.Future.assertNoFutureLeftBehind (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:174:9)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/nativescript-cli.js:23:12
```

**Comment by vchimev** [comment]
I got the same call stack executing *ios* related command with `--log trace`, ex. `tns prepare ios --log trace`.
