### ISSUE TITLE
Unit Test: Can not load "ios_simulator"!

### ISSUE THREAD

**Issue by charalamposc** [NativeScript/nativescript-cli#1284]
Hello,
I wanted to try out the unit test mechanism, so I created a new project and typed
- tns test init
- tns test ios --emulator
but I got the following error message:
```
01 12 2015 11:21:46.153:WARN [plugin]: Error during loading "/.../sandbox/unitTestTry/node_modules/karma-nativescript-launcher" plugin:
  Cannot find module 'shelljs'
01 12 2015 11:21:46.153:DEBUG [plugin]: Loading inlined plugin (defining launcher:android, launcher:ios, launcher:ios_simulator).
01 12 2015 11:21:46.242:INFO [karma]: Karma v0.13.15 server started at http://localhost:9876/
01 12 2015 11:21:46.245:WARN [launcher]: Can not load "ios_simulator"!
  Error: No provider for "launcher:NS". Can not use provider from the parent!
    at /.../sandbox/unitTestTry/node_modules/karma/node_modules/di/lib/injector.js:84:17
    at Array.forEach (native)
    at createChild (/.../sandbox/unitTestTry/node_modules/karma/node_modules/di/lib/injector.js:82:27)
    at module.(anonymous function) (/.../sandbox/unitTestTry/node_modules/karma/lib/config.js:198:25)
    at Array.invoke (/.../sandbox/unitTestTry/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at get (/.../sandbox/unitTestTry/node_modules/karma/node_modules/di/lib/injector.js:48:43)
    at /.../sandbox/unitTestTry/node_modules/karma/lib/launcher.js:60:76
    at Array.forEach (native)
    at launch (/.../sandbox/unitTestTry/node_modules/karma/lib/launcher.js:43:11)
    at invoke (/.../sandbox/unitTestTry/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Server.<anonymous> (/.../sandbox/unitTestTry/node_modules/karma/lib/server.js:170:24)
    at Server.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1260:10)
    at doNTCallback1 (node.js:441:9)
    at process._tickCallback (node.js:363:17)
```
I seems that the shelljs wasn't installed, because after installing it
```
npm install shelljs --save
```
everything worked fine. Shouldn't shelljs be installed automatically?

**Comment by ligaz** [comment]
Thanks for reporting this. The issue has already been addressed in #1299
