### ISSUE TITLE
LiveSync fails when a new directory is added into the app folder

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#1285]
Tested with 1.5.1 RC.

Steps to reproduce:
- tns livesync android --watch
- create a new directory into the *app* folder

Output:
```
Project successfully prepared
AfterHookName for command prepare is after-prepare
Start syncing application org.nativescript.TNSApp at Dec 1, 2015 1:24:50 PM.
spawn: /Users/vchimev/Library/Android/sdk/platform-tools/adb "-s" "emulator-5554" "shell" "rm" "-rf" "/data/local/tmp/org.nativescript.TNSApp/fullsync" "/data/local/tmp/org.nativescript.TNSApp/sync" "/data/local/tmp/org.nativescript.TNSApp/removedsync"
Transferring project files...
Error: ENOENT: no such file or directory, stat '/Work/GitHub/nativescript-cli-tests/TNS_App/platforms/android/src/main/assets/app/folder'
    at FiberFuture.Future.wait (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:535:15)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/common/errors.js:109:33
    at Function.settle (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:534:10)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/common/services/commands-service.js:87:106
    at Function.settle (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:534:10)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/common/dispatchers.js:39:85
    at Function.settle (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Work/GitHub/nativescript-cli-tests/node_modules/fibers/future.js:534:10)
    at /Work/GitHub/nativescript-cli-tests/node_modules/nativescript/lib/nativescript-cli.js:20:45
    - - - - -
    at Error (native)
```

**Comment by vchimev** [comment]
https://github.com/NativeScript/nativescript-cli/issues/1339
