### ISSUE TITLE
"tns test" fails if you don't have the "shelljs" npm module installed

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/nativescript-cli#1299]
I get this error when trying to run tests both on ios and android:
```
hdeshev@hdeshevmac ~/w/nativescript-test-hello (master)> tns test ios --emulator
03 12 2015 11:35:25.119:WARN [plugin]: Error during loading "/Users/hdeshev/w/nativescript-test-hello/node_modules/karma-nativescript-launcher" plugin:
  Cannot find module 'shelljs'
03 12 2015 11:35:25.171:INFO [karma]: Karma v0.13.15 server started at http://localhost:9876/
03 12 2015 11:35:25.173:WARN [launcher]: Can not load "ios_simulator"!
  Error: No provider for "launcher:NS". Can not use provider from the parent!
    at /Users/hdeshev/w/nativescript-test-hello/node_modules/karma/node_modules/di/lib/injector.js:84:17
    at Array.forEach (native)
    at createChild (/Users/hdeshev/w/nativescript-test-hello/node_modules/karma/node_modules/di/lib/injector.js:82:27)
```

The only difference is that I don't see the shelljs error line, and there is no way to know what the problem is.

Reproduce by creating a simple project with `tns create` and then doing a `tns test init`.

Doing a `npm install shelljs` fixes the problem.

**Comment by Fatme** [comment]
https://github.com/NativeScript/karma-nativescript-launcher/pull/22
