### ISSUE TITLE
A problem with prepare --path

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#1309]
It seems that `tns prepare <platform> --path <path to the project>` does not install the *devDependencies* and does not find local *dependencies* listed in the package.json.

Steps to reproduce:
- git clone https://github.com/NativeScript/sample-Xpensity.git
- tns prepare android --path sample-Xpensity

Output:
```
VCHIMEVMAC:nativescript-cli-tests vchimev$ tns prepare android --path sample-Xpensity --log trace
execFile: /Users/vchimev/Library/Android/sdk/platform-tools/adb "help"
spawn: /Users/vchimev/Library/Android/sdk/tools/android "--help"

       Usage:
       android [global options] action [action options]
       Global options:
  -s --silent     : Silent mode, shows errors only.
  -v --verbose    : Verbose mode, shows errors, warnings and all messages.
     --clear-cache: Clear the SDK Manager repository manifest cache.
  -h --help       : Help on a specific command.

                                                                    Valid
                                                                    actions
                                                                    are
                                                                    composed
                                                                    of a verb
                                                                    and an
                                                                    optional
                                                                    direct
                                                                    object:
-    sdk              : Displays the SDK Manager window.
-    avd              : Displays the AVD Manager window.
-   list              : Lists existing targets or virtual devices.
-   list avd          : Lists existing Android Virtual Devices.
-   list target       : Lists existing targets.
-   list device       : Lists existing devices.
-   list sdk          : Lists remote SDK repository.
- create avd          : Creates a new Android Virtual Device.
-   move avd          : Moves or renames an Android Virtual Device.
- delete avd          : Deletes an Android Virtual Device.
- update avd          : Updates an Android Virtual Device to match the folders
                        of a new SDK.
- create project      : Creates a new Android project.
- update project      : Updates an Android project (must already have an
                        AndroidManifest.xml).
- create test-project : Creates a new Android project for a test package.
- update test-project : Updates the Android project for a test package (must
                        already have an AndroidManifest.xml).
- create lib-project  : Creates a new Android library project.
- update lib-project  : Updates an Android library project (must already have
                        an AndroidManifest.xml).
- create uitest-project: Creates a new UI test project.
- update adb          : Updates adb to support the USB devices declared in the
                        SDK add-ons.
- update sdk          : Updates the SDK by suggesting new platforms to install
                        if available.

Exec uname -a 
 stdout: Darwin VCHIMEVMAC.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
 
 stderr: 
Exec npm -v 
 stdout: 3.3.12
 
 stderr: 
spawn: java "-version"
Exec node-gyp -v 
 stdout:  
 stderr: /bin/sh: node-gyp: command not found

Exec xcodebuild -version 
 stdout: Xcode 7.1
Build version 7B91b
 
 stderr: 
Exec pod --version 
 stdout:  
 stderr: /bin/sh: pod: command not found

Exec '/Users/vchimev/Library/Android/sdk/platform-tools/adb' version 
 stdout: Android Debug Bridge version 1.0.32
Revision eac51f2bb6a8-android
 
 stderr: 
spawn: /Users/vchimev/Library/Android/sdk/tools/android "-h"
Exec mono --version 
 stdout:  
 stderr: /bin/sh: mono: command not found

Exec git --version 
 stdout: git version 2.6.2
 
 stderr: 
Exec gradle -v 
 stdout:  
 stderr: /bin/sh: gradle: command not found

Exec "/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/javac" -version 
 stdout:  
 stderr: javac 1.8.0_60

System information:
{ procInfo: 'nativescript/1.5.1',
  platform: 'darwin',
  os: 'Darwin VCHIMEVMAC.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64\n',
  shell: '/bin/bash',
  dotNetVer: null,
  procArch: 'x64',
  nodeVer: 'v5.1.0',
  npmVer: '3.3.12',
  javaVer: '1.8.0',
  nodeGypVer: null,
  xcodeVer: 'Xcode 7.1\nBuild version 7B91b\n',
  itunesInstalled: true,
  cocoapodVer: null,
  adbVer: 'Android Debug Bridge version 1.0.32',
  androidInstalled: true,
  monoVer: null,
  gitVer: '2.6.2',
  gradleVer: null,
  javacVersion: '1.8.0_60' }
execFile: /Users/vchimev/Library/Android/sdk/platform-tools/adb "help"
spawn: /Users/vchimev/Library/Android/sdk/platform-tools/adb "start-server"
Looking for project in '/Work/GitHub/nativescript-cli-tests/sample-Xpensity'
Project directory is '/Work/GitHub/nativescript-cli-tests/sample-Xpensity'.
Initializing analytics statuses.
Analytics statuses: 
{ TrackFeatureUsage: 1, TrackExceptions: 1 }
Trying to track feature 'CLI' with value 'prepare'.
npm WARN package.json @ No repository field.
npm WARN package.json @ No license field.
npm ERR! addLocal Could not install /Work/GitHub/nativescript-cli-tests/plugins/date-picker
npm ERR! addLocal Could not install /Work/GitHub/nativescript-cli-tests/plugins/drop-down-list
npm ERR! addLocal Could not install /Work/GitHub/nativescript-cli-tests/plugins/edit-view-model-base
npm ERR! addLocal Could not install /Work/GitHub/nativescript-cli-tests/plugins/everlive
npm ERR! addLocal Could not install /Work/GitHub/nativescript-cli-tests/plugins/grid-view
npm ERR! addLocal Could not install /Work/GitHub/nativescript-cli-tests/plugins/navigation
npm ERR! addLocal Could not install /Work/GitHub/nativescript-cli-tests/plugins/notifications
npm ERR! addLocal Could not install /Work/GitHub/nativescript-cli-tests/plugins/table
npm ERR! addLocal Could not install /Work/GitHub/nativescript-cli-tests/plugins/validation-rules
npm ERR! addLocal Could not install /Work/GitHub/nativescript-cli-tests/plugins/view-model-base
npm ERR! addLocal Could not install /Work/GitHub/nativescript-cli-tests/plugins/custom-control
npm ERR! addLocal Could not install /Work/GitHub/nativescript-cli-tests/plugins/data-source
{ [Error: ENOENT: no such file or directory, open '/Work/GitHub/nativescript-cli-tests/plugins/date-picker']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Work/GitHub/nativescript-cli-tests/plugins/date-picker' }
Error: ENOENT: no such file or directory, open '/Work/GitHub/nativescript-cli-tests/plugins/date-picker'
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:535:15)
    at /usr/local/lib/node_modules/nativescript/lib/services/platform-service.js:139:75
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /usr/local/lib/node_modules/nativescript/lib/commands/prepare.js:13:66
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/services/commands-service.js:54:55
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/errors.js:109:33
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/services/commands-service.js:87:106
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    - - - - -
    at Error (native)
Error: Unable to install dependencies. Make sure your package.json is valid and all dependencies are correct. Error is: ENOENT: no such file or directory, open '/Work/GitHub/nativescript-cli-tests/plugins/date-picker'
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:7:23)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:9:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

Steps to work:
- git clone https://github.com/NativeScript/sample-Xpensity.git
- cd sample-Xpensity
- tns prepare android

**Comment by rosen-vladimirov** [comment]
This is a problem with npm itself. I've tried to add some options ("cwd", "dir", etc.) to our npm install code. I"ve event changed the process.cwd(), but nothing helped. One possible solution is to install the dependencies to temp dir and copy the dependencies to project's node_modules, for example:
```TypeScript
if(process.cwd() !== this.$projectData.projectDir) {
	// Install to temp dir and move to project after that
	temp.track();
	let dir = temp.mkdirSync("nativescriptProjectDeps");
	let data: any[] = this.$npm.install(this.$projectData.projectDir,dir, { "ignore-scripts": this.$options.ignoreScripts}).wait();
	_.each(data, d => {
		shelljs.cp("-Rf", path.join(d[1]), path.join(this.$projectData.projectDir, "node_modules"));	
	});
} else {
	this.$npm.install(this.$projectData.projectDir,this.$projectData.projectDir, { "ignore-scripts": this.$options.ignoreScripts}).wait();
}
```
NOTE: this is in ensureAllDependenciesAreInstalled method

I do not like this solution, so I prefer to mark this as known-issue
