### ISSUE TITLE
LiveSync watch breaks when deleting a folder and then adding a new file|folder

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#1339]
Tested with {N} CLI 1.5.1 RC.

Steps to reproduce:
- tns livesync android|ios --watch
- delete a directory under the app folder
- add a new file|folder into the app folder

It seems that after deleting a folder the watcher continues to watch for it.

Output:
```
Error: watch /Work/GitHub/nativescript-cli-tests/TNS_App/app/awef ENOENT
    at exports._errnoException (util.js:856:11)
    at FSWatcher.start (fs.js:1313:19)
    at Object.fs.watch (fs.js:1341:11)
    at Gaze._watchDir (/Work/GitHub/nativescript-cli-tests/node_modules/gaze/lib/gaze.js:289:30)
    at /Work/GitHub/nativescript-cli-tests/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/Work/GitHub/nativescript-cli-tests/node_modules/gaze/lib/helper.js:52:5)
    at /Work/GitHub/nativescript-cli-tests/node_modules/gaze/lib/helper.js:61:11
    at /Work/GitHub/nativescript-cli-tests/node_modules/gaze/lib/gaze.js:420:5
    at iterate (/Work/GitHub/nativescript-cli-tests/node_modules/gaze/lib/helper.js:52:5)
    at /Work/GitHub/nativescript-cli-tests/node_modules/gaze/lib/helper.js:61:11
    at /Work/GitHub/nativescript-cli-tests/node_modules/gaze/lib/gaze.js:420:5
    at iterate (/Work/GitHub/nativescript-cli-tests/node_modules/gaze/lib/helper.js:52:5)
    at /Work/GitHub/nativescript-cli-tests/node_modules/gaze/lib/helper.js:61:11
    at /Work/GitHub/nativescript-cli-tests/node_modules/gaze/lib/gaze.js:420:5
    at iterate (/Work/GitHub/nativescript-cli-tests/node_modules/gaze/lib/helper.js:52:5)
    at /Work/GitHub/nativescript-cli-tests/node_modules/gaze/lib/helper.js:61:11
```

**Comment by teobugslayer** [comment]
After consulting with @vchimev , this happened on OS X.

**Comment by rosen-vladimirov** [comment]
It turns out this is bug in gaze module. Updating it should fix the issues.

**Comment by dtopuzov** [comment]
Delete folder is fixed, but create new folder still not.

Steps to reproduce:
tns create TestApp
cd TestApp
tns livesync ios --emulator --watch
create new folder with OSX Finder

Infrastructure
OSX: El Capitan
Xcode 7.2
{N} 1.6.0

**Comment by enchev** [comment]
Here is more info about the error: https://github.com/shama/gaze/issues/202

**Comment by pkoleva** [comment]
Issue is reproduced via command line as well
