### ISSUE TITLE
Cannot find module 'colors' during uninstall

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#1419]
I get this on `npm` 3.5.1 version, have not tried it on `npm` 2.*.

```
VCHIMEVMAC:mobile-master vchimev$ npm uninstall -g nativescript

> nativescript@1.5.2 preuninstall /usr/local/lib/node_modules/nativescript
> node preuninstall.js

Failed to complete all pre-uninstall steps. 
{ [Error: Command failed: /bin/sh -c node bin/nativescript.js dev-preuninstall
module.js:340
    throw err;
    ^

Error: Cannot find module 'colors'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.verifyNodeVersion (/usr/local/lib/node_modules/nativescript/lib/common/verify-node-version.js:6:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:3:41)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
]
```

**Comment by teobugslayer** [comment]
I can repro on Mac / El Capitan.
