### ISSUE TITLE
The test command fails on Android

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#1562]
```
mcsofvchimev:appTest vchimev$ tns test android
Copying template files...
Project successfully created.
Successfully prepared plugin nativescript-unit-test-runner for android.
Successfully prepared plugin tns-core-modules for android.
Project successfully prepared
Executing after-prepare hook from /Users/vchimev/Work/git/appTest/hooks/after-prepare/nativescript-unit-test-runner.js
02 03 2016 14:12:17.447:INFO [karma]: Karma v0.13.21 server started at http://localhost:9876/
02 03 2016 14:12:17.454:INFO [launcher]: Starting browser NativeScript Unit Test Runner
The application with id "org.nativescript.appTest" is not installed on device with identifier emulator-5554.
shell.js: internal error
Error: EEXIST: file already exists, symlink '../mkdirp/bin/cmd.js' -> '/Users/vchimev/Work/git/appTest/platforms/android/src/main/assets/app/tns_modules/nativescript-unit-test-runner/node_modules/nativescript-hook/node_modules/.bin/mkdirp'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at cpdirSyncRecursive (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:76:10)
    at cpdirSyncRecursive (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:73:7)
    at cpdirSyncRecursive (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:73:7)
    at cpdirSyncRecursive (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:73:7)
    at cpdirSyncRecursive (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:73:7)
    at /usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:183:9
    at Array.forEach (native)
    at Object._cp (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:157:11)
    at Object.cp (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/common.js:186:23)
    at DestCopy.copyDependencyDir (/usr/local/lib/node_modules/nativescript/lib/tools/broccoli/node-modules-dest-copy.js:88:17)
    at /usr/local/lib/node_modules/nativescript/lib/tools/broccoli/node-modules-dest-copy.js:62:19
    at /usr/local/lib/node_modules/nativescript/node_modules/lodash/index.js:3073:15
    at baseForOwn (/usr/local/lib/node_modules/nativescript/node_modules/lodash/index.js:2046:14)
    at /usr/local/lib/node_modules/nativescript/node_modules/lodash/index.js:3043:18
    at Function.<anonymous> (/usr/local/lib/node_modules/nativescript/node_modules/lodash/index.js:3346:13)
```

**Comment by rosen-vladimirov** [comment]
Issue is already fixed in `nativescript-unit-test-runner` - just update it to latest version (0.3.1) and it should work :)
