### ISSUE TITLE
Unable to build a project with CocoaPods version: 1.0.0.beta.6

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#1611]
CocoaPods version: 1.0.0.beta.6
App under test: [Groceries] (https://github.com/NativeScript/sample-Groceries)

The `tns build ios --log trace` does not create *.xcworkspace* and fails with:
```
[!] The dependency `IQKeyboardManager` is not used in any concrete target.
```

Output:
```
The iOS Deployment Target is now 8.0 in order to support Cocoa Touch Frameworks in CocoaPods.
Successfully prepared plugin nativescript-iqkeyboardmanager for ios.
Successfully prepared plugin nativescript-social-share for ios.
spawn: /usr/libexec/PlistBuddy "-c" "Print :CFBundlePackageType" "/Users/vchimev/Work/release/sample-Groceries/node_modules/nativescript-telerik-ui/platforms/ios/TelerikUI.framework/Info.plist"
spawn: otool "-Vh" "/Users/vchimev/Work/release/sample-Groceries/node_modules/nativescript-telerik-ui/platforms/ios/TelerikUI.framework/TelerikUI"
The iOS Deployment Target is now 8.0 in order to support Cocoa Touch Frameworks.
Successfully prepared plugin nativescript-telerik-ui for ios.
Successfully prepared plugin nativescript-unit-test-runner for ios.
Successfully prepared plugin tns-core-modules for ios.
Project Podfile content
use_frameworks!
# Begin Podfile - /Users/vchimev/Work/release/sample-Groceries/node_modules/nativescript-iqkeyboardmanager/platforms/ios/Podfile 
 pod 'IQKeyboardManager' 
 # End Podfile 

Creating project scheme...
Exec ruby -e "require 'xcodeproj'; xcproj = Xcodeproj::Project.open('sampleGroceries.xcodeproj'); xcproj.recreate_user_schemes; xcproj.save" 
 stdout:  
 stderr: 
Exec gem which cocoapods 
 stdout: /usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods.rb
 
 stderr: 
Exec gem which xcodeproj 
 stdout: /usr/local/lib/ruby/gems/2.2.0/gems/xcodeproj-1.0.0.beta.3/lib/xcodeproj.rb
 
 stderr: 
Installing pods...
spawn: pod "install"
Analyzing dependencies
[!] The dependency `IQKeyboardManager` is not used in any concrete target.
[Error: Command pod failed with exit code 1]
Error: Command pod failed with exit code 1
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:535:15)
    at /usr/local/lib/node_modules/nativescript/lib/services/platform-service.js:236:114
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/helpers.js:215:36
    at PlatformService.descriptor.value [as preparePlatformCore] (/usr/local/lib/node_modules/nativescript/lib/common/helpers.js:182:24)
    at /usr/local/lib/node_modules/nativescript/lib/services/platform-service.js:186:26
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /usr/local/lib/node_modules/nativescript/lib/services/platform-service.js:256:50
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /usr/local/lib/node_modules/nativescript/lib/commands/build.js:16:73
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/services/commands-service.js:53:55
    - - - - -
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/child-process.js:91:38)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
Processing node_modules failed. Error: Command pod failed with exit code 1
Error: Processing node_modules failed. Error: Command pod failed with exit code 1
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:7:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:8:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
Analytics statuses: 
{ TrackFeatureUsage: 0, TrackExceptions: 0 }
Trying to track exception with message 'Processing node_modules failed. Error: Command pod failed with exit code 1'.
Statistics was sent successfully (xhr).
```

**Comment by dtopuzov** [comment]
{N} CLI 2.0.1 works fine with pods 1.0.0
