### ISSUE TITLE
Critical bug on new fresh installation

### ISSUE THREAD

**Issue by meow0703** [NativeScript/nativescript-cli#1837]
HI there, please help investigate below console log on windows 10, thanks !
```
C:\Users\root>npm --version
2.15.5

C:\Users\root>node --version
v4.4.5

C:\Users\root>npm install -g nativescript
npm WARN excluding symbolic link docs\stylesheets\hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN excluding symbolic link docs\stylesheets\hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.4.5","npm":"2.15.5"})
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.

> fibers@1.0.6 install C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers
> node build.js || nodejs build.js

`win32-x64-v8-4.5` exists; testing
Binary is fine; exiting
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> ref@1.1.3 install C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\ref
> node ./build.js

`win32-x64-v8-4.5` exists; testing
Binary is fine; exiting

> utf-8-validate@1.0.1 install C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\utf-8-validate
> node ./build.js

`win32-x64-v8-4.5` exists; testing
Binary is fine; exiting

> bufferutil@1.0.1 install C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\bufferutil
> node ./build.js

`win32-x64-v8-4.5` exists; testing
Binary is fine; exiting
npm WARN excluding symbolic link docs\assets\ir_black.css -> ../../node_modules/highlight.js/src/styles/ir_black.css
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework\Resources -> Versions/Current/Resources
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework\Test Framework -> Versions/Current/Test Framework
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework\Versions\Current -> A
npm WARN excluding symbolic link docs\assets\ir_black.css -> ../../node_modules/highlight.js/src/styles/ir_black.css
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework\Resources -> Versions/Current/Resources
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework\Test Framework -> Versions/Current/Test Framework
npm WARN excluding symbolic link examples\TestFramework\Test Framework.framework\Versions\Current -> A
npm WARN excluding symbolic link docs\stylesheets\hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css

> ws@0.4.32 install C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\node-inspector\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

/
C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\node-inspector\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
npm WARN excluding symbolic link docs\stylesheets\hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css

> ffi@2.0.0 install C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\ffi
> node ./build.js

`win32-x64-v8-4.5` exists; testing
Binary is fine; exiting
C:\Users\root\AppData\Roaming\npm\tns -> C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\bin\nativescript.js
C:\Users\root\AppData\Roaming\npm\nativescript -> C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\bin\nativescript.js

> nativescript@2.0.1 postinstall C:\Users\root\AppData\Roaming\npm\node_modules\nativescript
> node postinstall.js

NOTE: You can develop for iOS only on Mac OS X systems.
To be able to work with iOS devices and projects, you need Mac OS X Mavericks or later.

Your components are up-to-date.

Unexpected token
SyntaxError: Unexpected token
    at FiberFuture.Future.wait (C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:535:15)
    at C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\lib\nativescript-cli.js:21:45
    - - - - -
    at Object.parse (native)
    at C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\lib\common\file-system.js:222:29
    at Function.settle (C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:249:26)
    at FiberFuture.Future.wait (C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:534:10)
    at C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\user-settings-service.js:50:89
    at Function.settle (C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:249:26)
    at FiberFuture.Future.wait (C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:534:10)
    at C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\user-settings-service.js:12:42
    at Function.settle (C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:249:26)
    at FiberFuture.Future.wait (C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:534:10)
    at C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\analytics-service.js:124:92
    at Function.settle (C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:249:26)
    at FiberFuture.Future.wait (C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:534:10)
    at C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\analytics-service.js:218:64
    at Function.settle (C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:249:26)
    at FiberFuture.Future.wait (C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:534:10)
nativescript@2.0.1 C:\Users\root\AppData\Roaming\npm\node_modules\nativescript
├── bufferpack@0.0.6
├── winreg@0.0.17
├── mute-stream@0.0.5
├── open@0.0.5
├── properties-parser@0.2.3
├── lockfile@1.0.1
├── xmldom@0.1.21
├── bplist-parser@0.1.0
├── esprima@2.7.0
├── tabtab@0.0.3
├── semver@5.0.1
├── filesize@3.1.2
├── colors@1.1.2
├── marked@0.3.3
├── node-uuid@1.4.3
├── xmlhttprequest@1.5.1
├── iconv-lite@0.4.11
├── osenv@0.1.3 (os-homedir@1.0.1, os-tmpdir@1.0.1)
├── byline@4.2.1
├── shelljs@0.5.3
├── temp@0.8.3 (os-tmpdir@1.0.1, rimraf@2.2.8)
├── ws@0.7.1 (options@0.0.6, ultron@1.0.2)
├── chalk@1.1.0 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.1)
├── minimatch@2.0.10 (brace-expansion@1.1.4)
├── bluebird@2.9.34
├── mkdirp@0.5.1 (minimist@0.0.8)
├── glob@7.0.3 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.3, inflight@1.0.5)
├── plist-merge-patch@0.0.9 (json-merge-patch@0.2.3, plist@1.2.0)
├── fibers@1.0.6
├── xcode@0.8.0 (node-uuid@1.3.3, pegjs@0.6.2)
├── progress-stream@1.1.1 (single-line-log@0.3.1, speedometer@0.1.4, through2@0.2.3)
├── gaze@0.5.2 (globule@0.1.0)
├── yargs@3.15.0 (decamelize@1.2.0, camelcase@1.2.1, window-size@0.1.4, cliui@2.1.0)
├── ref@1.1.3 (bindings@1.2.1, prebuilt@0.1.0, debug@2.2.0, nan@2.3.5)
├── moment@2.10.6
├── utf-8-validate@1.0.1 (bindings@1.2.1, prebuilt@0.1.0, nan@2.3.5)
├── inquirer@0.9.0 (strip-ansi@3.0.1, ansi-regex@2.0.0, through@2.3.8, rx-lite@2.5.2, cli-width@1.1.1, figures@1.7.0, run-async@0.1.0, readline2@0.1.1)
├── bufferutil@1.0.1 (bindings@1.2.1, prebuilt@0.1.0, nan@2.3.5)
├── marked-terminal@1.5.0 (node-emoji@0.1.0, lodash.assign@3.2.0, cardinal@0.5.0)
├── plistlib@0.2.1 (node-xml@1.0.2, async@0.2.10, underscore@1.5.2, xml@0.0.12, moment@2.4.0)
├── log4js@0.6.26 (async@0.2.10, underscore@1.8.2, semver@4.3.6, readable-stream@1.0.34)
├── lodash@3.10.0
├── cli-table@0.3.1 (colors@1.0.3, wcwidth@1.0.1, lodash@3.6.0)
├── ref-struct@1.0.2 (debug@2.2.0)
├── plist@1.1.0 (util-deprecate@1.0.0, base64-js@0.0.6, xmlbuilder@2.2.1)
├── broccoli-funnel@0.2.3 (symlink-or-copy@1.1.3, walk-sync@0.1.3, broccoli-read-compat@0.1.3, core-object@0.0.2)
├── broccoli@0.16.4 (broccoli-slow-trees@1.1.0, copy-dereference@1.0.0, promise-map-series@0.2.2, rimraf@2.5.2, mime@1.3.4, commander@2.9.0, rsvp@3.2.1, quick-temp@0.1.5, findup-sync@0.2.1, broccoli-kitchen-sink-helpers@0.2.9, connect@3.4.1, handlebars@3.0.3)
├── clui@0.3.1 (cli-color@0.3.2)
├── node-inspector@0.7.4 (debug@0.8.1, opener@1.3.0, which@1.0.9, async@0.8.0, strong-data-uri@0.1.1, rc@0.3.5, glob@3.2.11, yargs@1.2.6, express@4.0.0, ws@0.4.32)
├── ffi@2.0.0 (bindings@1.2.1, prebuilt@0.1.0, debug@2.2.0, nan@2.3.5)
├── npm@2.14.12
└── ios-sim-portable@1.0.23 (colors@0.6.2, lodash@3.2.0, nodobjc@2.0.0)

C:\Users\root>
```

**Comment by NickIliev** [comment]
Duplicate to [https://github.com/NativeScript/NativeScript/issues/2297](https://github.com/NativeScript/NativeScript/issues/2297)

**Comment by meow0703** [comment]
The issue still happen so far ! Hurry up folk @@
