### ISSUE TITLE
TNS doctor does not detect if JDK is not installed and throws an error

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#1922]
NativeScript CLI: 2.1.1
OS: OS X El Capitan
### Actual

If no JDK and JAVA_HOME environment variable are available, `tns doctor` throws an error: `Cannot read property``match``of null`.

After that, a java prompt leading to _www.java.com/en/download/mac_download.jsp_ appears (see https://github.com/NativeScript/nativescript-cli/issues/1863#issuecomment-232288875) which provides a download of JRE, but not JDK required by NativeScript. 
### Expected

A clear warning that JDK is not installed or is not configured properly, similarly to Android SDK for example: `WARNING: The Android SDK is not installed or is not configured properly.`

Output of `tns doctor --log trace`:

```
TypeError: Cannot read property 'match' of null
    at FiberFuture.Future.wait (/Users/nsbuilduser/Work/node_modules/nativescript/node_modules/fibers/future.js:566:15)
    at /Users/nsbuilduser/Work/node_modules/nativescript/lib/common/errors.js:123:33
    at Function.settle (/Users/nsbuilduser/Work/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/nsbuilduser/Work/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /Users/nsbuilduser/Work/node_modules/nativescript/lib/common/services/commands-service.js:84:106
    at Function.settle (/Users/nsbuilduser/Work/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/nsbuilduser/Work/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /Users/nsbuilduser/Work/node_modules/nativescript/lib/common/dispatchers.js:38:85
    at Function.settle (/Users/nsbuilduser/Work/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/nsbuilduser/Work/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /Users/nsbuilduser/Work/node_modules/nativescript/lib/nativescript-cli.js:22:45
    - - - - -
    at /Users/nsbuilduser/Work/node_modules/nativescript/lib/common/services/xcode-select-service.js:34:98
    at Function.settle (/Users/nsbuilduser/Work/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/nsbuilduser/Work/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /Users/nsbuilduser/Work/node_modules/nativescript/lib/services/xcproj-service.js:35:138
    at Function.settle (/Users/nsbuilduser/Work/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/nsbuilduser/Work/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /Users/nsbuilduser/Work/node_modules/nativescript/lib/services/xcproj-service.js:17:52
    at Function.settle (/Users/nsbuilduser/Work/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/nsbuilduser/Work/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /Users/nsbuilduser/Work/node_modules/nativescript/lib/services/doctor-service.js:81:62
    at Function.settle (/Users/nsbuilduser/Work/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/nsbuilduser/Work/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /Users/nsbuilduser/Work/node_modules/nativescript/lib/common/commands/doctor.js:17:72
    at Function.settle (/Users/nsbuilduser/Work/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/nsbuilduser/Work/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /Users/nsbuilduser/Work/node_modules/nativescript/lib/common/services/commands-service.js:51:55
Analytics statuses: 
{ TrackFeatureUsage: 1, TrackExceptions: 1 }
Trying to track feature 'CLI' with value 'help'.
List of registered commands: /?, appstore, appstore|upload, autocomplete, autocomplete|disable, autocomplete|enable, autocomplete|status, build, build|android, build|ios, create, debug, debug|android, debug|ios, deploy, dev-generate-help, dev-generate-messages, dev-post-install, dev-preuninstall, dev-test, dev-test|android, dev-test|ios, device, device|android, device|get-file, device|ios, device|list-applications, device|list-files, device|log, device|put-file, device|run, device|stop, device|uninstall, doctor, emulate, emulate|android, emulate|ios, error-reporting, help, info, init, install, livesync, platform, platform|add, platform|clean, platform|remove, platform|update, plugin, plugin|add, plugin|find, plugin|remove, plugin|search, prepare, publish, publish|ios, run, run|android, run|ios, test, test|android, test|init, test|ios, usage-reporting
Reading help for command 'doctor'. FileName is 'doctor.md'.
# doctor
┌─────────┬──────────────┐
│ Usage   │ Synopsis     │
│ General │ $ tns doctor │
└─────────┴──────────────┘

Checks your system for configuration problems which might prevent the NativeScript CLI from working properly.

Analytics statuses: 
{ TrackFeatureUsage: 1, TrackExceptions: 1 }
Trying to track exception with message 'Cannot read property 'match' of null'.

```

**Comment by Plamen5kov** [comment]
Behavior in master 2.5, offers to install jdk and can't reproduce the aforementioned error: `TypeError: Cannot read property 'match' of null`
@vchimev can you try reproducing it again with cli from master.

**Comment by pkoleva** [comment]
Reproduced with the latest master of v 2.5.0. On mac the popup leads nowhere, on windows there is no popup, idk if there should be one.

**Comment by vchimev** [comment]
A quick update from my side, as I got the chance to try this case on a clean Windows 10 machine.
On Windows 10 the expected behavior is met and there is a clear message that JKD is not installed.

Output:
```
C:\Users\vchimev\Work>node -v
v6.9.3

C:\Users\vchimev\Work>npm -v
3.10.10

C:\Users\vchimev\Work>tns --version
2.4.2

C:\Users\vchimev\Work>tns doctor
The ANDROID_HOME environment variable is not set or it points to a non-existent directory. You will not be able to perform any build-related operations for Android.
To be able to perform Android build-related operations, set the ANDROID_HOME variable to point to the root of your Android SDK installation directory.

...
...
...

Error executing command 'javac'. Make sure you have installed The Java Development Kit (JDK) and set JAVA_HOME environment variable.
You will not be able to build your projects for Android.
To be able to build for Android, verify that you have installed The Java Development Kit (JDK) and configured it according to system requirements as
 described in https://github.com/NativeScript/nativescript-cli#system-requirements.
```

Only the hyperlink is no more relevant.

I would give again a try on macOS when get the chance.
