### ISSUE TITLE
Nativescript firebase unable to create application

### ISSUE THREAD

**Issue by IvRRimum** [NativeScript/nativescript-cli#1937]
So after adding nativescript-plugin-firebase to my applications, I can't start it anymore. I got this error message when I am trying to open the app in my emulator( android 6 ).
```

07-20 12:56:34.350: I/ActivityManager(1530): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.nativescript.mobile/com.tns.NativeScriptActivity (has extras)} from uid 10007 on display 0
07-20 12:56:34.401: I/ActivityManager(1530): Start proc 5441:org.nativescript.mobile/u0a59 for activity org.nativescript.mobile/com.tns.NativeScriptActivity
07-20 12:56:34.404: I/art(5441): Not late-enabling -Xcheck:jni (already on)
07-20 12:56:34.410: D/AudioFlinger(1222): mixer(0xb44c0000) throttle end: throttle time(264)
07-20 12:56:34.442: D/AudioFlinger(1222): mixer(0xb44c0000) throttle end: throttle time(1)
07-20 12:56:34.566: I/FirebaseInitProvider(5441): FirebaseApp initialization unsuccessful
07-20 12:56:34.732: I/TNS.Native(5441): NativeScript Runtime Version 2.1.1, commit bce725184f249812c73163957aa50aa9339edddb
07-20 12:56:34.732: D/TNS.Native(5441): JNI_ONLoad
07-20 12:56:34.732: D/TNS.Native(5441): JNI_ONLoad END
07-20 12:56:35.099: I/Choreographer(1530): Skipped 33 frames!  The application may be doing too much work on its main thread.
07-20 12:56:35.238: E/Surface(2170): getSlotFromBufferLocked: unknown buffer: 0xa9bd01b0
07-20 12:56:35.340: D/TNS.Native(5441): V8 version 4.7.80
07-20 12:56:35.705: D/TNS.Native(5441): lenNodes=72600, lenNames=694867, lenValues=830135
07-20 12:56:35.705: D/TNS.Native(5441): time=2
07-20 12:56:35.867: D/TNS.Java(5441): Enabling NativeScript Debugger Agent
07-20 12:56:36.531: D/AndroidRuntime(5441): Shutting down VM
07-20 12:56:36.532: W/System.err(5441): java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
07-20 12:56:36.532: W/System.err(5441): Fail to load module: /data/data/org.nativescript.mobile/files/app/main.js
07-20 12:56:36.532: W/System.err(5441): Error: java.lang.ClassNotFoundException: com.tns.FragmentClass
07-20 12:56:36.532: W/System.err(5441):     java.lang.Class.classForName(Native Method)
07-20 12:56:36.532: W/System.err(5441):     java.lang.Class.forName(Class.java:324)
07-20 12:56:36.532: W/System.err(5441):     java.lang.Class.forName(Class.java:285)
07-20 12:56:36.532: W/System.err(5441):     com.tns.Runtime.getClassForName(Runtime.java:772)
07-20 12:56:36.532: W/System.err(5441):     com.tns.ClassResolver.resolveClass(ClassResolver.java:49)
07-20 12:56:36.532: W/System.err(5441):     com.tns.Runtime.resolveClass(Runtime.java:310)
07-20 12:56:36.532: W/System.err(5441):     com.tns.Runtime.runModule(Native Method)
07-20 12:56:36.532: W/System.err(5441):     com.tns.Runtime.runModule(Runtime.java:241)
07-20 12:56:36.532: W/System.err(5441):     com.tns.Runtime.run(Runtime.java:235)
07-20 12:56:36.532: W/System.err(5441):     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
07-20 12:56:36.532: W/System.err(5441):     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
07-20 12:56:36.532: W/System.err(5441):     android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
07-20 12:56:36.533: W/System.err(5441):     android.app.ActivityThread.-wrap1(ActivityThread.java)
07-20 12:56:36.533: W/System.err(5441):     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
07-20 12:56:36.533: W/System.err(5441):     android.os.Handler.dispatchMessage(Handler.java:102)
07-20 12:56:36.533: W/System.err(5441):     android.os.Looper.loop(Looper.java:148)
07-20 12:56:36.533: W/System.err(5441):     android.app.ActivityThread.main(ActivityThread.java:5417)
07-20 12:56:36.533: W/System.err(5441):     java.lang.reflect.Method.invoke(Native Method)
07-20 12:56:36.533: W/System.err(5441):     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-20 12:56:36.533: W/System.err(5441):     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-20 12:56:36.533: W/System.err(5441): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tns.FragmentClass" on path: DexPathList[[zip file "/data/app/org.nativescript.mobile-1/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.mobile-1/lib/x86, /data/app/org.nativescript.mobile-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
07-20 12:56:36.533: W/System.err(5441):     dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-20 12:56:36.533: W/System.err(5441):     java.lang.ClassLoader.loadClass(ClassLoader.java:511)
07-20 12:56:36.533: W/System.err(5441):     java.lang.ClassLoader.loadClass(ClassLoader.java:469)
07-20 12:56:36.533: W/System.err(5441):     java.lang.Class.classForName(Native Method)
07-20 12:56:36.533: W/System.err(5441):     java.lang.Class.forName(Class.java:324)
07-20 12:56:36.533: W/System.err(5441):     java.lang.Class.forName(Class.java:285)
07-20 12:56:36.533: W/System.err(5441):     com.tns.Runtime.getClassForName(Runtime.java:772)
07-20 12:56:36.533: W/System.err(5441):     com.tns.ClassResolver.resolveClass(ClassResolver.java:49)
07-20 12:56:36.533: W/System.err(5441):     com.tns.Runtime.resolveClass(Runtime.java:310)
07-20 12:56:36.533: W/System.err(5441):     com.tns.Runtime.runModule(Native Method)
07-20 12:56:36.533: W/System.err(5441):     com.tns.Runtime.runModule(Runtime.java:241)
07-20 12:56:36.533: W/System.err(5441):     com.tns.Runtime.run(Runtime.java:235)
07-20 12:56:36.533: W/System.err(5441):     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
07-20 12:56:36.533: W/System.err(5441):     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
07-20 12:56:36.535: W/System.err(5441):     android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
07-20 12:56:36.535: W/System.err(5441):     android.app.ActivityThread.-wrap1(ActivityThread.java)
07-20 12:56:36.535: W/System.err(5441):     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
07-20 12:56:36.535: W/System.err(5441):     android.os.Handler.dispatchMessage(Handler.java:102)
07-20 12:56:36.535: W/System.err(5441):     android.os.Looper.loop(Looper.java:148)
07-20 12:56:36.535: W/System.err(5441):     android.app.ActivityThread.main(ActivityThread.java:5417)
07-20 12:56:36.535: W/System.err(5441):     java.lang.reflect.Method.invoke(Native Method)
07-20 12:56:36.535: W/System.err(5441):     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-20 12:56:36.535: W/System.err(5441):     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-20 12:56:36.535: W/System.err(5441): File: "<unknown>, line: 1, column: 265
07-20 12:56:36.535: W/System.err(5441): StackTrace: 
07-20 12:56:36.535: W/System.err(5441): 	Frame: function:'', file:'/data/data/org.nativescript.mobile/files/internal/ts_helpers.js', line: 103, column: 29
07-20 12:56:36.535: W/System.err(5441): 	Frame: function:'DecorateConstructor', file:'/data/data/org.nativescript.mobile/files/app/tns_modules/reflect-metadata/Reflect.js', line: 536, column: 29
07-20 12:56:36.535: W/System.err(5441): 	Frame: function:'decorate', file:'/data/data/org.nativescript.mobile/files/app/tns_modules/reflect-metadata/Reflect.js', line: 98, column: 20
07-20 12:56:36.535: W/System.err(5441): 	Frame: function:'__decorate', file:'/data/data/org.nativescript.mobile/files/internal/ts_helpers.js', line: 14, column: 32
07-20 12:56:36.535: W/System.err(5441): 	Frame: function:'', file:'/data/data/org.nativescript.mobile/files/app/tns_modules/ui/frame/frame.js', line: 564, column: 21
07-20 12:56:36.535: W/System.err(5441): 	Frame: function:'', file:'/data/data/org.nativescript.mobile/files/app/tns_modules/ui/frame/frame.js', line: 568, column: 2
07-20 12:56:36.535: W/System.err(5441): 	Frame: function:'require', file:'', line: 1, column: 266
07-20 12:56:36.535: W/System.err(5441): 	Frame: function:'', file:'/data/data/org.nativescript.mobile/files/app/tns_modules/nativescript-angular/platform-providers.js', line: 2, column: 15
07-20 12:56:36.535: W/System.err(5441): 	Frame: function:'require', file:'', line: 1, column: 266
07-20 12:56:36.535: W/System.err(5441): 	Frame: function:'', file:'/data/data/org.nativescript.mobile/files/app/tns_modules/nativescript-angular/renderer.js', line: 21, column: 28
07-20 12:56:36.535: W/System.err(5441): 	Frame: function:'require', file:'', line: 1, column: 266
07-20 12:56:36.535: W/System.err(5441): 	Frame: function:'', file:'/data/data/org.nativescript.mobile/files/app/tns_modules/nativescript-angular/application.js', line: 11, column: 18
07-20 12:56:36.535: W/System.err(5441): 	Frame: function:'require', file:'', line: 1, column: 266
07-20 12:56:36.535: W/System.err(5441): 	Frame: function:'', file:'/data/data/org.nativescript.mobile/files/app/main.js', line: 3, column: 21
07-20 12:56:36.536: W/System.err(5441): 	Frame: function:'require', file:'', line: 1, column: 266
07-20 12:56:36.536: W/System.err(5441): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
07-20 12:56:36.536: W/System.err(5441): 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
07-20 12:56:36.536: W/System.err(5441): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
07-20 12:56:36.536: W/System.err(5441): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-20 12:56:36.536: W/System.err(5441): 	at android.os.Looper.loop(Looper.java:148)
07-20 12:56:36.536: W/System.err(5441): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
07-20 12:56:36.536: W/System.err(5441): 	at java.lang.reflect.Method.invoke(Native Method)
07-20 12:56:36.536: W/System.err(5441): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-20 12:56:36.536: W/System.err(5441): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-20 12:56:36.536: W/System.err(5441): Caused by: com.tns.NativeScriptException: 
07-20 12:56:36.537: W/System.err(5441): Fail to load module: /data/data/org.nativescript.mobile/files/app/main.js
07-20 12:56:36.537: W/System.err(5441): Error: java.lang.ClassNotFoundException: com.tns.FragmentClass
07-20 12:56:36.537: W/System.err(5441):     java.lang.Class.classForName(Native Method)
07-20 12:56:36.537: W/System.err(5441):     java.lang.Class.forName(Class.java:324)
07-20 12:56:36.537: W/System.err(5441):     java.lang.Class.forName(Class.java:285)
07-20 12:56:36.537: W/System.err(5441):     com.tns.Runtime.getClassForName(Runtime.java:772)
07-20 12:56:36.537: W/System.err(5441):     com.tns.ClassResolver.resolveClass(ClassResolver.java:49)
07-20 12:56:36.537: W/System.err(5441):     com.tns.Runtime.resolveClass(Runtime.java:310)
07-20 12:56:36.537: W/System.err(5441):     com.tns.Runtime.runModule(Native Method)
07-20 12:56:36.537: W/System.err(5441):     com.tns.Runtime.runModule(Runtime.java:241)
07-20 12:56:36.537: W/System.err(5441):     com.tns.Runtime.run(Runtime.java:235)
07-20 12:56:36.537: W/System.err(5441):     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
07-20 12:56:36.537: W/System.err(5441):     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
07-20 12:56:36.537: W/System.err(5441):     android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
07-20 12:56:36.537: W/System.err(5441):     android.app.ActivityThread.-wrap1(ActivityThread.java)
07-20 12:56:36.537: W/System.err(5441):     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
07-20 12:56:36.537: W/System.err(5441):     android.os.Handler.dispatchMessage(Handler.java:102)
07-20 12:56:36.537: W/System.err(5441):     android.os.Looper.loop(Looper.java:148)
07-20 12:56:36.539: W/System.err(5441):     android.app.ActivityThread.main(ActivityThread.java:5417)
07-20 12:56:36.539: W/System.err(5441):     java.lang.reflect.Method.invoke(Native Method)
07-20 12:56:36.541: W/System.err(5441):     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-20 12:56:36.542: W/System.err(5441):     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-20 12:56:36.542: W/System.err(5441): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tns.FragmentClass" on path: DexPathList[[zip file "/data/app/org.nativescript.mobile-1/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.mobile-1/lib/x86, /data/app/org.nativescript.mobile-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
07-20 12:56:36.543: W/System.err(5441):     dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-20 12:56:36.543: W/System.err(5441):     java.lang.ClassLoader.loadClass(ClassLoader.java:511)
07-20 12:56:36.543: W/System.err(5441):     java.lang.ClassLoader.loadClass(ClassLoader.java:469)
07-20 12:56:36.543: W/System.err(5441):     java.lang.Class.classForName(Native Method)
07-20 12:56:36.543: W/System.err(5441):     java.lang.Class.forName(Class.java:324)
07-20 12:56:36.543: W/System.err(5441):     java.lang.Class.forName(Class.java:285)
07-20 12:56:36.543: W/System.err(5441):     com.tns.Runtime.getClassForName(Runtime.java:772)
07-20 12:56:36.543: W/System.err(5441):     com.tns.ClassResolver.resolveClass(ClassResolver.java:49)
07-20 12:56:36.543: W/System.err(5441):     com.tns.Runtime.resolveClass(Runtime.java:310)
07-20 12:56:36.543: W/System.err(5441):     com.tns.Runtime.runModule(Native Method)
07-20 12:56:36.543: W/System.err(5441):     com.tns.Runtime.runModule(Runtime.java:241)
07-20 12:56:36.543: W/System.err(5441):     com.tns.Runtime.run(Runtime.java:235)
07-20 12:56:36.543: W/System.err(5441):     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
07-20 12:56:36.544: W/System.err(5441):     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
07-20 12:56:36.544: W/System.err(5441):     android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
07-20 12:56:36.544: W/System.err(5441):     android.app.ActivityThread.-wrap1(ActivityThread.java)
07-20 12:56:36.544: W/System.err(5441):     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
07-20 12:56:36.544: W/System.err(5441):     android.os.Handler.dispatchMessage(Handler.java:102)
07-20 12:56:36.544: W/System.err(5441):     android.os.Looper.loop(Looper.java:148)
07-20 12:56:36.544: W/System.err(5441):     android.app.ActivityThread.main(ActivityThread.java:5417)
07-20 12:56:36.544: W/System.err(5441):     java.lang.reflect.Method.invoke(Native Method)
07-20 12:56:36.544: W/System.err(5441):     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-20 12:56:36.544: W/System.err(5441):     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-20 12:56:36.544: W/System.err(5441): File: "<unknown>, line: 1, column: 265
07-20 12:56:36.545: W/System.err(5441): StackTrace: 
07-20 12:56:36.545: W/System.err(5441): 	Frame: function:'', file:'/data/data/org.nativescript.mobile/files/internal/ts_helpers.js', line: 103, column: 29
07-20 12:56:36.547: W/System.err(5441): 	Frame: function:'DecorateConstructor', file:'/data/data/org.nativescript.mobile/files/app/tns_modules/reflect-metadata/Reflect.js', line: 536, column: 29
07-20 12:56:36.547: W/System.err(5441): 	Frame: function:'decorate', file:'/data/data/org.nativescript.mobile/files/app/tns_modules/reflect-metadata/Reflect.js', line: 98, column: 20
07-20 12:56:36.547: W/System.err(5441): 	Frame: function:'__decorate', file:'/data/data/org.nativescript.mobile/files/internal/ts_helpers.js', line: 14, column: 32
07-20 12:56:36.547: W/System.err(5441): 	Frame: function:'', file:'/data/data/org.nativescript.mobile/files/app/tns_modules/ui/frame/frame.js', line: 564, column: 21
07-20 12:56:36.547: W/System.err(5441): 	Frame: function:'', file:'/data/data/org.nativescript.mobile/files/app/tns_modules/ui/frame/frame.js', line: 568, column: 2
07-20 12:56:36.547: W/System.err(5441): 	Frame: function:'require', file:'', line: 1, column: 266
07-20 12:56:36.547: W/System.err(5441): 	Frame: function:'', file:'/data/data/org.nativescript.mobile/files/app/tns_modules/nativescript-angular/platform-providers.js', line: 2, column: 15
07-20 12:56:36.547: W/System.err(5441): 	Frame: function:'require', file:'', line: 1, column: 266
07-20 12:56:36.547: W/System.err(5441): 	Frame: function:'', file:'/data/data/org.nativescript.mobile/files/app/tns_modules/nativescript-angular/renderer.js', line: 21, column: 28
07-20 12:56:36.547: W/System.err(5441): 	Frame: function:'require', file:'', line: 1, column: 266
07-20 12:56:36.547: W/System.err(5441): 	Frame: function:'', file:'/data/data/org.nativescript.mobile/files/app/tns_modules/nativescript-angular/application.js', line: 11, column: 18
07-20 12:56:36.547: W/System.err(5441): 	Frame: function:'require', file:'', line: 1, column: 266
07-20 12:56:36.547: W/System.err(5441): 	Frame: function:'', file:'/data/data/org.nativescript.mobile/files/app/main.js', line: 3, column: 21
07-20 12:56:36.547: W/System.err(5441): 	Frame: function:'require', file:'', line: 1, column: 266
07-20 12:56:36.548: W/System.err(5441): 	at com.tns.Runtime.runModule(Native Method)
07-20 12:56:36.548: W/System.err(5441): 	at com.tns.Runtime.runModule(Runtime.java:241)
07-20 12:56:36.548: W/System.err(5441): 	at com.tns.Runtime.run(Runtime.java:235)
07-20 12:56:36.548: W/System.err(5441): 	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
07-20 12:56:36.548: W/System.err(5441): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
07-20 12:56:36.548: W/System.err(5441): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
07-20 12:56:36.548: W/System.err(5441): 	... 8 more
07-20 12:56:36.548: W/System.err(5441): Caused by: java.lang.ClassNotFoundException: com.tns.FragmentClass
07-20 12:56:36.548: W/System.err(5441): 	at java.lang.Class.classForName(Native Method)
07-20 12:56:36.550: W/System.err(5441): 	at java.lang.Class.forName(Class.java:324)
07-20 12:56:36.550: W/System.err(5441): 	at java.lang.Class.forName(Class.java:285)
07-20 12:56:36.551: W/System.err(5441): 	at com.tns.Runtime.getClassForName(Runtime.java:772)
07-20 12:56:36.551: W/System.err(5441): 	at com.tns.ClassResolver.resolveClass(ClassResolver.java:49)
07-20 12:56:36.551: W/System.err(5441): 	at com.tns.Runtime.resolveClass(Runtime.java:310)
07-20 12:56:36.551: W/System.err(5441): 	... 14 more
07-20 12:56:36.551: W/System.err(5441): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tns.FragmentClass" on path: DexPathList[[zip file "/data/app/org.nativescript.mobile-1/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.mobile-1/lib/x86, /data/app/org.nativescript.mobile-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
07-20 12:56:36.551: W/System.err(5441): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-20 12:56:36.551: W/System.err(5441): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
07-20 12:56:36.552: W/System.err(5441): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
07-20 12:56:36.552: W/System.err(5441): 	... 20 more
07-20 12:56:36.552: W/System.err(5441): 	Suppressed: java.lang.ClassNotFoundException: com.tns.FragmentClass
07-20 12:56:36.552: W/System.err(5441): 		at java.lang.Class.classForName(Native Method)
07-20 12:56:36.552: W/System.err(5441): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
07-20 12:56:36.552: W/System.err(5441): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
07-20 12:56:36.552: W/System.err(5441): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
07-20 12:56:36.553: W/System.err(5441): 		... 21 more
07-20 12:56:36.553: W/System.err(5441): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
07-20 12:56:36.569: I/ActivityManager(1530): START u0 {flg=0x14008000 cmp=org.nativescript.mobile/com.tns.ErrorReportActivity (has extras)} from uid 10059 on display 0
07-20 12:56:36.875: I/WindowManager(1530): Screenshot max retries 4 of Token{202c286 ActivityRecord{6f56761 u0 org.nativescript.mobile/com.tns.NativeScriptActivity t40 f}} appWin=Window{e999c5e u0 Starting org.nativescript.mobile} drawState=4
07-20 12:56:36.883: I/Process(5441): Sending signal. PID: 5441 SIG: 9
07-20 12:56:36.955: I/ActivityManager(1530): Process org.nativescript.mobile (pid 5441) has died
07-20 12:56:36.969: I/art(5462): Not late-enabling -Xcheck:jni (already on)
07-20 12:56:37.021: I/ActivityManager(1530): Start proc 5462:org.nativescript.mobile/u0a59 for activity org.nativescript.mobile/com.tns.ErrorReportActivity
07-20 12:56:37.073: I/FirebaseInitProvider(5462): FirebaseApp initialization unsuccessful
07-20 12:56:37.158: I/TNS.Native(5462): NativeScript Runtime Version 2.1.1, commit bce725184f249812c73163957aa50aa9339edddb
07-20 12:56:37.158: D/TNS.Native(5462): JNI_ONLoad
07-20 12:56:37.158: D/TNS.Native(5462): JNI_ONLoad END
07-20 12:56:37.358: E/SurfaceFlinger(1208): ro.sf.lcd_density must be defined as a build property
07-20 12:56:37.360: D/OpenGLRenderer(5462): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
07-20 12:56:37.548: D/(5462): HostConnection::get() New Host Connection established 0xaa1a8a70, tid 5462
07-20 12:56:37.833: D/(5462): HostConnection::get() New Host Connection established 0xaa1a8c20, tid 5477
07-20 12:56:37.839: I/OpenGLRenderer(5462): Initialized EGL, version 1.4
07-20 12:56:38.235: I/ActivityManager(1530): Displayed org.nativescript.mobile/com.tns.ErrorReportActivity: +1s277ms (total +3s844ms)
07-20 12:57:28.561: I/perfprofd(1231): profile collection skipped (running in emulator)
07-20 12:57:44.473: I/ProcessStatsService(1530): Prepared write state in 1ms
07-20 12:57:44.474: I/ProcessStatsService(1530): Prepared write state in 1ms
07-20 13:14:17.717: I/UsageStatsService(1530): User[0] Flushing usage stats to disk
```

**Comment by enchev** [comment]
This issue was moved to EddyVerbruggen/nativescript-plugin-firebase#79
