### ISSUE TITLE
Exception on newly created project - both --tsc and --ng

### ISSUE THREAD

**Issue by jvzanatta** [NativeScript/nativescript-cli#1938]
Hi. I'm having this weird log when create a new project with **tns create AppName --ng** and then run with **tns build android**. Same happens if i change --ng for --tsc. Any workarounds?

Thanks in advance.

```
JS: EXCEPTION: Error: Uncaught (in promise): TypeError: this.page.frame._getNavBarVisible is not a function
JS: STACKTRACE:
JS: Error: Uncaught (in promise): TypeError: this.page.frame._getNavBarVisible is not a function
JS:     at resolvePromise (/data/data/org.nativescript.TCCTreino/files/app/tns_modules/zone.js/dist/zone-node.js:496:32)
JS:     at /data/data/org.nativescript.TCCTreino/files/app/tns_modules/zone.js/dist/zone-node.js:473:14
JS:     at ZoneDelegate.invoke (/data/data/org.nativescript.TCCTreino/files/app/tns_modules/zone.js/dist/zone-node.js:281:29)
JS:     at Object.NgZoneImpl.inner.inner.fork.onInvoke (/data/data/org.nativescript.TCCTreino/files/app/tns_modules/@angular/core/src/zone/ng_zone_impl.js:46:41)
JS:     at ZoneDelegate.invoke (/data/data/org.nativescript.TCCTreino/files/app/tns_modules/zone.js/dist/zone-node.js:280:35)
JS:     at Zone.run (/data/data/org.nativescript.TCCTreino/files/app/tns_modules/zone.js/dist/zone-node.js:174:44)
JS:     at /data/data/org.nativescript.TCCTreino/files/app/tns_modules/zone.js/dist/zone-node.js:529:58
JS:     at ZoneDelegate.invokeTask (/data/data/org.nativescript.TCCTreino/files/app/tns_modules/zone.js/dist/zone-node.js:314:38)
JS:     at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (/data/data/org.nativescript.TCCTreino/files/app/tns_modules/@angular/core/src/zone/ng_zone_impl.js:37:41)
JS:     at ZoneDelegate.invokeTask (/data/data/org.nativescript.TCCTreino/files/app/tns_modules/zone.js/dist/zone-node.js:313:43)
JS: Unhandled Promise rejection: this.page.frame._getNavBarVisible is not a function ; Zone: angular ; Task: Promise.then ; Value: TypeError: this.page.frame._getNavBarVisible is not a function
JS: Error: Uncaught (in promise): TypeError: this.page.frame._getNavBarVisible is not a function
JS: Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
JS: Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
JS: Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
```

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-angular#358
