### ISSUE TITLE
Issue with tns platform add android

### ISSUE THREAD

**Issue by hankey48756** [NativeScript/nativescript-cli#1946]
hello, i am a beginner with the mobile environment.  i am having an issue with one of the sample app when i was trying to add the platform.

this is the log i am getting, and can anyone please give me some suggestion.  thanks a million!!
```
G:\My Apps\Project>cd cuteness

G:\My Apps\Project\Cuteness>cd nativescript-sample-cuteness

G:\My Apps\Project\Cuteness\nativescript-sample-cuteness>git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.

G:\My Apps\Project\Cuteness\nativescript-sample-cuteness>tns add android
Unknown command 'add'. Use 'tns help' for help.

G:\My Apps\Project\Cuteness\nativescript-sample-cuteness>tns platform add android
No project found at or above 'G:\My Apps\Project\Cuteness\nativescript-sample-cuteness' and neither was a --path specified.
# platform add
┌──────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Usage                    │ Synopsis                                                                                                                                        │
│ Android latest runtime   │ $ tns platform add android [--framework-path <File Path>] [--symlink] [--sdk <API Level>] [--platform-template <Platform Template>]             │
│ Android selected runtime │ $ tns platform add android[@<Version>] [--framework-path <File Path>] [--symlink] [--sdk <API Level>] [--platform-template <Platform Template>] │
└──────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

Configures the current project to target the selected platform.

### Options

    * --framework-path - Sets the path to a NativeScript runtime for the specified platform that you want to use instead of the default runtime. If --symlink is specified, <File Path> must point to directory in which the runtime is already extracted. If --symlink is not specified, <File Path> must point to a valid npm package.
    * --symlink - Creates a symlink to a NativeScript runtime for the specified platform that you want to use instead of the default runtime. If --frameworkPath is specified, creates a symlink to the specified directory. If --frameworkPath is not specified, creates a symlink to platform runtime installed with your current version of NativeScript.
    * --sdk - Sets the target Android SDK for the project.
    * --platform-template - Sets the platform template that will be used for the native application.

### Attributes

    * <API Level> is a valid Android API level. For example: 17, 19, MNC.
    * <File Path> is the complete path to a valid npm package or a directory that contains a NativeScript runtime for the selected platform.
    * <Platform Template> is a valid npm package, path to directory, .tgz or GitHub URL that contains a native Android or iOS template.
    * <Version> is any available version of the respective platform runtime published in npm.


G:\My Apps\Project\Cuteness\nativescript-sample-cuteness>tns platform add android --log trace > out.txt
Error: No project found at or above 'G:\My Apps\Project\Cuteness\nativescript-sample-cuteness' and neither was a --path specified.
    at Object.<anonymous> (C:\Users\Win10Pro\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:7:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Win10Pro\AppData\Roaming\npm\node_modules\nativescript\lib\nativescript-cli.js:9:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

G:\My Apps\Project\Cuteness\nativescript-sample-cuteness>
```

**Comment by NickIliev** [comment]
Hello @hankey48756 

From your log error, it seems that you are trying to run NativeScript command in a directory where there is no NativeScript project present (or valid package.json for your project).

Which repository have you cloned? Is there a project directory inside with valid package.json.
If you are seeking for good tutorials and sample apps I recommend the following links:

[http://docs.nativescript.org/tutorial/chapter-1](http://docs.nativescript.org/tutorial/chapter-1) - the getting started tutorial for NativeScript core.

[https://www.nativescript.org/app-samples-with-code](https://www.nativescript.org/app-samples-with-code) - NativeScript sample apps 

[some NativeScript demo apps uncluding cuteness ](https://github.com/NickIliev/NativeScript-demos)

**Comment by zhangsuimi** [comment]
Me too!I download a ZIP ,and try to run it on my computer using VS Code.

[NativeScriptCli] execute: tns --analyticsClient VSCode --version
[NSDebugAdapter] Using tns CLI v4.0.0 on path 'tns'
[NSDebugAdapter] Running tns command...
[NativeScriptCli] execute: tns --analyticsClient VSCode debug android --no-client --watch 
[NSDebugAdapter] Watching the tns CLI output to receive a connection token
[31;1mNo project found at or above 'C:\Users\lenovo\iss2015302580302-U_cha-master' and neither was a --path specified.
# tns debug android

==========

┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────┐
│ Usage                                                                                                                   │ Synopsis                                                                     │
│ Deploy on device/emulator, run the app, follow generated link to use in Chrome Developer Tools, and attach the debugger │ $ tns debug android                                                          │
│ Deploy on device/emulator, run the app and stop at the first code statement                                             │ $ tns debug android --debug-brk [--device <Device ID>] [--timeout <timeout>] │
│ Deploy in the native emulator, run the app and stop at the first code statement                                         │ $ tns debug android --debug-brk --emulator [--timeout <timeout>]             │
│ Attach the debug tools to a running app on device/emulator                                                              │ $ tns debug android --start [--device <Device ID>] [--timeout <timeout>]     │
│ Attach the debug tools to a running app in the native emulator                                                          │ $ tns debug android --start --emulator [--timeout <timeout>]                 │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────┘

Prepares, builds and deploys the project when necessary. Debugs your project on a connected device or emulator.
While debugging, prints the output from the application in the console and watches for changes in your code. Once a change is detected, it synchronizes the change with the selected device and restarts the application.

### Options

    * --device - Specifies a connected device/emulator on which to debug the app.
    * --emulator - Specifies that you want to debug the app in the native Android emulator.
    * --debug-brk - Prepares, builds and deploys the application package on a device/emulator, generates a link for Chrome Developer Tools and stops at the first code statement.
    * --start - Attaches the debug tools to a deployed and running app.
    * --timeout - Sets the number of seconds that the NativeScript CLI will wait for the emulator/device to boot. If not set, the default timeout is 90 seconds.
    * --no-watch - If set, changes in your code will not be reflected during the execution of this command.
    * --clean - If set, forces rebuilding the native application.

### Attributes

    * <Device ID> is the device identifier or name of the target device as listed by $ tns device android

[NSDebugAdapter] The tns command finished its execution with code 127.
Error: Unknown signal: SIGQUIT

**Comment by AbdoQ** [comment]
I am facing this problem now, using sidekick with cloud builds, my log says:

[19-01-01 06:35:55.871] Build started.
[19-01-01 06:35:55.883] (CLI) Executing before-watchPatterns hook from /home/abdo/Documents/software/DrApp/DrApp/hooks/before-watchPatterns/nativescript-dev-sass.js
[19-01-01 06:35:55.888] (CLI) Executing before-watchPatterns hook from /home/abdo/Documents/software/DrApp/DrApp/hooks/before-watchPatterns/nativescript-dev-webpack.js
[19-01-01 06:35:55.888] (CLI) Executing before-watch hook from /home/abdo/Documents/software/DrApp/DrApp/hooks/before-watch/nativescript-dev-sass.js
[19-01-01 06:35:55.917] (CLI) Found peer node-sass
[19-01-01 06:35:57.180] (CLI) Executing before-watch hook from /home/abdo/Documents/software/DrApp/DrApp/hooks/before-watch/nativescript-dev-webpack.js
[19-01-01 06:35:57.684] (CLI) Executing before-shouldPrepare hook from /home/abdo/Documents/software/DrApp/DrApp/hooks/before-shouldPrepare/nativescript-dev-webpack.js
[19-01-01 06:35:57.690] (CLI) Executing before-prepare hook from /home/abdo/Documents/software/DrApp/DrApp/hooks/before-prepare/nativescript-dev-sass.js
[19-01-01 06:35:57.690] (CLI) Hook skipped because either bundling or livesync is in progress.
[19-01-01 06:35:57.690] (CLI) Preparing project...
[19-01-01 06:35:57.690] (CLI) Executing before-prepareJSApp hook from /home/abdo/Documents/software/DrApp/DrApp/hooks/before-prepareJSApp/nativescript-dev-webpack.js
[19-01-01 06:35:57.783] (CLI) Project successfully prepared (Android)
[19-01-01 06:35:57.791] (CLI) Executing after-prepare hook from /home/abdo/Documents/software/DrApp/DrApp/hooks/after-prepare/nativescript-dev-sass.js
[19-01-01 06:35:57.791] (CLI) Executing after-prepare hook from /home/abdo/Documents/software/DrApp/DrApp/hooks/after-prepare/nativescript-dev-webpack.js
[19-01-01 06:36:04.988] (CLI) Getting accounts information...
[19-01-01 06:36:08.682] (CLI) Using account de177c5ea3714188a8056cd5551099b5.
[19-01-01 06:36:08.682] (CLI) Starting cloud build of '/home/abdo/Documents/software/DrApp/DrApp', platform: 'Android', configuration: 'Debug', buildId: e2d0a581-02d4-4f6b-a5c3-f9cc73c4838a.
[19-01-01 06:36:08.692] Prepare step started.
[19-01-01 06:36:09.044] (CLI) Executing before-shouldPrepare hook from /home/abdo/Documents/software/DrApp/DrApp/hooks/before-shouldPrepare/nativescript-dev-webpack.js
[19-01-01 06:36:09.044] (CLI) Skipping prepare.
[19-01-01 06:36:09.048] Prepare step completed.
[19-01-01 06:36:12.572] Upload step started.
[19-01-01 06:36:18.735] Upload step completed.
[19-01-01 06:36:20.478] Build step started.
[19-01-01 06:36:32.963] (CLI) GRADLE_USER_HOME is /opt/docker_shared/SUzZd7mXPRT3GpBh6C.gradle
[19-01-01 06:36:34.616] (CLI) android Build Tooling revision 2018.12.11.1 origin/release-v2
[19-01-01 06:36:34.616] (CLI)   Build Tooling Hostname 1e6d83db87f2
[19-01-01 06:36:34.616] (CLI)  App package not specified. Skipping unzip step.
[19-01-01 06:36:34.616] (CLI)   NativeScript CLI version 5.0.3
[19-01-01 06:36:34.616] (CLI)  Add platform android with runtime version 5.0.0
[19-01-01 06:36:40.529] (CLI) No project found at or above '/mnt/storage/builds/_/1a89ccf896d256227efb40fe7cc4ec7912e4a6b5/5.0.3/5.0.0/DrApp' and neither was a --path specified.
[19-01-01 06:36:40.529] (CLI)  # tns platform add
[19-01-01 06:36:40.529] (CLI) ### Description
[19-01-01 06:36:40.529] (CLI) Configures the current project to target the selected platform.
[19-01-01 06:36:40.529] (CLI) ### Commands
[19-01-01 06:36:40.529] (CLI) ┌──────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
[19-01-01 06:36:40.529] (CLI) │ Usage                    │ Synopsis                                                                                                                                        │
[19-01-01 06:36:40.529] (CLI) │ Android latest runtime   │ $ tns platform add android [--framework-path <File Path>] [--symlink] [--sdk <API Level>] [--platform-template <Platform Template>]             │
[19-01-01 06:36:40.529] (CLI) │ Android selected runtime │ $ tns platform add android[@<Version>] [--framework-path <File Path>] [--symlink] [--sdk <API Level>] [--platform-template <Platform Template>] │
[19-01-01 06:36:40.529] (CLI) └──────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
[19-01-01 06:36:40.529] (CLI) ### Options
[19-01-01 06:36:40.529] (CLI)     * --framework-path - Sets the path to a NativeScript runtime for the specified platform that you want to use instead of the default runtime. If --symlink is specified, <File Path> is the complete path to a valid npm package or a directory that contains a NativeScript runtime for the selected platform and must point to directory in which the runtime is already extracted. If --symlink is not specified, <File Path> must point to a valid npm package.
[19-01-01 06:36:40.529] (CLI)     * --symlink - Creates a symlink to a NativeScript runtime for the specified platform that you want to use instead of the default runtime. If --frameworkPath is specified, creates a symlink to the specified directory. If --frameworkPath is not specified, creates a symlink to platform runtime installed with your current version of NativeScript.
[19-01-01 06:36:40.529] (CLI)     * --sdk - Sets the target Android SDK for the project. <API Level> is a valid Android API level. For example: 17, 19, MNC.
[19-01-01 06:36:40.529] (CLI)     * --platform-template - Sets the platform template that will be used for the native application. <Platform Template> is a valid npm package, path to directory, .tgz or GitHub URL that contains a native Android or iOS template.
[19-01-01 06:36:40.529] (CLI) ### Arguments
[19-01-01 06:36:40.529] (CLI)     * <Version> is any available version of the respective platform runtime published in npm.
[19-01-01 06:36:40.529] (CLI) No project found at or above '/mnt/storage/builds/_/1a89ccf896d256227efb40fe7cc4ec7912e4a6b5/5.0.3/5.0.0/DrApp' and neither was a --path specified.
[19-01-01 06:36:40.529] (CLI) bc_SUzZd7mXPRT3GpBh6C
[19-01-01 06:36:45.133] (CLI) Unable to apply changes on device: Y7L7N15805000724. Error is: Build failed..
[19-01-01 06:36:45.137] (CLI) Executing after-watch hook from /home/abdo/Documents/software/DrApp/DrApp/hooks/after-watch/nativescript-dev-sass.js
[19-01-01 06:36:45.145] Error detected during LiveSync on Y7L7N15805000724 for /home/abdo/Documents/software/DrApp/DrApp. Error: Build failed.
[19-01-01 06:36:45.153] Stopped LiveSync on Y7L7N15805000724 for /home/abdo/Documents/software/DrApp/DrApp.
[19-01-01 06:36:45.157] (CLI) Executing after-watch hook from /home/abdo/Documents/software/DrApp/DrApp/hooks/after-watch/nativescript-dev-webpack.js
[19-01-01 06:36:45.157] (CLI) Stopping webpack watch
[19-01-01 06:36:45.157] (CLI) Executing after-watch hook from /home/abdo/Documents/software/DrApp/DrApp/hooks/after-watch/nativescript-dev-sass.js
[19-01-01 06:36:45.157] (CLI) Executing after-watch hook from /home/abdo/Documents/software/DrApp/DrApp/hooks/after-watch/nativescript-dev-webpack.js
[19-01-01 06:36:45.157] (CLI) Stopping webpack watch
