### ISSUE TITLE
java.lang.OutOfMemoryError after upgrade to 2.2.0

### ISSUE THREAD

**Issue by ryc16** [NativeScript/nativescript-cli#1995]
Just got upgrade to latest 2.2.0. After the upgrade, I got below problem java.lang.OutOfMemoryError where wasn't have problem before. It happens from main screen contains list view item, then got crashed when click on the item to navigate to details page. Please advice if it is better to downgrade all three of them (nativescript, tns-core-modules, tns-android) or just one or two components?

Failed on my detial page with image.

`      <StackLayout class="header-container" row="0" backgroundImage="~/res/my.jpg">`

```
E/dalvikvm-heap( 2456): Out of memory on a 12203712-byte allocation.
I/dalvikvm( 2456): "main" prio=5 tid=1 RUNNABLE
I/dalvikvm( 2456):   | group="main" sCount=0 dsCount=0 obj=0xb0d67bd8 self=0xb8c194a0
I/dalvikvm( 2456):   | sysTid=2456 nice=0 sched=0/0 cgrp=[fopen-error:2] handle=-1216524192
I/dalvikvm( 2456):   | state=R schedstat=( 0 0 0 ) utm=230 stm=211 core=0
I/dalvikvm( 2456):   at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
I/dalvikvm( 2456):   at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:613)
I/dalvikvm( 2456):   at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:589)
I/dalvikvm( 2456):   at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:369)
I/dalvikvm( 2456):   at com.tns.Runtime.callJSMethodNative(Native Method)
I/dalvikvm( 2456):   at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:862)
I/dalvikvm( 2456):   at com.tns.Runtime.callJSMethodImpl(Runtime.java:727)
I/dalvikvm( 2456):   at com.tns.Runtime.callJSMethod(Runtime.java:713)
I/dalvikvm( 2456):   at com.tns.Runtime.callJSMethod(Runtime.java:694)
I/dalvikvm( 2456):   at com.tns.Runtime.callJSMethod(Runtime.java:684)
I/dalvikvm( 2456):   at com.tns.gen.android.widget.AdapterView_OnItemClickListener.onItemClick(AdapterView_OnItemClickListener.java:14)

D/skia    ( 2456): --- decoder->decode returned false
D/AndroidRuntime( 2456): Shutting down VM
W/dalvikvm( 2456): threadid=1: thread exiting with uncaught exception (group=0xb0d66b20)
W/System.err( 2456): com.tns.NativeScriptException:
W/System.err( 2456): Calling js method onItemClick failed
W/System.err( 2456): Error: Building UI from XML. @file:///app/./pages/contact/contact-details.xml:4:7
W/System.err( 2456):  ↳java.lang.OutOfMemoryError
W/System.err( 2456):       android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
W/System.err( 2456):     android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:613)
W/System.err( 2456):     android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:589)
W/System.err( 2456):     android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:369)
W/System.err( 2456):     com.tns.Runtime.callJSMethodNative(Native Method)
W/System.err( 2456):     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:862)
W/System.err( 2456):     com.tns.Runtime.callJSMethodImpl(Runtime.java:727)
W/System.err( 2456):     com.tns.Runtime.callJSMethod(Runtime.java:713)
W/System.err( 2456):     com.tns.Runtime.callJSMethod(Runtime.java:694)
W/System.err( 2456):     com.tns.Runtime.callJSMethod(Runtime.java:684)
W/System.err( 2456):     com.tns.gen.android.widget.AdapterView_OnItemClickListener.onItemClick(AdapterView_OnItemClickListener.java:14)

java.lang.OutOfMemoryError
W/System.err( 2456):       android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
W/System.err( 2456):     android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:613)
W/System.err( 2456):     android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:589)
W/System.err( 2456):     android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:369)
W/System.err( 2456):     com.tns.Runtime.callJSMethodNative(Native Method)
W/System.err( 2456):     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:862)
W/System.err( 2456):     com.tns.Runtime.callJSMethodImpl(Runtime.java:727)
W/System.err( 2456):     com.tns.Runtime.callJSMethod(Runtime.java:713)
W/System.err( 2456):     com.tns.Runtime.callJSMethod(Runtime.java:694)
W/System.err( 2456):     com.tns.Runtime.callJSMethod(Runtime.java:684)
```

```
>tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 2.2.0           │ 2.2.0          │ Up to date    │
│ tns-core-modules │ 2.2.0           │ 2.2.0          │ Up to date    │
│ tns-android      │ 2.2.0           │ 2.2.0          │ Up to date    │
│ tns-ios          │                 │ 2.2.0          │ Not installed │
└──────────────────┴─────────────────┴────────────────┴───────────────┘

```

**Comment by ryc16** [comment]
Hi, I followed the instruction to downgrade {N} back to 2.1.1 http://fluentreports.com/blog/?p=303

>npm remove -g nativescript
>npm remove tns-core-modules
>npm install -g nativescript@2.1.1
>npm install tns-core-modules@2.1.0
>tns platform remove android
>tns platform add android@2.1.1

However, I continue to get the problem OutOfMemory error. Any idea what is missing from downgrade process.

Note: I do remove/uninstall from emulator and device before run it again.
Note: I do have another computer without upgrade to 2.2.0 and everything works. This indicates there is problem on 2.2.0 and downgrade seem not clear or failed.

**Comment by enchev** [comment]
@ryc16 In my opinion this problem is not related to the {N} version but mostly related to running out of memory because of large bitmap. Can you check how much memory your emulator is allowed to use on both machines?

**Comment by ryc16** [comment]
@enchev, it is 64MB heap. I put my measurement on https://github.com/NativeScript/NativeScript/issues/2571. From my measurement, v2.2.0 eats up memory significantly (I believe dealing with image too). You could close this issue and comment on #2571.

By the way, need your suggestion to do deep memory profiling for object allocation.
