### ISSUE TITLE
tests with tns-android 2.2.0 not working

### ISSUE THREAD

**Issue by hypery2k** [NativeScript/nativescript-cli#2021]
always getting error when running *tns test android --bundle --emulator --justlaunch*
```
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: metadata file (treeNodeStream.dat) couldn't be opened!
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4556)
at android.app.ActivityThread.access$1500(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: com.tns.NativeScriptException: metadata file (treeNodeStream.dat) couldn't be opened!
at com.tns.Runtime.initNativeScript(Native Method)
at com.tns.Runtime.init(Runtime.java:197)
at com.tns.Runtime.init(Runtime.java:162)
at com.tns.RuntimeHelper.initRuntime(RuntimeHelper.java:131)
at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:15)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
... 9 more
```

It also doesn't matter if I try it on the emulator, real device or genymotion

**Comment by SvetoslavTsenov** [comment]
Hi @hypery2k,
We are working on the bundling command and running tests with "--bundle" option is still not implemented.

**Comment by hypery2k** [comment]
but I can use for the build alias, or?

**Comment by SvetoslavTsenov** [comment]
Currently, you can use the --bundle option with the run command:
tns run android --bundle but when using the test command, skip the --bundle option.
You can read more about this here: [Using Webpack to Bundle Your Code](https://docs.nativescript.org/tooling/bundling-with-webpack)
