### ISSUE TITLE
(node) warning: possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by roblav96** [NativeScript/nativescript-cli#2033]
```
Executing before-prepare hook from /Volumes/OSX HD/Projects/screenshotty/client/hooks/before-prepare/nativescript-dev-typescript.js
Project successfully prepared (ios)
Transferring project files...
Successfully transferred screenshot.component.js.
Applying changes...
(node) warning: possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.addListener (events.js:239:17)
    at WriteStream.Readable.on (_stream_readable.js:680:33)
    at WriteStream.once (events.js:265:8)
    at GDBStandardOutputAdapter.Readable.pipe (_stream_readable.js:589:8)
    at /usr/local/lib/node_modules/nativescript/lib/common/mobile/ios/device/ios-core.js:1055:71
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/mobile/ios/device/ios-application-manager.js:149:53
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service-base.js:207:147
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at /usr/local/lib/node_modules/nativescript/lib/common/mobile/mobile-core/devices-service.js:260:28
    at arrayMap (/usr/local/lib/node_modules/nativescript/node_modules/lodash/lodash.js:574:23)
    at Function.map (/usr/local/lib/node_modules/nativescript/node_modules/lodash/lodash.js:8851:14)
    at /usr/local/lib/node_modules/nativescript/lib/common/mobile/mobile-core/devices-service.js:257:29
```

Not a big deal considering my desktop has 32gb of RAM, but some people don't so I figured I'd drop this here.

**Comment by tzraikov** [comment]
@roblav96 Please could you post here the exact CLI command that you are running?

**Comment by roblav96** [comment]
`tns livesync ios --watch` with my device plugged in via USB.

**Comment by tzraikov** [comment]
@roblav96 I was not able to reproduce the issue with the latest release - 2.3.0. Please, could you confirm that the issue still occurs when using the latest release?

**Comment by roblav96** [comment]
@tzraikov I'm not getting that specific error anymore, but since updating to `2.3.0` I'm getting a new memory leak error everytime I run `tns livesync <platform> --watch`

## Error
```shell
<--- Last few GCs --->

   34333 ms: Mark-sweep 1302.5 (1438.6) -> 1302.5 (1438.6) MB, 1193.3 / 0.0 ms [allocation failure] [GC in old space requested].
   35573 ms: Mark-sweep 1302.5 (1438.6) -> 1302.6 (1438.6) MB, 1240.0 / 0.0 ms [allocation failure] [GC in old space requested].
   36761 ms: Mark-sweep 1302.6 (1438.6) -> 1308.7 (1421.6) MB, 1187.4 / 0.0 ms [last resort gc].
   38056 ms: Mark-sweep 1308.7 (1421.6) -> 1315.0 (1421.6) MB, 1295.0 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x331d839cfb51 <JS Object>
    1: createSymbolTable [/Users/roblav96/Downloads/actions/node_modules/typescript/lib/tsc.js:14351] [pc=0x1c8fee732809] (this=0x331d839e6ee9 <JS Global Object>,symbols=0xe4c1438e969 <JS Array[4]>)
    2: resolveObjectTypeMembers [/Users/roblav96/Downloads/actions/node_modules/typescript/lib/tsc.js:~14388] [pc=0x1c8feeb3de59] (this=0x331d839e6ee9 <JS Global Object>,type=0x3381919f44b1 <a Type ...


FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 
node::Abort() [/usr/local/bin/node]
```

### `node_modules/typescript/lib/tsc.js:14351`
```javascript
function createSymbolTable(symbols) {
    var result = {};
    for (var _i = 0, symbols_1 = symbols; _i < symbols_1.length; _i++) {
        var symbol = symbols_1[_i];
        result[symbol.name] = symbol; // << THIS IS LINE 14351
    }
    return result;
}
```

### `node_modules/typescript/lib/tsc.js:~14388`
```javascript
function resolveObjectTypeMembers(type, source, typeParameters, typeArguments) { // THIS IS LINE 14388
    var mapper = identityMapper;
    var members = source.symbol.members;
    var callSignatures = source.declaredCallSignatures;
    var constructSignatures = source.declaredConstructSignatures;
    var stringIndexType = source.declaredStringIndexType;
    var numberIndexType = source.declaredNumberIndexType;
    if (!ts.rangeEquals(typeParameters, typeArguments, 0, typeParameters.length)) {
        mapper = createTypeMapper(typeParameters, typeArguments);
        members = createInstantiatedSymbolTable(source.declaredProperties, mapper, typeParameters.length === 1);
        callSignatures = instantiateList(source.declaredCallSignatures, mapper, instantiateSignature);
        constructSignatures = instantiateList(source.declaredConstructSignatures, mapper, instantiateSignature);
        stringIndexType = instantiateType(source.declaredStringIndexType, mapper);
        numberIndexType = instantiateType(source.declaredNumberIndexType, mapper);
    }
    var baseTypes = getBaseTypes(source);
    if (baseTypes.length) {
        if (members === source.symbol.members) {
            members = createSymbolTable(source.declaredProperties);
        }
        var thisArgument = ts.lastOrUndefined(typeArguments);
        for (var _i = 0, baseTypes_1 = baseTypes; _i < baseTypes_1.length; _i++) {
            var baseType = baseTypes_1[_i];
            var instantiatedBaseType = thisArgument ? getTypeWithThisArgument(instantiateType(baseType, mapper), thisArgument) : baseType;
            addInheritedMembers(members, getPropertiesOfObjectType(instantiatedBaseType));
            callSignatures = ts.concatenate(callSignatures, getSignaturesOfType(instantiatedBaseType, 0));
            constructSignatures = ts.concatenate(constructSignatures, getSignaturesOfType(instantiatedBaseType, 1));
            stringIndexType = stringIndexType || getIndexTypeOfType(instantiatedBaseType, 0);
            numberIndexType = numberIndexType || getIndexTypeOfType(instantiatedBaseType, 1);
        }
    }
    setObjectTypeMembers(type, members, callSignatures, constructSignatures, stringIndexType, numberIndexType);
}
```

The app builds, but as soon as I make a change, the cli freezes and throws this error.
