### ISSUE TITLE
CLI does not work with Node7

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#2155]
```
Support for node.js 7.0.0 is not verified. This CLI might not install or run properly.

/Users/nsbuilduser/workspace/tns-stable-build-testapps-android-full/node_modules/fibers/fibers.js:16
    throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibers`?');
    ^

Error: `/Users/nsbuilduser/workspace/tns-stable-build-testapps-android-full/node_modules/fibers/bin/darwin-x64-v8-5.4/fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (/Users/nsbuilduser/workspace/tns-stable-build-testapps-android-full/node_modules/fibers/fibers.js:16:8)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/nsbuilduser/workspace/tns-stable-build-testapps-android-full/node_modules/nativescript/lib/common/helpers.js:3:13)
    at Module._compile (module.js:573:32)
```

**Comment by Splaktar** [comment]
I uninstalled nativescript and reinstalled it, but I'm still seeing these errors on OS X El Capitan with NodeJS 6.7.0, 6.9.2, and 7.3.0.

Trying to do the reinstall as suggested gets me:
`Registry returned 404 for GET on https://registry.npmjs.org/node-fibers`
