### ISSUE TITLE
tns test android exhausting all my 8GB of memory

### ISSUE THREAD

**Issue by pocesar** [NativeScript/nativescript-cli#2176]
I'm trying to run unit tests on the emulator, and it's always consuming my whole available memory, then crashing explorer.exe, and many windows services, until I have to hit the power button. 

I tried to watch what is happening, when it comes to the "Transferring project files..." step, it starts spawning `adb.exe` processes non-stop with `push` argument, with A LOT of babel files, each process takes like 6MB, and you do the math. and of course, using 100% of CPU, making anything else impossible to do

it started in 2GB, in no time, was 5.6GB, then I couldn't use the process explorer anymore, since everything froze, I couldn't even be able to take an screenshot. 

is there a way to set a maximum of spawned processes? they aren't lightweight. wasted like 2 hours trying to make the unit test work, and failed everytime. can't even tell if the files are actually being uploaded to the emulator, there's no progress, no indication that it's working.

EDIT: went away from the computer while it was frozen (for like 10 minutes), lo and behold, after "Transferring project files..." it gave the nicest error:

```
Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:569:26)
```

EDIT2: Manage to take screenshots before complete freeze

![processes](https://cloud.githubusercontent.com/assets/461084/19834339/ce93a206-9e41-11e6-963c-a8f246f73beb.png)
![cpu](https://cloud.githubusercontent.com/assets/461084/19834340/ce94251e-9e41-11e6-90f2-a663e654f02f.png)

**Comment by tzraikov** [comment]
@pocesar I confirm that currently the CLI consumes a lot of memory in certain cases. We are working to improve this. You should be able to work around the issue by passing the `--force` option to the CLI.  When using this option CLI will sync directories instead of files. This will decrease dramatically the number of adb processes, however it could slow down the file transfer.

**Comment by slavchev** [comment]
>is there a way to set a maximum of spawned processes? 

Currently there is no way.

@tzraikov we should throttle the spawned processes (say 2 * # of CPU cores). Syncing directories would definitely reduce the number of processes but won't work in all cases.

**Comment by pocesar** [comment]
yeah, I still can't use unit testing, have to test manually on the emulator, even using `@next`

**Comment by rosen-vladimirov** [comment]
In latest releases, we have tuned the sync of files, so now they are limited, so now the machine should not become unresponsive. @pocesar can you please inform us if you still face the same issue?

**Comment by rosen-vladimirov** [comment]
Closing due to inactivity.
