### ISSUE TITLE
Installation failed on Windows 10

### ISSUE THREAD

**Issue by hantsy** [NativeScript/nativescript-cli#2188]
NodeJS 7.0, Windows 64 bit, why it does not download fibers bin directly, and compiling it from sources.

No doubts about my build, I have installed C++ build(Visual Studio 2015 with C++), and Python 2.7.

```
antsy@HANTSY-T540P E:\Users\hantsy\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers
$ if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "" rebuild --release )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  fibers.cc
  coroutine.cc
  win_delay_load_hook.cc
..\src\fibers.cc(49): error C4430: missing type specifier - int assumed. Note:
C++ does not support default-int [E:\Users\hantsy\AppData\Roaming\npm\node_modu les\nativescript\node_modules\fibers\build\fibers.vcxproj]
..\src\fibers.cc(49): error C2988: unrecognizable template declaration/definiti on [E:\Users\hantsy\AppData\Roaming\npm\node_modules\nativescript\node_modules\ fibers\build\fibers.vcxproj]
..\src\fibers.cc(49): error C2143: syntax error: missing ',' before '<' [E:\Use rs\hantsy\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\bui ld\fibers.vcxproj]
..\src\fibers.cc(102): warning C4996: 'v8::String::NewFromOneByte': was declare d deprecated [E:\Users\hantsy\AppData\Roaming\npm\node_modules\nativescript\nod e_modules\fibers\build\fibers.vcxproj]
  e:\users\hantsy\.node-gyp\7.0.0\include\node\v8.h(2319): note: see declaratio
  n of 'v8::String::NewFromOneByte'
..\src\fibers.cc(106): warning C4996: 'v8::String::NewFromOneByte': was declare d deprecated [E:\Users\hantsy\AppData\Roaming\npm\node_modules\nativescript\nod e_modules\fibers\build\fibers.vcxproj]
  e:\users\hantsy\.node-gyp\7.0.0\include\node\v8.h(2319): note: see declaratio
  n of 'v8::String::NewFromOneByte'
..\src\fibers.cc(423): warning C4996: 'v8::Function::NewInstance': was declared  deprecated [E:\Users\hantsy\AppData\Roaming\npm\node_modules\nativescript\node _modules\fibers\build\fibers.vcxproj]
  e:\users\hantsy\.node-gyp\7.0.0\include\node\v8.h(3288): note: see declaratio
  n of 'v8::Function::NewInstance'
..\src\fibers.cc(727): warning C4244: 'argument': conversion from 'std::size_t'  to 'double', possible loss of data [E:\Users\hantsy\AppData\Roaming\npm\node_m odules\nativescript\node_modules\fibers\build\fibers.vcxproj]
..\src\fibers.cc(731): warning C4244: '=': conversion from 'double' to 'std::si ze_t', possible loss of data [E:\Users\hantsy\AppData\Roaming\npm\node_modules\ nativescript\node_modules\fibers\build\fibers.vcxproj]
..\src\fibers.cc(731): warning C4996: 'v8::Value::ToNumber': was declared depre cated [E:\Users\hantsy\AppData\Roaming\npm\node_modules\nativescript\node_modul es\fibers\build\fibers.vcxproj]
  e:\users\hantsy\.node-gyp\7.0.0\include\node\v8.h(8406): note: see declaratio
  n of 'v8::Value::ToNumber'
..\src\fibers.cc(738): warning C4244: 'argument': conversion from 'std::size_t'  to 'double', possible loss of data [E:\Users\hantsy\AppData\Roaming\npm\node_m odules\nativescript\node_modules\fibers\build\fibers.vcxproj]
..\src\fibers.cc(785): warning C4996: 'v8::Object::SetAccessor': was declared d eprecated [E:\Users\hantsy\AppData\Roaming\npm\node_modules\nativescript\node_m odules\fibers\build\fibers.vcxproj]
  e:\users\hantsy\.node-gyp\7.0.0\include\node\v8.h(2759): note: see declaratio
  n of 'v8::Object::SetAccessor'
..\src\fibers.cc(786): warning C4996: 'v8::Object::SetAccessor': was declared d eprecated [E:\Users\hantsy\AppData\Roaming\npm\node_modules\nativescript\node_m odules\fibers\build\fibers.vcxproj]
  e:\users\hantsy\.node-gyp\7.0.0\include\node\v8.h(2759): note: see declaratio
  n of 'v8::Object::SetAccessor'
..\src\fibers.cc(787): warning C4996: 'v8::Object::SetAccessor': was declared d eprecated [E:\Users\hantsy\AppData\Roaming\npm\node_modules\nativescript\node_m odules\fibers\build\fibers.vcxproj]
  e:\users\hantsy\.node-gyp\7.0.0\include\node\v8.h(2759): note: see declaratio
  n of 'v8::Object::SetAccessor'
..\src\coroutine.cc(137): warning C4552: '!': operator has no effect; expected
operator with side-effect [E:\Users\hantsy\AppData\Roaming\npm\node_modules\nat ivescript\node_modules\fibers\build\fibers.vcxproj]
..\src\coroutine.cc(214): warning C4267: 'argument': conversion from 'size_t' t o 'unsigned int', possible loss of data [E:\Users\hantsy\AppData\Roaming\npm\no de_modules\nativescript\node_modules\fibers\build\fibers.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd E:\Users\hantsy\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++`
Alpine users please run: `sudo apk add python make g++`
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
E:\Users\hantsy\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "nativescript"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.13 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.13 install script 'node build.js || nodejs build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with: npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Users\hantsy\npm-debug.log
npm ERR! code 1
```

**Comment by NickIliev** [comment]
Hello @hantsy 

Currently, Nodejs v.7 is not supported - use node 5.x or 6.x .
Our team is working actively and once the support is official will be updated [in this thread](https://github.com/NativeScript/nativescript-cli/issues/2155)

Closing as duplicate to [https://github.com/NativeScript/nativescript-cli/issues/2155](https://github.com/NativeScript/nativescript-cli/issues/2155)

**Comment by hantsy** [comment]
@NickIliev 
 Thanks
