### ISSUE TITLE
Empty project for ios build fails: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by af-fess** [NativeScript/nativescript-cli#2230]
I run following command:

```
tns create NTSDemo1
cd NTSDemo1/
tns platform add ios
Copying template files...
Project successfully created.

tns run ios --emulator
Cannot read property 'id' of undefined


tns run ios
Cannot read property 'id' of undefined
```

Logs (`tns run ios --log trace`):

```
System information:
{ procInfo: 'nativescript/2.3.0',
  platform: 'darwin',
  os: 'Darwin Maxims-MacBook-Pro.local 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64\n',
  shell: '/bin/bash',
  dotNetVer: null,
  procArch: 'x64',
  nodeVer: 'v6.6.0',
  npmVer: '3.10.3',
  javaVer: '1.8.0',
  nodeGypVer: null,
  xcodeVer: 'Xcode 8.1\nBuild version 8B62\n',
  xcodeprojGemLocation: '/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj.rb\n',
  itunesInstalled: true,
  cocoapodVer: '1.1.1',
  adbVer: 'Android Debug Bridge version 1.0.36',
  androidInstalled: true,
  monoVer: null,
  gitVer: '2.9.3 (Apple Git-75)',
  gradleVer: '3.1',
  javacVersion: '1.8.0_101' }


...


Trying to track feature 'CLI' with value 'run|ios'.
Waiting for analytics to send information. Will check in a 1000ms.
Statistics was sent successfully (xhr).
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 29000
startLookingForDevices; platform is iOS
Found device with identifier '9733281ceeb0aa378a7e8e0a33b48a8af7ec49cc'
Exec ps cax | grep launchd_sim 
 stdout: 34344   ??  S      0:15.12 launchd_sim
34355   ??  S      0:14.95 launchd_sim
 
 stderr: 
TypeError: Cannot read property 'id' of undefined
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:566:15)
    at /usr/local/lib/node_modules/nativescript/lib/common/errors.js:128:33
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/services/commands-service.js:84:106
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/yok.js:208:124
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/services/commands-service.js:51:55
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/errors.js:128:33
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    - - - - -
    at IOSSimulator.get [as deviceInfo] (/usr/local/lib/node_modules/nativescript/lib/common/mobile/ios/simulator/ios-simulator-device.js:15:43)
    at IOSSimulatorDiscovery.DeviceDiscovery.addDevice (/usr/local/lib/node_modules/nativescript/lib/common/mobile/mobile-core/device-discovery.js:16:28)
    at IOSSimulatorDiscovery.createAndAddDevice (/usr/local/lib/node_modules/nativescript/lib/common/mobile/mobile-core/ios-simulator-discovery.js:58:14)
    at IOSSimulatorDiscovery.checkForDevices (/usr/local/lib/node_modules/nativescript/lib/common/mobile/mobile-core/ios-simulator-discovery.js:27:26)
    at IOSSimulatorDiscovery.startLookingForDevices (/usr/local/lib/node_modules/nativescript/lib/common/mobile/mobile-core/ios-simulator-discovery.js:20:21)
    at /usr/local/lib/node_modules/nativescript/lib/common/mobile/mobile-core/devices-service.js:212:50
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/mobile/mobile-core/devices-service.js:327:48
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/services/platform-service.js:366:103
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/services/platform-service.js:402:58
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
Analytics statuses: 
{ TrackFeatureUsage: 0, TrackExceptions: 0 }
Trying to track feature 'CLI' with value 'help'.
Waiting for analytics to send information. Will check in a 1000ms.
Statistics was sent successfully (xhr).
List of registered commands: /?, appstore, appstore|upload, autocomplete, autocomplete|disable, autocomplete|enable, autocomplete|status, build, build|android, build|ios, create, debug, debug|android, debug|ios, deploy, dev-generate-help, dev-generate-messages, dev-post-install, dev-preuninstall, dev-test, dev-test|android, dev-test|ios, device, device|android, device|get-file, device|ios, device|list-applications, device|list-files, device|log, device|put-file, device|run, device|stop, device|uninstall, doctor, emulate, emulate|android, emulate|ios, error-reporting, help, info, init, install, livesync, platform, platform|add, platform|clean, platform|remove, platform|update, plugin, plugin|add, plugin|find, plugin|install, plugin|remove, plugin|search, plugin|update, prepare, publish, publish|ios, run, run|android, run|ios, test, test|android, test|init, test|ios, usage-reporting
Reading help for command 'run|ios'. FileName is 'run-ios.md'.
Waiting for analytics to send information. Will check in a 1000ms. Remaining time is: 29000

```

**Comment by rosen-vladimirov** [comment]
Hey @af-fess , can you check if you have working iOS Simulator when the error occurs? In case yes, can you try stopping it and see if it will work.

**Comment by af-fess** [comment]
I get the same error as described here: https://codedump.io/share/6LTtf3Be5SRu/1/nativescript-app-won39t-run-on-ios.

**Comment by af-fess** [comment]
I restarted my Mac and it started to work. Now `tns livesync ios --watch` looks good, triggers on every code change

However after 15 min I got this one:

```
Nov 18 22:55:43 Maxims-MacBook-Pro demoNative[29661]: AppsFlyer: sent information to server
Project successfully prepared (ios)
Transferring project files...
Successfully transferred all files.
Applying changes...
Nov 18 22:55:57 Maxims-MacBook-Pro com.apple.CoreSimulator.SimDevice.73DE4DE7-EA48-4AB0-AE31-B192FF74F456.launchd_sim[28794] (UIKitApplication:com.appsflyer.nativescript.demoNative[0xb53][29661]): Service exited due to Terminated: 15
Successfully synced application com.appsflyer.nativescript.demoNative on device 73DE4DE7-EA48-4AB0-AE31-B192FF74F456.
Nov 18 22:55:58 Maxims-MacBook-Pro demoNative[29981]: objc[29981]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x117f05998) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x117d2ad38). One of the two will be used. Which one is undefined.

//...


Project successfully prepared (ios)
Transferring project files...
Successfully transferred all files.
Applying changes...
Successfully synced application com.appsflyer.nativescript.demoNative on device 73DE4DE7-EA48-4AB0-AE31-B192FF74F456.


```

I pressed `Ctrl+C`, closed simulator.

after next `tns livesync ios --watch` I got the previous error: `Cannot read property 'id' of undefined`

**Comment by tzraikov** [comment]
@af-fess Your log shows that you are using version 2.3.0 of {N}. I recommend that you try our latest release 2.4.0. It addresses similar issue. Please, could you confirm that everything is OK when using the new version?

**Comment by af-fess** [comment]
I work with `2.4.0` for now everything is ok,
