### ISSUE TITLE
Class android.support.v7.widget.AdapterHelper$UpdateOp conflict during debug

### ISSUE THREAD

**Issue by af-fess** [NativeScript/nativescript-cli#2261]
`tns debug android` fails.

`tns livesync android --watch` works well for android, however when I try to run:

```
tns debug android --debug
``` 

I get an error:

```
:buildMetadata
Exception in thread "main" java.lang.IllegalArgumentException: Class android.support.v7.widget.AdapterHelper$UpdateOp conflict: /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demoNative/platforms/android/build/intermediates/transforms/dex/F0F1/debug/folders/1000/1f/main/classes.dex and /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demoNative/platforms/android/build/intermediates/transforms/dex/F0/debug/folders/1000/1f/main/classes.dex
	at com.telerik.metadata.ClassRepo.addToCache(ClassRepo.java:21)
	at com.telerik.metadata.Builder.build(Builder.java:40)
	at com.telerik.metadata.Generator.main(Generator.java:44)
:buildMetadata FAILED

FAILURE: Build failed with an exception.
```

here is a full stack trace:

```
Maxims-MacBook-Pro:demoNative maxim$ tns debug android --debug

:config phase:  createDefaultIncludeFiles
	+found plugins: tns-core-modules-widgets

:config phase:  createPluginsConfigFile
	 Creating product flavors include.gradle file in /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demoNative/platforms/android/configurations folder...

:config phase:  pluginExtend
	+applying configuration from: /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demoNative/platforms/android/configurations/include.gradle
	+applying configuration from: /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demoNative/platforms/android/configurations/tns-core-modules-widgets/include.gradle

:config phase:  copyAarDependencies

:config phase:  addAarDependencies
	+adding dependency: /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demoNative/platforms/android/libs/aar/af-android-sdk-4.6.0.aar
	+adding dependency: /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demoNative/platforms/android/libs/aar/widgets-release.aar
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preF0DebugBuild UP-TO-DATE
:checkF0DebugManifest
:preF0ReleaseBuild UP-TO-DATE
:prepareAfAndroidSdk460Library UP-TO-DATE
:prepareComAndroidSupportAnimatedVectorDrawable2501Library UP-TO-DATE
:prepareComAndroidSupportAppcompatV72501Library UP-TO-DATE
:prepareComAndroidSupportDesign2501Library UP-TO-DATE
:prepareComAndroidSupportRecyclerviewV72501Library UP-TO-DATE
:prepareComAndroidSupportSupportCompat2501Library UP-TO-DATE
:prepareComAndroidSupportSupportCoreUi2501Library UP-TO-DATE
:prepareComAndroidSupportSupportCoreUtils2501Library UP-TO-DATE
:prepareComAndroidSupportSupportFragment2501Library UP-TO-DATE
:prepareComAndroidSupportSupportMediaCompat2501Library UP-TO-DATE
:prepareComAndroidSupportSupportV42501Library UP-TO-DATE
:prepareComAndroidSupportSupportVectorDrawable2501Library UP-TO-DATE
:prepareComAndroidSupportTransition2501Library UP-TO-DATE
:prepareNativescriptRuntimeUnspecifiedLibrary UP-TO-DATE
:prepareWidgetsReleaseLibrary UP-TO-DATE
:prepareF0DebugDependencies
:compileF0DebugAidl UP-TO-DATE
:compileF0DebugRenderscript UP-TO-DATE
:generateF0DebugBuildConfig UP-TO-DATE
:cleanLocalAarFiles
:ensureMetadataOutDir
:collectAllJars
:setProperties
:generateTypescriptDefinitions SKIPPED
:copyTypings SKIPPED
:asbg:generateInterfaceNamesList
:asbg:traverseJsFiles
:asbg:runAstParser UP-TO-DATE
:asbg:generateBindings UP-TO-DATE
:mergeF0DebugShaders UP-TO-DATE
:compileF0DebugShaders UP-TO-DATE
:generateF0DebugAssets UP-TO-DATE
:mergeF0DebugAssets UP-TO-DATE
:generateF0DebugResValues UP-TO-DATE
:generateF0DebugResources UP-TO-DATE
:mergeF0DebugResources UP-TO-DATE
:processF0DebugManifest UP-TO-DATE
:processF0DebugResources UP-TO-DATE
:generateF0DebugSources UP-TO-DATE
:incrementalF0DebugJavaCompilationSafeguard UP-TO-DATE
:compileF0DebugJavaWithJavac UP-TO-DATE
:compileF0DebugNdk UP-TO-DATE
:compileF0DebugSources UP-TO-DATE
:prePackageMarkerForF0Debug
:transformClassesWithDexForF0Debug
Result compacted from 4406.2KiB to 3254.5KiB to save 1151.6KiB
Merged dex #1 (205 defs/310.8KiB)
Merged dex #2 (5 defs/15.2KiB)
Merged dex #3 (356 defs/581.2KiB)
Merged dex #4 (199 defs/288.4KiB)
Merged dex #5 (150 defs/324.4KiB)
Merged dex #6 (437 defs/468.5KiB)
Merged dex #7 (130 defs/243.6KiB)
Merged dex #8 (53 defs/76.5KiB)
Merged dex #9 (56 defs/147.3KiB)
Merged dex #10 (141 defs/172.2KiB)
Merged dex #11 (1 defs/0.7KiB)
Merged dex #12 (15 defs/47.9KiB)
Merged dex #13 (83 defs/84.7KiB)
Merged dex #14 (76 defs/186.5KiB)
Merged dex #15 (45 defs/100.8KiB)
Merged dex #16 (93 defs/177.3KiB)
Merged dex #17 (73 defs/58.2KiB)
Merged dex #18 (10 defs/15.2KiB)
Merged dex #19 (17 defs/28.5KiB)
Merged dex #20 (8 defs/8.3KiB)
Merged dex #21 (250 defs/187.4KiB)
Merged dex #22 (69 defs/105.2KiB)
Merged dex #23 (47 defs/8.6KiB)
Result is 2519 defs/3254.5KiB. Took 0.9s
:myMergeDex
Merged dex #1 (1 defs/1.6KiB)
Merged dex #2 (1 defs/1.4KiB)
Merged dex #3 (1 defs/1.9KiB)
Merged dex #4 (1 defs/1.7KiB)
Merged dex #5 (1 defs/1.4KiB)
Merged dex #6 (1 defs/1.6KiB)
Merged dex #7 (1 defs/1.4KiB)
Merged dex #8 (1 defs/1.3KiB)
Merged dex #9 (1 defs/1.5KiB)
Merged dex #10 (1 defs/1.7KiB)
Merged dex #11 (1 defs/2.7KiB)
Merged dex #12 (1 defs/1.5KiB)
Merged dex #13 (1 defs/1.4KiB)
Merged dex #14 (1 defs/1.6KiB)
Merged dex #15 (1 defs/1.6KiB)
Merged dex #16 (1 defs/1.7KiB)
Merged dex #17 (1 defs/1.3KiB)
Merged dex #18 (1 defs/1.4KiB)
Merged dex #19 (1 defs/1.7KiB)
Merged dex #20 (1 defs/1.8KiB)
Merged dex #21 (1 defs/1.7KiB)
Merged dex #22 (1 defs/1.4KiB)
Merged dex #23 (1 defs/1.3KiB)
Merged dex #24 (1 defs/1.4KiB)
Merged dex #25 (1 defs/1.4KiB)
Merged dex #26 (1 defs/2.0KiB)
Merged dex #27 (1 defs/1.3KiB)
Merged dex #28 (1 defs/2.3KiB)
Merged dex #29 (1 defs/1.5KiB)
Merged dex #30 (1 defs/2.3KiB)
Merged dex #31 (1 defs/1.4KiB)
Merged dex #32 (1 defs/1.5KiB)
Merged dex #33 (1 defs/1.3KiB)
Merged dex #34 (1 defs/1.4KiB)
Merged dex #35 (1 defs/1.3KiB)
Merged dex #36 (1 defs/1.4KiB)
Merged dex #37 (1 defs/1.7KiB)
Merged dex #38 (1 defs/1.6KiB)
Merged dex #39 (1 defs/1.3KiB)
Merged dex #40 (1 defs/1.3KiB)
Merged dex #41 (1 defs/1.5KiB)
Merged dex #42 (1 defs/1.4KiB)
Merged dex #43 (1 defs/2.5KiB)
Merged dex #44 (1 defs/2.6KiB)
Merged dex #45 (1 defs/1.2KiB)
Merged dex #46 (1 defs/1.3KiB)
Merged dex #47 (1 defs/1.4KiB)
Merged dex #48 (2519 defs/3254.5KiB)
Result is 2566 defs/4128.7KiB. Took 0.2s
:buildMetadata
Exception in thread "main" java.lang.IllegalArgumentException: Class android.support.v7.widget.AdapterHelper$UpdateOp conflict: /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demoNative/platforms/android/build/intermediates/transforms/dex/F0F1/debug/folders/1000/1f/main/classes.dex and /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demoNative/platforms/android/build/intermediates/transforms/dex/F0/debug/folders/1000/1f/main/classes.dex
	at com.telerik.metadata.ClassRepo.addToCache(ClassRepo.java:21)
	at com.telerik.metadata.Builder.build(Builder.java:40)
	at com.telerik.metadata.Generator.main(Generator.java:44)
:buildMetadata FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildMetadata'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 17.396 secs
Command /Users/maxim/Appsflyer/projects/nativescript-plugin-appsflyer/demoNative/platforms/android/gradlew failed with exit code 1
# debug android
```

TO fix it I need to remove and add android platform. However after 1st debug launch above mentioned error happens again

**Comment by Pip3r4o** [comment]
@af-fess what versions of NativeScript CLI, Android Platform, and tns-core-modules are you using? Do you install any additional npm modules? How can we replicate the errors?

**Comment by af-fess** [comment]
1st off I released plugin with demo, so you can try to use `demoNative` project. [nativescript-plugin-appsflyer](https://github.com/AppsFlyerSDK/nativescript-plugin-appsflyer)


Maxims-MacBook-Pro:demoNative maxim$ tns info
All NativeScript components versions information

```
│ Component           │ Current version │ Latest version │ Information │
│ nativescript        │ 2.4.0           │ 2.4.0          │ Up to date  │
│ tns-core-modules    │ 2.4.0           │ 2.4.0          │ Up to date  │
│ tns-android         │ 2.4.1           │ 2.4.1          │ Up to date  │
│ tns-ios             │ 2.4.0           │ 2.4.0          │ Up to date  │

```

**Comment by Pip3r4o** [comment]
@af-fess that problem is common and occurs build-time, after a plugin that installs native dependencies (much like nativescript-appsflyer) is removed without cleaning the platforms directory.

I was able to reproduce it by doing the following:
```shell
tns create appsFlyer
cd appsFlyer
tns plugin add ../nativescript-plugin-appsFlyer
tns run android
tns plugin remove nativescript-plugin-appsFlyer
tns build android
```

The main culprit here is the build/ directory which keeps the build results from previous builds in order to make them `incremental` instead of rebuilding all over again each time. This however is a problem when a plugin with an .aar/.jar is removed, as conflicts, like the one that you are observing occur. We will look into fixing it.

As a workaround, when necessary, you can manually delete the `build` dir in `platforms/android` to trigger a full build, or just remove/install platform again.

Also, please note that `tns livesync` will only synchronize javascript/xml/css files on the device, and will only trigger a build if an `apk` isn't readily available already in the build dir.


Offtopic: include any redundant, insignificant files in the `.npmignore` you don't need those ending up on the device, unless they are used as application resources. (looking at you, `es6-promise.d.ts`, `af-logo.png`, `README.md`, any `.ts` file)

**Comment by af-fess** [comment]
@Pip3r4o thank you for quick response. It makes sense. Suppose there should be some flag to for deleting `build` dir and its critical for plugin development.  Thank you (for tips too :) )
