### ISSUE TITLE
Creating app - --ng flag not recognized

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/nativescript-cli#2338]
Creating a new app with the `--ng` flag is not working:
```shell
$ tns create appNG —-ng
Error: The parameter —-ng is not valid for this command.
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:7:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:9:16)
    at Module._compile (module.js:570:32)
```

Trying with `--template ng` has no luck, too:
```shell
The parameter —-template is not valid for this command.
```

Using NativeScript 2.4.2 on macOS with Node 6.

**Comment by rosen-vladimirov** [comment]
@jasssonpet  it looks like the problem is with your dashes `--ng` is correct flag, on your side I see: `—-ng`. Can you try passing `--ng` instead and see if it works on your side.

**Comment by jasssonpet** [comment]
Closing the issue because the dashes in `—-` are not the normal one.
