### ISSUE TITLE
Always get Application entry point file not found

### ISSUE THREAD

**Issue by michaellee8** [NativeScript/nativescript-cli#2372]
I am working on my own angular+nativescript app but found `Application entry point file not found` that even the bare project just ran `tns create --ng proj` and `tns add platform android` show the error above every time I try to run it. Then I tried to test the `angular-end` of  `sample-Groceries` as well but the error still exists. It happens even when I use bare javascript from the `end` branch.

**Comment by michaellee8** [comment]
By inspecting the apk, it seems that the `*.ts` files are not compiled.

**Comment by NickIliev** [comment]
Hey @michaellee8 

As suggested [here](https://github.com/NativeScript/NativeScript/issues/3322#issuecomment-268174631) a possible reason for this issue is using incompatible Node.js version. Can you try updating to the latest stable versions (at this point 6.9.2) and also try the steps suggested in the linked issue.

**Comment by michaellee8** [comment]
I have v7.3.0 here, is it a problem?

**Comment by NickIliev** [comment]
@michaellee8 at this moment only the LTS versions are officially supported and indeed there are some issues with the 7.x versions of Node.js. You can try to reinstall  Node.js using 6.9.2 or if you want you can try a Node.js version manager like [nvm](https://github.com/coreybutler/nvm-windows) or [n](https://github.com/tj/n) (tools that allow you to have multiple Node.js versions and switch them with commands)

**Comment by michaellee8** [comment]
@NickIliev I am on windows, how do I do it?

**Comment by michaellee8** [comment]
Still the same situation

An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4643)
	at android.app.ActivityThread.access$1300(ActivityThread.java:165)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1433)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5391)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
	at com.tns.Module.bootstrapApp(Module.java:337)
	at com.tns.Runtime.run(Runtime.java:508)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1065)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4640)
	... 10 more
Caused by: com.tns.NativeScriptException: Failed to find module: "./", relative to: app//
	at com.tns.Module.resolvePathHelper(Module.java:159)
	at com.tns.Module.bootstrapApp(Module.java:335)
	... 14 more

**Comment by NickIliev** [comment]
Hey @michaellee8 
I've just realised that you have two opened issues and I have given a possible reason for your issue [here](https://github.com/NativeScript/sample-Groceries/issues/197#issuecomment-269289365). Closing this one as duplicate - let's continue our discussion in the another issue
