### ISSUE TITLE
[next] Error: Unable to send QStartNoAckMode

### ISSUE THREAD

**Issue by roblav96** [NativeScript/nativescript-cli#2442]
I get this error when trying to install my ios app. It crashes the cli but does install the app.
```
Transferring project files...
Creating zip file: /var/folders/17/mflv1l352j53v7kmx8rdmfsc0000gn/T/sync117018-40349-mq4dcx.3b6m7psyvi.zip
spawn: zip "-r" "-0" "/var/folders/17/mflv1l352j53v7kmx8rdmfsc0000gn/T/sync117018-40349-mq4dcx.3b6m7psyvi.zip" "app"
Successfully transferred all files.
PlistService sending: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Command</key>
	<string>VendContainer</string>
	<key>Identifier</key>
	<string>com.gethuman.GetHuman</string>
</dict>
</plist>

Removing device file 'Library/Application Support/LiveSync/app/.nslivesyncinfo', result: 0
transfer-> localFilePath: '/Users/roblav96/Projects/app-smile/ghmobile/platforms/ios/.nsprepareinfo', devicePath: 'Library/Application Support/LiveSync/app/.nslivesyncinfo', localFilePathSize: '192', transferred bytes: '192'
Refreshing application...
GDB: send packet $QStartNoAckMode#b0
GDB: send packet +
GDB: send packet $QEnvironmentHexEncoded:#f7
MESSAGE RECEIVING
{ Status: 'Complete' }
Status: Complete
Status: Complete PercentComplete: undefined
Removing device file 'Library/Application Support/LiveSync/sync.zip', result: 8
GDB: read packet: +$OK#9a$OK#00
GDB: read packet: +$OK#9a$OK#00
GDB: actual response: +$OK#9a$OK#00, expected response: + await 
Unable to send QStartNoAckMode.
GDB: send packet $QSetDisableASLR:1#ce
Error: Unable to send QStartNoAckMode.
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:14:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:14:18)
    at Module._compile (module.js:570:32)
```
```
┌──────────────────┬────────────────────────────┬────────────────┬─────────────┐
│ Component        │ Current version            │ Latest version │ Information │
│ nativescript     │ 2.6.0-2017-01-17-7788      │ 2.4.2          │ Up to date  │
│ tns-core-modules │ 2.4.4                      │ 2.4.4          │ Up to date  │
│ tns-android      │ 2.6.0-next-2017-01-18-1633 │ 2.4.1          │ Up to date  │
│ tns-ios          │ 2.6.0-2017-1-17-1          │ 2.4.0          │ Up to date  │
└──────────────────┴────────────────────────────┴────────────────┴─────────────┘
```

**Comment by halaharr** [comment]
I am having the same issue. I am on 2.5 version. Were you able to fix it?

**Comment by roblav96** [comment]
@halaharr Idk it worked when I upgraded to 2.5 stable.

**Comment by Plamen5kov** [comment]
closed in favor of: https://github.com/NativeScript/nativescript-cli/issues/2562
working on fixing it.
