### ISSUE TITLE
Run with --clean option fails on iOS device

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#2449]
### Prerequisites:
- installed {N} CLI 2.5.0
- attached iOS device

### Workflow:
```shell
git clone git@github.com:NativeScript/sample-Groceries.git
cd sample-Groceries
tns update 2.5.0
tns run ios --clean
```
- changes on `.ts` files

### Result:

The `tns run ios --clean` command rebuilds the project on every change. After a few changes, the command exits with no warning or message. At this moment, the app stumbles at the launch screen and the iOS device gets unresponsive.

The next execution of `tns run ios --clean` fails with:
```shell
Error: Unable to kill the application.
```

Output:
```
MESSAGE RECEIVING
{ Status: 'Complete' }
Status: Complete
Removing device file 'Library/Application Support/LiveSync/.nslivesyncinfo', result: 8
Status: Complete PercentComplete: undefined
transfer-> localFilePath: '/Users/vchimev/Work/master/sample-Groceries/platforms/ios/.nsprepareinfo', devicePath: 'Library/Application Support/LiveSync/.nslivesyncinfo', localFilePathSize: '193', transferred bytes: '193'
Refreshing application...
GDB: send packet $QStartNoAckMode#b0
GDB: read packet: +
GDB: send packet +
GDB: send packet $QEnvironmentHexEncoded:#f7
GDB: read packet: $OK#9a
GDB: send packet $QSetDisableASLR:1#ce
GDB: read packet: $OK#00
GDB: send packet $A198,0,2f707269766174652f7661722f636f6e7461696e6572732f42756e646c652f4170706c69636174696f6e2f46303244313542442d323130462d344642342d424133372d3431434141413546323645382f73616d706c6547726f6365726965732e617070#2d
GDB: read packet: $OK#00
GDB: send packet 
GDB: send packet 
GDB: send packet 
GDB: send packet 
Error: Unable to kill the application.
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:566:15)
    at ex (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:120:33)
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/services/commands-service.js:80:104
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/yok.js:191:124
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    - - - - -
    at Timeout.setTimeout (/usr/local/lib/node_modules/nativescript/lib/common/mobile/ios/device/ios-core.js:1087:34)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
Analytics statuses: 
```

### Notes:
I was able to reproduce this issue on more than one iOS device.
I was __unable__ to reproduce this issue without the `--clean` option.

**Comment by Plamen5kov** [comment]
closed in favor of: https://github.com/NativeScript/nativescript-cli/issues/2500
