### ISSUE TITLE
Error while installing nativescript : Cannot find module 'd'

### ISSUE THREAD

**Issue by smithamalur** [NativeScript/nativescript-cli#2498]
Cannot find module 'd'
Error: Unknown command 'post-install-cli'. Try '$ tns help' for a full list of supported commands.
    at Object.<anonymous> (C:\Users\smalur\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:7:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\smalur\AppData\Roaming\npm\node_modules\nativescript\lib\nativescript-cli.js:8:18)
    at Module._compile (module.js:570:32)
Sending exception report (press Ctrl+C to stop)...C:\Users\smalur\AppData\Roaming\npm

**Comment by Plamen5kov** [comment]
Hi @smithamalur,
Can you provide the steps to reproduce this problem, so we can have a look.

**Comment by rosen-vladimirov** [comment]
Hey @smithamalur ,
It looks like something went wrong during post-install step of the CLI. However this will not prevent you from using the CLI itself. 
The error itself is related to npm not being able to resolve some module. In some npm versions, the scripts (like preuninstall, postinstall, etc.) are executed in incorrect order, which may result in such strange errors.
I would like to ask you to try upgrading your Node.js to latest 6.x.x version (this will update npm itself). After that try cleaning the cache and installing CLI again:
```
$ npm cache clean
$ npm install -g nativescript
```

Can you try this and inform us if it works on your side?

**Comment by pkoleva** [comment]
Closing the issue due to lack of response. If you reproduce it again with our latest release, please reopen it and give detailed steps to reproduce.
