### ISSUE TITLE
[OSX] No validation for command options

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#251]
If you have a typo in --frameworkPath CLI defaults to npmjs.org without any error.
If some of the CLI params is wrong I expect error instead of default behavior without error.

**Comment by rosen-vladimirov** [comment]
This should work fine, could you give some more details how to reproduce the problem.

**Comment by dtopuzov** [comment]
Valication for --frameworkPath is ok on Windows, but when run this on OSX:
tns platform add android --framerowkpaht tns-android.tgz --path TNSApp

Result is:
No error message, platform added (the one from npmjs.org)

Expected:
Error message, because "--framerowkpaht" is not a valid option

**Comment by dtopuzov** [comment]
Same applies also for symlink:
tns platform add android --frameworkPath tns-android.tgz --simlink --path TNS_App

Windows: Error message (expected, because there is a typo in --simlink)
OSX: No validation, command executed and --simlink is just ignored

**Comment by dtopuzov** [comment]
Same for:
node_modules/.bin/tns build android --debug --path TNS_App

In Windows environment result is:
The option 'debug' is not supported.

In OSX result is:
```Shell
shell.js: internal error
Error: ENOENT, no such file or directory '/Users/topuzov/Git/nativescript-cli-tests/TNS_App/platforms/android/assets/App_Resources'
    at Object.fs.mkdirSync (fs.js:653:18)
    at /Users/topuzov/Git/nativescript-cli-tests/node_modules/nativescript/node_modules/shelljs/src/cp.js:174:14
    at Array.forEach (native)
    at Object._cp (/Users/topuzov/Git/nativescript-cli-tests/node_modules/nativescript/node_modules/shelljs/src/cp.js:157:11)
    at Object.cp (/Users/topuzov/Git/nativescript-cli-tests/node_modules/nativescript/node_modules/shelljs/src/common.js:186:23)
    at /Users/topuzov/Git/nativescript-cli-tests/node_modules/nativescript/lib/services/android-project-service.js:101:19
    at Function.settle (/Users/topuzov/Git/nativescript-cli-tests/node_modules/nativescript/node_modules/fibers/future.js:220:26)
    at FiberFuture.Future.wait (/Users/topuzov/Git/nativescript-cli-tests/node_modules/nativescript/node_modules/fibers/future.js:487:10)
    at /Users/topuzov/Git/nativescript-cli-tests/node_modules/nativescript/lib/services/platform-service.js:121:88
    at Function.settle (/Users/topuzov/Git/nativescript-cli-tests/node_modules/nativescript/node_modules/fibers/future.js:220:26)

**Comment by rosen-vladimirov** [comment]
It turned out the problem is when you have installed nativescript with -g option
$ npm install -g nativescript
After that our validation for -- is not working correctly when you call tns ...
It is working fine in case you are using " $ nativescript ... "
