### ISSUE TITLE
"The package archive file is invalid" android message after build

### ISSUE THREAD

**Issue by eesdil** [NativeScript/nativescript-cli#2596]
How to find out what is wrong with the build?

First time running the application in android working fine, but building is producing invalid package.
After this invalid package the normal run is not working anymore either...

Trying to check the log, but it does not really give any useful information. 

Was trying to remove android files , clean, but after it gets wrong I cannot fix it anymore. At least not sure where...

tns info:
```
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 2.5.2           │ 2.5.2          │ Up to date  │
│ tns-core-modules │ 2.5.1           │ 2.5.1          │ Up to date  │
│ tns-android      │ 2.5.0           │ 2.5.0          │ Up to date  │
│ tns-ios          │ 2.5.0           │ 2.5.0          │ Up to date  │
```

To be fair, using angular-seed-advanced

```

Error: Multiple exceptions were thrown:
The package archive file is invalid.
The package archive file is invalid.: The package archive file is invalid.
    at Errors.fail (/Users/kcs/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/lib/common/errors.js:107:28)
    at Errors.failWithoutHelp (/Users/kcs/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/lib/common/errors.js:115:14)
    at AndroidDebugBridgeResultHandler.handleErrors (/Users/kcs/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/lib/common/mobile/android/android-debug-bridge-result-handler.js:40:26)
    at /Users/kcs/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/lib/common/mobile/android/android-debug-bridge.js:27:55
    at Function.settle (/Users/kcs/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/Users/kcs/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at decorateMethod (/Users/kcs/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/lib/common/helpers.js:253:36)
    at AndroidApplicationManager.descriptor.value (/Users/kcs/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/lib/common/helpers.js:219:24)
    at /Users/kcs/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/lib/common/mobile/application-manager-base.js:15:18
    at Function.settle (/Users/kcs/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)

Error: The package archive file is invalid.
    at Errors.fail (/Users/kcs/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/lib/common/errors.js:107:28)
    at Errors.failWithoutHelp (/Users/kcs/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/lib/common/errors.js:115:14)
    at AndroidDebugBridgeResultHandler.handleErrors (/Users/kcs/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/lib/common/mobile/android/android-debug-bridge-result-handler.js:40:26)
    at /Users/kcs/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/lib/common/mobile/android/android-debug-bridge.js:27:55
    at Function.settle (/Users/kcs/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/Users/kcs/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at decorateMethod (/Users/kcs/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/lib/common/helpers.js:253:36)
    at AndroidApplicationManager.descriptor.value (/Users/kcs/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/lib/common/helpers.js:219:24)
    at /Users/kcs/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/lib/common/mobile/application-manager-base.js:15:18
    at Function.settle (/Users/kcs/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
```

**Comment by eesdil** [comment]
Switched to pure tns... where build is working so closing this.
