### ISSUE TITLE
node postinstall.js fails

### ISSUE THREAD

**Issue by unlight** [NativeScript/nativescript-cli#265]
Node v0.10.36, Windows
```
npm i https://github.com/NativeScript/nativescript-cli/archive/master.tar.gz -msvs_version=2013
```

```sh
> nativescript@0.9.0 postinstall .../node_modules\nativescript
> node postinstall.js

stderr:
module.js:340
    throw err;
          ^
Error: Cannot find module '../lib/nativescript-cli.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (..\node_modules\nativescript\bin\nativescript.js:4:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by rosen-vladimirov** [comment]
Hi @unlight 
When you are using archive github option, it does not get the sources from the submodules. In our case nativescript-cli has one submodule - https://github.com/telerik/mobile-cli-lib Your command is not fetching it and that's why the installation fails. I suggest you to clone the repository and call git submodule init; git submodule update and create a pack from there (npm pack should do the job for you). Hope this helps.

**Comment by unlight** [comment]
No, this did not help.
I still see `nativescript-cli.ts` but not `nativescript-cli.js`

**Comment by rosen-vladimirov** [comment]
I'm glad this helped. I'm closing this thread now, but feel free to contact us in case you have any other problems or concerns.

**Comment by u14040426** [comment]
Hi @unlight what exactly did you do, as I have the exact same error but cannot seem to get rid of the error.
