### ISSUE TITLE
OSX issue with node 0.12.0

### ISSUE THREAD

**Issue by emazv72** [NativeScript/nativescript-cli#268]
I'm getting the following error when creating a new app:

> tns create TestApp

Error: "name" and "value" are required for setHeader().
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
    at new ClientRequest (_http_client.js:101:14)
    at Object.exports.request (http.js:49:10)
    at Object.exports.request (https.js:136:15)
    at Request.start (/usr/local/lib/node_modules/nativescript/node_modules/npm/node_modules/request/request.js:583:30)
    at Request.end (/usr/local/lib/node_modules/nativescript/node_modules/npm/node_modules/request/request.js:1237:28)
    at /usr/local/lib/node_modules/nativescript/node_modules/npm/node_modules/request/request.js:413:12
    at process._tickCallback (node.js:355:11)

**Comment by rosen-vladimirov** [comment]
Hi @emazv72 , 
Thank you for reporting this problem. It is related to old npm version that we are using in our code. I've prepared a fix, but until it's published, you have to use node 0.10.x (0.10.36 for example). Please excuse us for the caused inconvenience.

**Comment by dtopuzov** [comment]
Available in 0.9.1
