### ISSUE TITLE
android app crash immediately when started ( release version)

### ISSUE THREAD

**Issue by mshanak** [NativeScript/nativescript-cli#2761]
the problem is that my app when deployed on android device using `tns run android` works perfect, but when i release the app and install it on the same device the app crash befor it start , 
when i reported the crash log , the following report 
(NOTE: the released app was working before updating nativescript to 2.5.4) 
```

`
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

Error calling module function 

Error calling module function 

Error calling module function 

Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:580)
    com.tns.Runtime.run(Runtime.java:574)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4568)
    android.app.ActivityThread.access$1500(ActivityThread.java:154)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5271)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/components/Home/Home.component.js', line: 16, column: 30
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/components/news/news.component.js', line: 11, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/app.routing.js', line: 5, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/app.module.js', line: 5, column: 21
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/main.js', line: 4, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:580)
    com.tns.Runtime.run(Runtime.java:574)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4568)
    android.app.ActivityThread.access$1500(ActivityThread.java:154)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5271)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/components/Home/Home.component.js', line: 16, column: 30
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/components/news/news.component.js', line: 11, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/app.routing.js', line: 5, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/app.module.js', line: 5, column: 21
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/main.js', line: 4, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:580)
    com.tns.Runtime.run(Runtime.java:574)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4568)
    android.app.ActivityThread.access$1500(ActivityThread.java:154)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5271)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/components/Home/Home.component.js', line: 16, column: 30
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/components/news/news.component.js', line: 11, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/app.routing.js', line: 5, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/app.module.js', line: 5, column: 21
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/main.js', line: 4, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:580)
    com.tns.Runtime.run(Runtime.java:574)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4568)
    android.app.ActivityThread.access$1500(ActivityThread.java:154)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5271)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/components/Home/Home.component.js', line: 16, column: 30
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/components/news/news.component.js', line: 11, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/app.routing.js', line: 5, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/app.module.js', line: 5, column: 21
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/main.js', line: 4, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:580)
    com.tns.Runtime.run(Runtime.java:574)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4568)
    android.app.ActivityThread.access$1500(ActivityThread.java:154)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5271)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/components/Home/Home.component.js', line: 16, column: 30
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/components/news/news.component.js', line: 11, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/app.routing.js', line: 5, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/app.module.js', line: 5, column: 21
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/main.js', line: 4, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:580)
    com.tns.Runtime.run(Runtime.java:574)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4568)
    android.app.ActivityThread.access$1500(ActivityThread.java:154)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5271)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/components/Home/Home.component.js', line: 16, column: 30
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/components/news/news.component.js', line: 11, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/app.routing.js', line: 5, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/app.module.js', line: 5, column: 21
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/main.js', line: 4, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4571)
	at android.app.ActivityThread.access$1500(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5271)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
Caused by: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

Error calling module function 

Error calling module function 

Error calling module function 

Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:580)
    com.tns.Runtime.run(Runtime.java:574)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4568)
    android.app.ActivityThread.access$1500(ActivityThread.java:154)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5271)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/components/Home/Home.component.js', line: 16, column: 30
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/components/news/news.component.js', line: 11, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/app.routing.js', line: 5, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/app.module.js', line: 5, column: 21
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/main.js', line: 4, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:580)
    com.tns.Runtime.run(Runtime.java:574)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4568)
    android.app.ActivityThread.access$1500(ActivityThread.java:154)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5271)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/components/Home/Home.component.js', line: 16, column: 30
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/components/news/news.component.js', line: 11, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/app.routing.js', line: 5, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/app.module.js', line: 5, column: 21
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/main.js', line: 4, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:580)
    com.tns.Runtime.run(Runtime.java:574)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4568)
    android.app.ActivityThread.access$1500(ActivityThread.java:154)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5271)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/components/Home/Home.component.js', line: 16, column: 30
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/components/news/news.component.js', line: 11, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/app.routing.js', line: 5, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/app.module.js', line: 5, column: 21
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/main.js', line: 4, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:580)
    com.tns.Runtime.run(Runtime.java:574)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4568)
    android.app.ActivityThread.access$1500(ActivityThread.java:154)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5271)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/components/Home/Home.component.js', line: 16, column: 30
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/components/news/news.component.js', line: 11, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/app.routing.js', line: 5, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/app.module.js', line: 5, column: 21
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/main.js', line: 4, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:580)
    com.tns.Runtime.run(Runtime.java:574)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4568)
    android.app.ActivityThread.access$1500(ActivityThread.java:154)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5271)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/components/Home/Home.component.js', line: 16, column: 30
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/components/news/news.component.js', line: 11, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/app.routing.js', line: 5, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/app.module.js', line: 5, column: 21
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/main.js', line: 4, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:580)
    com.tns.Runtime.run(Runtime.java:574)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4568)
    android.app.ActivityThread.access$1500(ActivityThread.java:154)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5271)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/components/Home/Home.component.js', line: 16, column: 30
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/components/news/news.component.js', line: 11, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/app.routing.js', line: 5, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/app.module.js', line: 5, column: 21
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.bizloud.hura/files/app/main.js', line: 4, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


	at com.tns.Runtime.runModule(Native Method)
	at com.tns.Runtime.runModule(Runtime.java:580)
	at com.tns.Runtime.run(Runtime.java:574)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4568)
	... 9 more



`

```

**Comment by dtopuzov** [comment]
Hi @mshanak can you reproduce the issue with hello-world templates?
Can you please post package.json of your application?

**Comment by dtopuzov** [comment]
Closing due to inactivity.
