### ISSUE TITLE
Windows Installer: Executing operation InstallNativeScript failed

### ISSUE THREAD

**Issue by beauars** [NativeScript/nativescript-cli#2781]
The new Windows Installer failed for me and here's the log file.  Hope it helps. 

[2B0C:2B10][2017-05-04T17:24:30]i001: Burn v3.8.1128.0, Windows v6.3 (Build 9600: Service Pack 0), path: C:\Users\John\Downloads\nativescript-cli-setup-wix.exe, cmdline: ''
[2B0C:2B10][2017-05-04T17:24:30]i000: Initializing version variable 'RequiredJdkVersion' to value '1.8'
[2B0C:2B10][2017-05-04T17:24:30]i000: Initializing version variable 'RequiredNodeJsVersion' to value '6.0.0'
[2B0C:2B10][2017-05-04T17:24:30]i000: Setting string variable 'WixBundleLog' to value 'C:\Users\John\AppData\Local\Temp\NativeScript_CLI_Setup_20170504172430.log'
[2B0C:2B10][2017-05-04T17:24:30]i000: Setting string variable 'WixBundleOriginalSource' to value 'C:\Users\John\Downloads\nativescript-cli-setup-wix.exe'
[2B0C:2B10][2017-05-04T17:24:30]i000: Setting string variable 'WixBundleName' to value 'NativeScript CLI Setup'
[2B0C:2B10][2017-05-04T17:24:30]i000: Loading managed bootstrapper application.
[2B0C:2B10][2017-05-04T17:24:30]i000: Creating BA thread to run asynchronously.
[2B0C:2B48][2017-05-04T17:24:31]i052: Condition 'VersionNT > v6.1 OR (VersionNT = v6.1 AND ServicePackLevel >= 1)' evaluates to true.
[2B0C:2B10][2017-05-04T17:24:33]i100: Detect begin, 5 packages
[2B0C:2B10][2017-05-04T17:24:33]i000: Registry key not found. Key = 'SOFTWARE\Android SDK Tools'
[2B0C:2B10][2017-05-04T17:24:33]i000: Setting numeric variable 'AndroidSdkPath' to value 0
[2B0C:2B10][2017-05-04T17:24:33]i000: Registry key not found. Key = 'SOFTWARE\JavaSoft\Java Development Kit'
[2B0C:2B10][2017-05-04T17:24:33]i000: Registry key not found. Key = 'SOFTWARE\Node.js'
[2B0C:2B10][2017-05-04T17:24:33]i000: Registry key not found. Key = 'SOFTWARE\Android Studio'
[2B0C:2B10][2017-05-04T17:24:33]i000: Setting numeric variable 'AndroidStudioSdkPathx64' to value 0
[2B0C:2B10][2017-05-04T17:24:33]i000: Registry key not found. Key = 'SOFTWARE\Android Studio'
[2B0C:2B10][2017-05-04T17:24:33]i000: Setting numeric variable 'AndroidStudioSdkPath' to value 0
[2B0C:2B10][2017-05-04T17:24:33]i000: Registry key not found. Key = 'SOFTWARE\Node.js'
[2B0C:2B10][2017-05-04T17:24:33]i000: Setting string variable 'Netfx4x64FullVersion' to value '4.6.01586'
[2B0C:2B10][2017-05-04T17:24:33]i000: Setting string variable 'JdkVersionx64' to value '1.8'
[2B0C:2B10][2017-05-04T17:24:33]i000: Setting string variable 'Netfx4FullVersion' to value '4.6.01586'
[2B0C:2B10][2017-05-04T17:24:33]i052: Condition 'Netfx4FullVersion AND (NOT VersionNT64 OR Netfx4x64FullVersion)' evaluates to true.
[2B0C:2B10][2017-05-04T17:24:33]i052: Condition 'JdkVersion >= RequiredJdkVersion OR (VersionNT64 AND JdkVersionx64 >= RequiredJdkVersion)' evaluates to true.
[2B0C:2B10][2017-05-04T17:24:33]i052: Condition '(AndroidSdkPath OR AndroidStudioSdkPath) OR (VersionNT64 AND AndroidStudioSdkPathx64)' evaluates to false.
[2B0C:2B10][2017-05-04T17:24:33]i101: Detected package: Netfx4Full, state: Present, cached: None
[2B0C:2B10][2017-05-04T17:24:33]i101: Detected package: Jdk8, state: Present, cached: None
[2B0C:2B10][2017-05-04T17:24:33]i101: Detected package: AndroidSdk, state: Absent, cached: None
[2B0C:2B10][2017-05-04T17:24:33]i101: Detected package: NodeJs, state: Absent, cached: None
[2B0C:2B10][2017-05-04T17:24:33]i101: Detected package: NodeJsx64, state: Absent, cached: None
[2B0C:2B10][2017-05-04T17:24:33]i199: Detect complete, result: 0x0
[2B0C:2B10][2017-05-04T17:24:33]i200: Plan begin, 5 packages, action: Install
[2B0C:2B10][2017-05-04T17:24:33]w321: Skipping dependency registration on package with no dependency providers: Netfx4Full
[2B0C:2B10][2017-05-04T17:24:33]i052: Condition 'False' evaluates to false.
[2B0C:2B10][2017-05-04T17:24:33]w321: Skipping dependency registration on package with no dependency providers: Jdk8
[2B0C:2B10][2017-05-04T17:24:33]w321: Skipping dependency registration on package with no dependency providers: AndroidSdk
[2B0C:2B10][2017-05-04T17:24:33]i000: Setting string variable 'WixBundleLog_AndroidSdk' to value 'C:\Users\John\AppData\Local\Temp\NativeScript_CLI_Setup_20170504172430_0_AndroidSdk.log'
[2B0C:2B10][2017-05-04T17:24:33]i052: Condition 'NOT VersionNT64 AND ((NOT NodeJsVersion AND NOT NodeJsVersionx64) OR NodeJsVersion < RequiredNodeJsVersion OR NodeJsVersionx64 < RequiredNodeJsVersion)' evaluates to false.
[2B0C:2B10][2017-05-04T17:24:33]i052: Condition 'VersionNT64 AND ((NOT NodeJsVersion AND NOT NodeJsVersionx64) OR NodeJsVersion < RequiredNodeJsVersion OR NodeJsVersionx64 < RequiredNodeJsVersion)' evaluates to true.
[2B0C:2B10][2017-05-04T17:24:33]i000: Setting string variable 'WixBundleLog_NodeJsx64' to value 'C:\Users\John\AppData\Local\Temp\NativeScript_CLI_Setup_20170504172430_1_NodeJsx64.log'
[2B0C:2B10][2017-05-04T17:24:33]i201: Planned package: Netfx4Full, state: Present, default requested: Present, ba requested: Present, execute: None, rollback: None, cache: No, uncache: No, dependency: None
[2B0C:2B10][2017-05-04T17:24:33]i201: Planned package: Jdk8, state: Present, default requested: Absent, ba requested: Absent, execute: None, rollback: None, cache: No, uncache: No, dependency: None
[2B0C:2B10][2017-05-04T17:24:33]i201: Planned package: AndroidSdk, state: Absent, default requested: Present, ba requested: Present, execute: Install, rollback: None, cache: Yes, uncache: No, dependency: None
[2B0C:2B10][2017-05-04T17:24:33]i201: Planned package: NodeJs, state: Absent, default requested: Absent, ba requested: Absent, execute: None, rollback: None, cache: No, uncache: No, dependency: None
[2B0C:2B10][2017-05-04T17:24:33]i201: Planned package: NodeJsx64, state: Absent, default requested: Present, ba requested: Present, execute: Install, rollback: None, cache: Yes, uncache: No, dependency: Register
[2B0C:2B10][2017-05-04T17:24:33]i299: Plan complete, result: 0x0
[2B0C:2B10][2017-05-04T17:24:51]i300: Apply begin
[2A94:2A98][2017-05-04T17:24:56]i360: Creating a system restore point.
[2A94:2A98][2017-05-04T17:24:56]i361: Created a system restore point.
[2A94:2A98][2017-05-04T17:24:56]i000: Caching bundle from: 'C:\Users\John\AppData\Local\Temp\{62077766-c609-4248-80d3-eec5636c3d7d}\.be\NativeScript.Cli.Setup.Wix.exe' to: 'C:\ProgramData\Package Cache\{62077766-c609-4248-80d3-eec5636c3d7d}\NativeScript.Cli.Setup.Wix.exe'
[2A94:2A98][2017-05-04T17:24:56]i320: Registering bundle dependency provider: {62077766-c609-4248-80d3-eec5636c3d7d}, version: 1.0.0.0
[2B0C:2BFC][2017-05-04T17:24:56]w343: Prompt for source of package: AndroidSdk, payload: AndroidSdk, path: C:\Users\John\Downloads\Android Software Development Kit
[2B0C:2BFC][2017-05-04T17:24:56]i338: Acquiring package: AndroidSdk, payload: AndroidSdk, download from: https://dl.google.com/android/installer_r24.4.1-windows.exe
[2A94:1B90][2017-05-04T17:26:11]i305: Verified acquired payload: AndroidSdk at path: C:\ProgramData\Package Cache\.unverified\AndroidSdk, moving to: C:\ProgramData\Package Cache\F9B59D72413649D31E633207E31F456443E7EA0B\Android Software Development Kit.
[2B0C:2BFC][2017-05-04T17:26:11]w343: Prompt for source of package: NodeJsx64, payload: NodeJsx64, path: C:\Users\John\Downloads\Node.js
[2B0C:2BFC][2017-05-04T17:26:11]i338: Acquiring package: NodeJsx64, payload: NodeJsx64, download from: https://nodejs.org/download/release/v6.9.1/node-v6.9.1-x64.msi
[2A94:1B90][2017-05-04T17:26:18]i305: Verified acquired payload: NodeJsx64 at path: C:\ProgramData\Package Cache\.unverified\NodeJsx64, moving to: C:\ProgramData\Package Cache\{672B5547-D20B-4D19-9BFD-B93C32BC77DA}v6.9.1\Node.js.
[2A94:2A98][2017-05-04T17:26:18]i301: Applying execute package: AndroidSdk, action: Install, path: C:\ProgramData\Package Cache\F9B59D72413649D31E633207E31F456443E7EA0B\Android Software Development Kit, arguments: '"C:\ProgramData\Package Cache\F9B59D72413649D31E633207E31F456443E7EA0B\Android Software Development Kit" /S'
[2B0C:2B10][2017-05-04T17:26:40]i000: Applying package AndroidSdk completed successfuly.
[2B0C:2B10][2017-05-04T17:26:40]i319: Applied execute package: AndroidSdk, result: 0x0, restart: None
[2A94:2A98][2017-05-04T17:26:40]i323: Registering package dependency provider: {672B5547-D20B-4D19-9BFD-B93C32BC77DA}, version: 6.9.1, package: NodeJsx64
[2A94:2A98][2017-05-04T17:26:40]i301: Applying execute package: NodeJsx64, action: Install, path: C:\ProgramData\Package Cache\{672B5547-D20B-4D19-9BFD-B93C32BC77DA}v6.9.1\Node.js, arguments: ' MSIFASTINSTALL="7"'
[2B0C:2B10][2017-05-04T17:26:51]i000: Applying package NodeJsx64 completed successfuly.
[2B0C:2B10][2017-05-04T17:26:51]i319: Applied execute package: NodeJsx64, result: 0x0, restart: None
[2A94:2A98][2017-05-04T17:26:51]i325: Registering dependency: {62077766-c609-4248-80d3-eec5636c3d7d} on package provider: {672B5547-D20B-4D19-9BFD-B93C32BC77DA}, package: NodeJsx64
[2B0C:2B10][2017-05-04T17:26:51]i000: Executing operation: JavaHome.
[2B0C:2B10][2017-05-04T17:26:51]i000: Executing operation JavaHome completed successfully.
[2B0C:2B10][2017-05-04T17:26:51]i000: Executing operation: AndroidHome.
[2B0C:2B10][2017-05-04T17:26:51]i000: Executing operation AndroidHome completed successfully.
[2B0C:2B10][2017-05-04T17:26:51]i000: Executing operation: AndroidSdkUpdate.
[2B0C:2B10][2017-05-04T17:26:57]i000: Executing command echo Y | "C:\Users\John\AppData\Local\Android\android-sdk\tools\android" update sdk --filter platform-tools --all --no-ui
[2B0C:2B10][2017-05-04T17:27:17]i000: Executing command echo Y | "C:\Users\John\AppData\Local\Android\android-sdk\tools\android" update sdk --filter tools --all --no-ui
[2B0C:2B10][2017-05-04T17:29:44]i000: Executing command echo Y | "C:\Users\John\AppData\Local\Android\android-sdk\tools\android" update sdk --filter android-23 --all --no-ui
[2B0C:2B10][2017-05-04T17:30:40]i000: Executing command echo Y | "C:\Users\John\AppData\Local\Android\android-sdk\tools\android" update sdk --filter build-tools-25.0.2 --all --no-ui
[2B0C:2B10][2017-05-04T17:31:12]i000: Executing command echo Y | "C:\Users\John\AppData\Local\Android\android-sdk\tools\android" update sdk --filter extra-android-m2repository --all --no-ui
[2B0C:2B10][2017-05-04T17:35:37]i000: Executing command echo Y | "C:\Users\John\AppData\Local\Android\android-sdk\tools\android" update sdk --filter extra-google-m2repository --all --no-ui
[2B0C:2B10][2017-05-04T17:37:49]i000: Executing operation AndroidSdkUpdate completed successfully.
[2B0C:2B10][2017-05-04T17:37:49]i000: Executing operation: InstallNativeScript.
[2B0C:2B10][2017-05-04T17:38:42]e000: Executing operation InstallNativeScript failed. 
Error: [31;1mPath must be a string. Received undefined[0m
Error: Unknown command 'post-install-cli'. Try '$ tns help' for a full list of supported commands.
    at Object.<anonymous> (C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:15:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\lib\nativescript-cli.js:14:18)
    at Module._compile (module.js:570:32)
[2B0C:2B10][2017-05-04T17:38:42]i399: Apply complete, result: 0x0, restart: None, ba requested restart:  No

**Comment by pkoleva** [comment]
Hey, @beauars,

It seems the post install of the CLI fails, not the installer itself, so we'd need some more details. Could you please run `tns post-install-cli --log trace` if you already have tns. If not, you can install nativescript using npm following these instructions -> http://docs.nativescript.org/start/quick-setup.

**Comment by beauars** [comment]
Thanks, @pkoleva.  It worked.  Here's the output.  

HTML file path for 'autocomplete-status.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\autocomplete-status.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\autocomplete-status.html'.
HTML file path for 'autocomplete.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\autocomplete.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\autocomplete.html'.
HTML file path for 'doctor.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\doctor.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\doctor.html'.
HTML file path for 'error-reporting.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\error-reporting.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\error-reporting.html'.
HTML file path for 'extension-install.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\extension-install.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\extension-install.html'.
HTML file path for 'extension-uninstall.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\extension-uninstall.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\extension-uninstall.html'.
HTML file path for 'extension.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\extension.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\extension.html'.
HTML file path for 'help.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\help.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\help.html'.
HTML file path for 'info.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\info.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\info.html'.
HTML file path for 'proxy-clear.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\proxy-clear.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\proxy-clear.html'.
HTML file path for 'proxy-set.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\proxy-set.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\proxy-set.html'.
HTML file path for 'proxy.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\proxy.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\proxy.html'.
HTML file path for 'usage-reporting.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\usage-reporting.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\general\usage-reporting.html'.
HTML file path for 'index.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\index.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\index.html'.
HTML file path for 'plugin-add.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\lib-management\plugin-add.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\lib-management\plugin-add.html'.
HTML file path for 'plugin-find.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\lib-management\plugin-find.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\lib-management\plugin-find.html'.
HTML file path for 'plugin-install.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\lib-management\plugin-install.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\lib-management\plugin-install.html'.
HTML file path for 'plugin-remove.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\lib-management\plugin-remove.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\lib-management\plugin-remove.html'.
HTML file path for 'plugin-search.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\lib-management\plugin-search.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\lib-management\plugin-search.html'.
HTML file path for 'plugin-update.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\lib-management\plugin-update.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\lib-management\plugin-update.html'.
HTML file path for 'plugin.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\lib-management\plugin.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\lib-management\plugin.html'.
HTML file path for 'install.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\configuration\install.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\configuration\install.html'.
HTML file path for 'platform-add.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\configuration\platform-add.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\configuration\platform-add.html'.
HTML file path for 'platform-clean.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\configuration\platform-clean.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\configuration\platform-clean.html'.
HTML file path for 'platform-remove.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\configuration\platform-remove.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\configuration\platform-remove.html'.
HTML file path for 'platform-update.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\configuration\platform-update.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\configuration\platform-update.html'.
HTML file path for 'platform.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\configuration\platform.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\configuration\platform.html'.
HTML file path for 'prepare.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\configuration\prepare.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\configuration\prepare.html'.
HTML file path for 'update.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\configuration\update.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\configuration\update.html'.
HTML file path for 'create.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\creation\create.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\creation\create.html'.
HTML file path for 'init.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\creation\init.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\creation\init.html'.
HTML file path for 'build-android.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\build-android.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\build-android.html'.
HTML file path for 'build-ios.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\build-ios.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\build-ios.html'.
HTML file path for 'build.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\build.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\build.html'.
HTML file path for 'debug-android.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\debug-android.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\debug-android.html'.
HTML file path for 'debug-ios.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\debug-ios.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\debug-ios.html'.
HTML file path for 'debug.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\debug.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\debug.html'.
HTML file path for 'deploy.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\deploy.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\deploy.html'.
HTML file path for 'dev-test-android.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\dev-test-android.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\dev-test-android.html'.
HTML file path for 'dev-test-ios.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\dev-test-ios.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\dev-test-ios.html'.
HTML file path for 'emulate-android.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\emulate-android.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\emulate-android.html'.
HTML file path for 'emulate-ios.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\emulate-ios.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\emulate-ios.html'.
HTML file path for 'emulate.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\emulate.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\emulate.html'.
HTML file path for 'run-android.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\run-android.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\run-android.html'.
HTML file path for 'run-ios.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\run-ios.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\run-ios.html'.
HTML file path for 'run.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\run.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\run.html'.
HTML file path for 'test-android.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\test-android.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\test-android.html'.
HTML file path for 'test-init.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\test-init.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\test-init.html'.
HTML file path for 'test-ios.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\test-ios.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\test-ios.html'.
HTML file path for 'test.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\test.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\project\testing\test.html'.
HTML file path for 'appstore-upload.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\publishing\appstore-upload.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\publishing\appstore-upload.html'.
HTML file path for 'appstore.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\publishing\appstore.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\publishing\appstore.html'.
HTML file path for 'publish-ios.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\publishing\publish-ios.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\publishing\publish-ios.html'.
HTML file path for 'publish.md' man page is: 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\publishing\publish.html'.
Finished writing file 'C:\Users\John\AppData\Roaming\npm\node_modules\nativescript\docs\html\publishing\publish.html'.
Finished generating HTML files.
execFile: C:\Users\John\AppData\Local\Android\android-sdk\platform-tools\adb "help"
NOTE: You can develop for iOS only on Mac OS X systems.
To be able to work with iOS devices and projects, you need Mac OS X Mavericks or later.

Installed Android Targets are:  [ 'android-23' ]
Directories found in C:\Users\John\AppData\Local\Android\android-sdk\build-tools are 25.0.2
Versions found in C:\Users\John\AppData\Local\Android\android-sdk\build-tools are 25.0.2
Selected version is:  25.0.2
Selected targetSdk is: 23
Directories found in C:\Users\John\AppData\Local\Android\android-sdk\extras\android\m2repository\com\android\support\appcompat-v7 are 18.0.0, 19.0.0, 19.0.1, 19.1.0, 20.0.0, 21.0.0, 21.0.2, 21.0.3, 22.0.0, 22.1.0, 22.1.1, 22.2.0, 22.2.1, 23.0.0, 23.0.1, 23.1.0, 23.1.1, 23.2.0, 23.2.1, 23.3.0, 23.4.0, 24.0.0, 24.0.0-alpha1, 24.0.0-alpha2, 24.0.0-beta1, 24.1.0, 24.1.1, 24.2.0, 24.2.1, 25.0.0, 25.0.1, 25.1.0, 25.1.1, 25.2.0, 25.3.0, 25.3.1, 26.0.0-alpha1, maven-metadata.xml, maven-metadata.xml.md5, maven-metadata.xml.sha1
Versions found in C:\Users\John\AppData\Local\Android\android-sdk\extras\android\m2repository\com\android\support\appcompat-v7 are 18.0.0, 19.0.0, 19.0.1, 19.1.0, 20.0.0, 21.0.0, 21.0.2, 21.0.3, 22.0.0, 22.1.0, 22.1.1, 22.2.0, 22.2.1, 23.0.0, 23.0.1, 23.1.0, 23.1.1, 23.2.0, 23.2.1, 23.3.0, 23.4.0, 24.0.0, 24.0.0, 24.0.0, 24.0.0, 24.1.0, 24.1.1, 24.2.0, 24.2.1, 25.0.0, 25.0.1, 25.1.0, 25.1.1, 25.2.0, 25.3.0, 25.3.1, 26.0.0
Selected version is:  23.4.0
Selected AppCompat version is: 23.4.0
Exec npm view nativescript  dist-tags --json
 stdout: {
  "latest": "3.0.0",
  "next": "3.0.0-2017-05-05-8820",
  "rc": "3.0.0-rc.2"
}

 stderr:
Using version 3.0.0.
Exec npm view tns-core-modules  dist-tags --json
 stdout: {
  "latest": "3.0.0",
  "angular": "2.0.0-angular-7",
  "css-animations": "1.6.2-css-animations-0",
  "next": "3.1.0-2017-05-05-6503",
  "uglify": "2.4.3-uglify",
  "internal-preview": "3.1.0-2017-05-04-6490",
  "rc": "3.0.0-rc.2"
}

 stderr:
Using version 3.0.0.
Exec npm view tns-android  dist-tags --json
 stdout: {
  "latest": "3.0.0",
  "next": "3.1.0-next-2017-05-03-1774",
  "rc": "3.0.0-rc.1"
}

 stderr:
Using version 3.0.0.
Exec npm view tns-ios  dist-tags --json
 stdout: {
  "latest": "3.0.0",
  "exp-ios-8.2": "0.9.2-exp-ios-8.2",
  "next": "3.1.0-2017-4-26-1",
  "rc": "3.0.0-rc.2"
}

 stderr:
Using version 3.0.0.
Your components are up-to-date.

Do you want to help us improve NativeScript by automatically sending anonymous usage statistics? We will not use this information to identify or contact you. You can read our official Privacy Policy at
? http://www.telerik.com/company/privacy-policy (Y/n)

**Comment by dtopuzov** [comment]
Hi @beauars glad to hear it is ok now :)
