### ISSUE TITLE
Livesync stops working

### ISSUE THREAD

**Issue by hshristov** [NativeScript/nativescript-cli#2881]
### Tell us about the problem
When I hit F5 from VS Code with modified `launch.json`
```
"tnsArgs": [
    "--sync-all-files"
]
```

and
```
npm link tns-core-modules
```
livesync stop working at some point with the following message:

```
Preparing project...
ShellJS: internal error
Error: ENOENT: no such file or directory, unlink '/Users/hhristov/tmp/recycling/platforms/android/src/main/assets/app/main-page.js'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1089:18)
    at Object.unlinkSync (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/common.js:259:8)
    at /usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/rm.js:129:16
    at Array.forEach (native)
    at Object._rm (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/rm.js:113:9)
    at Object.rm (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/common.js:365:25)
    at FileSystem.deleteDirectory (/usr/local/lib/node_modules/nativescript/lib/common/file-system.js:110:17)
    at AppFilesUpdater.deleteDestinationItem (/usr/local/lib/node_modules/nativescript/lib/services/app-files-updater.js:38:17)
    at _.each (/usr/local/lib/node_modules/nativescript/lib/services/app-files-updater.js:26:18)
[NSDebugAdapter] The tns command finished its execution with code 1.
```
### Which platform(s) does your issue occur on?
I was running Android but it may happen as well on iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.0.3
- Cross-platform modules: 3.0.1
- Runtime(s): 3.0.1
- Plugin(s): no plugins.

### Please tell us how to recreate the issue in as much detail as possible.

Modify launch.json as shown above then npm link tns-core-modules from NativeScript repo.
From VS Code hit F5 and start changing files in your application.

**Comment by endarova** [comment]
Cannot reproduce with latest versions of CLI: 5.0.0RC  and VS Code extension (v.2018.10.19.1)
