### ISSUE TITLE
Error building tutorial app + plugin on Android platform

### ISSUE THREAD

**Issue by marco-gagliardi** [NativeScript/nativescript-cli#2891]
I'm playing around with NS Grocery Angular+Typescript app tutorial and trying to integrate [nativescript-google-maps](https://github.com/dapriett/nativescript-google-maps-sdk/tree/master/ng-demo/app) plugin on it (just using the same map component code). It all works fine on iOs emulator, but when trying to build on Android emulator (API 25) i get a build failure (Execution failed for task ':buildMetadata').

This is my 'tns build android' output:

```
Executing before-prepare hook from /Users/marcogagliardi/Projects/NativeScript/Groceries/hooks/before-prepare/nativescript-dev-android-snapshot.js
Executing before-prepare hook from /Users/marcogagliardi/Projects/NativeScript/Groceries/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.2.2
Preparing project...
Project successfully prepared (android)
Executing after-prepare hook from /Users/marcogagliardi/Projects/NativeScript/Groceries/hooks/after-prepare/nativescript-dev-android-snapshot.js
Building project...

:config phase:  createDefaultIncludeFiles
        +found plugins: nativescript-google-maps-sdk
        +found plugins: tns-core-modules-widgets

:config phase:  createPluginsConfigFile
         Creating product flavors include.gradle file in /Users/marcogagliardi/Projects/NativeScript/Groceries/platforms/android/configurations folder...

:config phase:  pluginExtend
        +applying configuration from: /Users/marcogagliardi/Projects/NativeScript/Groceries/platforms/android/configurations/include.gradle
        +applying configuration from: /Users/marcogagliardi/Projects/NativeScript/Groceries/platforms/android/configurations/nativescript-google-maps-sdk/include.gradle
        +applying configuration from: /Users/marcogagliardi/Projects/NativeScript/Groceries/platforms/android/configurations/tns-core-modules-widgets/include.gradle

:config phase:  addAarDependencies
        +adding dependency: /Users/marcogagliardi/Projects/NativeScript/Groceries/platforms/android/libs/aar/widgets-release.aar
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
Incremental java compilation is an incubating feature.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_9kie10nwkgwmdz6d4v90ppg8z.run(/Users/marcogagliardi/Projects/NativeScript/Groceries/platforms/android/build-tools/android-static-binding-generator/build.gradle:126)
:preBuild UP-TO-DATE
:preF0F1DebugBuild UP-TO-DATE
:checkF0F1DebugManifest
:preF0F1ReleaseBuild UP-TO-DATE
:prepareComAndroidSupportAnimatedVectorDrawable2531Library UP-TO-DATE
:prepareComAndroidSupportAppcompatV72531Library UP-TO-DATE
:prepareComAndroidSupportDesign2531Library UP-TO-DATE
:prepareComAndroidSupportRecyclerviewV72531Library UP-TO-DATE
:prepareComAndroidSupportSupportCompat2531Library UP-TO-DATE
:prepareComAndroidSupportSupportCoreUi2531Library UP-TO-DATE
:prepareComAndroidSupportSupportCoreUtils2531Library UP-TO-DATE
:prepareComAndroidSupportSupportFragment2531Library UP-TO-DATE
:prepareComAndroidSupportSupportMediaCompat2531Library UP-TO-DATE
:prepareComAndroidSupportSupportV42531Library UP-TO-DATE
:prepareComAndroidSupportSupportVectorDrawable2531Library UP-TO-DATE
:prepareComAndroidSupportTransition2531Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBase1100Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBasement1100Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesMaps1100Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesTasks1100Library UP-TO-DATE
:prepareGroceriesRuntimeUnspecifiedLibrary UP-TO-DATE
:prepareWidgetsReleaseLibrary UP-TO-DATE
:prepareF0F1DebugDependencies
:compileF0F1DebugAidl UP-TO-DATE
:compileF0F1DebugRenderscript UP-TO-DATE
:generateF0F1DebugBuildConfig UP-TO-DATE
:cleanLocalAarFiles
:ensureMetadataOutDir
:collectAllJars
:setProperties
:generateTypescriptDefinitions SKIPPED
:copyTypings SKIPPED
:asbg:generateInterfaceNamesList
:asbg:traverseJsFiles
:asbg:runAstParser UP-TO-DATE
:asbg:generateBindings UP-TO-DATE
:generateF0F1DebugResValues UP-TO-DATE
:generateF0F1DebugResources UP-TO-DATE
:mergeF0F1DebugResources UP-TO-DATE
:processF0F1DebugManifest UP-TO-DATE
:processF0F1DebugResources UP-TO-DATE
:generateF0F1DebugSources UP-TO-DATE
:incrementalF0F1DebugJavaCompilationSafeguard UP-TO-DATE
:compileF0F1DebugJavaWithJavac UP-TO-DATE
:compileF0F1DebugNdk UP-TO-DATE
:compileF0F1DebugSources UP-TO-DATE
:buildMetadata
Exception in thread "main" java.lang.IllegalArgumentException: Class android.support.graphics.drawable.AnimatedVectorDrawableCompat$AnimatedVectorDrawableCompatState conflict: /Users/marcogagliardi/Projects/NativeScript/Groceries/platforms/android/build/intermediates/exploded-aar/com.android.support/animated-vector-drawable/25.3.1/jars/classes.jar and /Users/marcogagliardi/Projects/NativeScript/Groceries/platforms/android/build/intermediates/exploded-aar/com.android.support/animated-vector-drawable/25.2.0/jars/classes.jar
        at com.telerik.metadata.ClassRepo.addToCache(ClassRepo.java:21)
        at com.telerik.metadata.Builder.build(Builder.java:38)
        at com.telerik.metadata.Generator.main(Generator.java:44)
:buildMetadata FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildMetadata'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.983 secs
Command ./gradlew failed with exit code 1
```

**Comment by marco-gagliardi** [comment]
looks like it can be reduced to this issue:
https://github.com/NativeScript/android-runtime/issues/339

removing/readding the Android platform is a workaround.

**Comment by dtopuzov** [comment]
Hi @marco-gagliardi 

Can you config that this issues still exists with `nativescript@3.1.2` we did some changes in platform clean logic in latest versions and problem might be resolved.

**Comment by dtopuzov** [comment]
Close due to inactivity.
