### ISSUE TITLE
Android Webpack Bundling and extending Activity

### ISSUE THREAD

**Issue by mrdeleon** [NativeScript/nativescript-cli#2901]
- CLI: 3.0.3
- Cross-platform modules: 3.0.1

```
{
  "description": "NativeScript Application",
  "license": "MIT",
  "readme": "NativeScript Application",
  "repository": "",
  "nativescript": {
    "id": "com.nativescript.255955",
    "tns-android": {
      "version": "3.0.1"
    }
  },
  "dependencies": {
    "@angular/animations": "4.1.3",
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/router": "4.1.3",
    "nativescript-angular": "^3.0.0",
    "nativescript-plugin-firebase": "3.12.0",
    "nativescript-social-share": "1.3.2",
    "nativescript-telerik-ui": "^2.0.1",
    "nativescript-theme-core": "^1.0.4",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~5.4.0",
    "tns-core-modules": "^3.0.1",
    "tns-platform-declarations": "^3.0.1",
    "zone.js": "~0.8.12"
  },
  "devDependencies": {
    "@angular/compiler-cli": "4.1.3",
    "@ngtools/webpack": "~1.4.0",
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.0",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~2.1.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-android-snapshot": "^0.0.9",
    "nativescript-dev-sass": "^1.1.1",
    "nativescript-dev-typescript": "^0.4.0",
    "nativescript-dev-webpack": "^0.6.3",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.0.2",
    "typescript": "^2.2.1",
    "webpack": "~2.6.1",
    "webpack-sources": "~1.0.1"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}

```

I am running 'npm run start-android-bundle' and I am getting this build error. This started after I added in a class that extends the 'com.tns.NativeScriptActivity' Activity. I used the documented example from here just changed the activity name.
https://docs.nativescript.org/runtimes/android/advanced-topics/extend-application-activity

If I remove the extend class it will run the app just fine. Also if I keep the extend class and just run 'tns run android' it build fine as well.

 Is there another way I need to extend activities when using webpack?

```
Warning: there already is an extend called com.tns.NativeScriptActivity.
Warning: The static binding generator will generate extend from:vendor.js implementation
:asbg:generateBindings
Exception in thread "main" java.io.IOException: File already exists. This may lead to undesired behavior.ilding 67% > :asbg:generateBindings
Please change the name of one of the extended classes.
/Users/me/Documents/project/myApp/platforms/android/src/main/java/com/tns/NativeScriptActivity.java
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:59)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:15)
:asbg:generateBindings FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/me/Documents/project/myApp/platforms/android/build-tools/android-static-binding-generator/build.gradle' line: 251

* What went wrong:
Execution failed for task ':asbg:generateBindings'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 18.818 secs
Multiple errors were thrown:
Command ./gradlew failed with exit code 1
```

**Comment by Pip3r4o** [comment]
Hey @mrdeleon! 

Just as the error states, you are attempting to extend a named class (@JavaProxy decoration) with the same name, more specifically - `com.tns.NativeScriptActivity`. It's a base class and the implementation is provided by the `tns-core-modules` plugin.

To make your own Activity implementation you will simply need to provide a different name than the one that is already used up. Example: 
```typescript
@JavaProxy("com.mrdeleon.MainActivity")
class MainActivity extends android.app.Activity {
...
}
```

Don't forget to also change the name of the `activity` entry in the `app/App_Resources/android/AndroidManifest.xml` file to that of your extended activity.

Please let me know if this solves your problem.

**Comment by mrdeleon** [comment]
Hello @Pip3r4o I must have missed the notification on your feedback. I changed the name from 

'com.tns.NativeScriptActivity' to 'com.tns.NativeScriptActivityTest' 

in both areas and that works most of the time. I still get the same error very randomly. Out of the 13 days since this post and changing the name i've seen the error about 4 time. To get it building again I delete the android platform folder and run it again.

**Comment by Pip3r4o** [comment]
@mrdeleon that seems like a very random and unpredictable behavior. Please install the latest CLI with the latest android runtime package, and see if your problem persists. I'd be more than glad to help you get past that!

**Comment by rosen-vladimirov** [comment]
Hey @mrdeleon ,
Do you still have this issue?

**Comment by Fatme** [comment]
I'm closing this due to inactivity. Please feel free to write here or open an another issue in case you have some problems.

**Comment by alexma01** [comment]
Same problem

**Comment by Fatme** [comment]
Hi @alexma01,

Can you give us more information about your problem?

Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

Please tell us how to recreate the issue in as much detail as possible.

**Comment by manojdcoder** [comment]
@Pip3r4o @Fatme It's been a problem when extending activity more than once with same name. This is still essential as there may be more than one plugin I use in my project might want to extend activity to use some special features / callbacks that is not implemented in default NativeScriptActivity.

In my case, I wanted to listen for few events in my activity within the project and again the NFC plugin extends the activity for it's own purpose. This becomes hard to manage, finally I had to copy everything manually from NFC plugin's activity then merge my code with it. 

If there is a mechanism to extend NativeScriptActivity more like Mixins in Vue.js, basically merges all prototypes / objects that will be great.

**Comment by vance** [comment]
still having this issue in 4.2.4

**Comment by alvarotor** [comment]
Hi @Fatme or whoever that can have a look at this issue, its still happening to me, been a few days fighting with it, used to happen randomly but now i cant build the project at all.

`$ tns --version 6.0.3`

```    
"tns-android": {
      "version": "6.0.0"
    },
    "tns-ios": {
      "version": "6.0.1"
    },
"dependencies": {
    "@angular/animations": "~8.0.0",
    "@angular/common": "~8.0.0",
    "@angular/compiler": "~8.0.0",
    "@angular/core": "~8.0.0",
    "@angular/forms": "~8.0.0",
    "@angular/http": "~8.0.0-beta.10",
    "@angular/platform-browser": "~8.0.0",
    "@angular/platform-browser-dynamic": "~8.0.0",
    "@angular/router": "~8.0.0",
    "@ngx-translate/core": "11.0.1",
    "@ngx-translate/http-loader": "4.0.0",
    "crypto-js": "3.1.9-1",
    "nativescript-angular": "~8.0.0",
    "nativescript-background-http": "3.4.1",
    "nativescript-camera": "4.5.0",
    "nativescript-drop-down": "5.0.2",
    "nativescript-fingerprint-auth": "7.0.1",
    "nativescript-google-maps-sdk": "2.7.0",
    "nativescript-ngx-slides": "6.1.0",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-toast": "2.0.0",
    "nativescript-ui-sidedrawer": "7.0.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.5.0",
    "tns-core-modules": "~6.0.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.0.0",
    "@ngtools/webpack": "~8.0.0",
    "@types/node": "12.7.1",
    "nativescript-dev-webpack": "~1.0.0",
    "tns-platform-declarations": "6.0.6",
    "typescript": "~3.4.0"
  }
```

Would be great if you guys can give us a hand with this bug.

Thank you!
