### ISSUE TITLE
[npm5] tns plugin add/remove error

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#2935]
Steps to reproduce:
```
<install latest CLI from master>
tns create TestApp
tns plugin remove tns-core-modules --path TestApp
```

Result:
```
Support for Node.js 8.1.2 is not verified. This CLI might not install or run properly.

Error: Cannot find module 'lodash-node'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/topuzov/Git/nativescript-cli-tests/node_modules/plist/node_modules/xmlbuilder/lib/index.js:5:7)
    at Object.<anonymous> (/Users/topuzov/Git/nativescript-cli-tests/node_modules/plist/node_modules/xmlbuilder/lib/index.js:14:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

Same happens when try to install plugin:
```
Successfully installed plugin tns-core-modules.
Error: Cannot find module 'lodash-node'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/topuzov/Git/nativescript-cli-tests/node_modules/plist/node_modules/xmlbuilder/lib/index.js:5:7)
    at Object.<anonymous> (/Users/topuzov/Git/nativescript-cli-tests/node_modules/plist/node_modules/xmlbuilder/lib/index.js:14:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

This issues is critical for enabling CI tests with npm5.

**Comment by dtopuzov** [comment]
And same for `tns platform add android --path TestApp --frameworkPath tns-android.tgz:
```
Support for Node.js 8.1.2 is not verified. This CLI might not install or run properly.

Cannot find module 'lodash-node'
# platform add
```

**Comment by dtopuzov** [comment]
Seems to be some temporary issue, can not longer reproduce.
