### ISSUE TITLE
callJSMethodNative error on launch after tns upgrade 

### ISSUE THREAD

**Issue by marco-gagliardi** [NativeScript/nativescript-cli#2939]
After upgrading  to the latest tns stack version (3.1.1) I get the following error right after the application  is launched on my real device (Nexus 5x, Android 7.1.2, API 25):

```
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
07-01 17:43:48.384 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethodNative(Native Method)
07-01 17:43:48.384 18089 18089 W ExifInterface:         at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
07-01 17:43:48.384 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
07-01 17:43:48.384 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:912)
07-01 17:43:48.384 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:896)
07-01 17:43:48.384 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:888)
07-01 17:43:48.444 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethodNative(Native Method)
07-01 17:43:48.444 18089 18089 W ExifInterface:         at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
07-01 17:43:48.444 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
07-01 17:43:48.444 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:912)
07-01 17:43:48.444 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:896)
07-01 17:43:48.444 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:888)
07-01 17:43:48.451 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethodNative(Native Method)
07-01 17:43:48.451 18089 18089 W ExifInterface:         at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
07-01 17:43:48.451 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
07-01 17:43:48.451 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:912)
07-01 17:43:48.451 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:896)
07-01 17:43:48.451 18089 18089 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:888)

```

If I run the application on the Android emulator (Nexus 5x, API 26) I don't get any error

**Comment by dtopuzov** [comment]
Hi @marco-gagliardi 

May be your Nexus5x use `arm` cpu, while usually emulators use `x86` cpu architecture.
Can you create `arm` based emulator and run your app there?

Can you also add some more details for your app:
- What plugins you have (or better post `pacakge.json` of the app)
- Do you use `webpack`, `snapshots`, `abi splits` or some other technique to optimize the app.
- Does it happens with both `debug` and `release` builds?
- Can you reproduce the same issue with hello-world application?

**Comment by marco-gagliardi** [comment]
Hi @dtopuzov , 
I don't use anything that is not included and shipped along with NativeScript platform, except a couple of plugins as you can see in my  `package.json:`

```
         "nativescript": {
		"id": "org.nativescript.EstateRomana2017",
		"tns-android": {
			"version": "3.1.1"
		},
		"tns-ios": {
			"version": "3.1.0"
		}
	},
	"dependencies": {
		"@angular/animations": "~4.1.0",
		"@angular/common": "~4.1.0",
		"@angular/compiler": "~4.1.0",
		"@angular/core": "~4.1.0",
		"@angular/forms": "~4.1.0",
		"@angular/http": "~4.1.0",
		"@angular/platform-browser": "~4.1.0",
		"@angular/router": "~4.1.0",
		"nativescript-angular": "~3.0.0",
		"nativescript-geolocation": "^3.0.0",
		"nativescript-google-maps-sdk": "^2.3.0",
		"nativescript-theme-core": "~1.0.2",
		"reflect-metadata": "~0.1.8",
		"rxjs": "~5.3.0",
		"tns-core-modules": "^3.1.0",
		"zone.js": "~0.8.2"
	},
	"devDependencies": {
		"babel-traverse": "6.25.0",
		"babel-types": "6.25.0",
		"babylon": "6.17.4",
		"lazy": "1.0.11",
		"nativescript-dev-typescript": "~0.4.0",
		"typescript": "~2.2.1"
	}
```
Quick update: the app actually doesn't crash anymore, it works properly on my device, but  the console still logs such sort of error when the phone is plugged to my computer. Some page use advanced components, such as TabView or Maps, but - can't say this is 100% tue - that output apparently is only streamed when I navigate to one specific page: the homepage. So this happens the first time when the app is started and then everytime I navigated back to it. The homepage si  is a really simple page: 

```
<ActionBar title="Estate Romana 2017" class="action-bar myactionbar" android.icon="~/images/logo-roma.png" android.iconVisibility="always">
</ActionBar>
<GridLayout rows="*, auto" class="page">
    <StackLayout row="0">
        <ListView [items]="menu" class="list-group">
            <ng-template let-item="item">
                <StackLayout orientation="horizontal" class="list-group-item" [nsRouterLink]="['/'+item.link]" >
                    <GridLayout columns="50, *, auto" rows="auto" >
                        <Label text="{{ getIcon(item.icon) }}" class="icon" row="0" col="0"></Label>
                        <Label [text]="item.name" row="0" col="1"></Label>
                        <Label text="{{ getIcon('0xf105') }}" class="icon" row="0" col="2"></Label>
                    </GridLayout>
                </StackLayout>
            </ng-template>
        </ListView>
    </StackLayout>
    <GridLayout row="1">
        <Image src="~/images/footer-app_ER.jpg" stretch="aspectFill"></Image>
    </GridLayout>

</GridLayout>


```

**Comment by dtopuzov** [comment]
Hi @marco-gagliardi it looks like this issue is not related with CLI, so I'll move it to main repo (where we log issues related to tns-core-modules).

**Comment by dtopuzov** [comment]
This issue was moved to NativeScript/NativeScript#4502
