### ISSUE TITLE
Build failure for helloworld project on nativescript.org

### ISSUE THREAD

**Issue by hy9be** [NativeScript/nativescript-cli#299]
I setup the environment as instructed by the page: http://docs.nativescript.org/setup/ns-cli-setup/ns-setup-os-x.html
And then I try to build the hello world project on nativescript.org: http://docs.nativescript.org/hello-world/hello-world-ns-cli.html. But I was given the error below:

BUILD FAILED
/usr/local/Cellar/android-sdk/24.0.2/tools/ant/build.xml:653: The following error occurred while executing this line:
/usr/local/Cellar/android-sdk/24.0.2/tools/ant/build.xml:698: null returned: 1

Total time: 0 seconds
Command ant failed with exit code 1

**Comment by Fatme** [comment]
Hi @hy9be,

Could you try executing $tns build android --log trace and send the output?

**Comment by Fatme** [comment]
Could you also send the hardware info of your machine? I experienced such issue on machines with less than 512MB RAM.

**Comment by hy9be** [comment]
Thanks! I will try to collect the log. The machine has 16GB RAM so should be fine in terms of available memory.

**Comment by hy9be** [comment]
Here you go, the build trace:

TypeError: Cannot read property 'isLessThanOrEqualTo' of undefined
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:488:15)
    at /usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:15:45
    - - - - -
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:488:15)
    at /usr/local/lib/node_modules/nativescript/lib/common/dispatchers.js:30:46
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:220:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:487:10)
    at /usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:15:45
    - - - - -
    at Logger.isLevelEnabled (/usr/local/lib/node_modules/nativescript/node_modules/log4js/lib/logger.js:58:20)
    at Logger.(anonymous function) [as trace] (/usr/local/lib/node_modules/nativescript/node_modules/log4js/lib/logger.js:69:16)
    at Logger.trace (/usr/local/lib/node_modules/nativescript/lib/common/logger.js:73:33)
    at /usr/local/lib/node_modules/nativescript/lib/common/services/cancellation.js:25:27
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:220:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:487:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/dispatchers.js:30:46
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:220:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:487:10)
    at /usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:15:45

**Comment by SiddharthaRRamesh** [comment]
Even I have the same problem

**Comment by slavchev** [comment]
Hi all,

This is a known bug in our build logic. Please see the following link http://www.telerik.com/forums/nativescript-cli-build-failed-no-resource-found-that-matches-the-given-name-%27android-theme-material-light%27 for workarounds.

**Comment by SiddharthaRRamesh** [comment]
I just deleted my sdk folder and trying with the latest sdk. This might take a while!

**Comment by hy9be** [comment]
Thanks! I tried to "replaced on the file "res/values/styles.xml" Theme.Material.Light to Theme.Light". It did work.

**Comment by fedmich** [comment]
Changing from android:Theme.Material.Light to **android:Theme.Light** worked for me too. Thanks
