### ISSUE TITLE
Project builds successfully and runs on IOS emulator, but fails on real device

### ISSUE THREAD

**Issue by ryanzaatari** [NativeScript/nativescript-cli#3096]
I have no idea if this is a result of updating firebase package, I removed npm_modules, hooks, and platforms and rebuilt.
It used to work on my iphone just fine.

package.json:

> {
  "description": "Makhzoumi Foundation public application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "----NO DATA AVAILABLE----",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.makhzoumifoundation.general",
    "tns-ios": {
      "version": "2.5.0"
    },
    "tns-android": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "nativescript-cardview": "^1.3.2",
    "nativescript-carousel": "^2.4.2",
    "nativescript-floatingactionbutton": "^2.2.7",
    "nativescript-intl": "^3.0.0",
    "nativescript-loading-indicator": "^2.3.2",
    "nativescript-orientation": "^1.6.1",
    "nativescript-phone": "^1.3.0",
    "nativescript-plugin-firebase": "^4.0.6",
    "nativescript-pulltorefresh": "^1.1.10",
    "nativescript-sqlite": "^1.1.7",
    "nativescript-statusbar": "^1.0.0",
    "nativescript-telerik-ui-pro": "file:///Users/ryanzaatari/Documents/Development/NativeScript/nativescript-ui-pro.tgz",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-toasts": "^1.0.3",
    "tns-core-modules": "^2.5.2"
  },
  "devDependencies": {
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.0",
    "lazy": "1.0.11"
  }
}

Below is where it fails after running `tns run ios --log trace`

appreciate any help.
 
```
{
    "CFBundleIdentifier": "com.getray.bdd",
    "IceniumLiveSyncEnabled": false,
    "configuration": ""
  },
  {
    "CFBundleIdentifier": "com.imesart.AudioMemos2",
    "IceniumLiveSyncEnabled": false,
    "configuration": ""
  }
]
Installing...
Uninstalling com.makhzoumifoundation.general from devices with identifiers: 7340bc83b338db5470d95341c48c2554b5089700.
Received multiple results:
{ '7340bc83b338db5470d95341c48c2554b5089700':
   [ { deviceId: '7340bc83b338db5470d95341c48c2554b5089700',
       response: 'Successfully uninstalled application' } ] }
Application com.makhzoumifoundation.general has been uninstalled successfully.
Project dir from hooksArgs is: undefined.
Hooks directories: [ '/usr/local/lib/node_modules/nativescript/lib/hooks',
  '/usr/local/lib/node_modules/nativescript/lib/common/hooks',
  '/Users/ryanzaatari/Documents/Development/NativeScript/Projects/MakhzoumiFoundation/makhzoumifoundation/hooks' ]
BeforeHookName for command install is before-install
Installing /Users/ryanzaatari/Documents/Development/NativeScript/Projects/MakhzoumiFoundation/makhzoumifoundation/platforms/ios/build/device/makhzoumifoundation.ipa on devices with identifiers: 7340bc83b338db5470d95341c48c2554b5089700.
Error while executing ios device operation: Could not install application with code: -402620394
Failed to install /Users/ryanzaatari/Documents/Development/NativeScript/Projects/MakhzoumiFoundation/makhzoumifoundation/platforms/ios/build/device/makhzoumifoundation.ipa on device with identifier 7340bc83b338db5470d95341c48c2554b5089700. Error is: Could not install application
Skipping package build. No changes detected on the native side. This will be fast!
Skipping install.
Analytics statuses:
{ TrackFeatureUsage: 1, TrackExceptions: 1 }
Trying to track feature 'Deploy' with value 'iOS.emulator'.
Analytics statuses:
{ TrackFeatureUsage: 1, TrackExceptions: 1 }
Trying to track feature 'Device OS version' with value 'iOS_10.2'.
Error: Multiple errors were thrown:
Failed to install /Users/ryanzaatari/Documents/Development/NativeScript/Projects/MakhzoumiFoundation/makhzoumifoundation/platforms/ios/build/device/makhzoumifoundation.ipa on device with identifier 7340bc83b338db5470d95341c48c2554b5089700. Error is: Could not install application
    at DevicesService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/mobile/mobile-core/devices-service.js:267:23)
    at next (native)
    at fulfilled (/usr/local/lib/node_modules/nativescript/lib/common/mobile/mobile-core/devices-service.js:10:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Analytics statuses:
{ TrackFeatureUsage: 1, TrackExceptions: 1 }
Trying to track feature 'CLI' with value 'help'.
List of registered commands: /?, appstore, appstore|upload, autocomplete, autocomplete|disable, autocomplete|enable, autocomplete|status, build, build|android, build|ios, clean-app, clean-app|android, clean-app|ios, create, debug, debug|android, debug|ios, deploy, dev-generate-help, dev-generate-messages, dev-post-install, dev-preuninstall, dev-test, dev-test|android, dev-test|ios, device, devices, devices|android, devices|ios, device|android, device|get-file, device|ios, device|list-applications, device|list-files, device|log, device|put-file, device|run, device|stop, device|uninstall, doctor, emulate, emulate|android, emulate|ios, error-reporting, extension, extension|install, extension|uninstall, help, info, init, install, platform, platform|add, platform|clean, platform|remove, platform|update, plugin, plugin|add, plugin|install, plugin|remove, plugin|update, post-install-cli, prepare, proxy, proxy|clear, proxy|set, publish, publish|ios, run, run|android, run|ios, test, test|android, test|init, test|ios, update, usage-reporting
Reading help for command 'run|ios'. FileName is 'run-ios.md'.
```

**Comment by dtopuzov** [comment]
Hi @ryanzaatari

I see you use nativescript@2.5 and we did a lot of fixes since then :)
Can you reproduce the issue with `nativescript@3.1.3` or `nativescript@next`?

**Comment by ryanzaatari** [comment]
Thank you for the suggestion @dtopuzov & I'm aware of that, but the fact that upgrading breaks most of my code makes me hesitant (I did try it upon the 3.0 release).
Now for some weird reason after removing both platforms and reading/building them (I have no idea if this is even relevant), it started working again.

Cheers!
