### ISSUE TITLE
Re install fails if user setting file is not valid json

### ISSUE THREAD

**Issue by Meyer-dev** [NativeScript/nativescript-cli#3151]
On reinstalling nativescript; error in CLI:
```
Unexpected token   in JSON at position 0
Failed to display command help SyntaxError: Unexpected token   in JSON at position 0
    at Object.parse (native)
    at FileSystem.readJson (C:\Users\Renier weitz\AppData\Roaming\npm\node_modules\nativescript\lib\common\file-system.js:171:25)
    at UserSettingsService.<anonymous> (C:\Users\Renier weitz\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\user-settings-service.js:92:46)
    at next (native)
    at C:\Users\Renier weitz\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\user-settings-service.js:7:71
    at __awaiter (C:\Users\Renier weitz\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\user-settings-service.js:3:12)
    at UserSettingsService.loadUserSettingsData (C:\Users\Renier weitz\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\user-settings-service.js:82:16)
    at UserSettingsService.<anonymous> (C:\Users\Renier weitz\AppData\Roaming\npm\node_modules\nativescript\lib\services\user-settings-service.js:20:24)
    at next (native)
    at C:\Users\Renier weitz\AppData\Roaming\npm\node_modules\nativescript\lib\services\user-settings-service.js:7:71
Error while reporting exception: SyntaxError: Unexpected token   in JSON at position 0
```
Is there something I'm not doing correctly on reinstallation? any help would be greatly appreciated.Thanks :)

**Comment by rosen-vladimirov** [comment]
Hey @Meyer-dev ,
Can you check the content of your `C:\Users\Renier weitz\AppData\Roaming\.nativescript-cli\user-settings.json` file and see if it is valid JSON? I've seen such errors in the past that were raised when the file has incorrect content. If this is the case, can you please delete the file and run any CLI command again.
Also, if this is the case, may I ask if you have used `yarn` to install/update CLI?

**Comment by Meyer-dev** [comment]
Hi, thanks for the help. Deleted that file and re ran the install command.
Everything seems to be working again. I will investigate yarn:)
