### ISSUE TITLE
The test command fails to find a running iOS simulator

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#3161]
NativeScript CLI Version: 3.2.1

The following command fails to find a running iOS simulator:
```
tns test ios --emulator --debug-brk --no-watch
```

iOS Simulator:
```
$ xcrun simctl list | grep Booted
    iPhone710 (2BDC5561-F115-4E58-A042-9F7C0C7BCC3D) (Booted)
```

Output:
```
mcsofvchimev:appTS vchimev$ tns test ios --emulator --debug-brk --no-watch
Searching for devices...
16 10 2017 19:15:28.589:WARN [karma]: Port 9876 in use
16 10 2017 19:15:28.592:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9877/
16 10 2017 19:15:28.593:INFO [launcher]: Launching browser ios with unlimited concurrency
16 10 2017 19:15:28.603:INFO [launcher]: Starting browser NativeScript Unit Test Runner
Executing before-prepare hook from /Users/vchimev/Work/tmp/appTS/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.2.2
Preparing project...
Project successfully prepared (ios)
Executing after-prepare hook from /Users/vchimev/Work/tmp/appTS/hooks/after-prepare/nativescript-unit-test-runner.js
{ Error
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:16:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:15:18)
    at Module._compile (module.js:570:32)
  name: 'Exception',
  message: 'Could not find device by specified identifier \'undefined\'. To list currently connected devices and verify that the specified identifier exists, run \'tns device\'.',
  errorCode: 127,
  suppressCommandHelp: undefined }
```

**Comment by marksutt** [comment]
Still broken with tns 3.4.2
Which makes debugging tests impossible on iOS!
