### ISSUE TITLE
Wont Install Node V9

### ISSUE THREAD

**Issue by packytagliaferro** [NativeScript/nativescript-cli#3207]
Currently I cannot get this to install. 

Command: `sudo npm install -g nativescript`

Error:
```

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abbrev@1.1.0 (node_modules/nativescript/node_modules/fsevents/node_modules/abbrev):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/nativescript/node_modules/fsevents/node_modules/abbrev' -> '/usr/local/lib/node_modules/nativescript/node_modules/fsevents/node_modules/.abbrev.DELETE'

npm ERR! path /usr/local/lib/node_modules/nativescript/node_modules/fsevents/node_modules/ansi-regex
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/nativescript/node_modules/fsevents/node_modules/ansi-regex' -> '/usr/local/lib/node_modules/nativescript/node_modules/fsevents/node_modules/.ansi-regex.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

```

NPM : `5.5.1`

Node:` V 9`

**Comment by rosen-vladimirov** [comment]
Hey @packytagliaferro ,
This is an issue in npm 5, sometimes it fails to delete some metafiles, that it had already deleted in a previous step. 
Can you try the following:
```
$ npm uninstall -g nativescript
$ npm install -g nativescript
```
NOTE: based on your setup, the commands may require `sudo` privileges.

**Comment by packytagliaferro** [comment]
@rosen-vladimirov That worked sort of after running `sudo npm install -g nativescript`. I still get some errors and a message about Node V9

```
/usr/local/bin/nativescript -> /usr/local/lib/node_modules/nativescript/bin/tns
/usr/local/bin/tns -> /usr/local/lib/node_modules/nativescript/bin/tns

> fsevents@1.1.2 install /usr/local/lib/node_modules/nativescript/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@9.0.0 (node-v59 ABI) (falling back to source compile with node-gyp) 
gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /usr/local/lib/node_modules/nativescript/node_modules/fsevents
gyp ERR! node -v v9.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/nativescript/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:135:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:224:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/nativescript/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/nativescript/node_modules/fsevents
node-pre-gyp ERR! node -v v9.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)

> nativescript@3.3.0 postinstall /usr/local/lib/node_modules/nativescript
> node postinstall.js


Support for Node.js 9.0.0 is not verified. This CLI might not install or run properly.

EACCES: permission denied, mkdir '/usr/local/lib/node_modules/nativescript/docs/html'
Failed to display command help { Error: EEXIST: file already exists, open '/Users/PackyTagliaferro/.local/share/.nativescript-cli/user-settings.json.lock'
  errno: -17,
  code: 'EEXIST',
  syscall: 'open',
  path: '/Users/PackyTagliaferro/.local/share/.nativescript-cli/user-settings.json.lock' }
Error while reporting exception: Error: EEXIST: file already exists, open '/Users/PackyTagliaferro/.local/share/.nativescript-cli/user-settings.json.lock'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/nativescript/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ nativescript@3.3.0
added 685 packages and updated 7 package
```

**Comment by rosen-vladimirov** [comment]
Hey @packytagliaferro ,
Some of the errors are caused by the way `npm` executes postinstall scripts when `sudo` is used. You can find more infomation in [this thread](https://github.com/NativeScript/nativescript-cli/issues/2885) and [this one](https://github.com/NativeScript/nativescript-cli/issues/1425)
Based on your logs I think everything should be working fine, can you confirm you can use NativeScript?
For the `Support for Node.js 9.0.0 is not verified. This CLI might not install or run properly.` warning - it is our way to inform users that we are still in the process of verifying this Node.js version. Once we ensure everything works correctly, we'll remove it.

**Comment by etabakov** [comment]
I'm closing the issue due to inactivity. If you still have problems with the described scenario - feel free to write back.

**Comment by Guchster** [comment]
Try this: `sudo npm i -g nativescript --unsafe-perm=true`
