### ISSUE TITLE
tns run android - EMFILE: too many open files

### ISSUE THREAD

**Issue by JILeXanDR** [NativeScript/nativescript-cli#3268]
`tns --version` **3.3.1**

Command's `tns run android` output is:
```
Searching for devices...
Skipping prepare.
Building project...
Gradle build...
         + applying user-defined configuration from /home/alexandr/projects/MyApp/app/App_Resources/Android/app.gradle
         + creating include.gradle for plugin /home/alexandr/projects/MyApp/node_modules/tns-core-modules-widgets
         + applying plugin configuration from /home/alexandr/projects/MyApp/platforms/android/build/configurations/tns-core-modules-widgets/include.gradle
         + adding nativescript runtime package dependency: nativescript-optimized
         + adding aar plugin dependency: /home/alexandr/projects/MyApp/node_modules/tns-core-modules-widgets/platforms/android/widgets-release.aar
Running full build
Project successfully built.
Installing...
Successfully installed on device with identifier 'd5a7d6b70404'.
Unable to apply changes on device: d5a7d6b70404. Error is: EMFILE: too many open files, open '/home/alexandr/projects/MyApp/platforms/android/src/main/assets/app/tns_modules/rxjs/_esm5/operators/retry.js.map'.
The project file undefined is corrupted. 
Consider restoring an earlier version from your source control or backup.
Additional technical info: Error: EMFILE: too many open files, open '/home/alexandr/projects/MyApp/package.json'
Failed to display command help { Error: EMFILE: too many open files, scandir '/home/alexandr/.nvm/versions/node/v7.5.0/lib/node_modules/nativescript/docs/man_pages'
    at Object.fs.readdirSync (fs.js:871:18)
    at FileSystem.readDirectory (/home/alexandr/.nvm/versions/node/v7.5.0/lib/node_modules/nativescript/lib/common/file-system.js:153:19)
    at FileSystem.enumerateFilesInDirectorySync (/home/alexandr/.nvm/versions/node/v7.5.0/lib/node_modules/nativescript/lib/common/file-system.js:275:31)
    at HelpService.<anonymous> (/home/alexandr/.nvm/versions/node/v7.5.0/lib/node_modules/nativescript/lib/common/services/help-service.js:136:50)
    at Generator.next (<anonymous>)
    at fulfilled (/home/alexandr/.nvm/versions/node/v7.5.0/lib/node_modules/nativescript/lib/common/services/help-service.js:4:58)
  errno: -24,
  code: 'EMFILE',
  syscall: 'scandir',
  path: '/home/alexandr/.nvm/versions/node/v7.5.0/lib/node_modules/nativescript/docs/man_pages' }
```

**Comment by sis0k0** [comment]
@JILeXanDR can you share your package.json?

**Comment by JILeXanDR** [comment]
@sis0k0 
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.MyApp",
    "tns-android": {
      "version": "3.3.1"
    }
  },
  "dependencies": {
    "nativescript-theme-core": "~1.0.4",
    "nativescript-vue": "^0.1.1",
    "tns-core-modules": "^3.0.0",
    "vue-router": "^2.4.0"
  },
  "devDependencies": {
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.16.1",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*"
  }
}
```
