### ISSUE TITLE
`npm install nativescript` failed with "Cannot read property '1' of null"

### ISSUE THREAD

**Issue by matyapiro31** [NativeScript/nativescript-cli#3285]
OS: Ubuntu 16.04 LTS
node: v9.3.0
npm v3.9.0
javac 1.8.0_101/Oracle Java 8
ANDROID_HOME & JAVA_HOME are set correctly.

command : `npm install nativescript`with `--unsafe-perm` or `-g` also tried.
I read installation tutorial and tried os restart.
npm-debug.log: 

```python
45429 verbose stack TypeError: Cannot read property '1' of null
45429 verbose stack     at markDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:108:43)
45429 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
45429 verbose stack     at Array.forEach (<anonymous>)
45429 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
45429 verbose stack     at Array.forEach (<anonymous>)
45429 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
45429 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
45429 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
45429 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
45429 verbose stack     at recalculateMetadata (/usr/local/lib/node_modules/npm/lib/install/deps.js:147:3)
```

**Comment by NickIliev** [comment]
@matyapiro31 if you have Android Studio installed the SDK path might be different (in the case where there are two separate SDK installed) - if so see this thread [for possible solution](https://github.com/NativeScript/nativescript-cli/issues/3152#issuecomment-336579548)

**Comment by NickIliev** [comment]
Closing due to inactivity - @matyapiro31 please do let me know if you still need to resolve this issue

**Comment by matyapiro31** [comment]
Maybe I found what is the cause.
