### ISSUE TITLE
Error trying to run on ios simulator

### ISSUE THREAD

**Issue by hamdiwanis** [NativeScript/nativescript-cli#3322]
When after getting everything to work and tns doctor passes, I get this with tns run ios

```
Searching for devices...
Error: Could not find device section. null
    at Object.fail (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/lib/errors.js:5:11)
    at Simctl.getDevices (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/lib/simctl.js:57:20)
    at XCodeSimctlSimulator.getBootedDevice (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/lib/iphone-simulator-xcode-simctl.js:166:35)
    at Timeout.setInterval [as _onTimeout] (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/lib/ios-sim.js:18:60)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```
Which platform(s) does your issue occur on?

MacOS Sierra
Xcode 9

**Comment by dtopuzov** [comment]
Hi @hamdiwanis 

Can you please run this command `xcrun simctl list devices` and check if some simulators are listed in the output?

**Comment by hamdiwanis** [comment]
thanks for your response.
i run it and this is the result

```
== Devices ==
-- iOS 9.2 --
    iPhone 4s (29B4BF2F-E12A-4A1E-9FAB-0ECD4F8A3D32) (Shutdown)
    iPhone 5 (9645F443-45C6-418F-86A9-515AF3E28197) (Shutdown)
    iPhone 5s (17F13CD4-93C3-499D-98B0-1597E6665669) (Shutdown)
    iPhone 6 (D8B92F34-DB11-4BA0-97F0-6D334C665F82) (Shutdown)
    iPhone 6 Plus (6B536332-FDF0-4B69-B5C7-3B214B5A7F5C) (Shutdown)
    iPhone 6s (E20DBB72-B1B0-4928-AE0C-8FF52C553C74) (Shutdown)
    iPhone 6s Plus (9EBF5DC9-AD5D-4A96-9D1A-0EC25472FFD0) (Shutdown)
    iPad 2 (6684D6BF-14BC-41D8-AB25-D8B77C7F79DD) (Shutdown)
    iPad Retina (835E5607-96B6-4E7A-A457-A9EB6CB274C8) (Shutdown)
    iPad Air (3722B766-237C-4404-9264-B9520F5597EE) (Shutdown)
    iPad Air 2 (AE2F209D-47D5-46E1-85CB-FF869342ECCF) (Shutdown)
    iPad Pro (A08B6927-F00C-4E3D-B170-7F9AFE9A12D4) (Shutdown)
-- iOS 10.3 --
    iPhone 5 (79912C09-4EC5-4215-99B9-F9360B40EF6F) (Shutdown)
    iPhone 5s (FBAF2A44-67C9-4CC4-81DF-719552DE1A1E) (Shutdown)
    iPhone 6 (C9480914-4BF9-4728-B4E5-3677C58FD13A) (Shutdown)
    iPhone 6 Plus (43BF32DC-3FF7-4B97-9EC1-F04544AE5A63) (Shutdown)
    iPhone 6s (6F981337-2545-4949-A41E-25369ADBCC9F) (Shutdown)
    iPhone 6s Plus (5F3B8821-CD7D-4088-B208-BBC85E64C59C) (Shutdown)
    iPhone 7 (30186150-E502-4656-8087-B7D526336FCC) (Shutdown)
    iPhone 7 Plus (5F2FF4D6-3740-4A0A-AEB0-A3862A5D4DB9) (Shutdown)
    iPhone SE (1862771C-5E38-4B9F-A32E-FD78EC487DFE) (Shutdown)
    iPad Air (9AFD6666-7427-4FE8-B5B2-670B25F86CE4) (Shutdown)
    iPad Air 2 (E887C1F1-02AE-4B22-B415-80CA66846D1A) (Shutdown)
    iPad (5th generation) (F2DD3835-CF9F-484A-882F-2535E9F019AA) (Shutdown)
    iPad Pro (9.7 inch) (7F1C604D-07B3-436F-AEDD-9D46D8D952B0) (Shutdown)
    iPad Pro (12.9 inch) (43F4E388-ECA3-4EA2-8E50-45E4F9E04C73) (Shutdown)
    iPad Pro (12.9-inch) (2nd generation) (D1010C94-2CA7-4C6C-B24F-87B9CCC68598) (Shutdown)
    iPad Pro (10.5-inch) (8E5557AE-2F4B-41A9-8A5C-E532F38A79AC) (Shutdown)
-- iOS 11.1 --
    iPhone 5s (B685DB1D-081E-4F23-BC7F-811D86F029A0) (Shutdown)
    iPhone 6 (26CD9632-52C2-4832-86EA-BBD61123F975) (Shutdown)
    iPhone 6 Plus (67309953-3A0A-4E99-AB00-352E8F748104) (Shutdown)
    iPhone 6s (6F577129-1D18-4493-8696-AB0B324ECB9A) (Shutdown)
    iPhone 6s Plus (6EC47E1B-6E3E-436F-9F71-326BC4607590) (Shutdown)
    iPhone 7 (E3791354-DDBD-4D5D-84E9-1CD09720893D) (Shutdown)
    iPhone 7 Plus (4DE310E0-35B9-45E7-9D19-C3EE6F63DEEF) (Shutdown)
    iPhone 8 (706AF583-4F53-4BE2-858B-F6678F3C4C8C) (Shutdown)
    iPhone 8 Plus (3962D75F-F77E-44EE-9C23-B16C07FEB7CA) (Shutdown)
    iPhone SE (654F22FB-D770-456A-B7F3-8B85C0E4C9EB) (Shutdown)
    iPhone X (53A09762-8E83-4FA9-AB59-96F6BED8D313) (Shutdown)
    iPad Air (84277A31-71EA-485A-B5DF-5935379F7D44) (Shutdown)
    iPad Air 2 (552796F1-86EB-473A-A557-111336423C3F) (Shutdown)
    iPad (5th generation) (BF47F122-F9C6-4B0F-9D91-5D8C30BBBC8C) (Shutdown)
    iPad Pro (9.7-inch) (072E6E88-660A-46B6-9945-F92B4C3799A2) (Shutdown)
    iPad Pro (12.9-inch) (25EFAC0C-002C-43B9-A638-04FE9852864E) (Shutdown)
    iPad Pro (12.9-inch) (2nd generation) (8A4C532A-464C-42EE-A425-DD5D114D7208) (Shutdown)
    iPad Pro (10.5-inch) (0CA4B105-E9AC-4242-907F-13164192B378) (Shutdown)
-- tvOS 11.1 --
    Apple TV (8D8AA596-7CE5-47DF-A55E-3908C852A953) (Shutdown)
    Apple TV 4K (DBC87805-C7AF-4F9F-B776-A0D253BC769D) (Shutdown)
    Apple TV 4K (at 1080p) (E1400874-2B8A-4249-A11F-650A51F94312) (Shutdown)
-- watchOS 4.1 --
    Apple Watch - 38mm (9C4C388C-EE55-447B-92A0-CBA6D988D7D4) (Shutdown)
    Apple Watch - 42mm (C764B1A9-E69E-48C7-9965-22DCA491FF65) (Shutdown)
    Apple Watch Series 2 - 38mm (72D082D1-0A07-42E7-9402-15B985674069) (Shutdown)
    Apple Watch Series 2 - 42mm (F31094BB-BA4F-4B17-8816-78F04592556F) (Shutdown)
    Apple Watch Series 3 - 38mm (C741B680-0A90-4703-882B-8D7F3D302781) (Shutdown)
    Apple Watch Series 3 - 42mm (3D9AD638-9149-409E-8861-8E17A627FF85) (Shutdown)
```

**Comment by dtopuzov** [comment]
What about `xcrun simctl boot <some of the ids, for example E3791354-DDBD-4D5D-84E9-1CD09720893D>`, does it start simulator?
Can `tns run ios` deploy on already running simulator?

**Comment by hamdiwanis** [comment]
The simulator runs fine but still i can not run the app on it even if the simulator is already running.

**Comment by Fatme** [comment]
Hi @hamdiwanis,

Can you please run this command `ls -la /usr/bin/xcrun` and send us the output. I'm suspecting that this is some elevation issue.

**Comment by Fatme** [comment]
I'm closing this due to inactivity. Please feel free to write here or open an another issue in case you have some problems.

**Comment by Fatme** [comment]
Hi @hamdiwanis,

It seems that for some reasons `xcrun simctl list devices` sometimes prints an error on stderr and on stdout returns an empty array. This is the reason why our regex is not able to parse the output and `Error: Could not find device section. null` error is thrown. We've improved this behaviour in {N} 4.0.0 and handle this errors in a better way.

This is the printed error from `xcrun simctl list devices` command.
```
Unable to locate device set: Error Domain=com.apple.CoreSimulator.SimError Code=159 "Failed to initialize simulator device set." UserInfo={NSLocalizedFailureReason=Failed to subscribe to notifications from CoreSimulatorService., NSLocalizedDescription=Failed to initialize simulator device set., NSUnderlyingError=0x7fc947602fb0 {Error Domain=com.apple.CoreSimulator.SimError Code=159 "Unable to determine SimDeviceSet, set_path=/private/var/empty/Library/Developer/CoreSimulator/Devices" UserInfo={NSLocalizedDescription=Unable to determine SimDeviceSet, set_path=/private/var/empty/Library/Developer/CoreSimulator/Devices, NSUnderlyingError=0x7fc9476009f0 {Error Domain=NSPOSIXErrorDomain Code=12 "Cannot allocate memory" UserInfo={NSLocalizedFailureReason=Allocation or initialization failed., NSLocalizedDescription=Failed to initialize simulator device set.}}}}}
```
