### ISSUE TITLE
How to configure tns to read the transpiled .js files from another directory?

### ISSUE THREAD

**Issue by ramtinsoltani** [NativeScript/nativescript-cli#3420]
I've just started using NativeScript and instantly noticed that the `app` directory gets polluted with the transpiled .js files when building the app.

Since it's possible to configure tsc to transpile the files into a specific directory through `tsconfig.json`, is there a way to also let tns know where to read the files from?

**Comment by NickIliev** [comment]
@ramtinsoltani you can simply ignore these files from your source control (e.g. [here](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/.gitignore#L10-L11))

**Comment by ramtinsoltani** [comment]
@NickIliev Thanks for the quick reply. I did add `"outDir": "dist"` and it worked fine with TypeScript, but when I ran `tns run android` I got this error regarding the entry file:
`System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.`

So my question was, is there a way to configure tns to recognize the `dist` directory and use it for building the app in conjunction with the `.html` and `.css` files in the `app` directory?

**Comment by Fjnova** [comment]
same issue with .scss file. I did not want to see .css in project

**Comment by satishblr** [comment]
I have the same issue. I have a shared app for web and mobile. when I run ng serve it works good. but when i try 
`tns preview`

I get this error

`LOG from device sPhone: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
        at com.tns.Module.bootstrapApp(Module.java:311)
        at com.tns.Runtime.run(Runtime.java:615)
        at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1126)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6097)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1791)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7002)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
Caused by: com.tns.NativeScriptException: Failed to find module: "./", relative to: app//
        at com.tns.Module.resolvePathHelper(Module.java:146)
        at com.tns.Module.bootstrapApp(Module.java:309)
        ... 12 more
`
