### ISSUE TITLE
tns plugin remove fails with : Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by zbranzov** [NativeScript/nativescript-cli#3451]
### Tell us about the problem
tns plugin remove fails with: Cannot convert undefined or null to object when trying to remove "nativescript-socket.io" plugin.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.0-2018-03-09-11006
- Cross-platform modules: 3.4.1
- Runtime(s): "tns-android": {
      "version": "4.0.0-2018.3.12.1"
    }
- Plugin(s): "nativescript-socket.io": "^0.9.0"

### Please tell us how to recreate the issue in as much detail as possible.
1. tns plugin add nativescript-socket.io
2. tns plugin remove nativescript-socket.io      => Cannot convert undefined or null to object
3.  The error below is shown when using --log trace

mcsofbranzov:demo branzov$ ../node_modules/.bin/tns plugin remove nativescript-socket.io --log trace
Loading extensions.
System information:
{ platform: 'darwin',
  shell: '/bin/bash',
  os: 'Darwin mcsofbranzov 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64\n',
  procArch: 'x64',
  nodeVer: '6.10.0',
  npmVer: '3.10.10',
  nodeGypVer: null,
  dotNetVer: null,
  javacVersion: '1.8.0_121',
  xcodeVer: '9.2.0',
  xcodeprojLocation: '/usr/local/bin/xcodeproj',
  itunesInstalled: true,
  cocoaPodsVer: '1.4.0',
  adbVer: '1.0.39',
  androidInstalled: true,
  monoVer: null,
  gitVer: '2.14.3 (Apple Git-98)',
  gradleVer: null,
  isCocoaPodsWorkingCorrectly: true,
  nativeScriptCliVersion: '3.4.3',
  isCocoaPodsUpdateRequired: false,
  isAndroidSdkConfiguredCorrectly: true,
  pythonInfo: { isInstalled: true, isSixPackageInstalled: true } }
Looking for project in '/Users/branzov/Git/testRC/demo'
Project directory is '/Users/branzov/Git/testRC/demo'.
Initializing analytics statuses.
Analytics statuses:  { TrackFeatureUsage: 'disabled', TrackExceptions: 'disabled' }
TypeError: Cannot convert undefined or null to object
    at ProjectDataService.removeProperty (/Users/branzov/Git/testRC/node_modules/nativescript/lib/services/project-data-service.js:91:28)
    at ProjectDataService.removeNSProperty (/Users/branzov/Git/testRC/node_modules/nativescript/lib/services/project-data-service.js:26:14)
    at PluginVariablesService.removePluginVariablesFromProjectFile (/Users/branzov/Git/testRC/node_modules/nativescript/lib/services/plugin-variables-service.js:37:34)
    at PluginsService.<anonymous> (/Users/branzov/Git/testRC/node_modules/nativescript/lib/services/plugins-service.js:82:42)
    at next (native)
    at /Users/branzov/Git/testRC/node_modules/nativescript/lib/services/plugins-service.js:7:71
    at __awaiter (/Users/branzov/Git/testRC/node_modules/nativescript/lib/services/plugins-service.js:3:12)
    at PluginsService.remove (/Users/branzov/Git/testRC/node_modules/nativescript/lib/services/plugins-service.js:77:16)
    at RemovePluginCommand.<anonymous> (/Users/branzov/Git/testRC/node_modules/nativescript/lib/commands/plugin/remove-plugin.js:22:41)
    at next (native)
List of registered commands: /?, appstore, appstore|upload, autocomplete, autocomplete|disable, autocomplete|enable, autocomplete|status, build, build|android, build|ios, clean-app, clean-app|android, clean-app|ios, create, debug, debug|android, debug|ios, deploy, dev-generate-help, dev-generate-messages, dev-post-install, dev-preuninstall, dev-test, dev-test|android, dev-test|ios, device, devices, devices|android, devices|ios, device|android, device|get-file, device|ios, device|list-applications, device|list-files, device|log, device|put-file, device|run, device|stop, device|uninstall, doctor, error-reporting, extension, extension|install, extension|uninstall, help, info, init, install, platform, platform|add, platform|clean, platform|remove, platform|update, plugin, plugin|*list, plugin|add, plugin|build, plugin|install, plugin|remove, plugin|update, post-install-cli, prepare, proxy, proxy|clear, proxy|set, publish, publish|ios,run, run|android, run|ios, test, test|android, test|init, test|ios, update, usage-reporting
Reading help for command 'plugin|remove'. FileName is 'plugin-remove.md'.

**Comment by zbranzov** [comment]
Same happens with nativescript-linearprogressbar-swift-3.2
