### ISSUE TITLE
Trying to use default `app` folder despite using nsconfig.json

### ISSUE THREAD

**Issue by dolanmiu** [NativeScript/nativescript-cli#3558]
Platform: Windows to run Android

I get this error:

```
Error: ENOENT: no such file or directory, open 'C:\Users\Dolan\Documents\Musical\jukebox-client\apps\mobile\app\vendor-platform.android.ts'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.writeFileSync (fs.js:1314:33)
    at copyTemplate (C:\Users\Dolan\Documents\Musical\jukebox-client\apps\mobile\node_modules\nativescript-dev-webpack\projectFilesManager.js:79:12)
    at C:\Users\Dolan\Documents\Musical\jukebox-client\apps\mobile\node_modules\nativescript-dev-webpack\projectFilesManager.js:44:9
    at Array.forEach (<anonymous>)
    at Object.addProjectFiles (C:\Users\Dolan\Documents\Musical\jukebox-client\apps\mobile\node_modules\nativescript-dev-webpack\projectFilesManager.js:42:31)
    at Object.install (C:\Users\Dolan\Documents\Musical\jukebox-client\apps\mobile\node_modules\nativescript-dev-webpack\installer.js:14:25)
    at Object.<anonymous> (C:\Users\Dolan\Documents\Musical\jukebox-client\apps\mobile\node_modules\nativescript-dev-webpack\postinstall.js:12:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
```

But I have a `nsconfig.json`:

```
{
    "appPath": "src",
    "appResourcesPath": "app-resources"
}
```

So why does it still try to find the file in the `/app` folder?

I am using `"tns-android": "4.1.0-2018.4.30.1"` with `nativescript@4.1.0-2018-04-18-11407` and `"tns-core-modules": "4.0.0"`,

**Comment by dolanmiu** [comment]
Resolved by uninstalling and reinstalling
