### ISSUE TITLE
Exception will throw if you open URL with delay

### ISSUE THREAD

**Issue by miroslavaivanova** [NativeScript/nativescript-cli#3637]
### Tell us about the problem
exception will throw if you open URL with delay

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.0-rc
- Runtime(s): 4.1.1-rc

### Please tell us how to recreate the issue in as much detail as possible.
1. tns create app
2. tns debug android
Please don't open the URL. Open it after 10 min(for example). You will see the following exception:
```
System.err: java.io.IOException: Broken pipe
System.err: 	at android.net.LocalSocketImpl.write_native(Native Method)
System.err: 	at android.net.LocalSocketImpl.-wrap2(Unknown Source:0)
System.err: 	at android.net.LocalSocketImpl$SocketOutputStream.write(LocalSocketImpl.java:154)
System.err: 	at fi.iki.elonen.NanoWSD$WebSocketFrame.write(NanoWSD.java:700)
System.err: 	at fi.iki.elonen.NanoWSD$WebSocket.sendFrame(NanoWSD.java:271)
System.err: 	at fi.iki.elonen.NanoWSD$WebSocket.close(NanoWSD.java:135)
System.err: 	at fi.iki.elonen.NanoWSD$WebSocket.handleCloseFrame(NanoWSD.java:184)
System.err: 	at fi.iki.elonen.NanoWSD$WebSocket.handleWebsocketFrame(NanoWSD.java:218)
System.err: 	at fi.iki.elonen.NanoWSD$WebSocket.readWebsocket(NanoWSD.java:246)
System.err: 	at fi.iki.elonen.NanoWSD$WebSocket.access$200(NanoWSD.java:65)
System.err: 	at fi.iki.elonen.NanoWSD$WebSocket$1.send(NanoWSD.java:88)
System.err: 	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:1011)
System.err: 	at fi.iki.elonen.NanoHTTPD$LocalClientHandler.run(NanoHTTPD.java:251)
System.err: 	at java.lang.Thread.run(Thread.java:764)
```

**Comment by surdu** [comment]
This happens in our case even on normal run (not debug). Just save some file after the application was successfully installed and we get the following error:

```
System.err: java.io.IOException: Broken pipe

System.err:     at android.net.LocalSocketImpl.writeba_native(Native Method)
System.err:     at android.net.LocalSocketImpl.-wrap3(Unknown Source:0)
System.err:     at android.net.LocalSocketImpl$SocketOutputStream.write(LocalSocketImpl.java:144)
System.err:     at android.net.LocalSocketImpl$SocketOutputStream.write(LocalSocketImpl.java:131)
System.err:     at com.tns.NativeScriptSyncServiceSocketImpl$LiveSyncWorker.closeWithError(NativeScriptSyncServiceSocketImpl.java
:425)
System.err:     at com.tns.NativeScriptSyncServiceSocketImpl$LiveSyncWorker.run(NativeScriptSyncServiceSocketImpl.java:188)
System.err:     at java.lang.Thread.run(Thread.java:764)
```

**Comment by surdu** [comment]
@miroslavaivanova In our case the problem was cause my version mismatch in between components. Try running `tns info` and make sure that you run the latest versions.
