### ISSUE TITLE
tns test <platform> throw exception

### ISSUE THREAD

**Issue by miroslavaivanova** [NativeScript/nativescript-cli#3689]
### Tell us about the problem
tns test <platform>  is failing with :`ERROR [karma]: TypeError: Cannot read property 'markCaptured' of undefined`

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: next
- Runtime(s): next

### Please tell us how to recreate the issue in as much detail as possible.
1. `tns create app`
2. `tns build <platform>`
3. `tns test init --framework mocha`
4. `npm install mocha --save-dev`
5. `tns test <platform>`

`18 06 2018 13:30:02.974:ERROR [karma]: TypeError: Cannot read property 'markCaptured' of undefined
    at Launcher.markCaptured (/Users/user/MyDocuments/unitApp/node_modules/karma/lib/launcher.js:176:13)
    at Server.on (/Users/user/MyDocuments/unitApp/node_modules/karma/lib/server.js:179:16)
    at Server.emit (events.js:164:20)
    at Browser.init (/Users/user/MyDocuments/unitApp/node_modules/karma/lib/browser.js:54:18)
    at Socket.socket.on (/Users/user/MyDocuments/unitApp/node_modules/karma/lib/server.js:235:22)
    at Socket.emit (events.js:159:13)
    at /Users/user/MyDocuments/unitApp/node_modules/socket.io/lib/socket.js:513:12
    at process._tickCallback (internal/process/next_tick.js:150:11)
CONSOLE LOG file:///app/tns_modules/nativescript-unit-test-runner/main-view-model.js:90:28: NSUTR-socket.io: io server disconnect
Test run failed.
`

**Comment by rosen-vladimirov** [comment]
Issue us caused by 2.0.3 release of karma. More information can be found [here](https://github.com/karma-runner/karma/issues/3052).

As a workaround you can manually apply the fix from [here](https://github.com/karma-runner/karma/pull/3047) or use 2.0.2 of karma - just execute `npm install --save-dev --save-exact karma@2.0.2` in your project dir.
