### ISSUE TITLE
ERROR: An uncaught Exception occurred on "AsyncTask #1" thread. with alert('z') inside ngOnInit and constructors in first route

### ISSUE THREAD

**Issue by ElecTreeFrying** [NativeScript/nativescript-cli#3693]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

yes

### Tell us about the problem
I am getting this error then logging with alerts `alert('any-string')` inside constructors and ngOnInit, in `app/item/items.component.ts` and in `app.component.ts`. 

and in all routes after `"/"` only

```
const routes: Routes = [
    { path: "", redirectTo: "/a", pathMatch: "full" },
    { path: "a", component: aC },     // affected 
    { path: "b", component: bC }      // affected
    { path: "c", component: cC},      // affected
    { path: "c/:id", component: X},   // not affected
    { path: "d/e", component: X},     // not affected
    { path: "d/e/f/g", component: X},    // not affected
];
```
but is working perfectly fine with tap events `(tap)="anyFunction()"`

app
 | -> App_Resources
 | -> item
 | | -> item-detail.component.html
 | | -> item-detail.component.ts
 | | -> item.service.ts
 | | -> item.ts
 | | -> items.component.html
 | | -> items.component.ts
 -> app.component.html
 -> app.component.ts
 -> app.css
 -> app.module.ngfactory.d.ts
 -> app.module.ts
 -> app.routing.ts
 -> main.aot.ts
 -> main.ts
 -> package.json
 -> README.md

after the very first `successfully synced application org.nativescript.myApp` this error appears in CLI

```
An uncaught Exception occurred on "AsyncTask #1" thread.
java.lang.RuntimeException: An error occured while executing doInBackground()
	at org.nativescript.widgets.image.AsyncTask$3.done(AsyncTask.java:326)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at org.nativescript.widgets.image.AsyncTask$SerialExecutor$1.run(AsyncTask.java:256)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalArgumentException: not a directory: /storage/emulated/0/Android/data/org.nativescript.myapp/cache/http
	at org.nativescript.widgets.image.DiskLruCache.deleteContents(DiskLruCache.java:257)
	at org.nativescript.widgets.image.DiskLruCache.delete(DiskLruCache.java:713)
	at org.nativescript.widgets.image.DiskLruCache.open(DiskLruCache.java:328)
	at org.nativescript.widgets.image.Fetcher.initDiskCacheInternal(Fetcher.java:92)
	at org.nativescript.widgets.image.Worker$CacheAsyncTask.doInBackground(Worker.java:502)
	at org.nativescript.widgets.image.Worker$CacheAsyncTask.doInBackground(Worker.java:493)
	at org.nativescript.widgets.image.AsyncTask$2.call(AsyncTask.java:313)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.0
- Cross-platform modules: 4.1.0
- Runtime(s): 4.1.3
- Plugin(s): 4.1.3

### Please tell us how to recreate the issue in as much detail as possible.

Step to reproduce:
1. `tns create myApp --ng;cd myApp;tns platform add android;tns run android`

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-angular#1394
