### ISSUE TITLE
Openning Chrome url in second tab cannot connect when debug iOS on device

### ISSUE THREAD

**Issue by Natalia-Hristova** [NativeScript/nativescript-cli#3712]
### Tell us about the problem
Try to debug iOS on device and open Chrome `url` in 2 tabs - the first one work as expected, the second one not. _Works on simulator._

**Tested on iPhone 6 - OS 11.3.1**

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: `4.1.2`
- Runtime(s): ios `4.1.1`

### Please tell us how to recreate the issue in as much detail as possible.
1. `tns create SomeApp`
2. `tns debug ios`
3. Open url in Chrome tab
4. Open the same `url` in another Chrome tab

```
// Open url in Chrome tab
Frontend client connected.
Backend socket created.
CONSOLE LOG file:///app/tns_modules/tns-core-modules/inspector_modules.js:1:82: Loading inspector modules...
CONSOLE LOG file:///app/tns_modules/tns-core-modules/inspector_modules.js:6:12: Finished loading inspector modules.
NativeScript debugger attached.

// Open another tab
Frontend client connected.
Backend socket closed!
Frontend socket closed!

// Trying to reconnent the first one or open new tabs
Frontend client connected.
Error: Cannot connect to device socket. The error message is This socket has been ended by the other party
    at Errors.fail (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:125:28)
    at Errors.failWithoutHelp (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:135:21)
    at SocketProxyFactory.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/device-sockets/ios/socket-proxy-factory.js:91:38)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/nativescript/lib/device-sockets/ios/socket-proxy-factory.js:5:65)
    at <anonymous>
```

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Consider using the [playground](https://play.nativescript.org) to provide the code you have issues with.

**Comment by Natalia-Hristova** [comment]
duplicated: https://github.com/NativeScript/nativescript-cli/issues/3654
