### ISSUE TITLE
npm test error

### ISSUE THREAD

**Issue by deepthignair** [NativeScript/nativescript-cli#3740]
SyntaxError: Unexpected token import

      19 |
      20 | import { DrawerNavigator } from 'react-navigation';
    > 21 | import { Container, Content, Header, Body, Icon } from 'native-base';
      22 |
      23 |
      24 | import Splash from './src/screens/Splash';

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:318:17)
      at Object.<anonymous> (node_modules/native-base/dist/src/index.js:1:1115)
      at Object.<anonymous> (App.js:21:17)

**Comment by rosen-vladimirov** [comment]
Hey @deepthignair ,
This repository is related to NativeScript CLI. It looks like your issue is related to react-native, so I suggest you to file an issue in their [GitHub repository](https://github.com/facebook/react-native).
