### ISSUE TITLE
Cant't run android commands

### ISSUE THREAD

**Issue by FahmiChaar** [NativeScript/nativescript-cli#3790]
### Tell us about the problem
> tns doctor

infinit run ⠋ Getting environment information with no result or error

> tns run android

also still blank with no result or error

and the terminal title is <command-name | exp: tns doctor> (qemu-system-i386)

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.2

### Please tell us how to recreate the issue in as much detail as possible.
- install nativescript package with npm and create fresh project 

Note: when i use 
> tns run ios

The app run on the device successfully.

Note: Im from ionic/cordova background and my dev envirement work fine on android and ios

**Comment by rosen-vladimirov** [comment]
Hey @FahmiChaar ,
Can you please run 
```
tns run android --log trace
```
and send us the output.

Can you do the same with
```
tns build android --log trace
```

Also do you have attached Android device or running Android Emulator when you execute the `tns run android` command?

**Comment by rosen-vladimirov** [comment]
Hey @FahmiChaar ,
Please excuse me for the late reply, I was on a vacation. 
Unfortunately the output you've posted is not the full one from the command, can you please try `tns build android --log trace > out.txt` and send us the out.txt file that will be created once the command finishes its execution.

**Comment by NickIliev** [comment]
Closing due to inactivity - @FahmiChaar  will reopen if you are still experiencing the issue (please provide the log as requested in the comment above)

**Comment by FahmiChaar** [comment]
Hi, i come back again and i still have the same issue
> tns info

✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.4.2 version and is up to date.
✔ Component tns-core-modules has 5.4.2 version and is up to date.
✔ Component tns-android has 5.4.0 version and is up to date.
✔ Component tns-ios has 5.4.2 version and is up to date.

> tns build android --log trace > out.txt


```
Trying to get macOS version.
Exec system_profiler SPSoftwareDataType -detailLevel mini 
 stdout: Software:

    System Software Overview:

      System Version: macOS 10.13.6 (17G65)
      Kernel Version: Darwin 17.7.0
      Time since boot: 3:11

 
 stderr: 
macOS version based on system_profiler is 10.13.
Error: Trying to handle SIGINT event. CLI overrides this behavior and does not allow handling SIGINT as this causes issues with Ctrl + C in terminal
    at process.on (/usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:22:22)
    at /usr/local/lib/node_modules/nativescript/node_modules/signal-exit/index.js:122:15
    at Array.filter (<anonymous>)
    at load (/usr/local/lib/node_modules/nativescript/node_modules/signal-exit/index.js:120:21)
    at module.exports (/usr/local/lib/node_modules/nativescript/node_modules/signal-exit/index.js:35:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/node_modules/proper-lockfile/lib/lockfile.js:296:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Looking for project in '/Users/imac/projects/nativescript/xxx'
Project directory is '/Users/imac/projects/nativescript/xxx'.
Loading extensions.
Asserting extension nativescript-cloud is installed.
Extension nativescript-cloud is installed.
Asserting extension nativescript-starter-kits is installed.
Extension nativescript-starter-kits is installed.

```
