### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by jibon57** [NativeScript/nativescript-cli#3811]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it) 4.2.0
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project) 4.2.0
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project) 4.2.0

### Please tell us how to recreate the issue in as much detail as possible.

Hello,

After upgrading to NativeScript 4.2.0 I am getting following error when I am try to run `tns run android`.
```
Connected devices & emulators
Searching for devices...
iTunes is not installed. Install it on your system and run this command again.
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:489:7)
    at AndroidVirtualDeviceService.<anonymous> (C:\Users\Jibon\AppData\Roaming\npm\node_modules\nativescript\lib\common\mobile\android\android-virtual-device-service.js:64:38)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Jibon\AppData\Roaming\npm\node_modules\nativescript\lib\common\mobile\android\android-virtual-device-service.js:10:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
`tns info`:

```
√ Getting NativeScript components versions information...
√ Component nativescript has 4.2.0 version and is up to date.
√ Component tns-core-modules has 4.2.0 version and is up to date.
√ Component tns-android has 4.2.0 version and is up to date.
× Component tns-ios is not installed.
```
`tns doctor`:

```
√ Getting environment information

No issues were detected.
√ Your ANDROID_HOME environment variable is set and points to correct directory.
√ Your adb from the Android SDK is correctly installed.
√ The Android SDK is installed.
√ A compatible Android SDK for compilation is found.
√ Javac is installed and is configured properly.
√ The Java Development Kit (JDK) is installed and is configured properly.
√ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
√ Getting NativeScript components versions information...
√ Component nativescript has 4.2.0 version and is up to date.
√ Component tns-core-modules has 4.2.0 version and is up to date.
√ Component tns-android has 4.2.0 version and is up to date.
× Component tns-ios is not installed.
```
Any hints in where I am doing mistake? Thanks in advance.

**Comment by jibon57** [comment]
Thanks @rosen-vladimirov. I am confirming that `4.2.1` has solved my problem :)
