### ISSUE TITLE
TNS Doctor does not detect the version of NS CLI

### ISSUE THREAD

**Issue by Nati323** [NativeScript/nativescript-cli#3815]
Hi, I'm trying to install SideKick.

it tells me that it wants to install Native Script CLI 4.1.0,
I clicked Install and I get this error:
`TNS Doctor does not detect the version of NS CLI`.

when I run `tns` command on the cmd I get the list of commands, but in SideKick I get the above error.

I'm using Windows 10.

**Comment by rosen-vladimirov** [comment]
Hey @Nati323 ,
Please excuse us for the late reply. May I ask you what is your tns version, i.e. can you send us the output of the following command:
```
tns --version
```
Also you can try installing the latest available CLI version by executing `npm install -g nativescript@latest`.

If this does not solve your issue, can you share the log files that Sidekick created. 
You can access the logs by following the steps outlined below.
* In NativeScript Sidekick <br/> _Launch Sidekick and select **Help** &#8594; **Show Logs** from the top menu._

**Comment by NickIliev** [comment]
Closing this issue due to inactivity - @Nati323 let us know if you are still experiencing troubles after testing with the lates.

**Comment by ostadsaleh** [comment]
Support for Node.js 11.1.0 is not verified. NativeScript CLI might not install or run properly.

ReferenceError: internalBinding is not defined
    at fs.js:25:1
    at req_ (C:\Users\ostadsaleh\AppData\Roaming\npm\node_modules\nativescript\node_modules\natives\index.js:140:5)
    at Object.req [as require] (C:\Users\ostadsaleh\AppData\Roaming\npm\node_modules\nativescript\node_modules\natives\index.js:54:10)
    at Object.<anonymous> (C:\Users\ostadsaleh\AppData\Roaming\npm\node_modules\nativescript\node_modules\fstream\node_modules\graceful-fs\fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)



i have the same issue?

**Comment by Fatme** [comment]
@ostadsaleh,
> Support for Node.js 11.1.0 is not verified. NativeScript CLI might not install or run properly.

The support for node11 will be released with {N} 5.0.1 version. So in order to use it, you need to install the next version of {N} CLI.
```
npm un -g nativescript
npm i -g nativescript@next
```

**Comment by musifor** [comment]
I had the exact same issue as the one above. How can I fix it?

**Comment by gkumar414** [comment]
npm un -g nativescript
npm i -g nativescript@next

**Comment by ostadsaleh** [comment]
Support for Node.js 11.1.0 is not verified. NativeScript CLI might not install or run properly.


The support for node11 will be released with {N} 5.0.1 version. So in order to use it, you need to install the next version of {N} CLI.
npm un -g nativescript
npm i -g nativescript@next
    On Monday, December 24, 2018, 9:59:14 PM GMT+3:30, Rafael Hovhannisyan <notifications@github.com> wrote:  
 
 
I have the same issue, then trying to run Sidekick at first.
Sidekick required the nativescript@latest version, but after installing it says the same error and asking me to retry.

**Comment by jaredware** [comment]
I am receiving the same issue as above on the initial installation. I ran the manual upgrade and restarted the app, restarted pc, uninstalled and reinstalled and still, the same error occurs.

I am using nativescript@6.3.3

I ran the `tns --version` code you suggested to the original thread and it returned `6.13.4`

**Comment by ostadsaleh** [comment]
Thanks Jared for your opinion 

Sent from Yahoo Mail on Android 
 
  On Mon, Jan 20, 2020 at 15:17, Jared Ware<notifications@github.com> wrote:   
I am receiving the same issue as above on the initial installation. I ran the manual upgrade and restarted the app, restarted pc, uninstalled and reinstalled and still, the same error occurs.

I am using nativescript@6.3.3

I ran the tns --version code you suggested to the original thread and it returned 6.13.4
