### ISSUE TITLE
[Sporadic] Unable to start iOS debugger from VSCode extension

### ISSUE THREAD

**Issue by Fatme** [NativeScript/nativescript-cli#3821]
### Tell us about the problem
Sometimes {N} CLI is not able to start iOS debugger from VSCode extension.

### Which platform(s) does your issue occur on?
iOS

### Please tell us how to recreate the issue in as much detail as possible.
Steps to reproduce:
1. Create project and open it with VSCode extension
2. Run `Launch on iOS` from VSCode extension
3. An error is thrown:
`Error: Cannot connect to device socket. The error message is NativeScript debugger was not able to get inspector socket port.
    at Errors.fail (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:125:28)
    at Errors.failWithoutHelp (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:135:21)
    at SocketProxyFactory.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/device-sockets/ios/socket-proxy-factory.js:91:38)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/nativescript/lib/device-sockets/ios/socket-proxy-factory.js:5:65)
    at <anonymous>
`

**Comment by nickcabral** [comment]
I'm still getting this exact error after updating to CLI 4.2.2. Possible to reopen this issue?
