### ISSUE TITLE
[Major] Unable to start iOS debugger from VSCode extension

### ISSUE THREAD

**Issue by nickcabral** [NativeScript/nativescript-cli#3826]
Copied from #3821, which has been prematurely closed (issue still exists). Really need the vscode debugger to work.

### Tell us about the problem
{N} CLI is not able to start iOS debugger from VSCode extension.

### Which platform(s) does your issue occur on?
iOS

### Please tell us how to recreate the issue in as much detail as possible.
Steps to reproduce:
- Create project and open it with VSCode extension
- Run Launch on iOS from VSCode extension
- An error is thrown:
`Error: Cannot connect to device socket. The error message is NativeScript debugger was not able to get inspector socket port. at Errors.fail (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:125:28) at Errors.failWithoutHelp (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:135:21) at SocketProxyFactory.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/device-sockets/ios/socket-proxy-factory.js:91:38) at Generator.throw (<anonymous>) at rejected (/usr/local/lib/node_modules/nativescript/lib/device-sockets/ios/socket-proxy-factory.js:5:65) at <anonymous>`

**Comment by nickcabral** [comment]
@rosen-vladimirov see my response on the related issue over on the nativescript-vscode-extension repo: [link](https://github.com/NativeScript/nativescript-vscode-extension/issues/188#issuecomment-415621165). You suggested a workaround to me over on that tread (thanks again!)

To answer your specific questions:
1. Yes I can repro the issue with a new project.
2. I've only experienced the issue with a simulator; haven't had a chance to debug on a device recently.
3. I don't experience the issue when I run `tns debug ios` directly from the terminal.

Based on #<span/>3, this seems to be a problem with the ns-vscode-extension, and not the NS CLI. So I think this issue can be closed, and the problem addressed on the the issue I linked above. Thoughts?
