### ISSUE TITLE
Unable to find the Genymotion player

### ISSUE THREAD

**Issue by richjava** [NativeScript/nativescript-cli#3845]
### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.
On Windows 7, when I run a Genymotion virtual device and then run the command "tns devices android --available-device" I get an error help message of: "Unable to find the Genymotion player in the following locations: %ProgramFiles%\Genymobile\Genymotion\player.exe", but I have player.exe at the following path: C:\Program Files\Genymobile\Genymotion, so it should work. 

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.2.2
- Runtime(s): tns-android and tns-ios 4.2.0

### Please tell us how to recreate the issue in as much detail as possible.
Install Genymotion, run a virtual device, and then run "tns devices android --available-device"

**Comment by Fatme** [comment]
Hi @richjava,

Can you please execute `tns devices android --available-device --log trace` and send us the output?

**Comment by richjava** [comment]
Strange... Now when I run `tns devices android --available-device` I get the following:

> The option 'available-device' is not supported. To see command's options, use '$ tns help devices'. To see all commands use '$ tns help'.

Here is the output for `tns devices android --available-device --log trace`:
```
Loading extensions.
Asserting extension nativescript-cloud is installed.
Extension nativescript-cloud is installed.
Asserting extension nativescript-starter-kits is installed.
Extension nativescript-starter-kits is installed.
System information:
{ platform: 'win32',
  shell: 'C:\\Windows\\system32\\cmd.exe',
  os: 'Windows 7 Ultimate 6.1.7601',
  procArch: 'x64',
  nodeVer: '8.9.4',
  npmVer: '6.4.0',
  nodeGypVer: '3.6.2',
  nativeScriptCliVersion: '4.2.2',
  gitVer: '2.16.2.windows.1',
  dotNetVer: '4.7.03062',
  javacVersion: '1.8.0_181',
  adbVer: '1.0.40',
  androidInstalled: true,
  monoVer: null,
  gradleVer: '1.12',
  isAndroidSdkConfiguredCorrectly: true,
  xcodeVer: undefined,
  xcodeprojLocation: null,
  itunesInstalled: false,
  cocoaPodsVer: undefined,
  isCocoaPodsWorkingCorrectly: false,
  isCocoaPodsUpdateRequired: false,
  pythonInfo: null }
Starting watch on killswitch C:\Users\RICHAR~1\AppData\Local\Temp\richard_lovell\KillSwitches\cli
The option 'available-device' is not supported. To see command's options, use '$ tns help devices'. To see all commands use '$ tns
help'.
Error: The option 'available-device' is not supported. To see command's options, use '$ tns help devices'. To see all commands use
'$ tns help'.
    at Errors.fail (C:\Users\richard_lovell\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:125:28)
    at Errors.failWithoutHelp (C:\Users\richard_lovell\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:135:21)
    at _.each (C:\Users\richard_lovell\AppData\Roaming\npm\node_modules\nativescript\lib\common\options.js:92:34)
    at C:\Users\richard_lovell\AppData\Roaming\npm\node_modules\nativescript\node_modules\lodash\lodash.js:4925:15
    at baseForOwn (C:\Users\richard_lovell\AppData\Roaming\npm\node_modules\nativescript\node_modules\lodash\lodash.js:3010:24)
    at C:\Users\richard_lovell\AppData\Roaming\npm\node_modules\nativescript\node_modules\lodash\lodash.js:4894:18
    at Function.forEach (C:\Users\richard_lovell\AppData\Roaming\npm\node_modules\nativescript\node_modules\lodash\lodash.js:9342:14)
    at Options.validateOptions (C:\Users\richard_lovell\AppData\Roaming\npm\node_modules\nativescript\lib\common\options.js:85:11)
    at CommandsService.<anonymous> (C:\Users\richard_lovell\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\commands-service.js:108:31)
    at Generator.next (<anonymous>)
Initializing analytics statuses.
Analytics statuses:  { TrackFeatureUsage: 'disabled', TrackExceptions: 'disabled' }
```

**Comment by NickIliev** [comment]
@richjava you are misspelling the flag is is plural **devices**
```
tns devices --available-devices
```
```
Available emulators
┌───────────────────┬──────────┬─────────┬───────────────────┬───────────────────┬────────────┐
│ Device Name       │ Platform │ Version │ Device Identifier │ Image Identifier  │ Error Help │
│ Nexus 5X API 25   │ Android  │ 7.1.1   │ emulator-5554     │ Nexus_5X_API_25   │            │
│ Pixel 2 XL API 28 │ Android  │ 9.0.0   │                   │ Pixel_2_XL_API_28 │            │
```

**Comment by Yura13** [comment]
Hi, I have the same issue.
Here logs:
```
Loading extensions.
System information:
{ platform: 'win32',
  shell: 'C:\\Windows\\system32\\cmd.exe',
  os: 'Windows 8.1 Pro 6.3.9600',
  procArch: 'x64',
  nodeVer: '8.11.3',
  npmVer: '5.6.0',
  nodeGypVer: null,
  nativeScriptCliVersion: '4.2.3',
  gitVer: '2.16.2.windows.1',
  dotNetVer: '4.7.03062',
  javacVersion: '1.8.0_112',
  adbVer: null,
  androidInstalled: false,
  monoVer: null,
  gradleVer: null,
  isAndroidSdkConfiguredCorrectly: false,
  xcodeVer: undefined,
  xcodeprojLocation: null,
  itunesInstalled: false,
  cocoaPodsVer: undefined,
  isCocoaPodsWorkingCorrectly: false,
  isCocoaPodsUpdateRequired: false,
  pythonInfo: null }
Starting watch on killswitch C:\Users\Yura\AppData\Local\Temp\Yura\KillSwitches\cli
Initializing analytics statuses.
Analytics statuses:  { TrackFeatureUsage: 'disabled', TrackExceptions: 'disabled' }
Looking for project in 'C:\Projects\acquaintanceship'
Project directory is 'C:\Projects\acquaintanceship'.
spawn: adb "version"
spawn: C:\Users\Yura\AppData\Local\Temp\telerik-common-lib-0.22.0\adb "start-server"
spawn: C:\Users\Yura\AppData\Local\Temp\telerik-common-lib-0.22.0\adb "devices"
spawn: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe "list" "vms"
spawn: player 0
Configuration error for Genymotion { stdout: '', stderr: 'spawn player ENOENT', exitCode: 'ENOENT' }
spawn: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe "guestproperty" "enumerate" "ca5001a2-cbe2-4378-90a2-c38c20041278"
spawn: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe "guestproperty" "enumerate" "1ea81634-1ca4-493f-9ee1-0747a3e3abfd"

Available emulators
┌────────────────────────────┬──────────┬─────────┬───────────────┬──────────────────────┬───────────────────────────────────────────────────────────────────────────────────┐
│ Device Name                │ Platform │ Version │ Device        │ Image Identifier     │ Error Help                                                                        │
│                            │          │         │ Identifier    │                      │                                                                                   │
│ Google Nexus 5 - 4.4.4 -   │ Android  │ 4.4.4   │               │ ca5001a2-cbe2-4378   │ Unable to find the Genymotion player in the following locations:                  │
│ API 19 - 1080x1920         │          │         │               │ -90a2-c38c20041278   │ %ProgramFiles%                                                                    │
│                            │          │         │               │                      │ \Genymobile\Genymotion\player.exe                                                 │
│                            │          │         │               │                      │ %ProgramFiles(x86)%\Genymobile\Genymotion                                         │
│                            │          │         │               │                      │ \player.exe                                                                       │
│                            │          │         │               │                      │ In case you have installed Genymotion in a different location, please             │
│                            │          │         │               │                      │ add the path to player executable to your PATH environment variable.              │
│ Nexus 5 - 5.1.0 - API 22 - │ Android  │ 5.1.0   │               │ 1ea81634-1ca4-493f   │ Unable to find the Genymotion player in the following locations:                  │
│ 1080x1920                  │          │         │               │ -9ee1-0747a3e3abfd   │ %ProgramFiles%                                                                    │
│                            │          │         │               │                      │ \Genymobile\Genymotion\player.exe                                                 │
│                            │          │         │               │                      │ %ProgramFiles(x86)%\Genymobile\Genymotion                                         │
│                            │          │         │               │                      │ \player.exe                                                                       │
│                            │          │         │               │                      │ In case you have installed Genymotion in a different location, please             │
│                            │          │         │               │                      │ add the path to player executable to your PATH environment variable.              │
└────────────────────────────┴──────────┴─────────┴───────────────┴──────────────────────┴───────────────────────────────────────────────────────────────────────────────────┘

Connected devices & emulators
Searching for devices...
Options for ios-device-discovery { platform: undefined,
  shouldReturnImmediateResult: false,
  emulator: false }
iTunes is not installed. Install it on your system and run this command again.
spawn: C:\Users\Yura\AppData\Local\Temp\telerik-common-lib-0.22.0\adb "start-server"
Result when throw error is false:
{ stdout: '', stderr: '', exitCode: 0 }
spawn: C:\Users\Yura\AppData\Local\Temp\telerik-common-lib-0.22.0\adb "devices"
Cannot find connected devices. Reconnect any connected devices, verify that your system recognizes them, and run this command again.

```

**Comment by Yura13** [comment]
Everything works after: tns platform add android.
