### ISSUE TITLE
Not able to install NativeScript on OS X

### ISSUE THREAD

**Issue by xaransh** [NativeScript/nativescript-cli#4104]
npm install -g nativescript

Gives the following output.

> nativescript@5.0.0 preuninstall /usr/local/lib/node_modules/nativescript
> node preuninstall.js

Failed to complete all pre-uninstall steps.
/usr/local/bin/tns -> /usr/local/lib/node_modules/nativescript/bin/tns
/usr/local/bin/nativescript -> /usr/local/lib/node_modules/nativescript/bin/tns

> nativescript@5.0.0 postinstall /usr/local/lib/node_modules/nativescript
> node postinstall.js

Support for Node.js 11.1.0 is not verified. NativeScript CLI might not install or run properly.

ReferenceError: internalBinding is not defined
    at fs.js:25:1
    at req_ (/usr/local/lib/node_modules/nativescript/node_modules/natives/index.js:140:5)
    at Object.req [as require] (/usr/local/lib/node_modules/nativescript/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/node_modules/fstream/node_modules/graceful-fs/fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
+ nativescript@5.0.0
updated 67 packages in 5.276s

**Comment by Fatme** [comment]
> Support for Node.js 11.1.0 is not verified. NativeScript CLI might not install or run properly.

You need to downgrade your node version. The support for node11 will be released in 5.0.1 version.

**Comment by xaransh** [comment]
ok.
