### ISSUE TITLE
 Getting error "PubNub call failed, check status for details"

### ISSUE THREAD

**Issue by atulpandey34** [NativeScript/nativescript-cli#4120]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.0.0
 - Cross-platform modules: 5.0.2
 - Android Runtime: 5.0.0
 - iOS Runtime: 5.0.0
 - Plugin(s):

**Describe the bug**
After running command tns preview --bundle and scanning the QR code from playground , the application is not loading. Getting below error in command prompt 

Successfully synced changes for platform android.
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\apande72\AppData\Roaming\npm\node_modules\nativ
escript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31
)
    at onResponse (C:\Users\apande72\AppData\Roaming\npm\node_modules\nativescri
pt\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\apande72\AppData\Roaming\npm\node_modules\nativescr
ipt\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59
:17)
    at Request.callback (C:\Users\apande72\AppData\Roaming\npm\node_modules\nati
vescript\node_modules\superagent\lib\node\index.js:728:3)
    at RequestBase._timeoutError (C:\Users\apande72\AppData\Roaming\npm\node_mod
ules\nativescript\node_modules\superagent\lib\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\apande72\AppData\Roaming\npm\node_modules\n
ativescript\node_modules\superagent\lib\request-base.js:685:12)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\apande72\AppData\Roaming\npm\node_modules\nativ
escript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31
)
    at onResponse (C:\Users\apande72\AppData\Roaming\npm\node_modules\nativescri
pt\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\apande72\AppData\Roaming\npm\node_modules\nativescr
ipt\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59
:17)
    at Request.callback (C:\Users\apande72\AppData\Roaming\npm\node_modules\nati
vescript\node_modules\superagent\lib\node\index.js:728:3)
    at RequestBase._timeoutError (C:\Users\apande72\AppData\Roaming\npm\node_mod
ules\nativescript\node_modules\superagent\lib\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\apande72\AppData\Roaming\npm\node_modules\n
ativescript\node_modules\superagent\lib\request-base.js:685:12)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)

**To Reproduce**
1. Run tns preview --bundle
2. Scan QR code from playground app
3. app is not loading in mobile and getting above error on cmd

**Comment by letsgoforaride** [comment]
I have the same problem which occurs when I run tns preview command with angular code shared application type by command: ng new -c=@nativescript/schematics --name=my-app-name  --shared

For angular based project created by command: tns create app-name --ng and run tns preview - everything is okay

**Comment by guibot17** [comment]
I'm having the same problem. It looks like there is no solution yet.

**Comment by KristianDD** [comment]
Hi @guibot17 ,
We will need more information in order to investigate this behaviour. Please attach to your reply:
1.  A simple application with which you reproduce the issue.
2. A list of the exact CLI commands you executed.
3. A log of the commands you executed. For example:
- on MacOS and Linux:
`tns preview --bundle --log trace | tee log.txt`
- on Windows:
`tns preview --bundle --log trace > log.txt 2>&1`

**Comment by guibot17** [comment]
Hi @KristianDD ,

Sorry, I was away.

Here is the only command I execute on my Windows 10:
`tns preview --hmr`

For the application, it's the sidedrawer on the playground with a few textfields added to the home page; nothing fancy.

Here is the log trace:
`Start sending initial files for platform android.
Successfully sent initial files for platform android.
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31)
    at onResponse (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59:17)
    at Request.callback (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\node\index.js:728:3)
    at RequestBase._timeoutError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:685:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31)
    at onResponse (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59:17)
    at Request.callback (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\node\index.js:728:3)
    at RequestBase._timeoutError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:685:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31)
    at onResponse (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59:17)
    at Request.callback (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\node\index.js:728:3)
    at RequestBase._timeoutError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:685:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31)
    at onResponse (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59:17)
    at Request.callback (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\node\index.js:728:3)
    at RequestBase._timeoutError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:685:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31)
    at onResponse (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59:17)
    at Request.callback (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\node\index.js:728:3)
    at RequestBase._timeoutError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:685:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31)
    at onResponse (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59:17)
    at Request.callback (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\node\index.js:728:3)
    at RequestBase._timeoutError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:685:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31)
    at onResponse (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59:17)
    at Request.callback (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\node\index.js:728:3)
    at RequestBase._timeoutError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:685:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31)
    at onResponse (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59:17)
    at Request.callback (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\node\index.js:728:3)
    at RequestBase._timeoutError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:685:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31)
    at onResponse (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59:17)
    at Request.callback (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\node\index.js:728:3)
    at RequestBase._timeoutError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:685:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31)
    at onResponse (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59:17)
    at Request.callback (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\node\index.js:728:3)
    at RequestBase._timeoutError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:685:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31)
    at onResponse (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59:17)
    at Request.callback (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\node\index.js:728:3)
    at RequestBase._timeoutError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:685:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31)
    at onResponse (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59:17)
    at Request.callback (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\node\index.js:728:3)
    at RequestBase._timeoutError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:685:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31)
    at onResponse (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59:17)
    at Request.callback (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\node\index.js:728:3)
    at RequestBase._timeoutError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:685:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31)
    at onResponse (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59:17)
    at Request.callback (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\node\index.js:728:3)
    at RequestBase._timeoutError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:685:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31)
    at onResponse (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59:17)
    at Request.callback (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\node\index.js:728:3)
    at RequestBase._timeoutError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:685:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31)
    at onResponse (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59:17)
    at Request.callback (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\node\index.js:728:3)
    at RequestBase._timeoutError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:685:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31)
    at onResponse (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59:17)
    at Request.callback (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\node\index.js:728:3)
    at RequestBase._timeoutError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:685:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31)
    at onResponse (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59:17)
    at Request.callback (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\node\index.js:728:3)
    at RequestBase._timeoutError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:685:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31)
    at onResponse (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59:17)
    at Request.callback (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\node\index.js:728:3)
    at RequestBase._timeoutError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:685:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31)
    at onResponse (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59:17)
    at Request.callback (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\node\index.js:728:3)
    at RequestBase._timeoutError (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\Me\AppData\Roaming\nvm\v10.14.1\node_modules\nativescript\node_modules\superagent\lib\request-base.js:685:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
`

I always have to insist before my android shows the app.

Your help is really appreciated.

**Comment by VaidasDatenis** [comment]
So what is the answer? I have the same problem.

**Comment by NickIliev** [comment]
@VaidasDatenis check [this SO thread ](https://stackoverflow.com/a/55921523/4936697)for possible solution/directions.

**Comment by VaidasDatenis** [comment]
My problem was caused by .mp4 file size. I was trying to display a video HD file size of 100mb. 15 sec video. So I just shortened that video and the problem was gone.
P.S. I used Adobe Premiere. When exporting video, select Mobile Device 1024.
