### ISSUE TITLE
TNS cli genereate Service

### ISSUE THREAD

**Issue by applke** [NativeScript/nativescript-cli#4209]
`Error: Schematic input does not validate against the Schema: {"flat":true,"spec":true,"lintFix":false}
Errors:

  Data path "" should have required property 'name'.
`
Command : `tns generate service user`

**Comment by NickIliev** [comment]
@applke I think the error message you are receving is stating that you need to pass a name like this
```
tns generate service name=my-service
```

Still even the above is crashing on my side (Widnows with tns 5.0.3) with the followin:
```
$ tns generate service name=my-service
RangeError: Maximum call stack size exceeded
    at t._error (C:\Users\niliev\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:1479)
    at t.error (C:\Users\niliev\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:1173)
    at t._error (C:\Users\niliev\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:1479)
    at t.error (C:\Users\niliev\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:1173)
    at t._error (C:\Users\niliev\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:1479)
    at t.error (C:\Users\niliev\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:1173)
    at t._error (C:\Users\niliev\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:1479)
    at t.error (C:\Users\niliev\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:1173)
    at t._error (C:\Users\niliev\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:1479)
    at t.error (C:\Users\niliev\AppData\Roaming\npm\node_modules\nativescript\node_modules\@nativescript\schematics-executor\dist\index.js:16:1173)

```

**Comment by arodiani** [comment]
Any update here? i have the same problem

**Comment by flynsequeira** [comment]
Facing the same issue. Let me know what the problem is

**Comment by sebawita** [comment]
I think that it is better to use the Angular CLI for now, as we are still experimenting with this in the NativeScript CLI.

The following should work:

```
ng generate service user
```

Note, that you will need the Angular CLI v7
