### ISSUE TITLE
NativeScript tns run android throw ENOSPC error

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#4212]
@AbdullatifJamous891 commented on [Mon Dec 10 2018](https://github.com/NativeScript/NativeScript/issues/6688)

**Environment**
this is my environment information
 ✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.0.3 version and is up to date.
✔ Component tns-core-modules has 5.0.5 version and is up to date.
✔ Component tns-android has 5.0.0 version and is up to date.
✔ Component tns-ios has 5.0.0 version and is up to date.

**Describe the bug**
I am trying to run  a simple nativeScript app by this comman ( tns run android ) and I got this error  

`Error: watch /home/abdullatif/Documents/projects/nativescript/native/app ENOSPC
    at _errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at createFsWatchInstance (/usr/local/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:37:15)`

I installed Genymotion, it has worked successfully at the first time but after that it did not work, I have not change any thing in my code or my setting

**Comment by NickIliev** [comment]
ENOSPC as the error suggests usually means that there is not enough space on the device - verify that you have enough space before running `npm i` (which is called with `tns run android`)

**Comment by dtopuzov** [comment]
Hi @AbdullatifJamous891,

As @NickIliev said it migth be disk space issue.

It may also be an issue with OS setting for max watchers or max number of opened file descriptors.

Resources:
https://stackoverflow.com/questions/22475849/node-js-what-is-enospc-error-and-how-to-solve/32600959#32600959

It might also be an issue specific to Genymotion emulators.

Can you please post:
- OS type and version
- Node and npm versions
- Is the app angular, can you also reproduce on plain JS hello world app?
- Can you reproduce the same issue with real device or standard Android Studio emulators?

**Comment by DimitarTachev** [comment]
Closing due to inactivity.
