### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'platforms\android\app\src\main\assets\app\tns_modules\nativescript\node_modules\ios-device-lib\node_modules\.bin\package.json'

### ISSUE THREAD

**Issue by StevenSeo** [NativeScript/nativescript-cli#4247]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.1.0

When I run "tns build android", I got below error. I couldn't figure it out. For some reason, myProject\platforms\android\app\src\main\assets\app folder is disappeared while building it. Any advise please?

**Processing node_modules failed. Error: ENOENT: no such file or directory, open 'D:\myProject\platforms\android\app\src\main\assets\app\tns_modules\nativescript\node_modules\ios-device-lib\node_modules\.bin\package.json'**

Executing before-prepareJSApp hook at location myProject\hooks\before-prepareJSApp\nativescript-dev-webpack.js in-process
Validating before-prepareJSApp arguments.
 at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at FileSystem.readFile (C:\Users\Administrator\AppData\Roaming\npm\node_modules\nativescript\lib\common\file-system.js:161:19)
    at FileSystem.readText (C:\Users\Administrator\AppData\Roaming\npm\node_modules\nativescript\lib\common\file-system.js:171:21)
    at FileSystem.readJson (C:\Users\Administrator\AppData\Roaming\npm\node_modules\nativescript\lib\common\file-system.js:174:27)
    at PluginsService.isNativeScriptPlugin (C:\Users\Administrator\AppData\Roaming\npm\node_modules\nativescript\lib\services\plugins-service.js:189:51)
    at dependencies.forEach.d (C:\Users\Administrator\AppData\Roaming\npm\node_modules\nativescript\lib\tools\node-modules\node-modules-dest-copy.js:50:42)
    at Array.forEach (<anonymous>)
    at TnsModulesCopy.removeDependenciesPlatformsDirs (C:\Users\Administrator\AppData\Roaming\npm\node_modules\nativescript\lib\tools\node-modules\node-modules-dest-copy.js:47:18)
    at dependencies.forEach.d (C:\Users\Administrator\AppData\Roaming\npm\node_modules\nativescript\lib\tools\node-modules\node-modules-dest-copy.js:53:22)
    at Array.forEach (<anonymous>)
    at TnsModulesCopy.removeDependenciesPlatformsDirs (C:\Users\Administrator\AppData\Roaming\npm\node_modules\nativescript\lib\tools\node-modules\node-modules-dest-copy.js:47:18)
    at TnsModulesCopy.copyDependencyDir (C:\Users\Administrator\AppData\Roaming\npm\node_modules\nativescript\lib\tools\node-modules\node-modules-dest-copy.js:37:18)
    at TnsModulesCopy.copyModules (C:\Users\Administrator\AppData\Roaming\npm\node_modules\nativescript\lib\tools\node-modules\node-modules-dest-copy.js:25:18)
    at NodeModulesBuilder.initialPrepareNodeModules (C:\Users\Administrator\AppData\Roaming\npm\node_modules\nativescript\lib\tools\node-modules\node-modules-builder.js:56:28)
    at NodeModulesBuilder.intialPrepareNodeModulesIfRequired (C:\Users\Administrator\AppData\Roaming\npm\node_modules\nativescript\lib\tools\node-modules\node-modules-builder.js:37:18)

Here is my package.json

{
  "main": "MyApp",
  "profiling": "timeline",
  "description": "Mobile Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "Mobile Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.test.mobile",
    "tns-android": {
      "version": "4.2.0"
    }
  },
  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "^5.2.11",
    "@angular/common": "^5.2.11",
    "@angular/compiler": "^5.2.11",
    "@angular/core": "^5.2.11",
    "@angular/forms": "^5.2.11",
    "@angular/http": "^5.2.11",
    "@angular/platform-browser": "^5.2.11",
    "@angular/platform-browser-dynamic": "^5.2.11",
    "@angular/router": "^5.2.11",
    "moment": "^2.22.2",
    "nativescript": "^4.2.4",
    "nativescript-angular": "~5.2.0",
    "nativescript-background-http": "^3.3.1",
    "nativescript-cfalert-dialog": "^1.0.12",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-drop-down": "^3.2.5",
    "nativescript-exit": "^1.0.1",
    "nativescript-imagepicker": "^6.0.5",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-mediafilepicker": "^1.0.7",
    "nativescript-plugin-firebase": "^5.3.1",
    "nativescript-pro-ui": "~3.3.0",
    "nativescript-social-share": "^1.5.1",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.10",
    "rxjs": "^5.5.12",
    "timeline-view": "0.0.6",
    "tns-android": "^5.1.0",
    "tns-core-modules": "^5.1.1",
    "tns-platform-declarations": "^3.4.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^5.2.11",
    "@ngtools/webpack": "~1.9.4",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "codelyzer": "~4.0.2",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "^1.6.0",
    "nativescript-dev-typescript": "~0.6.0",
    "nativescript-dev-webpack": "~0.9.1",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "sass-loader": "^7.1.0",
    "tslint": "~5.8.0",
    "typescript": "~2.6.2",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-sources": "~1.1.0"
  }
}

**Comment by StevenSeo** [comment]
@Fatme Thank you so much. It works!

**Comment by OysteinAmundsen** [comment]
Why can't `nativescript` be a dependency to the project? Is it required to install `nativescript` globally?
