### ISSUE TITLE
Error in destination while trying to extract stream from tns-ios@5.1.0. Error is ZlibError: zlib: unexpected end of file

### ISSUE THREAD

**Issue by yueguanyu** [NativeScript/nativescript-cli#4249]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.1.0 version and is up to date.
✔ Component tns-core-modules has 5.1.1 version and is up to date.
✔ Component tns-android has 5.1.0 version and is up to date.
✔ Component tns-ios has 5.1.0 version and is up to date.
 - Cross-platform modules:
 - Android Runtime:5.1.0
 - iOS Runtime:5.1.0
 - Plugin(s):
@angular/animations
~7.1.0
@angular/common
~7.1.0
@angular/compiler
~7.1.0
@angular/core
~7.1.0
@angular/forms
~7.1.0
@angular/http
~7.1.0
@angular/platform-browser
~7.1.0
@angular/platform-browser-dynamic
~7.1.0
@angular/router
~7.1.0
@feathersjs/client
^3.7.5
nativescript-angular
~7.1.0
nativescript-grid-view
^4.1.1
nativescript-socketio
^3.2.1
nativescript-theme-core
~1.0.4
nativescript-ui-autocomplete
^3.9.0
nativescript-ui-calendar
^3.9.0
nativescript-ui-chart
^3.9.0
nativescript-ui-dataform
^3.7.3
nativescript-ui-gauge
^3.7.1
nativescript-ui-listview
^3.7.1
nativescript-ui-sidedrawer
~5.0.0
reflect-metadata
~0.1.10
rxjs
~6.3.0
tns-core-modules
~5.1.0
zone.js
~0.8.18
@nativescript/schematics dev
~0.4.0
codelyzer dev
~4.5.0
nativescript-dev-sass dev
~1.6.0
nativescript-dev-typescript dev
~0.7.0
nativescript-dev-webpack dev
~0.18.0
tslint dev
~5.11.0
@angular/compiler-cli dev
~7.1.0
@ngtools/webpack dev
~7.1.0

**Describe the bug**
Error by running:  tns platform add ios.
And i have tried to clean the cache with command: npm cache clean --force, but it still not help by running the same command.

**To Reproduce**
tns platform add ios --log trace

**Expected behavior**
tns platform add ios
**Sample project**

**Additional context**
Loading extensions.
Asserting extension nativescript-cloud is installed.
Extension nativescript-cloud is installed.
Asserting extension nativescript-starter-kits is installed.
Extension nativescript-starter-kits is installed.
Trying to get macOS version.
Exec system_profiler SPSoftwareDataType -detailLevel mini 
 stdout: Software:

    System Software Overview:

      System Version: macOS 10.13.6 (17G65)
      Kernel Version: Darwin 17.7.0
      Time since boot: 5:35

 
 stderr: 
macOS version based on system_profiler is 10.13.
System information:
{ platform: 'darwin',
  shell: '/bin/bash',
  os: 'Darwin MACs-iMac-2.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64\n',
  procArch: 'x64',
  nodeVer: '8.12.0',
  npmVer: '6.4.1',
  nodeGypVer: null,
  nativeScriptCliVersion: '5.1.0',
  gitVer: '2.17.1 (Apple Git-112)',
  dotNetVer: null,
  javacVersion: '1.8.0_181',
  adbVer: '1.0.40',
  androidInstalled: true,
  monoVer: null,
  gradleVer: null,
  isAndroidSdkConfiguredCorrectly: true,
  xcodeVer: '10.0.0',
  xcodeprojLocation: '/usr/local/bin/xcodeproj',
  itunesInstalled: true,
  cocoaPodsVer: '1.6.0',
  isCocoaPodsWorkingCorrectly: true,
  isCocoaPodsUpdateRequired: false,
  pythonInfo: { isInstalled: true, isSixPackageInstalled: true } }
Looking for project in '/Users/mac/develop/gitstore/apps/dipingxianApp/wanli99'
Project directory is '/Users/mac/develop/gitstore/apps/dipingxianApp/wanli99'.
Initializing analytics statuses.
Analytics statuses:  { TrackFeatureUsage: 'enabled', TrackExceptions: 'enabled' }
Will send the following information to Google Analytics: { type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Check Local Build Setup',
  label: 'Starting',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' } }
spawn: /usr/local/bin/node "/usr/local/lib/node_modules/nativescript/lib/services/analytics/analytics-broker-process.js" "/usr/local/lib/node_modules/nativescript/lib/bootstrap.js"
Xcode is installed and is configured properly.
xcodeproj is installed and is configured properly.
CocoaPods are installed.
CocoaPods update is not required.
CocoaPods are configured properly.
Your current CocoaPods version is newer than 1.0.0.
Python installed and configured correctly.
The Python 'six' package is found.
Xcode version 10.0.0 satisfies minimum required version 9.
Will send the following information to Google Analytics: { type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Check Local Build Setup',
  label: 'Finished: Is setup correct: true',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' } }
Exec xcodebuild -version | head -n 1 | sed -e 's/Xcode //' 
 stdout: 10.0
 
 stderr: 
Will send the following information to Google Analytics: { type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'pageview',
  path: 'platform add',
  title: 'platform add',
  customDimensions: { cd5: 'CLI', cd2: 'Angular', cd9: 'false' } }
Will send the following information to Google Analytics: { type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Options',
  label: '{"log":"trace","$0":"tns","profileDir":"private"}',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' } }
Creating NativeScript project for the ios platform
Path: /Users/mac/develop/gitstore/apps/dipingxianApp/wanli99/platforms/ios
Package: org.nativescript.wanli99
Name: wanli99
Copying template files...
⠋ Calling pacoteService.extractPackage for packageName: 'tns-ios@5.1.0', destinationDir: '/var/folders/97/94rvbyn53nx827j6c2f009080000gn/T/runtimeDir1181128-32874-f3ei0b.wv1gh' and options: undefined
⠹ Exec npm config get cache 
 stdout: /Users/mac/.npm
 
 stderr: 
Calling pacoteService.extractPackage for packageName: 'tns-ios@5.1.0', destinationDir: '/var/folders/97/94rvbyn53nx827j6c2f009080000gn/T/runtimeDir1181128-32874-f3ei0b.wv1gh' and options: undefined
Creating extract tar stream with options: {
  "strip": 1,
  "C": "/var/folders/97/94rvbyn53nx827j6c2f009080000gn/T/runtimeDir1181128-32874-f3ei0b.wv1gh"
}
⠧ Error in destination while trying to extract stream from tns-ios@5.1.0. Error is ZlibError: zlib: unexpected end of file
ZlibError: zlib: unexpected end of file
    at Zlib.(anonymous function).onerror (/usr/local/lib/node_modules/nativescript/node_modules/minizlib/index.js:131:21)
    at Unzip.write (/usr/local/lib/node_modules/nativescript/node_modules/minizlib/index.js:255:31)
    at Unzip.flush (/usr/local/lib/node_modules/nativescript/node_modules/minizlib/index.js:222:10)
    at Unzip.end (/usr/local/lib/node_modules/nativescript/node_modules/minizlib/index.js:229:10)
    at Unpack.end (/usr/local/lib/node_modules/nativescript/node_modules/tar/lib/parse.js:415:21)
    at PassThrough.onend (_stream_readable.js:595:10)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at PassThrough.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
List of registered commands: /?, accept, accept|eula, account, account|features, account|usage, appstore, appstore|upload, autocomplete, autocomplete|disable, autocomplete|enable, autocomplete|status, build, build|android, build|cloud, build|ios, clean-app, clean-app|android, clean-app|ios, cloud, cloud|build, cloud|clean|workspace, cloud|codesign, cloud|deploy, cloud|lib|version, cloud|publish|android, cloud|publish|ios, cloud|run|*all, cloud|run|android, cloud|run|ios, cloud|setup, codesign, codesign|cloud, config, config|apply, config|reset, config|set, create, debug, debug|android, debug|ios, deploy, deploy|cloud, dev-generate-help, dev-generate-messages, dev-login, dev-post-install, dev-preuninstall, dev-test, dev-test|android, dev-test|ios, device, devices, devices|android, devices|ios, device|android, device|get-file, device|ios, device|list-applications, device|list-files, device|log, device|put-file, device|run, device|stop, device|uninstall, doctor, error-reporting, extension, extension|install, extension|uninstall, generate, help, info, init, install, kill-server, login, logout, package-manager, package-manager|get, package-manager|set, platform, platform|*list, platform|add, platform|clean, platform|remove, platform|update, plugin, plugin|add, plugin|build, plugin|create, plugin|install, plugin|remove, plugin|update, policy, policy|accept, post-install-cli, prepare, preview, proxy, proxy|clear, proxy|set, publish, publish|ios, resources, resources|generate|icons, resources|generate|splashes, resources|update, run, run|android, run|cloud|*all, run|cloud|android, run|cloud|ios, run|ios, setup, setup|cloud, test, test|android, test|init, test|ios, update, usage-reporting, user
Reading help for command 'platform|add'. FileName is 'platform-add.md'.
# tns platform add

### Description

Configures the current project to target the selected platform. 

### Commands

┌──────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Usage                    │ Synopsis                                                                                                                                        │
│ Android latest runtime   │ $ tns platform add android [--framework-path <File Path>] [--symlink] [--sdk <API Level>] [--platform-template <Platform Template>]             │
│ Android selected runtime │ $ tns platform add android[@<Version>] [--framework-path <File Path>] [--symlink] [--sdk <API Level>] [--platform-template <Platform Template>] │
│ iOS latest runtime       │ $ tns platform add ios [--framework-path <File Path>] [--symlink]                                                                               │
│ iOS selected runtime     │ $ tns platform add ios[@<Version>] [--framework-path <File Path>] [--symlink] [--platform-template <Platform Template>]                         │
└──────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

### Options

    * --framework-path - Sets the path to a NativeScript runtime for the specified platform that you want to use instead of the default runtime. If --symlink is specified, <File Path> is the complete path to a valid npm package or a directory that contains a NativeScript runtime for the selected platform and must point to directory in which the runtime is already extracted. If --symlink is not specified, <File Path> must point to a valid npm package.
    * --symlink - Creates a symlink to a NativeScript runtime for the specified platform that you want to use instead of the default runtime. If --frameworkPath is specified, creates a symlink to the specified directory. If --frameworkPath is not specified, creates a symlink to platform runtime installed with your current version of NativeScript.
    * --sdk - Sets the target Android SDK for the project. <API Level> is a valid Android API level. For example: 17, 19, MNC.
    * --platform-template - Sets the platform template that will be used for the native application. <Platform Template> is a valid npm package, path to directory, .tgz or GitHub URL that contains a native Android or iOS template.

### Arguments

    * <Version> is any available version of the respective platform runtime published in npm.

**Comment by yueguanyu** [comment]
By the previous Version of Nativescript can ios app gut running on Simulator, the Nativescript is updated recently and it went wrong.

**Comment by dtopuzov** [comment]
To be honest I have no idea what causes the issue, but just a blind guess:
sudo rm -rf /var/folders/97

**Comment by dtopuzov** [comment]
Also try to check tar on your system:
which tar

Once I had issue with system tar that was resolved by installing gnu tar:
brew install gnu-tar

**Comment by DimitarTachev** [comment]
Closing due to inactivity.
