### ISSUE TITLE
Error when running 'tns' (Ubuntu 14.04 x84)

### ISSUE THREAD

**Issue by kaurag007ph** [NativeScript/nativescript-cli#425]
Hi Guys,
I have a problem running nativescript with my fresh installed ubuntu 14.04 x84. 
This is the log when I try to exec 'tns' or nativescript on my terminal.

Error: /usr/local/lib/node_modules/nativescript/node_modules/fibers/bin/linux-ia32-v8-4.1/fibers.node: undefined symbol: _ZN2v86String9NewSymbolEPKci
    at Error (native)-------
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/node_modules/fibers/fibers.js:20:37)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)

**Comment by kaurag007ph** [comment]
TNS is not working with iojs. It works after I install nodejs-legacy.
