### ISSUE TITLE
Unable to merge Debug resources

### ISSUE THREAD

**Issue by itsmeneartou** [NativeScript/nativescript-cli#4316]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.1.1
 - Cross-platform modules:
 - Android Runtime:5.10
 - iOS Runtime:N/A
 - Plugin(s):

**Describe the bug**
I just want to run my existing angular web app on android and I use `tns run android` and I get all these merging resources problem.

**To Reproduce**
Install native script for your project on one pc, take another laptop copy project from previous pc to laptop without node_modules, install dependencies and stuff whatever required , run `tns run android` and get into merging errors. Although my previous pc didn't had much ram to run nativescript so I never reached till this point in previous pc.

**Expected behavior**
Android app should run on emulator using command `tns run android`.
**Sample project**
Not available

**Additional context**
```
Could not merge source set folders:
[app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\bytebuffer\dist\bytebuffer-dataview.min.js    [app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\bytebuffer\dist\bytebuffer-dataview.min.js.gz: Error: Duplicate resources
[app/tns_modules/bytebuffer/dist/bytebuffer.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\bytebuffer\dist\bytebuffer.min.js      [app/tns_modules/bytebuffer/dist/bytebuffer.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\bytebuffer\dist\bytebuffer.min.js.gz: Error: Duplicate resources
[app/tns_modules/long/dist/long.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\long\dist\long.min.js      [app/tns_modules/long/dist/long.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\long\dist\long.min.js.gz: Error: Duplicate resources
[app/tns_modules/protobufjs/dist/protobuf-light.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\protobufjs\dist\protobuf-light.min.js      [app/tns_modules/protobufjs/dist/protobuf-light.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\protobufjs\dist\protobuf-light.min.js.gz: Error: Duplicate resources
[app/tns_modules/protobufjs/dist/protobuf.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\protobufjs\dist\protobuf.min.js  [app/tns_modules/protobufjs/dist/protobuf.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\protobufjs\dist\protobuf.min.js.gz: Error: Duplicate resources
        at com.android.ide.common.resources.DataSet.checkItems(DataSet.java:486)
        at com.android.ide.common.resources.DataSet.loadFromFiles(DataSet.java:256)
        at com.android.ide.common.resources.AssetSet.loadFromFiles(AssetSet.java:28)
        at com.android.build.gradle.tasks.MergeSourceSetFolders.doFullTaskAction(MergeSourceSetFolders.java:127)
        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:106)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> [app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\bytebuffer\dist\bytebuffer-dataview.min.js  [app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\bytebuffer\dist\bytebuffer-dataview.min.js.gz: Error: Duplicate resources
  [app/tns_modules/bytebuffer/dist/bytebuffer.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\bytebuffer\dist\bytebuffer.min.js    [app/tns_modules/bytebuffer/dist/bytebuffer.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\bytebuffer\dist\bytebuffer.min.js.gz: Error: Duplicate resources
  [app/tns_modules/long/dist/long.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\long\dist\long.min.js    [app/tns_modules/long/dist/long.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\long\dist\long.min.js.gz: Error: Duplicate resources
  [app/tns_modules/protobufjs/dist/protobuf-light.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\protobufjs\dist\protobuf-light.min.js    [app/tns_modules/protobufjs/dist/protobuf-light.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\protobufjs\dist\protobuf-light.min.js.gz: Error: Duplicate resources
  [app/tns_modules/protobufjs/dist/protobuf.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\protobufjs\dist\protobuf.min.js        [app/tns_modules/protobufjs/dist/protobuf.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\protobufjs\dist\protobuf.min.js.gz: Error: Duplicate resources

BUILD FAILED in 7m 59s
Unable to apply changes on device: emulator-5554. Error is: Command gradlew.bat failed with exit code 1.
Executing after-watch hook from C:\Users\karti\WebApps\abc\hooks\after-watch\nativescript-dev-webpack.js
Stopping webpack watch
Executing after-watch hook from C:\Users\karti\WebApps\abc\hooks\after-watch\nativescript-dev-webpack.js
Stopping webpack watch
```

**Comment by NickIliev** [comment]
@itsmeneartou can you clarify what do you mean by `Install native script for your project on one pc,` - are you creating new NativeScript project or trying to enable NativeScript in code shared project? Please post the exact command you are running and also the content of your `package.json` file.

**Comment by itsmeneartou** [comment]
I am trying to enable NativeScript in an existing Angular Web App by following [This](https://blog.angular.io/apps-that-work-natively-on-the-web-and-mobile-9b26852495e7) tutorial. I have done everything correctly as told in the tutorial but I am facing the errors shown above. As the error is due to inability of merging of source set folders I feel this is due to me copying the project folder from "old pc"(Which I no longer work on) to "new laptop"(where I work now) and something wrong happening during that process. Lets forget what happened in the past. Now I did things suggested by @tsonevn in [this](https://github.com/NativeScript/NativeScript/issues/6088#issuecomment-458095632) comment. I deleted  `node_modules`, `hooks`, `platforms` folders and `package-lock.json` file then `npm i` and in last `tns run android`. I ran into the errors shown below. Can you please help me rectifying it ?


```
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
Copying template files...
Platform android successfully added. v5.1.0
Preparing project...
Successfully prepared plugin nativescript-angular for android.
Successfully prepared plugin nativescript-theme-core for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin nativescript-intl for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Project successfully prepared (Android)
Building project...
Gradle build...
         + setting applicationId
         + applying user-defined configuration from C:\Users\karti\WebApps\abc\App_Resources\Android\app.gradle
Using support library version 28.0.0
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: C:\Users\karti\WebApps\abc\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar
(node:12228) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Could not merge source set folders:
[app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\bytebuffer\dist\bytebuffer-dataview.min.js    [app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\bytebuffer\dist\bytebuffer-dataview.min.js.gz: Error: Duplicate resources
[app/tns_modules/bytebuffer/dist/bytebuffer.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\bytebuffer\dist\bytebuffer.min.js      [app/tns_modules/bytebuffer/dist/bytebuffer.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\bytebuffer\dist\bytebuffer.min.js.gz: Error: Duplicate resources
[app/tns_modules/long/dist/long.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\long\dist\long.min.js      [app/tns_modules/long/dist/long.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\long\dist\long.min.js.gz: Error: Duplicate resources
[app/tns_modules/protobufjs/dist/protobuf-light.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\protobufjs\dist\protobuf-light.min.js      [app/tns_modules/protobufjs/dist/protobuf-light.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\protobufjs\dist\protobuf-light.min.js.gz: Error: Duplicate resources
[app/tns_modules/protobufjs/dist/protobuf.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\protobufjs\dist\protobuf.min.js  [app/tns_modules/protobufjs/dist/protobuf.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\protobufjs\dist\protobuf.min.js.gz: Error: Duplicate resources
        at com.android.ide.common.resources.DataSet.checkItems(DataSet.java:486)
        at com.android.ide.common.resources.DataSet.loadFromFiles(DataSet.java:256)
        at com.android.ide.common.resources.AssetSet.loadFromFiles(AssetSet.java:28)
        at com.android.build.gradle.tasks.MergeSourceSetFolders.doFullTaskAction(MergeSourceSetFolders.java:127)
        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:106)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> [app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\bytebuffer\dist\bytebuffer-dataview.min.js  [app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\bytebuffer\dist\bytebuffer-dataview.min.js.gz: Error: Duplicate resources
  [app/tns_modules/bytebuffer/dist/bytebuffer.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\bytebuffer\dist\bytebuffer.min.js    [app/tns_modules/bytebuffer/dist/bytebuffer.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\bytebuffer\dist\bytebuffer.min.js.gz: Error: Duplicate resources
  [app/tns_modules/long/dist/long.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\long\dist\long.min.js    [app/tns_modules/long/dist/long.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\long\dist\long.min.js.gz: Error: Duplicate resources
  [app/tns_modules/protobufjs/dist/protobuf-light.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\protobufjs\dist\protobuf-light.min.js    [app/tns_modules/protobufjs/dist/protobuf-light.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\protobufjs\dist\protobuf-light.min.js.gz: Error: Duplicate resources
  [app/tns_modules/protobufjs/dist/protobuf.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\protobufjs\dist\protobuf.min.js        [app/tns_modules/protobufjs/dist/protobuf.min.js] C:\Users\karti\WebApps\abc\platforms\android\app\src\main\assets\app\tns_modules\protobufjs\dist\protobuf.min.js.gz: Error: Duplicate resources

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8m 26s
Unable to apply changes on device: emulator-5554. Error is: Command gradlew.bat failed with exit code 1.

```

**Comment by rosen-vladimirov** [comment]
Hey @itsmeneartou ,for code sharing projects you must pass `--bundle` flag:
```
tns run android --bundle
```
Can you give it a try and see if it works?
