### ISSUE TITLE
Emulators don't availables

### ISSUE THREAD

**Issue by mariodiciccio** [NativeScript/nativescript-cli#4585]
Environment
 - CLI: 

I installed the android SDK con avd devices, i installed nativescript, but when i compile the project dont work because it don't found the emulators.

tns create HelloWorld --template tns-template-blank

tns doctor
✔ Getting environment information 

No issues were detected.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 10.1.0 satisfies minimum required version 9.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.3.4 version and is up to date.
✔ Component tns-core-modules has 5.3.2 version and is up to date.

tns run android
> Cannot find connected devices.
> Emulator start failed with: No emulator image available for device identifier 'undefined'.
> To list currently connected devices and verify that the specified identifier exists, run 'tns device'.
> To list available emulator images, run 'tns device <Platform> --available-devices'.

tns device android --available-devices
> Available emulators
> Device Name │ Platform │ Version │ Device Identifier │ Image Identifier │ Error Help
> Connected devices & emulators
> Searching for devices...
> Cannot find connected devices. Reconnect any connected devices, verify that your system recognizes them, and run this command again

export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
export ANDROID_SDK_ROOT=/Users/O/Library/Android/sdk
export ANDROID_SDK_HOME=/Users/O/Library/Android/sdk
export ANDROID_AVD_HOME=/Users/O/.android/avd
export PATH=$PATH:$ANDROID_AVD_HOME

Help me, please.

**Comment by Fatme** [comment]
@mariodiciccio,

Can you please execute `tns run android --log trace` and send us the log file?

**Comment by mariodiciccio** [comment]
Loading extensions.
Trying to get macOS version.
Exec system_profiler SPSoftwareDataType -detailLevel mini 
 stdout: Software:

    System Software Overview:

      System Version: macOS 10.13.6 (17G6030)
      Kernel Version: Darwin 17.7.0
      Time since boot: 22:52

 
 stderr: 
macOS version based on system_profiler is 10.13.
Looking for project in '/Users/aasci/Documents/Workspace-Private-Photon/isam/mobile-app/myisam-app2/hello'
Project directory is '/Users/aasci/Documents/Workspace-Private-Photon/isam/mobile-app/myisam-app2/hello'.
System information:
{ platform: 'darwin',
  shell: '/bin/bash',
  os:
   'Darwin aasci.local 17.7.0 Darwin Kernel Version 17.7.0: Wed Feb 27 00:43:23 PST 2019; root:xnu-4570.71.35~1/RELEASE_X86_64 x86_64\n',
  procArch: 'x64',
  nodeVer: '10.9.0',
  npmVer: '6.9.0',
  nodeGypVer: null,
  nativeScriptCliVersion: '5.3.4',
  gitVer: '2.17.2 (Apple Git-113)',
  dotNetVer: null,
  javacVersion: '1.8.0_181',
  javaVersion: '1.8.0_181',
  adbVer: '1.0.40',
  androidInstalled: true,
  monoVer: null,
  gradleVer: '4.10',
  isAndroidSdkConfiguredCorrectly: true,
  xcodeVer: '10.1.0',
  xcodeprojLocation: '/usr/local/bin/xcodeproj',
  itunesInstalled: true,
  cocoaPodsVer: '1.5.3',
  isCocoaPodsWorkingCorrectly: true,
  isCocoaPodsUpdateRequired: false,
  pythonInfo: { isInstalled: true, isSixPackageInstalled: true } }
Initializing analytics statuses.
Analytics statuses:  { TrackFeatureUsage: 'disabled', TrackExceptions: 'disabled' }
Your ANDROID_HOME environment variable is set and points to correct directory.
Your adb from the Android SDK is correctly installed.
The Android SDK is installed.
A compatible Android SDK for compilation is found.
Javac is installed and is configured properly.
The Java Development Kit (JDK) is installed and is configured properly.
Installed Android Targets are:  [ '.DS_Store',
  'android-19',
  'android-22',
  'android-23',
  'android-26',
  'android-28',
  'android-MNC',
  'android-N' ]
Directories found in /Users/aasci/Library/Android/sdk/build-tools are .DS_Store, 21.1.2, 25.0.2, 25.0.3, 27.0.3, 28.0.3
Versions found in /Users/aasci/Library/Android/sdk/build-tools are 21.1.2, 25.0.2, 25.0.3, 27.0.3, 28.0.3
Selected version is:  28.0.3
Selected targetSdk is: 28
Validate options for platform: Android
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
startLookingForDevices; platform is Android
Options for ios-device-discovery { platform: 'Android',
  shouldReturnImmediateResult: false,
  emulator: false }
spawn: /Users/aasci/Library/Android/sdk/platform-tools/adb "start-server"
Result when throw error is false:
{ stdout: '', stderr: '', exitCode: 0 }
spawn: /Users/aasci/Library/Android/sdk/platform-tools/adb "devices"
spawn: /Users/aasci/Library/Android/sdk/platform-tools/adb "devices"
spawn: /Users/aasci/Library/Android/sdk/tools/android "list" "avd"
spawn: /usr/local/bin/VBoxManage "list" "vms"
spawn: player 0
Configuration error for Genymotion { stdout: '', stderr: 'spawn player ENOENT', exitCode: 'ENOENT' }
spawn: /usr/local/bin/VBoxManage "guestproperty" "enumerate" "43b9158b-c4f4-4f75-9f2a-89f98a5ac076"
spawn: /usr/local/bin/VBoxManage "guestproperty" "enumerate" "98693fec-a44c-4420-a441-880d85c6e830"
spawn: /usr/local/bin/VBoxManage "guestproperty" "enumerate" "f3e9320e-f330-4421-85af-f32dd792c766"
No emulator image available for device identifier 'undefined'.
Cannot find connected devices.
Emulator start failed with: No emulator image available for device identifier 'undefined'.
To list currently connected devices and verify that the specified identifier exists, run 'tns device'.
To list available emulator images, run 'tns device <Platform> --available-devices'.
Error while initializing devicesService: Exception: Cannot find connected devices.
Emulator start failed with: No emulator image available for device identifier 'undefined'.
To list currently connected devices and verify that the specified identifier exists, run 'tns device'.
To list available emulator images, run 'tns device <Platform> --available-devices'.
Error: Cannot find connected devices.
Emulator start failed with: No emulator image available for device identifier 'undefined'.
To list currently connected devices and verify that the specified identifier exists, run 'tns device'.
To list available emulator images, run 'tns device <Platform> --available-devices'.
    at Errors.fail (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:126:28)
    at Errors.failWithoutHelp (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:136:21)
    at DevicesService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/mobile/mobile-core/devices-service.js:445:34)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/nativescript/lib/common/mobile/mobile-core/devices-service.js:11:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by mariodiciccio** [comment]
I have moved avd folder from /Users/aasci/.android/avd to /Users/aasci/Library/Android/sdk/.android/avd and it works well.

How tns read ANDROID_AVD_HOME?

**Comment by KristianDD** [comment]
Hi @mariodiciccio ,
We have a theory why this happens. We use ANDROID_AVD_HOME only if the Android tooling doesn't return any available devices. [Here](https://github.com/NativeScript/nativescript-cli/blob/2761adc0c0decaffb9ac9d862867d08098390e1c/lib/common/mobile/android/android-virtual-device-service.ts#L152) is the logic for getting the available devices from the Android tooling.

Based on your log, we spawn the `/Users/aasci/Library/Android/sdk/tools/android "list" "avd"` to get the available devices - this corresponds to this [line of code](https://github.com/NativeScript/nativescript-cli/blob/2761adc0c0decaffb9ac9d862867d08098390e1c/lib/common/mobile/android/android-virtual-device-service.ts#L164). This is a legacy way of getting the list of devices. The new one is using `avdmanager` - [path to avdmanager](https://github.com/NativeScript/nativescript-cli/blob/2761adc0c0decaffb9ac9d862867d08098390e1c/lib/common/mobile/android/android-virtual-device-service.ts#L209). 

It seems we don't find the `avdmanager` and fallback to the old way of getting the devices, but our theory is that the old Android tooling doesn't find the emulators when they are located at `/Users/aasci/.android/avd`. When you change the directory the tooling most probably returns a valid list of devices and the NativeScript CLI won't start looking for avds using the file system - [here](https://github.com/NativeScript/nativescript-cli/blob/2761adc0c0decaffb9ac9d862867d08098390e1c/lib/common/mobile/android/android-virtual-device-service.ts#L249). This is the only case we use the ANDROID_AVD_HOME variable which we get from [this method](https://github.com/NativeScript/nativescript-cli/blob/2761adc0c0decaffb9ac9d862867d08098390e1c/lib/common/mobile/android/android-virtual-device-service.ts#L226).

To verify this theory you can try few things:
1. Execute `/Users/aasci/Library/Android/sdk/tools/android list avd`. This should return a result with available avds. Then move `/Users/aasci/Library/Android/sdk/.android/avd` to `/Users/aasci/.android/avd` and execute the command again. If we are right, this should not return a result.

2. Check if you have `avdmanager` at `/Users/aasci/Library/Android/sdk/tools/bin/avdmanager`.

**Comment by voigtd** [comment]
@mariodiciccio @Fatme Hi, I'm getting the same error. Tried a lot of things to debug but haven't found a solution. 

When I run ```tns run android --log trace``` I get the following error:

```
Loading extensions.
Asserting extension nativescript-cloud is installed.
Extension nativescript-cloud is installed.
Trying to get macOS version.
Exec system_profiler SPSoftwareDataType -detailLevel mini
 stdout: Software:

    System Software Overview:

      System Version: macOS 10.14.3 (18D42)
      Kernel Version: Darwin 18.2.0
      Time since boot: 4:19


 stderr:
macOS version based on system_profiler is 10.14.
Looking for project in '/Users/daniel/Desktop/ng-ns-demo'
Project directory is '/Users/daniel/Desktop/ng-ns-demo'.
System information:
[Object: null prototype] {
  platform: 'darwin',
  shell: '/bin/bash',
  os:
   'Darwin Daniels-Mac 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64\n',
  procArch: 'x64',
  nodeVer: '10.15.3',
  npmVer: '6.4.1',
  nodeGypVer: null,
  nativeScriptCliVersion: '5.3.4',
  gitVer: '2.18.0',
  dotNetVer: null,
  javacVersion: '1.8.0_212',
  javaVersion: '1.8.0_212',
  adbVer: '1.0.41',
  androidInstalled: true,
  monoVer: null,
  gradleVer: null,
  isAndroidSdkConfiguredCorrectly: true,
  xcodeVer: '10.2.1',
  xcodeprojLocation: '/usr/local/bin/xcodeproj',
  itunesInstalled: true,
  cocoaPodsVer: '1.6.1',
  isCocoaPodsWorkingCorrectly: true,
  isCocoaPodsUpdateRequired: false,
  pythonInfo: { isInstalled: true, isSixPackageInstalled: true } }
Initializing analytics statuses.
Analytics statuses:  { TrackFeatureUsage: 'disabled', TrackExceptions: 'disabled' }
Your ANDROID_HOME environment variable is set and points to correct directory.
Your adb from the Android SDK is correctly installed.
The Android SDK is installed.
A compatible Android SDK for compilation is found.
Javac is installed and is configured properly.
The Java Development Kit (JDK) is installed and is configured properly.
Installed Android Targets are:  [ 'android-28' ]
Directories found in /Users/daniel/Library/Android/sdk/build-tools are 28.0.3
Versions found in /Users/daniel/Library/Android/sdk/build-tools are 28.0.3
Selected version is:  28.0.3
Selected targetSdk is: 28
Validate options for platform: Android
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
startLookingForDevices; platform is Android
Options for ios-device-discovery { platform: 'Android',
  shouldReturnImmediateResult: false,
  emulator: false }
spawn: /Users/daniel/Library/Android/sdk/platform-tools/adb "start-server"
Result when throw error is false:
{ stdout: '', stderr: '', exitCode: 0 }
spawn: /Users/daniel/Library/Android/sdk/platform-tools/adb "devices"
spawn: /Users/daniel/Library/Android/sdk/platform-tools/adb "devices"
spawn: /Users/daniel/Library/Android/sdk/tools/bin/avdmanager "list" "avds"
spawn: /usr/local/bin/VBoxManage "list" "vms"
spawn: player 0
Configuration error for Genymotion { stdout: '', stderr: 'spawn player ENOENT', exitCode: 'ENOENT' }
spawn: /usr/local/bin/VBoxManage "guestproperty" "enumerate" "e58dcf62-74df-43eb-858a-07faa6606f14"
No emulator image available for device identifier 'undefined'.
Cannot find connected devices.
Emulator start failed with: No emulator image available for device identifier 'undefined'.
To list currently connected devices and verify that the specified identifier exists, run 'tns device'.
To list available emulator images, run 'tns device <Platform> --available-devices'.
Error while initializing devicesService: Exception: Cannot find connected devices.
Emulator start failed with: No emulator image available for device identifier 'undefined'.
To list currently connected devices and verify that the specified identifier exists, run 'tns device'.
To list available emulator images, run 'tns device <Platform> --available-devices'.
Error: Cannot find connected devices.
Emulator start failed with: No emulator image available for device identifier 'undefined'.
To list currently connected devices and verify that the specified identifier exists, run 'tns device'.
To list available emulator images, run 'tns device <Platform> --available-devices'.
    at Errors.fail (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:126:28)
    at Errors.failWithoutHelp (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:136:21)
    at DevicesService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/mobile/mobile-core/devices-service.js:445:34)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/nativescript/lib/common/mobile/mobile-core/devices-service.js:11:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

Also, when I run ```tns device android --available-devices``` it shows that I my installed devices while simultaneously saying that devices weren't found:

```

Available emulators
┌─────────────┬──────────┬───────────┬───────────────────┬──────────────────┬────────────┐
│ Device Name │ Platform │ Version   │ Device Identifier │ Image Identifier │ Error Help │
│ Pixel2      │ Android  │           │                   │ Pixel2           │            │
└─────────────┴──────────┴───────────┴───────────────────┴──────────────────┴────────────┘

Connected devices & emulators
Searching for devices...
Cannot find connected devices. Reconnect any connected devices, verify that your system recognizes them, and run this command again.
```

I initially installed via homebrew and then uninstalled and installed via Android Studio per many suggestions in these forums. Both haven't worked.
 
My ```~/.bash_profile``` file currently is the following:

```
export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
export ANDROID_HOME=/Users/daniel/Library/Android/sdk
export ANDROID_SDK_ROOT=/Users/daniel/Library/Android/sdk
export ANDROID_AVD_HOME=/Users/daniel/.android/avd
```

I just tried @KristianDD suggestion with ```avdmanager``` and it didn't work out. 

I'm new to NativeScript so any help would be greatly appreciated. Thanks

**Comment by DimitarTachev** [comment]
Closing due to inactivity.
