### ISSUE TITLE
Nativescript CLI broken

### ISSUE THREAD

**Issue by iyinusa** [NativeScript/nativescript-cli#4587]
When I tried running `tns doctor` or any `tns` commands, I keep getting these:

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/usr/local/Cellar/node@6/6.12.3/lib/node_modules/nativescript/node_modules/natives/index.js:137:5)
    at require (/usr/local/Cellar/node@6/6.12.3/lib/node_modules/nativescript/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/usr/local/Cellar/node@6/6.12.3/lib/node_modules/nativescript/node_modules/natives/index.js:137:5)
    at require (/usr/local/Cellar/node@6/6.12.3/lib/node_modules/nativescript/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (/usr/local/Cellar/node@6/6.12.3/lib/node_modules/nativescript/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/usr/local/Cellar/node@6/6.12.3/lib/node_modules/nativescript/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/usr/local/Cellar/node@6/6.12.3/lib/node_modules/nativescript/node_modules/fstream/node_modules/graceful-fs/fs.js:1:99)

Please can someone suggest what went wrong?

Thanks.

**Comment by Fatme** [comment]
@iyinusa,

The support for `node v6` is deprecated, please update to newer node version.

**Comment by iyinusa** [comment]
Thanks @Fatme 

I did updated to `node 10` and since then, the Nativescript CLI stops working.

**Comment by Fatme** [comment]
As I can see from your previous log, you're using node `v6`.

> /usr/local/Cellar/node@6/6.12.3

**Comment by iyinusa** [comment]
@Fatme 

Yes, please how can I force it to use `node v10`?

**Comment by Fatme** [comment]
Can you please execute `node --version` in order to check your current node version?

**Comment by iyinusa** [comment]
I just executed `node --version` and I got this:

v10.15.2

**Comment by Fatme** [comment]
```
npm un -g nativescript
npm i -g nativescript
```

**Comment by iyinusa** [comment]
@Fatme Thanks

Running `npm i -g nativescript` I got these:

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/nativescript/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ nativescript@5.3.4
added 944 packages from 1353 contributors in 81.295s

Than running `tns doctor` I got these:

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/usr/local/Cellar/node@6/6.12.3/lib/node_modules/nativescript/node_modules/natives/index.js:137:5)
    at require (/usr/local/Cellar/node@6/6.12.3/lib/node_modules/nativescript/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/usr/local/Cellar/node@6/6.12.3/lib/node_modules/nativescript/node_modules/natives/index.js:137:5)
    at require (/usr/local/Cellar/node@6/6.12.3/lib/node_modules/nativescript/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (/usr/local/Cellar/node@6/6.12.3/lib/node_modules/nativescript/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/usr/local/Cellar/node@6/6.12.3/lib/node_modules/nativescript/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/usr/local/Cellar/node@6/6.12.3/lib/node_modules/nativescript/node_modules/fstream/node_modules/graceful-fs/fs.js:1:99)

**Comment by Fatme** [comment]
@iyinusa,

Most probably you have installed NativeScript CLI twice - once with `node v10` and once with `node v6`. To check if this is the case, can you please execute the followings:
```
npm un -g nativescript
tns --version
echo $PATH
```

**Comment by iyinusa** [comment]
@Fatme Thanks

I executed `npm un -g nativescript` and it uninstall NativeScript CLI, then executed `tns --version` I got these:

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/usr/local/Cellar/node@6/6.12.3/lib/node_modules/nativescript/node_modules/natives/index.js:137:5)
    at require (/usr/local/Cellar/node@6/6.12.3/lib/node_modules/nativescript/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/usr/local/Cellar/node@6/6.12.3/lib/node_modules/nativescript/node_modules/natives/index.js:137:5)
    at require (/usr/local/Cellar/node@6/6.12.3/lib/node_modules/nativescript/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (/usr/local/Cellar/node@6/6.12.3/lib/node_modules/nativescript/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/usr/local/Cellar/node@6/6.12.3/lib/node_modules/nativescript/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/usr/local/Cellar/node@6/6.12.3/lib/node_modules/nativescript/node_modules/fstream/node_modules/graceful-fs/fs.js:1:99)

Then, executed `echo $PATH` I got these:

/usr/local/opt/node@6/bin:/usr/local/opt/node@6/bin:/usr/local/opt/node@10/bin:/usr/local/opt/node@10/bin:/usr/local/opt/node@10/bin:/usr/local/sbin:/usr/local/opt/node@6/bin:/usr/local/opt/node@6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/johnlambs/Library/Android/sdk/tools:/Users/johnlambs/Library/Android/sdk/build-tools/28.0.2
