### ISSUE TITLE
node-inspector terminated unexpectedly

### ISSUE THREAD

**Issue by philvbprogrammer** [NativeScript/nativescript-cli#472]
In AppBuilder for VS2013 clicking debug without a breakpoint set the process attaches, as soon as a break point is set this error appears in the AppBuilder output windows and debugging is stopped.

[2015-05-08 13:26:07.052] Log (Exception,High): node-inspector terminated unexpectedly: 
C:\Users\PAdams\AppData\Local\Telerik\BlackDragon\Cache\Node-Inspector-2015.2.429.1\lib\convert.js:41
  var path = url.replace(/^file:\/\//, '');
                 ^
TypeError: Cannot call method 'replace' of null
    at Object.exports.inspectorUrlToV8Name (C:\Users\PAdams\AppData\Local\Telerik\BlackDragon\Cache\Node-Inspector-2015.2.429.1\lib\convert.js:41:18)
    at Object.DebuggerAgent.setBreakpointByUrl (C:\Users\PAdams\AppData\Local\Telerik\BlackDragon\Cache\Node-Inspector-2015.2.429.1\lib\DebuggerAgent.js:313:23)
    at Object.FrontendCommandHandler.handleCommand (C:\Users\PAdams\AppData\Local\Telerik\BlackDragon\Cache\Node-Inspector-2015.2.429.1\lib\FrontendCommandHandler.js:148:12)
    at Object.FrontendCommandHandler._handleFrontendMessage (C:\Users\PAdams\AppData\Local\Telerik\BlackDragon\Cache\Node-Inspector-2015.2.429.1\lib\FrontendCommandHandler.js:107:10)
    at FrontendClient.emit (events.js:95:17)
    at FrontendClient._onConnectionMessage (C:\Users\PAdams\AppData\Local\Telerik\BlackDragon\Cache\Node-Inspector-2015.2.429.1\lib\FrontendClient.js:40:8)
    at WebSocket.emit (events.js:98:17)
    at Receiver.self._receiver.ontext (C:\Users\PAdams\AppData\Local\Telerik\BlackDragon\Cache\Node-Inspector-2015.2.429.1\node_modules\ws\lib\WebSocket.js:697:10)
    at Receiver.opcodes.1.finish (C:\Users\PAdams\AppData\Local\Telerik\BlackDragon\Cache\Node-Inspector-2015.2.429.1\node_modules\ws\lib\Receiver.js:397:14)
    at Receiver.expectHandler (C:\Users\PAdams\AppData\Local\Telerik\BlackDragon\Cache\Node-Inspector-2015.2.429.1\node_modules\ws\lib\Receiver.js:378:33)

Only code used in main-page.js

var view = require("ui/core/view");
var count = 0;
function buttonTap(args) {
    count++;
    var sender = args.object;
    var parent = sender.parent;
    if (parent) {
        var lbl = view.getViewById(parent, "Label1");
        if (lbl) {
            lbl.text = "You tapped " + count + " times!";
        }
    }
}
exports.buttonTap = buttonTap;

Thanks 
Phil

**Comment by teobugslayer** [comment]
Hello @philvbprogrammer, AppBuilder extension for Visual Studio is a paid product. To benefit from Telerik's support, please open a support ticket at [Telerik Support](http://www.telerik.com/support)
