### ISSUE TITLE
Mac os android command not working

### ISSUE THREAD

**Issue by FahmiChaar** [NativeScript/nativescript-cli#4748]
Original issue #3790

Hi, i come back again and i still have the same issue
> tns info

✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.4.2 version and is up to date.
✔ Component tns-core-modules has 5.4.2 version and is up to date.
✔ Component tns-android has 5.4.0 version and is up to date.
✔ Component tns-ios has 5.4.2 version and is up to date.

> tns build android --log trace > out.txt

```
Trying to get macOS version.
Exec system_profiler SPSoftwareDataType -detailLevel mini 
 stdout: Software:

    System Software Overview:

      System Version: macOS 10.13.6 (17G65)
      Kernel Version: Darwin 17.7.0
      Time since boot: 3:11

 
 stderr: 
macOS version based on system_profiler is 10.13.
Error: Trying to handle SIGINT event. CLI overrides this behavior and does not allow handling SIGINT as this causes issues with Ctrl + C in terminal
    at process.on (/usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:22:22)
    at /usr/local/lib/node_modules/nativescript/node_modules/signal-exit/index.js:122:15
    at Array.filter (<anonymous>)
    at load (/usr/local/lib/node_modules/nativescript/node_modules/signal-exit/index.js:120:21)
    at module.exports (/usr/local/lib/node_modules/nativescript/node_modules/signal-exit/index.js:35:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/node_modules/proper-lockfile/lib/lockfile.js:296:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Looking for project in '/Users/imac/projects/nativescript/xxx'
Project directory is '/Users/imac/projects/nativescript/xxx'.
Loading extensions.
Asserting extension nativescript-cloud is installed.
Extension nativescript-cloud is installed.
Asserting extension nativescript-starter-kits is installed.
Extension nativescript-starter-kits is installed.

```

**Comment by rosen-vladimirov** [comment]
Hey @FahmiChaar ,
As stated in my previous reply, the output you've sent is just the beginning of the command. Can you please wait until the command exits and send us the full log.

**Comment by FahmiChaar** [comment]
Hey @rosen-vladimirov 
The problem the command does not exit, it stuck at (qemu-system-i386)
In the terminal title i see (node and after few seconds replaced with java and after few second replaced with qemu-system-i386 and stuck in this step)

**Comment by rosen-vladimirov** [comment]
Hey @FahmiChaar ,
It looks like CLI is trying to start Android Emulator on your machine, but its stuck. Can you try starting Android Emulator manually (from Android Studio) before running CLI's command. After the emulator is started, try `tns run android` again.

**Comment by FahmiChaar** [comment]
Hey @rosen-vladimirov 
Yes i can't run android emulator so i use genymotion or real device but tns try to run the app in the emulator and ignore the device

**Comment by rosen-vladimirov** [comment]
@FahmiChaar ,
It's been a long time since this error happened. Do you still have similar problems? Can we close the issue?
