### ISSUE TITLE
dont know what kind of error is this

### ISSUE THREAD

**Issue by vick16ach** [NativeScript/nativescript-cli#4755]
i made a mistake by choosing yes while executing tns run android. now my app was not working. it will get install and when i open it, giving this error
```
ActivityManager: Scheduling restart of crashed service com.android.settings/.wifi.MiuiWifiService in 160302ms
ActivityManager: Activity pause timeout for ActivityRecord{2046448 u0 org.nativescript.demo/com.tns.NativeScriptActivity t55603}
ActivityManager: Duplicate finish request for ActivityRecord{2046448 u0 org.nativescript.demo/com.tns.NativeScriptActivity t55603 f}
ActivityManager: Unable to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms } U=999: not found
ActivityManager: cann't getContentProviderImpl: gmail-ofls, cpi is null.
ActivityManager: cann't getContentProviderImpl: gmail-ofls, cpi is null.
ActivityManager: cann't getContentProviderImpl: gmail-ofls, cpi is null.
ActivityManager: cann't getContentProviderImpl: gmail-ofls, cpi is null.
ActivityManager: cann't getContentProviderImpl: gmail-ofls, cpi is null.
ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@6035e3d
TNS.Native: NativeScript Runtime Version 5.1.0, commit 4497f43b69cb57ce65ece2aac5b98b2010f85857
TNS.Native: JNI_ONLoad
TNS.Native: JNI_ONLoad END
TNS.Native: V8 version 6.9.427.23
TNS.Native: lenNodes=108708, lenNames=1071494, lenValues=1426007
TNS.Native: time=9
JS: HMR: Hot Module Replacement Enabled. Waiting for signal.
JS: firebase.init done
System.err: com.tns.NativeScriptException:
System.err: Calling js method onViewAttachedToWindow failed
System.err: TypeError: Cannot read property 'onNavigatingTo' of undefined
System.err: File: "file:///data/data/com.megahard.AmarajyothiMember/files/app/vendor.js, line: 26781, column: 36
System.err: StackTrace:
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame-common.js.FrameBase._onNavigatingTo', file:'file:///data/data/com.megahard.AmarajyothiMember/files/app/vendor.js', line: 26781, column: 37
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame-common.js.FrameBase.performNavigation', file:'file:///data/data/com.megahard.AmarajyothiMember/files/app/vendor.js', line:
26753, column: 14
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame-common.js.FrameBase._processNextNavigationEntry', file:'file:///data/data/com.megahard.AmarajyothiMember/files/app/vendor.js', line: 26746, column: 22
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.Frame._processNextNavigationEntry', file:'file:///data/data/com.megahard.AmarajyothiMember/files/app/vendor.js', line: 27233, column: 58
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.Frame._onAttachedToWindow', file:'file:///data/data/com.megahard.AmarajyothiMember/files/app/vendor.js', line: 27208, column: 14
System.err:     Frame: function:'AttachListener.onViewAttachedToWindow', file:'file:///data/data/com.megahard.AmarajyothiMember/files/app/vendor.js', line: 27125, column: 27
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:987)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err:     at com.tns.gen.java.lang.Object_vendor_27119_36_AttachListener.onViewAttachedToWindow(Object_vendor_27119_36_AttachListener.java:17)
System.err:     at android.view.View.dispatchAttachedToWindow(View.java:14565)
System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2837)
System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2844)
System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2844)
System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2844)
System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2844)
System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2844)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1401)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1144)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6102)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:672)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:608)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
System.err:     at android.os.Handler.handleCallback(Handler.java:742)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:157)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5601)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)

```

**Comment by NickIliev** [comment]
@vick16ach I guess that by saying **_" I made a mistake by choosing yes"_** you mean that you have chosen to enable Webpack by default and the error started appearing after Webpack was enabled.

If that is so, please verify that you are using the latest versions of nativescript-dev--webpack and all related dependencies. [Here ](https://docs.nativescript.org/releases/upgrade-instructions)you can find upgrade instructions .

**Comment by rosen-vladimirov** [comment]
Hey @vick16ach ,
As pointed by @NickIliev , it will be great in case you can follow the upgrade instructions and update all your packages. 
Regarding the error itself, it could be caused by different reasons. Please note there are some differences in the legacy workflow and bundle (webpack) workflow. For example, in the legacy workflow, all of the files in your `app` directory and included in the application. With bundle workflow, this is not the same - pages (`.xml` files) and styles (`.css` files) will be automatically included in case they are named `-page.xml`/`-page.css`. Can you check your `.xml` files and ensure they follow this convention?

**Comment by DimitarTachev** [comment]
Closing due to inactivity.
