### ISSUE TITLE
Modules that have names ending in `.page` are not found

### ISSUE THREAD

**Issue by surdu** [NativeScript/nativescript-cli#4928]
**Describe the bug**
If a module name ends in `.page` (I'm guessing `.<anything>`) you'll not be able to use it, at least not as a Frame's `defaultPage`.

Please see this [Playground example](https://play.nativescript.org/?template=play-js&id=lfBxe9&v=1).

**To Reproduce**
Run the Playground example.

**Expected behavior**
The app starts without crash, showing the `home/home.page` page.

**Additional context**
I have a {N} 5.0 project and I preferred the `.page` suffix instead of the `-page` suffix for my pages.

**Comment by rosen-vladimirov** [comment]
@surdu , 
Thanks for the report. The files are correctly included in the bundle.js during build, but it fails at runtime when trying to construct the UI with error:
```
System.err: An uncaught Exception occurred on “main” thread.
System.err: Unable to start activity ComponentInfo{org.nativescript.appPage1/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Building UI from XML. @app-root.xml:1:1
System.err:  > Failed to load component from module: main
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.appPage1/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Building UI from XML. @app-root.xml:1:1
System.err:  > Failed to load component from module: main
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
```

As this seems an issue in the `tns-core-modules` I'm moving this issue in the NativeScript repository.
