### ISSUE TITLE
node_module errors after migrating to NS6

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#5065]
@Efrenray commented on [Wed Oct 09 2019](https://github.com/NativeScript/NativeScript/issues/7932)

I've migrated my app to NS6 though the app still uses some deprecated plugins such that I encountered these errors.

**Dependencies versions: NodeJS: 10.16.0, npm: 6.9.0, NativeScript CLI: 6.1.2.**

> WARNING in ../node_modules/encoding/lib/iconv-loader.js 9:12-34
> Critical dependency: the request of a dependency is an expression
>  @ ../node_modules/encoding/lib/encoding.js
>  @ ../node_modules/node-fetch/lib/body.js
>  @ ../node_modules/node-fetch/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> WARNING in ./login/login-page.css
> Module build failed (from ../node_modules/css-loader/dist/cjs.js):
> CssSyntaxError
> 
> (74:1) Unexpected }
> 
>   72 |
>   73 |  }
> > 74 | }
>      | ^
> 
>  @ \b_[\w-]*\.)scss)$ (. sync (?<!\bApp_Resources\b.*)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$) ./login/login-page.css
>  @ ./app.js
> 
> WARNING in ../node_modules/ws/lib/BufferUtil.js
> Module not found: Error: Can't resolve '../build/Release/bufferutil' in 'F:\NativeScript\simpleapp\node_modules\ws\lib'
>  @ ../node_modules/ws/lib/BufferUtil.js
>  @ ../node_modules/ws/lib/Sender.js
>  @ ../node_modules/ws/index.js
>  @ ../node_modules/node-xmpp-client/lib/websockets.js
>  @ ../node_modules/node-xmpp-client/lib/session.js
>  @ ../node_modules/node-xmpp-client/lib/Client.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> WARNING in ../node_modules/ws/lib/Validation.js
> Module not found: Error: Can't resolve '../build/Release/validation' in 'F:\NativeScript\simpleapp\node_modules\ws\lib'
>  @ ../node_modules/ws/lib/Validation.js
>  @ ../node_modules/ws/lib/Receiver.js
>  @ ../node_modules/ws/index.js
>  @ ../node_modules/node-xmpp-client/lib/websockets.js
>  @ ../node_modules/node-xmpp-client/lib/session.js
>  @ ../node_modules/node-xmpp-client/lib/Client.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> WARNING in ../node_modules/ws/lib/BufferUtil.js
> Module not found: Error: Can't resolve '../build/default/bufferutil' in 'F:\NativeScript\simpleapp\node_modules\ws\lib'
>  @ ../node_modules/ws/lib/BufferUtil.js
>  @ ../node_modules/ws/lib/Sender.js
>  @ ../node_modules/ws/index.js
>  @ ../node_modules/node-xmpp-client/lib/websockets.js
>  @ ../node_modules/node-xmpp-client/lib/session.js
>  @ ../node_modules/node-xmpp-client/lib/Client.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> WARNING in ../node_modules/ws/lib/Validation.js
> Module not found: Error: Can't resolve '../build/default/validation' in 'F:\NativeScript\simpleapp\node_modules\ws\lib'
>  @ ../node_modules/ws/lib/Validation.js
>  @ ../node_modules/ws/lib/Receiver.js
>  @ ../node_modules/ws/index.js
>  @ ../node_modules/node-xmpp-client/lib/websockets.js
>  @ ../node_modules/node-xmpp-client/lib/session.js
>  @ ../node_modules/node-xmpp-client/lib/Client.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> WARNING in ../node_modules/nativescript-sqlite/sqlite.js
> Module not found: Error: Can't resolve 'nativescript-sqlite-commercial' in 'F:\NativeScript\simpleapp\node_modules\nativescript-sqlite'
>  @ ../node_modules/nativescript-sqlite/sqlite.js
>  @ ./home/home-page.js
>  @ . sync (?<!\bApp_Resources\b.*)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$
>  @ ./app.js
> 
> WARNING in ../node_modules/nativescript-sqlite/sqlite.js
> Module not found: Error: Can't resolve 'nativescript-sqlite-encrypted' in 'F:\NativeScript\simpleapp\node_modules\nativescript-sqlite'
>  @ ../node_modules/nativescript-sqlite/sqlite.js
>  @ ./home/home-page.js
>  @ . sync (?<!\bApp_Resources\b.*)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$
>  @ ./app.js
> 
> ERROR in ../node_modules/nativescript-xmpp-client/lib/deps/buffer.js
> Module not found: Error: Can't resolve './buffer_ieee754' in 'F:\NativeScript\simpleapp\node_modules\nativescript-xmpp-client\lib\deps'
>  @ ../node_modules/nativescript-xmpp-client/lib/deps/buffer.js 808:11-38 829:11-38 1113:4-31 1142:4-31
>  @ ../node_modules/nativescript-xmpp-client/lib/Client.js
>  @ ../node_modules/nativescript-xmpp-client/xmpp-client.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/node-xmpp-client/lib/Client.js
> Module not found: Error: Can't resolve 'child_process' in 'F:\NativeScript\simpleapp\node_modules\node-xmpp-client\lib'
>  @ ../node_modules/node-xmpp-client/lib/Client.js 15:11-35
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/node-xmpp-core/lib/SRV.js
> Module not found: Error: Can't resolve 'dns' in 'F:\NativeScript\simpleapp\node_modules\node-xmpp-core\lib'
>  @ ../node_modules/node-xmpp-core/lib/SRV.js 3:10-24
>  @ ../node_modules/node-xmpp-core/index.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/debug/src/node.js
> Module not found: Error: Can't resolve 'net' in 'F:\NativeScript\simpleapp\node_modules\debug\src'
>  @ ../node_modules/debug/src/node.js 193:16-30
>  @ ../node_modules/debug/src/index.js
>  @ ../node_modules/node-xmpp-client/lib/Client.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/forever-agent/index.js
> Module not found: Error: Can't resolve 'net' in 'F:\NativeScript\simpleapp\node_modules\forever-agent'
>  @ ../node_modules/forever-agent/index.js 6:10-24
>  @ ../node_modules/request/request.js
>  @ ../node_modules/request/index.js
>  @ ../node_modules/node-xmpp-client/lib/bosh.js
>  @ ../node_modules/node-xmpp-client/lib/session.js
>  @ ../node_modules/node-xmpp-client/lib/Client.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/node-xmpp-core/lib/Connection.js
> Module not found: Error: Can't resolve 'net' in 'F:\NativeScript\simpleapp\node_modules\node-xmpp-core\lib'
>  @ ../node_modules/node-xmpp-core/lib/Connection.js 3:10-24
>  @ ../node_modules/node-xmpp-core/index.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/node-xmpp-tls-connect/starttls.js
> Module not found: Error: Can't resolve 'net' in 'F:\NativeScript\simpleapp\node_modules\node-xmpp-tls-connect'
>  @ ../node_modules/node-xmpp-tls-connect/starttls.js 27:10-24
>  @ ../node_modules/node-xmpp-core/lib/Connection.js
>  @ ../node_modules/node-xmpp-core/index.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/tough-cookie/lib/cookie.js
> Module not found: Error: Can't resolve 'net' in 'F:\NativeScript\simpleapp\node_modules\tough-cookie\lib'
>  @ ../node_modules/tough-cookie/lib/cookie.js 32:10-24
>  @ ../node_modules/request/lib/cookies.js
>  @ ../node_modules/request/index.js
>  @ ../node_modules/node-xmpp-client/lib/bosh.js
>  @ ../node_modules/node-xmpp-client/lib/session.js
>  @ ../node_modules/node-xmpp-client/lib/Client.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/tunnel-agent/index.js
> Module not found: Error: Can't resolve 'net' in 'F:\NativeScript\simpleapp\node_modules\tunnel-agent'
>  @ ../node_modules/tunnel-agent/index.js 3:10-24
>  @ ../node_modules/request/lib/tunnel.js
>  @ ../node_modules/request/request.js
>  @ ../node_modules/request/index.js
>  @ ../node_modules/node-xmpp-client/lib/bosh.js
>  @ ../node_modules/node-xmpp-client/lib/session.js
>  @ ../node_modules/node-xmpp-client/lib/Client.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/forever-agent/index.js
> Module not found: Error: Can't resolve 'tls' in 'F:\NativeScript\simpleapp\node_modules\forever-agent'
>  @ ../node_modules/forever-agent/index.js 7:10-24
>  @ ../node_modules/request/request.js
>  @ ../node_modules/request/index.js
>  @ ../node_modules/node-xmpp-client/lib/bosh.js
>  @ ../node_modules/node-xmpp-client/lib/session.js
>  @ ../node_modules/node-xmpp-client/lib/Client.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/node-xmpp-client/lib/session.js
> Module not found: Error: Can't resolve 'tls' in 'F:\NativeScript\simpleapp\node_modules\node-xmpp-client\lib'
>  @ ../node_modules/node-xmpp-client/lib/session.js 3:10-24
>  @ ../node_modules/node-xmpp-client/lib/Client.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/node-xmpp-tls-connect/starttls.js
> Module not found: Error: Can't resolve 'tls' in 'F:\NativeScript\simpleapp\node_modules\node-xmpp-tls-connect'
>  @ ../node_modules/node-xmpp-tls-connect/starttls.js 28:10-24
>  @ ../node_modules/node-xmpp-core/lib/Connection.js
>  @ ../node_modules/node-xmpp-core/index.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/tunnel-agent/index.js
> Module not found: Error: Can't resolve 'tls' in 'F:\NativeScript\simpleapp\node_modules\tunnel-agent'
>  @ ../node_modules/tunnel-agent/index.js 4:10-24
>  @ ../node_modules/request/lib/tunnel.js
>  @ ../node_modules/request/request.js
>  @ ../node_modules/request/index.js
>  @ ../node_modules/node-xmpp-client/lib/bosh.js
>  @ ../node_modules/node-xmpp-client/lib/session.js
>  @ ../node_modules/node-xmpp-client/lib/Client.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/ws/lib/WebSocketServer.js
> Module not found: Error: Can't resolve 'tls' in 'F:\NativeScript\simpleapp\node_modules\ws\lib'
>  @ ../node_modules/ws/lib/WebSocketServer.js 13:10-24
>  @ ../node_modules/ws/index.js
>  @ ../node_modules/node-xmpp-client/lib/websockets.js
>  @ ../node_modules/node-xmpp-client/lib/session.js
>  @ ../node_modules/node-xmpp-client/lib/Client.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> Webpack compilation complete.
> Executing webpack failed with exit code 2.

**Comment by Efrenray** [comment]
Removed the connectycube plugin and it went through though another error came,

> [19-10-11 18:40:37.664] (CLI) Exception in thread "main" java.lang.RuntimeException: Class not found com.telerik.android.data.ListViewGroupFunction
> 	at org.nativescript.staticbindinggenerator.Generator.getClass(Generator.java:549)
> [19-10-11 18:40:37.668] (CLI) at org.nativescript.staticbindinggenerator.Generator.getInterfacesFromCache(Generator.java:532)
> 	at org.nativescript.staticbindinggenerator.Generator.writeBinding(Generator.java:283)
> 	at org.nativescript.staticbindinggenerator.Generator.generateBinding(Generator.java:171)
> 	at org.nativescript.staticbindinggenerator.Generator.processRows(Generator.java:234)
> 	at org.nativescript.staticbindinggenerator.Generator.generateBindings(Generator.java:121)
> 	at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:97)
> 	at org.nativescript.staticbindinggenerator.Main.main(Main.java:53)
> [19-10-11 18:40:37.775] (CLI) FAILURE: Build failed with an exception.
> [19-10-11 18:40:37.779] (CLI) * What went wrong:
> Execution failed for task ':app:runSbg'.
> > Process 'command 'C:\Program Files\Java\jdk1.8.0_162\bin\java.exe'' finished with non-zero exit value 1
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at
> [19-10-11 18:40:37.787] (CLI) https://help.gradle.org
> BUILD FAILED in 1m 14s
> [19-10-11 18:40:38.079] Build failed. Command gradlew.bat failed with exit code 1

**Comment by Fatme** [comment]
Hey @Efrenray,

> WARNING in ../node_modules/encoding/lib/iconv-loader.js 9:12-34
Critical dependency: the request of a dependency is an expression
@ ../node_modules/encoding/lib/encoding.js
@ ../node_modules/node-fetch/lib/body.js
@ ../node_modules/node-fetch/index.js
@ ../node_modules/connectycube/src/cubeDependencies.js
@ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
@ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
@ ../node_modules/connectycube/src/cubeMain.js
@ ./app.js

It is just a warning from `webpack` due to [this dynamic import](https://github.com/andris9/encoding/blob/91ae950aaa854a119122c27cdbabd8c5585106f7/lib/iconv-loader.js#L9). It shouldn't cause issues if the dynamically required file is included inside `bundle/vendor.js`. If it is not included, you can hack it by adding `require("iconv")` somewhere in your application. That way, the dynamically loaded file will be gathered by webpack compilation.

> [19-10-11 18:40:37.664] (CLI) Exception in thread "main" java.lang.RuntimeException: Class not found com.telerik.android.data.ListViewGroupFunction
at org.nativescript.staticbindinggenerator.Generator.getClass(Generator.java:549)
[19-10-11 18:40:37.668] (CLI) at org.nativescript.staticbindinggenerator.Generator.getInterfacesFromCache(Generator.java:532)
at org.nativescript.staticbindinggenerator.Generator.writeBinding(Generator.java:283)
at org.nativescript.staticbindinggenerator.Generator.generateBinding(Generator.java:171)
at org.nativescript.staticbindinggenerator.Generator.processRows(Generator.java:234)
at org.nativescript.staticbindinggenerator.Generator.generateBindings(Generator.java:121)
at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:97)
at org.nativescript.staticbindinggenerator.Main.main(Main.java:53)
[19-10-11 18:40:37.775] (CLI) FAILURE: Build failed with an exception.
[19-10-11 18:40:37.779] (CLI) * What went wrong:
Execution failed for task ':app:runSbg'.

Regarding to your second error, can you try to delete the `platforms` directory and try again.

**Comment by rosen-vladimirov** [comment]
Closing due to inactivity.
