### ISSUE TITLE
Tns device run not working on Android Device

### ISSUE THREAD

**Issue by kerby82** [NativeScript/nativescript-cli#5154]
When I try to run an app on the device I obtain the following error:

TypeError: Cannot read property 'replace' of undefined
    at Object.regExpEscape (/usr/local/lib/node_modules/nativescript/lib/common/helpers.js:74:18)
    at AndroidApplicationManager.getFullyQualifiedActivityRegex (/usr/local/lib/node_modules/nativescript/lib/common/mobile/android/android-application-manager.js:164:40)
    at AndroidApplicationManager.descriptor.(anonymous function) (/usr/local/lib/node_modules/nativescript/lib/common/decorators.js:21:40)
    at AndroidApplicationManager.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/mobile/android/android-application-manager.js:89:40)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/nativescript/lib/common/mobile/android/android-application-manager.js:10:58)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

The same error is also trying to run example code from nativescript.org

My nativescript version is 6.2.1

**Comment by rosen-vladimirov** [comment]
Hey @kerby82 ,
Can you please share your package.json and the command you run? It seems CLI is unable to determine your application identifier, but the package.json file should help us to identify the issue.

**Comment by rosen-vladimirov** [comment]
Closing due to inactivity.
