### ISSUE TITLE
Can't build an {N} 6.3.0 iOS app due to pod install failure

### ISSUE THREAD

**Issue by shirakaba** [NativeScript/nativescript-cli#5191]
**Environment**

`tns doctor`:

```
$ tns doctor
✔ Getting environment information 

No issues were detected.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 11.3.0 satisfies minimum required version 10.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 6.3.0 version and is up to date.
✔ Component tns-core-modules has 6.3.2 version and is up to date.
✔ Component tns-android has 6.3.0 version and is up to date.
✔ Component tns-ios has 6.3.0 version and is up to date.
```

**Describe the bug**
This is a build-time error. The Webpack build completes, but the native app build fails at the `pod install` stage:

```
Installing pods...
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "MaterialComponents/Tabs":
  In Podfile:
    MaterialComponents/Tabs (~> 94.5)

None of your spec sources contain a spec satisfying the dependency: `MaterialComponents/Tabs (~> 94.5)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
'pod install' command failed.
For more information on resolving CocoaPod issues in NativeScript read.
```

My `platforms/ios/Podfile` looks like this:

```
use_frameworks!

target "sample" do
# NativeScriptPlatformSection /Users/jamie/Documents/git/react-nativescript/sample/node_modules/@nativescript/core/platforms/ios/Podfile with 9.0
platform :ios, '9.0'
# End NativeScriptPlatformSection

# Begin Podfile - /Users/jamie/Documents/git/react-nativescript/sample/node_modules/@nativescript/core/platforms/ios/Podfile
# platform :ios, '9.0'
use_frameworks!

pod 'MaterialComponents/Tabs', '~> 94.5'
# End Podfile
end
```

**To Reproduce**

```sh

git clone https://github.com/shirakaba/react-nativescript.git
cd react-nativescript
git checkout "ns-6-3"

# Build a local release of React NativeScript
cd react-nativescript && npm install && npm run build

cd ../sample
npm install
tns run ios
```

**Expected behavior**

iOS app should successfully build and run.

**Sample project**
See reproduction steps (which involve checking out [the `ns-6-3` branch](https://github.com/shirakaba/react-nativescript/tree/ns-6-3) of React NativeScript and running the sample app which I've just attempted to update to {N} v6.3.0).

**Additional context**
* Another pod install failure for 6.3.0: https://github.com/NativeScript/nativescript-cli/issues/5189
* A different `MaterialComponents/Tabs` issue: https://github.com/NativeScript/nativescript-cli/issues/5153
* Another different `MaterialComponents/Tabs` issue: https://github.com/NativeScript/NativeScript/issues/7928

**Comment by shirakaba** [comment]
Results of `tns prepare ios --log trace`:

```
$ tns prepare ios --log trace
Trying to get macOS version.
Exec system_profiler SPSoftwareDataType -detailLevel mini 
 stdout: Software:

    System Software Overview:

      System Version: macOS 10.14.6 (18G1012)
      Kernel Version: Darwin 18.7.0
      Time since boot: 13:14

 
 stderr: 
macOS version based on system_profiler is 10.14.
Looking for project in '/Users/jamie/Documents/git/react-nativescript/sample'
Project directory is '/Users/jamie/Documents/git/react-nativescript/sample'.
Loading extensions.
System information:
{
  "platform": "darwin",
  "shell": "/usr/local/bin/bash",
  "os": "Darwin Jamie-Birch-MBP-2017.local 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64\n",
  "procArch": "x64",
  "nodeVer": "13.4.0",
  "npmVer": "6.13.4",
  "nodeGypVer": null,
  "nativeScriptCliVersion": "6.3.0",
  "gitVer": "2.23.0",
  "dotNetVer": null,
  "javacVersion": "1.8.0_192",
  "javaVersion": "1.8.0_192",
  "javaPath": "/Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/bin/java",
  "adbVer": "1.0.41",
  "androidInstalled": true,
  "monoVer": null,
  "gradleVer": null,
  "isAndroidSdkConfiguredCorrectly": true,
  "xcodeVer": "11.3.0",
  "xcodeprojLocation": "/usr/local/bin/xcodeproj",
  "itunesInstalled": true,
  "cocoaPodsVer": "1.7.3",
  "isCocoaPodsWorkingCorrectly": true,
  "isCocoaPodsUpdateRequired": false,
  "pythonInfo": {
    "isInstalled": true,
    "isSixPackageInstalled": true
  }
}
Current CLI version:  6.3.0
Validate options for platform: iOS
Trying to handle SIGINT event. CLI overrides this behavior and does not allow handling SIGINT as this causes issues with Ctrl + C in terminal.
The stackTrace of the location trying to handle SIGINT is:
    at process.on (/usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:24:28)
    at /usr/local/lib/node_modules/nativescript/node_modules/signal-exit/index.js:122:15
    at Array.filter (<anonymous>)
    at load (/usr/local/lib/node_modules/nativescript/node_modules/signal-exit/index.js:120:21)
    at module.exports (/usr/local/lib/node_modules/nativescript/node_modules/signal-exit/index.js:35:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/node_modules/proper-lockfile/lib/lockfile.js:296:1)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/node_modules/proper-lockfile/index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
spawn: /usr/local/Cellar/node/13.4.0/bin/node "/usr/local/lib/node_modules/nativescript/lib/detached-processes/cleanup-process.js" "/usr/local/lib/node_modules/nativescript/lib/bootstrap.js"
Shasum of file /Users/jamie/Documents/git/react-nativescript/sample/package.json is 1daafcc202123639303278f932dbf53f852ecc00
Got cached result for shouldMigrate for platform: ios
Initializing analytics statuses.
Analytics statuses:  { TrackFeatureUsage: 'disabled', TrackExceptions: 'disabled' }
getInfos cacheConfig options: { forceCheck: undefined }  current info from cache:  [
  {
    message: 'Xcode is installed and is configured properly.',
    platforms: [ 'iOS' ],
    type: 'info'
  },
  {
    message: 'xcodeproj is installed and is configured properly.',
    platforms: [ 'iOS' ],
    type: 'info'
  },
  {
    message: 'CocoaPods are installed.',
    platforms: [ 'iOS' ],
    type: 'info'
  },
  {
    message: 'CocoaPods update is not required.',
    platforms: [ 'iOS' ],
    type: 'info'
  },
  {
    message: 'CocoaPods are configured properly.',
    platforms: [ 'iOS' ],
    type: 'info'
  },
  {
    message: 'Your current CocoaPods version is newer than 1.0.0.',
    platforms: [ 'iOS' ],
    type: 'info'
  },
  {
    message: 'Python installed and configured correctly.',
    platforms: [ 'iOS' ],
    type: 'info'
  },
  {
    message: "The Python 'six' package is found.",
    platforms: [ 'iOS' ],
    type: 'info'
  },
  {
    message: 'Xcode version 11.3.0 satisfies minimum required version 10.',
    platforms: [ 'iOS' ],
    type: 'info'
  }
]
Xcode is installed and is configured properly.
xcodeproj is installed and is configured properly.
CocoaPods are installed.
CocoaPods update is not required.
CocoaPods are configured properly.
Your current CocoaPods version is newer than 1.0.0.
Python installed and configured correctly.
The Python 'six' package is found.
Xcode version 11.3.0 satisfies minimum required version 10.
Project dir from hooksArgs is: /Users/jamie/Documents/git/react-nativescript/sample.
Hooks directories: [ '/Users/jamie/Documents/git/react-nativescript/sample/hooks' ]
BeforeHookName for command prepare is before-prepare
Preparing project...
spawn: /usr/local/Cellar/node/13.4.0/bin/node "--max_old_space_size=4096" "--preserve-symlinks" "/Users/jamie/Documents/git/react-nativescript/sample/node_modules/webpack/bin/webpack.js" "--config=/Users/jamie/Documents/git/react-nativescript/sample/webpack.config.js" "--env.ios" "--env.appPath=app" "--env.appResourcesPath=app/App_Resources" "--env.verbose" "--env.sourceMap"
clean-webpack-plugin: /Users/jamie/Documents/git/react-nativescript/sample/platforms/ios/sample/app/**/* has been removed.
Starting type checking service...
Using 1 worker with 4096MB memory limit
ℹ ｢atl｣: Using typescript@3.7.2 from typescript
ℹ ｢atl｣: Using tsconfig.json from /Users/jamie/Documents/git/react-nativescript/sample/tsconfig.tns.json
Hash: 31c8bd69ba9bf312f24e
Version: webpack 4.27.1
Time: 15739ms
Built at: 21/12/2019 23:49:21
                                            Asset       Size                                          Chunks             Chunk Names
                                        bundle.js    610 KiB                                          bundle  [emitted]  bundle
          images/RNTester_Thumbnails/bandaged.png   5.42 KiB                                                  [emitted]  
              images/RNTester_Thumbnails/call.png   8.12 KiB                                                  [emitted]  
           images/RNTester_Thumbnails/dislike.png   4.04 KiB                                                  [emitted]  
              images/RNTester_Thumbnails/fist.png   5.64 KiB                                                  [emitted]  
           images/RNTester_Thumbnails/flowers.png   9.48 KiB                                                  [emitted]  
             images/RNTester_Thumbnails/heart.png   6.89 KiB                                                  [emitted]  
              images/RNTester_Thumbnails/like.png    4.2 KiB                                                  [emitted]  
            images/RNTester_Thumbnails/liking.png   6.59 KiB                                                  [emitted]  
             images/RNTester_Thumbnails/party.png   8.37 KiB                                                  [emitted]  
              images/RNTester_Thumbnails/poke.png   4.81 KiB                                                  [emitted]  
         images/RNTester_Thumbnails/superlike.png   6.79 KiB                                                  [emitted]  
           images/RNTester_Thumbnails/victory.png   6.89 KiB                                                  [emitted]  
                                     package.json   81 bytes                                                  [emitted]  
                                       runtime.js   13.9 KiB                                         runtime  [emitted]  runtime
tns_modules/tns-core-modules/inspector_modules.js  642 bytes  tns_modules/tns-core-modules/inspector_modules  [emitted]  tns_modules/tns-core-modules/inspector_modules
                                        vendor.js   7.46 MiB                                          vendor  [emitted]  vendor
Entrypoint bundle = runtime.js vendor.js bundle.js
Entrypoint tns_modules/tns-core-modules/inspector_modules = runtime.js vendor.js tns_modules/tns-core-modules/inspector_modules.js
[../../react-nativescript/dist/client/ComponentTree.js] /Users/jamie/Documents/git/react-nativescript/react-nativescript/dist/client/ComponentTree.js 2.72 KiB {bundle} [built]
[../../react-nativescript/dist/client/ElementRegistry.js] /Users/jamie/Documents/git/react-nativescript/react-nativescript/dist/client/ElementRegistry.js 10.6 KiB {bundle} [built]
[../../react-nativescript/dist/client/EventHandling.js] /Users/jamie/Documents/git/react-nativescript/react-nativescript/dist/client/EventHandling.js 1.13 KiB {bundle} [built]
[../../react-nativescript/dist/client/HostConfig.js] /Users/jamie/Documents/git/react-nativescript/react-nativescript/dist/client/HostConfig.js 31.2 KiB {bundle} [built]
[../../react-nativescript/dist/client/ReactNativeScript.js] /Users/jamie/Documents/git/react-nativescript/react-nativescript/dist/client/ReactNativeScript.js 9.24 KiB {bundle} [built]
[../../react-nativescript/dist/client/ReactNativeScriptComponent.js] /Users/jamie/Documents/git/react-nativescript/react-nativescript/dist/client/ReactNativeScriptComponent.js 19.4 KiB {bundle} [built]
[../../react-nativescript/dist/client/ReactPortal.js] /Users/jamie/Documents/git/react-nativescript/react-nativescript/dist/client/ReactPortal.js 1.01 KiB {bundle} [built]
[../../react-nativescript/dist/index.js] /Users/jamie/Documents/git/react-nativescript/react-nativescript/dist/index.js 225 bytes {bundle} [built]
[../../react-nativescript/dist/shared/HostConfigTypes.js] /Users/jamie/Documents/git/react-nativescript/react-nativescript/dist/shared/HostConfigTypes.js 287 bytes {bundle} [built]
[../../react-nativescript/dist/shared/Logger.js] /Users/jamie/Documents/git/react-nativescript/react-nativescript/dist/shared/Logger.js 879 bytes {bundle} [built]
[./ sync ^\.\/app\.(css|scss|less|sass)$] . sync nonrecursive ^\.\/app\.(css|scss|less|sass)$ 174 bytes {bundle} [built]
[./ sync recursive (?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$] . sync (?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$ 187 bytes {bundle} [built]
[./app.css] 1.25 KiB {bundle} [optional] [built]
[./app.ts] 2.24 KiB {bundle} [built]
[./testComponents/AppContainer.tsx] 2.28 KiB {bundle} [built]
    + 441 hidden modules
Webpack compilation complete.
Project dir from hooksArgs is: /Users/jamie/Documents/git/react-nativescript/sample.
Hooks directories: [ '/Users/jamie/Documents/git/react-nativescript/sample/hooks' ]
BeforeHookName for command prepareNativeApp is before-prepareNativeApp
Project dir from hooksArgs is: /Users/jamie/Documents/git/react-nativescript/sample.
Hooks directories: [ '/Users/jamie/Documents/git/react-nativescript/sample/hooks' ]
BeforeHookName for command checkForChanges is before-checkForChanges
Executing before-checkForChanges hook at location /Users/jamie/Documents/git/react-nativescript/sample/hooks/before-checkForChanges/nativescript-core.js in-process
Validating before-checkForChanges arguments.
Executing before-checkForChanges hook at location /Users/jamie/Documents/git/react-nativescript/sample/hooks/before-checkForChanges/nativescript-dev-webpack.js in-process
Validating before-checkForChanges arguments.
Set configChanged to true, appResourcesChanged is: true
checkForChanges returns ProjectChangesInfo {
  appResourcesChanged: true,
  configChanged: true,
  nativeChanged: true,
  nsConfigChanged: true,
  nativePlatformStatus: '2'
}
Project dir from hooksArgs is: /Users/jamie/Documents/git/react-nativescript/sample.
Hooks directories: [ '/Users/jamie/Documents/git/react-nativescript/sample/hooks' ]
AfterHookName for command checkForChanges is after-checkForChanges
Images from Xcode project
[ 'Assets.xcassets', 'LaunchScreen.storyboard', 'build.xcconfig' ]
Current images from App_Resources
[ 'Assets.xcassets', 'LaunchScreen.storyboard', 'build.xcconfig' ]
New images to add into xcode project: 
Images to remove from xcode project: 
Successfully prepared plugin @nativescript/theme for ios.
Successfully prepared plugin tns-core-modules for ios.
Shasum of file /Users/jamie/Documents/git/react-nativescript/sample/node_modules/@nativescript/core/platforms/ios/src/NativeScriptEmbedder.h is 61d5332c711cc0ac62e0194e18077d2ff5293b11
Shasum of file /Users/jamie/Documents/git/react-nativescript/sample/node_modules/@nativescript/core/platforms/ios/Podfile is 32c7118af05cda2870d9693d93b4c9376840221e
Shasum of file /Users/jamie/Documents/git/react-nativescript/sample/node_modules/@nativescript/core/platforms/ios/src/NativeScriptEmbedder.m is 177d5673fac79dff28d09182eaef20778f66e787
Shasum of file /Users/jamie/Documents/git/react-nativescript/sample/node_modules/@nativescript/core/platforms/ios/src/module.modulemap is e3696280d924e540c4525889e025e1314ec183b9
Shasum of file /Users/jamie/Documents/git/react-nativescript/sample/node_modules/@nativescript/core/platforms/ios/.DS_Store is b450bd21c6c7f149825ca75dbdcfb90db64b0eb3
Shasum of file /Users/jamie/Documents/git/react-nativescript/sample/node_modules/@nativescript/core/platforms/ios/typings/objc!MaterialComponents.d.ts is 6e22ade7ce74eea47dc88478166c1fa7a4b2d3a0
Successfully prepared plugin @nativescript/core for ios.
Shasum of file /Users/jamie/Documents/git/react-nativescript/sample/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/Headers/NSString+Async.h is a3cdfaeb2f7360c395c8e6c2defb4a2b2ffc8f10
Shasum of file /Users/jamie/Documents/git/react-nativescript/sample/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/Headers/NSData+Async.h is 4eae4f66d67dc99a53dbbb7c2d8cf1b3df7eb487
Shasum of file /Users/jamie/Documents/git/react-nativescript/sample/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/Headers/TNSLabel.h is c7c5788d3ea834d96cf8a137cbf0c4ea28fd7829
Shasum of file /Users/jamie/Documents/git/react-nativescript/sample/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/Headers/TNSProcess.h is 787f09c57ede174d6323990e6d6e9eaf134da6f0
Shasum of file /Users/jamie/Documents/git/react-nativescript/sample/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/Headers/UIView+PassThroughParent.h is cddc4157f40983b34fcb1d3846666b5ecc5b1ca5
Shasum of file /Users/jamie/Documents/git/react-nativescript/sample/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/Headers/TNSWidgets.h is 814beee5b8d98390227b9889d64af11660eb1f09
Shasum of file /Users/jamie/Documents/git/react-nativescript/sample/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/Info.plist is a4a930fc63184d81a6b05b81bc432b1a82d0c515
Shasum of file /Users/jamie/Documents/git/react-nativescript/sample/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/Headers/UIImage+TNSBlocks.h is 3b31a5be818e25c142e99f98479c538632d350ae
Shasum of file /Users/jamie/Documents/git/react-nativescript/sample/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/Modules/module.modulemap is 00d2220e76eb098f1808eb4e9b5c43ad4cadf1da
Shasum of file /Users/jamie/Documents/git/react-nativescript/sample/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/TNSWidgets is b0f99b9b94900045c88587866a9297d5f783fb5a
Successfully prepared plugin tns-core-modules-widgets for ios.
No plist found at: /Users/jamie/Documents/git/react-nativescript/sample/node_modules/@nativescript/theme/platforms/ios/Info.plist
No plist found at: /Users/jamie/Documents/git/react-nativescript/sample/node_modules/tns-core-modules/platforms/ios/Info.plist
No plist found at: /Users/jamie/Documents/git/react-nativescript/sample/node_modules/@nativescript/core/platforms/ios/Info.plist
No plist found at: /Users/jamie/Documents/git/react-nativescript/sample/node_modules/tns-core-modules-widgets/platforms/ios/Info.plist
Schedule merge plist at: /Users/jamie/Documents/git/react-nativescript/sample/app/App_Resources/iOS/Info.plist
Info.plist: Start
Info.plist: Patch 'app/App_Resources/iOS/Info.plist'
Info.plist: Patch 'CFBundleIdentifier from package.json nativescript.id'
Info.plist: Patch 'CFBundleURLTypes from package.json nativescript.id'
Info.plist: Complete
Info.plist: Write to: /Users/jamie/Documents/git/react-nativescript/sample/platforms/ios/sample/sample-Info.plist
No plist found at: /Users/jamie/Documents/git/react-nativescript/sample/node_modules/@nativescript/theme/platforms/ios/app.entitlements
No plist found at: /Users/jamie/Documents/git/react-nativescript/sample/node_modules/tns-core-modules/platforms/ios/app.entitlements
Exec ruby -e "require 'xcodeproj'; Xcodeproj::Config.new('/Users/jamie/Documents/git/react-nativescript/sample/platforms/ios/plugins-debug.xcconfig').merge(Xcodeproj::Config.new('/Users/jamie/Documents/git/react-nativescript/sample/app/App_Resources/iOS/build.xcconfig')).save_as(Pathname.new('/Users/jamie/Documents/git/react-nativescript/sample/platforms/ios/plugins-debug.xcconfig'))" 
 stdout:  
 stderr: 
Exec ruby -e "require 'xcodeproj'; Xcodeproj::Config.new('/Users/jamie/Documents/git/react-nativescript/sample/platforms/ios/plugins-release.xcconfig').merge(Xcodeproj::Config.new('/Users/jamie/Documents/git/react-nativescript/sample/app/App_Resources/iOS/build.xcconfig')).save_as(Pathname.new('/Users/jamie/Documents/git/react-nativescript/sample/platforms/ios/plugins-release.xcconfig'))" 
 stdout:  
 stderr: 
Installing pods...
spawn: pod "install"
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "MaterialComponents/Tabs":
  In Podfile:
    MaterialComponents/Tabs (~> 94.5)

None of your spec sources contain a spec satisfying the dependency: `MaterialComponents/Tabs (~> 94.5)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
Result when throw error is false:
{ stdout: '', stderr: '', exitCode: 31 }
'pod install' command failed.
For more information on resolving CocoaPod issues in NativeScript read.
Error: 'pod install' command failed.
For more information on resolving CocoaPod issues in NativeScript read.
    at Errors.failWithOptions (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:147:28)
    at Errors.fail (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:120:21)
    at CocoaPodsService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/services/cocoapods-service.js:42:30)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/nativescript/lib/services/cocoapods-service.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by rosen-vladimirov** [comment]
Hey @shirakaba ,
It seems you've not executed `pod repo update` - can you execute this command and try `tns prepare ios` again?

**Comment by shirakaba** [comment]
@rosen-vladimirov Thanks for the tip; trying right now..!

**Comment by shirakaba** [comment]
@rosen-vladimirov It woooorks! Fastest issue turnaround ever 😆🙇‍♂️ thanks for responding at this time of night, in the holiday season, on a weekend no less!

A very Merry Christmas to you, and I have a beer with your name on it on the day we cross paths! 🎄🍺🎁

**Comment by muazmalas** [comment]
Nope, I wish if it was that easy. Still getting the same error.

```
[!] CocoaPods could not find compatible versions for pod "MaterialComponents/Tabs":
  In Podfile:
    MaterialComponents/Tabs (~> 94.5)

Specs satisfying the `MaterialComponents/Tabs (~> 94.5)` dependency were found, but they required a higher minimum deployment target.

[!] Smart quotes were detected and ignored in your Podfile. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.
'pod install' command failed.
```

**Comment by Fatme** [comment]
@muazmalas,

It seems the required iOS platform version for [MaterialComponents pod](https://cocoapods.org/pods/MaterialComponents#requirements) is `9.0`. Most probably you have a plugin in your application that requires lower iOS platform version. To check if this is the case you can see what is the value of `platform` property in `platforms/ios/<myAppName>/Podfile`. If this is the case you
need to specify `platform :ios, '9.0'` in your `App_Resources/iOS/Podfile`.

**Comment by imolecule** [comment]
Thanks. The fix works perfectly for me.

**Comment by hbg34** [comment]
We can not fix the problem. We started a new project with Angular, "tns create Name --ng", android has no problem however iOS stuck at these lines:
...
Installing MDFInternationalization (2.0.0)
Installing MaterialComponents (94.5.0)

We can not fix it with any of the recommended solutions.
Please advise.
