### ISSUE TITLE
NativeScript - unit tests throwing errors

### ISSUE THREAD

**Issue by aquinn637** [NativeScript/nativescript-cli#5277]
I'm writing an app with NativeScript 6+ and Angular 8+. I'm trying to write some unit tests for my services with karma and jasmine. My unit tests are throwing errors.

How can I write my unit tests properly? I read and followed the directions on this web page but it still doesn't work: https://docs.nativescript.org/angular/tooling/testing/testing

karma.config.js

```
// list of files / patterns to load in the browser
files: [
  'src/tests/setup.ts',
  'src/tests/**/*.spec.ts'
],
```

test

```
import {
  nsTestBedAfterEach,
  nsTestBedBeforeEach,
  nsTestBedRender
} from 'nativescript-angular/testing';

import { HttpInterceptorService } from '../app/core/interceptors/http-interceptor-service';

describe('HttpInterceptorService', () => {

  beforeEach(nsTestBedBeforeEach([HttpInterceptorService]));
  afterEach(nsTestBedAfterEach(false));

  it('should be created', () => {
  });

  it('should have its functions defined', () => {
  });

});
```
Error:

```
NativeScript / 13.3 (13.3; iPad): Executed 15 of 17 SUCCESS (0 secs / 0.018 secs)
NativeScript / 13.3 (13.3; iPad)  undefined at line undefined FAILED
    An error was thrown in afterAll
    TypeError: undefined is not an object (evaluating 'window.location.origin') (line 108)
        at <Jasmine>
    at file:///app/vendor.js:157139:46
        at <Jasmine>
    at file:///app/vendor.js:157341:57
        at <Jasmine>
    at file:///app/bundle.js:1389:28
        at <Jasmine>
    TypeError: undefined is not an object (evaluating 'window.location.origin') (line 108)
        at <Jasmine>
    at file:///app/vendor.js:157139:46
        at <Jasmine>
    at file:///app/vendor.js:157341:57
        at <Jasmine>
    at file:///app/bundle.js:1389:28
        at <Jasmine>
NativeScript / 13.3 (13.3; iPad): Executed 16 of 17 (1 FAILED) (0.084 secs / 0.018 secs)
TOTAL: 1 FAILED, 15 SUCCESS
CONSOLE LOG file:///node_modules/nativescript-unit-test-runner/app/main-view-model.js:132:0: NSUTR: this.error: An error was thrown in afterAll
TypeError: undefined is not an object (evaluating 'window.location.origin') (line 108)
at <Jasmine>
at file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.jasmine.js:1445:0
at <Jasmine>
at file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:188:0
at <Jasmine>
at file:///src/main.ts:11:16
at <Jasmine>
TypeError: undefined is not an object (evaluating 'window.location.origin') (line 108)
at <Jasmine>
at file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.jasmine.js:1445:0
at <Jasmine>
at file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:188:0
at <Jasmine>
at file:///src/main.ts:11:16
at <Jasmine>
CONSOLE LOG file:///node_modules/nativescript-unit-test-runner/app/main-view-model.js:120:0: NSUTR: completed test run.
CONSOLE LOG file:///node_modules/nativescript-unit-test-runner/app/main-view-model.js:120:0: NSUTR: completed test run.
CONSOLE LOG file:///node_modules/nativescript-unit-test-runner/app/main-view-model.js:124:0: NSUTR: completeAck
CONSOLE LOG file:///node_modules/nativescript-unit-test-runner/app/main-view-model.js:124:0: NSUTR: completeAck
NativeScript / 13.3 (13.3; iPad) ERROR
```

**Comment by Cheas** [comment]
**03/21/2020**

same problem:

k**arma.config.js**

```
module.exports = function (config) {
  const options = {

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',


    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine'],


    // list of files / patterns to load in the browser
    files: [
      'src/tests/**/*.*.ts'
    ],

    // list of files to exclude
    exclude: [
    ],

    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
    },

    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress'],


    // web server port
    port: 9876,


    // enable / disable colors in the output (reporters and logs)
    colors: true,

    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,


    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: false,


    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: [],

    customLaunchers: {
      android: {
        base: 'NS',
        platform: 'android'
      },
      android_simulator: {
        base: 'NS',
        platform: 'android',
        arguments: ['--emulator']
      },
      ios: {
        base: 'NS',
        platform: 'ios'
      },
      ios_simulator: {
        base: 'NS',
        platform: 'ios',
        arguments: ['--emulator']
      }
    },

    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false
  };

  setWebpackPreprocessor(config, options);
  setWebpack(config, options);

  config.set(options);
}

function setWebpackPreprocessor(config, options) {
  if (config && config.bundle) {
    if (!options.preprocessors) {
      options.preprocessors = {};
    }

    options.files.forEach(file => {
      if (!options.preprocessors[file]) {
        options.preprocessors[file] = [];
      }
      options.preprocessors[file].push('webpack');
    });
  }
}

function setWebpack(config, options) {
  if (config && config.bundle) {
    const env = {};
    env[config.platform] = true;
    env.sourceMap = config.debugBrk;
    env.appPath = config.appPath;
    options.webpack = require('./webpack.config')(env);
    delete options.webpack.entry;
    delete options.webpack.output.libraryTarget;
    const invalidPluginsForUnitTesting = ["GenerateBundleStarterPlugin", "GenerateNativeScriptEntryPointsPlugin"];
    options.webpack.plugins = options.webpack.plugins.filter(p => !invalidPluginsForUnitTesting.includes(p.constructor.name));
  }
} 
```
**tests:** 

```
// A sample Jasmine test
describe("A suite", () => {
  it("contains spec with an expectation", () => {
    expect(true).toBe(true);
  });
});
```
```
import "reflect-metadata";
import { Player } from "~/app/shared/classes/player.class";

declare var describe: any;
declare var expect: any;
declare var it: any;

describe("Email validation", () => {
  const user = new Player();

  it("Should reject an empty email address", () => {
    user.email = "";
    expect(user.isValidEmail()).toBe(true);
  });

  it("Should reject a malformed email addresses", () => {
    user.email = "nativescript";
    expect(user.isValidEmail()).toBe(false);

    user.email = "nativescript@";
    expect(user.isValidEmail()).toBe(false);

    user.email = "nativescript@isawesome";
    expect(user.isValidEmail()).toBe(false);
  });

  it("Should accept valid email addresses", () => {
    user.email = "nativescript@isawesome.com";
    expect(user.isValidEmail()).toBe(true);
  });
});
```

**result (test with error) :**
![image](https://user-images.githubusercontent.com/16763914/77225737-8896fc80-6b7a-11ea-8c2d-9009b375895f.png)

**result (test successfull):**
![image](https://user-images.githubusercontent.com/16763914/77225914-7a49e000-6b7c-11ea-98b6-fab1a72792f5.png)

**The problem - it is not visible where the error is, if any.**

**Comment by saschaarthur** [comment]
Oh yeah i have the same ! :(

We also set
 
logLevel: config.LOG_DEBUG, 

in karma conf

And still dont know where it happens. It randomly fails it seems ios/android affected...
