### ISSUE TITLE
Generate component is not working

### ISSUE THREAD

**Issue by petarGitNik** [NativeScript/nativescript-cli#5286]
**Environment**

 - CLI: 6.5.0
 - Cross-platform modules: none
 - Android Runtime: 6.5.0
 - iOS Runtime: 6.5.0
 - Plugin(s): none
- Angular: 8.2.0 (it does not work also with 9.1.0)

**Describe the bug**

When nativescript is installed it cannot generate component. Both with shorthand and with full notation (I get two different outputs).

```sh
user:ui$ tns g c login
Unknown command 'g'.
Run 'tns --help' for more information.

Did you mean?
        generate
        migrate
        usage-reporting
        package-manager
```

or

```sh
user:ui$ tns generate component login
Error: Invalid rule result: Instance of class Promise.
    at t.project (/home/user/.nvm/versions/node/v12.16.1/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:250:1038)
    at t._tryNext (/home/user/.nvm/versions/node/v12.16.1/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:30:1878)
    at t._next (/home/user/.nvm/versions/node/v12.16.1/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:30:1780)
    at t.next (/home/user/.nvm/versions/node/v12.16.1/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:16:1093)
    at e._subscribe (/home/user/.nvm/versions/node/v12.16.1/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:74:13873)
    at e._trySubscribe (/home/user/.nvm/versions/node/v12.16.1/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:16:4641)
    at e.subscribe (/home/user/.nvm/versions/node/v12.16.1/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:16:4427)
    at e.call (/home/user/.nvm/versions/node/v12.16.1/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:30:1459)
    at e.subscribe (/home/user/.nvm/versions/node/v12.16.1/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:16:4299)
    at /home/user/.nvm/versions/node/v12.16.1/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:145:10377
    at s (/home/user/.nvm/versions/node/v12.16.1/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:16:6063)
    at t._innerSub (/home/user/.nvm/versions/node/v12.16.1/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:30:2033)
    at t._tryNext (/home/user/.nvm/versions/node/v12.16.1/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:30:1957)
    at t._next (/home/user/.nvm/versions/node/v12.16.1/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:30:1780)
    at t.next (/home/user/.nvm/versions/node/v12.16.1/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:16:1093)
    at SafeSubscriber.__tryOrUnsub (/home/user/repos/project/ui/node_modules/@nativescript/schematics/node_modules/rxjs/internal/Subscriber.js:207:16)
```

**To Reproduce**

1. `npm install -g nativescript`
2. `tns create project --ng`
3. `cd project`
4. `npm i -D @angular/cli@8.2.0 @schematics/angular@8.2.0 @nativescript/schematics` (this is solution for similar bug, but it does not work)
5. `tns g c testCmp` -> fails (`g` is not recognized)
6. `tns generate component testCmp` -> fails (Error: Invalid rule result: Instance of class Promise.)

**Expected behavior**

Component is created without any error with tns.

**Sample project**

https://github.com/petarGitNik/tns-g-c-fails-bug

**Comment by rigor789** [comment]
use `ng g c testCmp` or `ng generate component testCmp` - these are angular specific commands, and are not in scope for the NativeScript CLI.
