### ISSUE TITLE
Unable to find entry module

### ISSUE THREAD

**Issue by reyldavid** [NativeScript/nativescript-cli#5287]
**Environment**
 - Angular CLI:  v8.2.14
 - Android Runtime:  v6.5.0
 - iOS Runtime:  v6.5.0

**Build-time bug**
First time running "tns preview".  My project runs fine on the web, but when I run "tns preview", I get:
Preparing project...
D:\<my_project_path>\node_modules\webpack-cli\bin\cli.js:244
                                throw err;
                                ^
Error: The specified path to app directory <my_project_path>\app does not exist. Unable to find entry module.
    at verifyEntryModuleDirectory (<my_project_path>\node_modules\nativescript-dev-webpack\index.js:211:15)
    at Object.exports.getEntryModule (<my_project_path>\node_modules\nativescript-dev-webpack\index.js:77:5)

The path to the app directory should be <my_project_path>\src\app but tns looks for it in <my_project_path>\app 

When I run "tns doctor", I get a message saying
    Could not find folder: <my_project_path>\app

And that's because <my_project_path>\app does not exist.  It should be looking for <my_project_path>\src\app 

**To Reproduce**
1)  console>tns preview
2)  When QR code appears, scan it with the Nativescript Playground app on Android phone
3)  console shows "Preparing project..." and in a minute, error described above appears

**Expected behavior**
After scanning the QR code with the Nativescript Playground app, the project should build without errors

![TNS Preview Unable to find Entry Module](https://user-images.githubusercontent.com/17441709/77709268-bbc8f980-6f87-11ea-8230-ddce358c7b0f.JPG)

**Comment by NickIliev** [comment]
@reyldavid no issues here with a template project.  However I saw that you have a whitespace in the pathname - can you move your project so that the path does not contain whitespace and re-test your case.

**Comment by offline-pixel** [comment]
It goes same with me, and ran default commands

getting this after `tns preview`

Preparing project...
/home/path/project/node_modules/webpack-cli/bin/cli.js:93
                                throw err;
                                ^

Error: The specified path to app directory /home/path/project/app does not exist. Unable to find entry module.
    at verifyEntryModuleDirectory (/home/path/project/node_modules/@nativescript/webpack/index.js:220:15)
    at Object.exports.getEntryModule (/home/path/project/node_modules/@nativescript/webpack/index.js:77:5)
    at module.exports (/home/path/project/webpack.config.js:99:36)
    at handleFunction (/home/path/project/node_modules/webpack-cli/bin/utils/prepareOptions.js:21:13)
    at prepareOptions (/home/path/project/node_modules/webpack-cli/bin/utils/prepareOptions.js:9:5)
    at requireConfig (/home/path/project/node_modules/webpack-cli/bin/utils/convert-argv.js:117:14)
    at /home/path/project/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/path/project/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at /home/path/project/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/home/path/project/node_modules/yargs/yargs.js:576:18)
    at /home/path/project/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/path/project/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/path/project/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
