### ISSUE TITLE
Support for Node.js 14.4.0 is not verified. NativeScript CLI might not install or run properly.

### ISSUE THREAD

**Issue by Work90210** [NativeScript/nativescript-cli#5335]
**Environment**
Component nativescript has 6.7.6 version and is up to date.
✔ Component tns-core-modules has 6.5.8 version and is up to date.
✔ Component tns-android has 6.5.1 version and is up to date.
✔ Component tns-ios has 6.5.1 version and is up to date.

**Describe the bug**
I get an enormous amount of errors.
(node:8331) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/Applications/NativeScript Sidekick.app/Contents/Resources/node_modules/nativescript/node_modules/shelljs/src/common.js:419:12)
    at Object.<anonymous> (/Applications/NativeScript Sidekick.app/Contents/Resources/node_modules/nativescript/node_modules/shelljs/src/cat.js:4:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)

This is one of them. There are many like it.

**To Reproduce**
Open NativeScript sidekick. Errors will occur.

**Additional context**
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:8331) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/Applications/NativeScript Sidekick.app/Contents/Resources/node_modules/nativescript/node_modules/shelljs/src/common.js:419:12)
    at Object.<anonymous> (/Applications/NativeScript Sidekick.app/Contents/Resources/node_modules/nativescript/node_modules/shelljs/src/toEnd.js:5:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:8331) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/Applications/NativeScript Sidekick.app/Contents/Resources/node_modules/nativescript/node_modules/shelljs/src/common.js:419:12)
    at Object.<anonymous> (/Applications/NativeScript Sidekick.app/Contents/Resources/node_modules/nativescript/node_modules/shelljs/src/touch.js:4:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:8331) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/Applications/NativeScript Sidekick.app/Contents/Resources/node_modules/nativescript/node_modules/shelljs/src/co
[20-06-25 20:58:26.367] Support for Node.js 14.4.0 is not verified. NativeScript CLI might not install or run properly.
[20-06-25 20:58:26.369] (CLI) mmon.js:419:12)
    at Object.<anonymous> (/Applications/NativeScript Sidekick.app/Contents/Resources/node_modules/nativescript/node_modules/shelljs/src/uniq.js:13:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:8331) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/Applications/NativeScript Sidekick.app/Contents/Resources/node_modules/nativescript/node_modules/shelljs/src/common.js:419:12)
    at Object.<anonymous> (/Applications/NativeScript Sidekick.app/Contents/Resources/node_modules/nativescript/node_modules/shelljs/src/which.js:5:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)

**Comment by NathanWalker** [comment]
Thanks for report @Work90210 - can you `node -v` and `npm -v` and drop results here? also would be curious if you have node 14 (under 14.4) installed in nvm to confirm? We have confirmed node `14.3.0` here so could be a subtle change in 14.4.

**Comment by NathanWalker** [comment]
https://github.com/shelljs/shelljs/issues/991

**Comment by Work90210** [comment]
Hi @NathanWalker 

When i run `node -v` i get v14.4.0

And when i run `npm -v` i get 6.14.5

**Comment by NathanWalker** [comment]
@Work90210 confirmed that 14.4.0 with npm 6.14.5 works fine. 

```
nmacbook:samplets nathan$ node -v
v14.4.0
nmacbook:samplets nathan$ npm -v
6.14.5


✔ Getting NativeScript components versions information...
✔ Component nativescript has 6.7.6 version and is up to date.
✔ Component tns-core-modules has 6.5.8 version and is up to date.
✔ Component @nativescript/core has 6.5.8 version and is up to date.


nmacbook:tmp nathan$ tns create samplets --tsc
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

> fsevents@1.2.13 install /Users/nathan/Documents/github/NativeScript/masters/tmp/samplets/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> ejs@2.7.4 postinstall /Users/nathan/Documents/github/NativeScript/masters/tmp/samplets/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> @nativescript/core@6.5.8 postinstall /Users/nathan/Documents/github/NativeScript/masters/tmp/samplets/node_modules/@nativescript/core
> node cli-hooks/postinstall.js


> nativescript-dev-webpack@1.5.1 postinstall /Users/nathan/Documents/github/NativeScript/masters/tmp/samplets/node_modules/nativescript-dev-webpack
> node postinstall.js

Creating file: /Users/nathan/Documents/github/NativeScript/masters/tmp/samplets/webpack.config.js
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"14.4.0","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0

added 649 packages from 438 contributors and audited 649 packages in 24.577s

5 packages are looking for funding
  run `npm fund` for details

found 6 vulnerabilities (1 low, 5 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

Project samplets was successfully created.

Now you can navigate to your project with $ cd samplets

After that you can preview it on device by executing $ tns preview

nmacbook:tmp nathan$ cd samplets/
nmacbook:samplets nathan$ tns run ios --emulator
Searching for devices...
Copying template files...
Platform ios successfully added. v6.5.0
Preparing project...
File change detected. Starting incremental webpack compilation...
Starting type checking service...
Using 1 worker with 4096MB memory limit

webpack is watching the files…

Hash: 99dbf84cb9ef36c61bd7
Version: webpack 4.27.1
Time: 3497ms
Built at: 06/26/2020 11:20:08 PM
                                            Asset       Size                                          Chunks             Chunk Names
                                        bundle.js   27.9 KiB                                          bundle  [emitted]  bundle
                                     package.json  112 bytes                                                  [emitted]  
                                       runtime.js   71.4 KiB                                         runtime  [emitted]  runtime
tns_modules/tns-core-modules/inspector_modules.js  665 bytes  tns_modules/tns-core-modules/inspector_modules  [emitted]  tns_modules/tns-core-modules/inspector_modules
                                        vendor.js   6.05 MiB                                          vendor  [emitted]  vendor
Entrypoint bundle = runtime.js vendor.js bundle.js
Entrypoint tns_modules/tns-core-modules/inspector_modules = runtime.js vendor.js tns_modules/tns-core-modules/inspector_modules.js
[./ sync ^\.\/app\.(css|scss|less|sass)$] . sync nonrecursive ^\.\/app\.(css|scss|less|sass)$ 174 bytes {bundle} [built]
[./ sync recursive (?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|kt|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$] . sync (?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|kt|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$ 270 bytes {bundle} [built]
[./app-root.xml] 309 bytes {bundle} [optional] [built]
[./app.css] 1.84 KiB {bundle} [optional] [built]
[./app.ts] 1.94 KiB {bundle} [built]
[./main-page.ts] 1.35 KiB {bundle} [optional] [built]
[./main-page.xml] 1.87 KiB {bundle} [optional] [built]
[./main-view-model.ts] 1.46 KiB {bundle} [built]
[./package.json] 99 bytes {bundle} {tns_modules/tns-core-modules/inspector_modules} [optional] [built]
    + 339 hidden modules
Webpack compilation complete. Watching for file changes.
Webpack build done!
Installing pods...
Analyzing dependencies
Downloading dependencies
Installing MDFInternationalization (2.0.0)
Installing MaterialComponents (94.5.0)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `samplets.xcworkspace` for this project from now on.
Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.
Project successfully prepared (ios)
Building project...
Xcode build...
Project successfully built.
The build result is located at: /Users/nathan/Documents/github/NativeScript/masters/tmp/samplets/platforms/ios/build/Debug-iphonesimulator/samplets.app
Installing on device 39DAB286-3728-45B3-9BDA-2CCB60190F18...
Successfully installed on device with identifier '39DAB286-3728-45B3-9BDA-2CCB60190F18'.
Successfully transferred bundle.js on device 39DAB286-3728-45B3-9BDA-2CCB60190F18.
Successfully transferred package.json on device 39DAB286-3728-45B3-9BDA-2CCB60190F18.
Successfully transferred runtime.js on device 39DAB286-3728-45B3-9BDA-2CCB60190F18.
Successfully transferred tns_modules on device 39DAB286-3728-45B3-9BDA-2CCB60190F18.
Successfully transferred tns-core-modules on device 39DAB286-3728-45B3-9BDA-2CCB60190F18.
Successfully transferred inspector_modules.js on device 39DAB286-3728-45B3-9BDA-2CCB60190F18.
Successfully transferred vendor.js on device 39DAB286-3728-45B3-9BDA-2CCB60190F18.
Restarting application on device 39DAB286-3728-45B3-9BDA-2CCB60190F18...
(RunningBoardServices) [com.apple.runningboard:connection] Identity resolved as application<org.nativescript.samplets>
CONSOLE WARN file: node_modules/@nativescript/core/ui/tab-view/tab-view.ios.js:18:0: Objective-C class name "UITabBarControllerImpl" is already in use - using "UITabBarControllerImpl1" instead.
CONSOLE WARN file: node_modules/@nativescript/core/ui/tab-view/tab-view.ios.js:79:0: Objective-C class name "UITabBarControllerDelegateImpl" is already in use - using "UITabBarControllerDelegateImpl1" instead.
CONSOLE WARN file: node_modules/@nativescript/core/ui/tab-view/tab-view.ios.js:117:0: Objective-C class name "UINavigationControllerDelegateImpl" is already in use - using "UINavigationControllerDelegateImpl1" instead.
CONSOLE INFO file: node_modules/nativescript-dev-webpack/hot.js:3:0: HMR: Hot Module Replacement Enabled. Waiting for signal.
NativeScript debugger has opened inspector socket on port 18183 for org.nativescript.samplets.
Successfully synced application org.nativescript.samplets on device 39DAB286-3728-45B3-9BDA-2CCB60190F18.
CONSOLE LOG file: node_modules/@nativescript/core/inspector_modules.ios.js:1:0: Loading inspector modules...
CONSOLE LOG file: node_modules/@nativescript/core/inspector_modules.ios.js:6:0: Finished loading inspector modules.

```

You may try cleaning your global node installs or `npm uninstall nativescript -g`, then `npm install nativescript -g`

**Comment by NedlyJ** [comment]
Hello,

I am trying to run NPM on my Mac but it is having the same issue. I have followed all the steps to try and fix this, but when I install after un-insttalling, I get npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

And I cannot run the npm to local host. When I try using npm run, I get this;

npm run
Lifecycle scripts included in react-redux-router:
  preinstall
    npm set audit false
  start
    webpack-dev-server --config webpack/dev.config.js --watch

available via `npm run-script`:
  build
    cross-env NODE_ENV=production webpack --config webpack/prod.config.js --progress --display-error-details --color
  heroku-postbuild
    npm run build
  precommit
    eslint src
  prod
    NODE_ENV=production node server.js

Any idea why this is happening or how I can fix it?

**Comment by Work90210** [comment]
@NedlyJ 

Try delete node_modules. 
Then run `npm install`

**Comment by NedlyJ** [comment]
Whenever I run delete node_modules it tells me i cannot and I get this back
'

zsh: command not found: delete

**Comment by NedlyJ** [comment]
Whenever I run delete node_modules it tells me i cannot and I get this back '
zsh: command not found: delete

**Comment by NedlyJ** [comment]
I do apologize on my limited knowledge, still getting the hang of it. Thank
you
