### ISSUE TITLE
Support for Node.js 12.18.3 is not verified. NativeScript CLI might not install or run properly.

### ISSUE THREAD

**Issue by rexkwan** [NativeScript/nativescript-cli#5353]
Platform:  Windows 7
Node:  12.18.3 over nvm
NPM:  6.14.6

I follow the steps given in "NativeScript Advanced Setup: Windows" to install the nativescript.  When I run "tns doctor", it gives following error:

> Support for Node.js 12.18.3 is not verified. NativeScript CLI might not install
> or run properly.
> 
> ReferenceError: primordials is not defined
>     at fs.js:36:5
>     at req_ (C:\Programs\nvm\v12.18.0\node_modules\nativescript\node_modules\nat
> ives\index.js:137:5)
>     at Object.req [as require] (C:\Programs\nvm\v12.18.0\node_modules\nativescri
> pt\node_modules\natives\index.js:54:10)
>     at Object.<anonymous> (C:\Programs\nvm\v12.18.0\node_modules\nativescript\no
> de_modules\fstream\node_modules\graceful-fs\fs.js:1:37)
>     at Module._compile (internal/modules/cjs/loader.js:1137:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
>     at Module.load (internal/modules/cjs/loader.js:985:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
>     at Module.require (internal/modules/cjs/loader.js:1025:19)
>     at require (internal/modules/cjs/helpers.js:72:18)

I get no clue about the error.  Please help.

**Comment by rexkwan** [comment]
After uninstalled node.js and then re-installed nvm and NativeScript, the problem is solved.
