### ISSUE TITLE
tns preiview: Not working, unable to parse JSON 

### ISSUE THREAD

**Issue by suryaajha** [NativeScript/nativescript-cli#5357]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.7.0
 - Android Runtime: 6.5.0
 - iOS Runtime: 6.5.0

Even tried with the latest version with no luck

**Describe the bug**
I am newbie to Nativescript, I was going through follow me guide https://docs.nativescript.org/angular/start/cli-basics, everything went super smooth while running tns preview. I am getting the following error
```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at PreviewSdkService.<anonymous> (/home/suryaa/.nvm/versions/node/v12.18.0/lib/node_modules/nativescript/lib/services/livesync/playground/preview-sdk-service.js:100:43)
    at Generator.next (<anonymous>)
    at fulfilled (/home/suryaa/.nvm/versions/node/v12.18.0/lib/node_modules/nativescript/lib/services/livesync/playground/preview-sdk-service.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
I consoled out the JSON that we are getting on line number 100, but I'm shocked it is HTML and not JSON

**To Reproduce**
```
tns create HelloWorld --template tns-template-blank-ng
cd HelloWorld
tns preview
```

**Expected behavior**
I should be able to see preview in my Nativescript Android Preview App

**Sample project**
I am following https://docs.nativescript.org/angular/start/cli-basics

**Comment by suryaajha** [comment]
Sorry, the issue was already posted the day ago
