### ISSUE TITLE
Cli Installation fails when excecuting 'preuninstall.js'

### ISSUE THREAD

**Issue by PawFV** [NativeScript/nativescript-cli#5371]
- CLI: 7.0.6
- Windows 10 x64
- Node 12.18.3 / Tried Current and 10.
- Npm v6.14.6 / Tried clearing cache and reinstalling everything including node.

I'm trying to install the cli but can't get a work around.
**To Reproduce**
```
C:\Users\prego\AppData\Roaming\npm\ns -> C:\Users\prego\AppData\Roaming\npm\node_modules\nativescript\bin\tns
> nativescript@7.0.6 postinstall C:\Users\prego\AppData\Roaming\npm\node_modules\nativescript
> node postinstall.js
*Error: Illegal characters in path.*
    at pathArg (C:\Users\prego\AppData\Roaming\npm\node_modules\**nativescript\node_modules\mkdirp\lib\path-arg.js:20:27**)
    at Function.mkdirpSync [as sync] (C:\Users\prego\AppData\Roaming\npm\node_modules\nativescript\node_modules\mkdirp\index.js:18:10)
    at FileSystem.createDirectory (C:\Users\prego\AppData\Roaming\npm\node_modules\nativescript\lib\common\file-system.js:176:16)
    at new CancellationService (C:\Users\prego\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\cancellation.js:24:22)
    at Yok.resolveConstructor (C:\Users\prego\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:313:20)
    at Yok.resolveByName (C:\Users\prego\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:343:33)
    at Yok.resolve (C:\Users\prego\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:278:25)
    at C:\Users\prego\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:308:29
    at Array.map (<anonymous>)
    at Yok.resolveConstructor (C:\Users\prego\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:303:48)
```

I tested it with debugger and seems to fail parsing something like 'C:\Users\prego\AppData\Local\Temp\C:\Users\prego\KillSwitches' which is the received path arg at /path-arg.js

And right after this evaluation
```js
const badWinChars = /[*|"<>?:]/
    const {root} = parse(path)
    if (badWinChars.test(path.substr(root.length))
```
logs this error in console.
**(node:3216) [DEP0016] DeprecationWarning: 'root' is deprecated, use 'global'**

I didn't find anything related to this, just one issue with a similar error but tried everything and it didn't work.

**Comment by jamescodesthings** [comment]
Similar issues with postinstall failing for me.

Environment:
`
OSX
Node version: v13.6.0
NPM Version: 6.13.4
✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 7.0.6 and the latest available version is 7.0.7.
⚠ Update available for component @nativescript/core. Your current version is 7.0.0 and the latest available version is 7.0.2.
✔ Component @nativescript/ios has 7.0.0 version and is up to date.
✔ Component @nativescript/android has 7.0.0 version and is up to date.
`

I get error: `
> nativescript@7.0.6 postinstall /private/etc/builds/F-TZuVTi/0/engineius/app/engineius-mobile-app/node_modules/nativescript
> node postinstall.js
/private/etc/builds/F-TZuVTi/0/engineius/app/engineius-mobile-app/node_modules/nativescript/node_modules/uuid/dist/esm-browser/index.js:1
export { default as v1 } from './v1.js';
^^^^^^
SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1060:16)
    at Module._compile (internal/modules/cjs/loader.js:1108:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/private/etc/builds/F-TZuVTi/0/engineius/app/engineius-mobile-app/node_modules/nativescript/lib/common/helpers.js:13:16)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
`

This is my CI build. On my local box (also osx) if I throw it at node@latest (14.9.0) it seems to work.

Just a heads up for those facing similar issues.

**Comment by jdcaacbay-wp** [comment]
Hi! Currently having issues on this in circleCI. Anyone have a solution to fix this?
