### ISSUE TITLE
[IOS 14] App crash (NS6)

### ISSUE THREAD

**Issue by kefahB** [NativeScript/nativescript-cli#5397]
Hi,

I work on NS6 and trying to the solutions [here](https://github.com/NativeScript/NativeScript/issues/8665) by Nathanael and some body speak about accepting licence contract or dev profile, I have all done but the error still there.

It work as expected with IOS 11.3.

**Project successfully built.**
**The build result is located at: /Users/.../Sites/nativescript-project/lp/platforms/ios/build/Debug-iphonesimulator/lp.app**
```bash
Unable to apply changes on device: 81AE90E9-713B-4210-BCD4-211523E98265. Error is: ENOENT: no such file or directory, scandir '/Users/.../Library/Developer/CoreSimulator/Devices/81AE90E9-713B-4210-BCD4-211523E98265/data/Applications'.
Will emit event runOnDeviceError with data { projectDir: '/Users/.../Sites/nativescript-project/lp',
  deviceIdentifier: '81AE90E9-713B-4210-BCD4-211523E98265',
  applicationIdentifier: 'com.......',
  error:
   { Error: ENOENT: no such file or directory, scandir '/Users/.../Library/Developer/CoreSimulator/Devices/81AE90E9-713B-4210-BCD4-211523E98265/data/Applications'
       at Object.readdirSync (fs.js:786:3)
       at Object.getInstalledApplications (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/lib/iphone-simulator-common.js:18:31)
       at XCodeSimctlSimulator.getInstalledApplications (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/lib/iphone-simulator-xcode-simctl.js:65:23)
       at Object.args (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/lib/ios-sim.js:102:76)
       at IOSSimulatorApplicationManager.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/mobile/ios/simulator/ios-simulator-application-manager.js:37:32)
       at Generator.next (<anonymous>)
       at /usr/local/lib/node_modules/nativescript/lib/common/mobile/ios/simulator/ios-simulator-application-manager.js:13:71
       at new Promise (<anonymous>)
       at __awaiter (/usr/local/lib/node_modules/nativescript/lib/common/mobile/ios/simulator/ios-simulator-application-manager.js:9:12)
       at IOSSimulatorApplicationManager.getInstalledApplications (/usr/local/lib/node_modules/nativescript/lib/common/mobile/ios/simulator/ios-simulator-application-manager.js:36:16)
       at IOSSimulatorApplicationManager.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/mobile/application-manager-base.js:55:77)
       at Generator.next (<anonymous>)
       at /usr/local/lib/node_modules/nativescript/lib/common/mobile/application-manager-base.js:7:71
       at new Promise (<anonymous>)
       at __awaiter (/usr/local/lib/node_modules/nativescript/lib/common/mobile/application-manager-base.js:3:12)
       at checkForApplicationUpdatesPromise.Promise (/usr/local/lib/node_modules/nativescript/lib/common/mobile/application-manager-base.js:52:91)
     errno: -2,
     syscall: 'scandir',
     code: 'ENOENT',
     path:
      '/Users/.../Library/Developer/CoreSimulator/Devices/81AE90E9-713B-4210-BCD4-211523E98265/data/Applications' } }
```

**Comment by kefahB** [comment]
Hi @NathanWalker,

What do you think about this ?

**Comment by JakeAi** [comment]
@NathanWalker @kefahB same issue with me.

**Comment by kefahB** [comment]
Hi @JakeAi,

I found the solution, you need to create `Applications` folder and this will done ;)
```bash
mkdir /Users/YOUR_USER_NAME/Library/Developer/CoreSimulator/Devices/81AE90E9-713B-4210-BCD4-211523E98265/data/Applications
```
