### ISSUE TITLE
Crashing after multiple changes

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/nativescript-cli#5403]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:  7.0.0
 - Cross-platform modules: -
 - Android Runtime: -
 - iOS Runtime: -
 - Plugin(s): -

**Describe the bug**
I am running my apps with `--no-hmr`
after multiple file changes i end up with a crash:
```
RuntimeError: memory access out of bounds
    at wasm-function[18]:0xf76
    at wasm-function[28]:0x3494
    at BasicSourceMapConsumer._parseMappings (/usr/local/pnpm-global/4/node_modules/.pnpm/source-map@0.7.3/node_modules/source-map/lib/source-map-consumer.js:335:44)
    at BasicSourceMapConsumer._getMappingsPtr (/usr/local/pnpm-global/4/node_modules/.pnpm/source-map@0.7.3/node_modules/source-map/lib/source-map-consumer.js:315:12)
    at /usr/local/pnpm-global/4/node_modules/.pnpm/source-map@0.7.3/node_modules/source-map/lib/source-map-consumer.js:510:14
    at Object.withMappingCallback (/usr/local/pnpm-global/4/node_modules/.pnpm/source-map@0.7.3/node_modules/source-map/lib/wasm.js:95:11)
    at BasicSourceMapConsumer.originalPositionFor (/usr/local/pnpm-global/4/node_modules/.pnpm/source-map@0.7.3/node_modules/source-map/lib/source-map-consumer.js:508:16)
    at LogSourceMapService.getOriginalFileLocation (/usr/local/pnpm-global/4/node_modules/.pnpm/nativescript@7.0.8/node_modules/nativescript/lib/services/log-source-map-service.js:116:46)
    at /usr/local/pnpm-global/4/node_modules/.pnpm/nativescript@7.0.8/node_modules/nativescript/lib/services/log-source-map-service.js:72:43
    at Array.forEach (<anonymous>)
```
This happens with or without source maps

**Comment by nkishor-nsf** [comment]
I am also facing the same issue like

Error: Error parsing mappings (code 1): the mappings contained a negative line, column, source index, or name index
    at BasicSourceMapConsumer._parseMappings (/usr/local/lib/node_modules/nativescript/node_modules/source-map/lib/source-map-consumer.js:360:13)
    at BasicSourceMapConsumer._getMappingsPtr (/usr/local/lib/node_modules/nativescript/node_modules/source-map/lib/source-map-consumer.js:315:12)
    at /usr/local/lib/node_modules/nativescript/node_modules/source-map/lib/source-map-consumer.js:510:14
    at Object.withMappingCallback (/usr/local/lib/node_modules/nativescript/node_modules/source-map/lib/wasm.js:95:11)
    at BasicSourceMapConsumer.originalPositionFor (/usr/local/lib/node_modules/nativescript/node_modules/source-map/lib/source-map-consumer.js:508:16)
    at LogSourceMapService.getOriginalFileLocation (/usr/local/lib/node_modules/nativescript/lib/services/log-source-map-service.js:123:46)
    at /usr/local/lib/node_modules/nativescript/lib/services/log-source-map-service.js:79:43
    at Array.forEach (<anonymous>)
    at LogSourceMapService.replaceWithOriginalFileLocations (/usr/local/lib/node_modules/nativescript/lib/services/log-source-map-service.js:77:15)
    at DeviceLogProvider.logData (/usr/local/lib/node_modules/nativescript/lib/common/mobile/device-log-provider.js:18:42)
