### ISSUE TITLE
Can't create using template 'tns-template-drawer-navigation-ts' with NS7 (v 7.0.10)

### ISSUE THREAD

**Issue by Daven005** [NativeScript/nativescript-cli#5435]
Crashes with:
`You are using the deprecated nsconfig.json file. Just be aware that NativeScript 7 has an improved nativescript.config.(js|ts) file for when you're ready to upgrade this project.
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.join (path.js:432:7)
    at ProjectConfigService.fallbackToLegacyNSConfig (C:\Program Files\nodejs\node_modules\nativescript\lib\services\project-config-service.js:207:52)
    at ProjectConfigService.readConfig (C:\Program Files\nodejs\node_modules\nativescript\lib\services\project-config-service.js:103:25)
    at ProjectData.initializeProjectDataFromContent (C:\Program Files\nodejs\node_modules\nativescript\lib\project-data.js:57:45)
    at ProjectData.initializeProjectData (C:\Program Files\nodejs\node_modules\nativescript\lib\project-data.js:47:22)
    at ProjectDataService.getProjectData (C:\Program Files\nodejs\node_modules\nativescript\lib\services\project-data-service.js:76:43)
    at ProjectService.<anonymous> (C:\Program Files\nodejs\node_modules\nativescript\lib\services\project-service.js:140:70)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\nodejs\node_modules\nativescript\lib\services\project-service.js:11:58)`

Is it related to the 'deprecated nsconfig.json file' message. If so where do I amend it? Otherwise do I haave to revert to NS6?

**Comment by rigor789** [comment]
Use the updated [`@nativescript/template-drawer-navigation-ts`](https://www.npmjs.com/package/@nativescript/template-drawer-navigation-ts) template for ns7

**Comment by Daven005** [comment]
Thanks
