### ISSUE TITLE
install from git - run bin/tns not working

### ISSUE THREAD

**Issue by ggros** [NativeScript/nativescript-cli#5436]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.0.11
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - XCode Version:
 - Plugin(s):

**Describe the bug**

unable to run the tool from another directory than local bin.

```
~/source/nativescript-cli$ ./bin/tns
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module '/home/ggros/source/nativescript-cli/lib/common/verify-node-version'
Require stack:
- /home/ggros/source/nativescript-cli/bin/tns
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ggros/source/nativescript-cli/bin/tns:8:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/ggros/source/nativescript-cli/bin/tns' ]
}
```

**To Reproduce**

like explained in the readme
git clone
npm run setup
./bin/tns -v

**Expected behavior**
```
./bin/tns -v
7.0.11
```
**Sample project**

**Additional context**

**Comment by ggros** [comment]
run setup, doesn't run the build....
`npm run build`
