### ISSUE TITLE
System.err: TypeError: Cannot read property 'setAttribute' of undefined

### ISSUE THREAD

**Issue by lundtropic** [NativeScript/nativescript-cli#5503]
**Environment**
```
{
  ...
  "dependencies": {
    "@nativescript/theme": "^3.0.0",
    "@nstudio/nativescript-loading-indicator": "^4.0.0",
    "@nstudio/nativescript-pulltorefresh": "^3.0.0",
    "axios": "^0.21.0",
    "lodash": "^4.17.15",
    "moment": "^2.29.0",
    "nativescript-animate-sass": "0.0.2",
    "nativescript-feedback": "^2.0.0",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-orientation": "^2.2.1",
    "nativescript-statusbar": "^5.0.0",
    "nativescript-ui-chart": "^8.0.0",
    "nativescript-ui-sidedrawer": "^9.0.0",
    "nativescript-vue": "^2.8.0",
    "vue-axios": "^3.2.0",
    "vuex": "^3.6.0",
    "@nativescript/core": "^7.2.0",
    "@nativescript/webpack": "3.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.13.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/preset-env": "^7.8.0",
    "@babel/traverse": "^7.13.0",
    "@babel/types": "^7.13.0",
    "@nativescript/android": "7.0.1",
    "@nativescript/ios": "7.2.0",
    "babel-loader": "^8.2.0",
    "babylon": "6.18.0",
    "css-hot-loader": "^1.4.2",
    "lazy": "^1.0.0",
    "mini-css-extract-plugin": "^1.3.0",
    "nativescript-vue-template-compiler": "^2.8.0",
    "node-sass": "^4.14.0",
    "uglifyjs-webpack-plugin": "^2.2.0",
    "vue-loader": "^15.9.0"
  },
  "main": "main"
}
```

```
✔ Getting NativeScript components versions information...
✔ Component nativescript has 7.2.0 version and is up to date.
✔ Component @nativescript/core has 7.2.1 version and is up to date.
✔ Component @nativescript/ios has 7.2.0 version and is up to date.
✔ Component @nativescript/android has 7.0.1 version and is up to date.
```

**Describe the bug**
Nativescript-Vue application. Upgrading from Nativescript 6 to Nativescript 7. Took the following actions:
- Upgraded to Nativescript 7 globally
- Ran `ns migrate`
- Updated other dependencies (eg. `nativescript-ui-chart`)
- Updated all references to `tns-core-modules` to imports of `@nativescript/core`
- Updated all imports of `util/util` to `@nativescript/core`
- Added `node: { net: 'empty' }` to `webpack.config.js`
- - Was getting an error at build time and this fixed it.
- `ns clean`
- `ns doctor` (no issues)

I run the app using `ns run android --bundle` and receive this error at run time:

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to start activity ComponentInfo{com.cometads.cometadstracker/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: TypeError: Cannot read property 'setAttribute' of undefined
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cometads.cometadstracker/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: TypeError: Cannot read property 'setAttribute' of undefined
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
System.err: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
System.err: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:107)
System.err: 	at android.os.Looper.loop(Looper.java:214)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: TypeError: Cannot read property 'setAttribute' of undefined
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err: 	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:29)
System.err: 	at android.app.Activity.performCreate(Activity.java:7802)
System.err: 	at android.app.Activity.performCreate(Activity.java:7791)
System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
System.err: 	... 11 more
```

*Edit*

I ran the app for ios using `ns run ios --bundle` and receive this similar error during run time:

```
***** Fatal JavaScript exception - application has been terminated. *****
NativeScript encountered a fatal error: Uncaught TypeError: Cannot read property 'setAttribute' of undefined
at
updateAttrs(file: node_modules/nativescript-vue/dist/index.js:6050:10)
at invokeCreateHooks(file: node_modules/nativescript-vue/dist/index.js:5410:22)
at createElm(file: node_modules/nativescript-vue/dist/index.js:5297:10)
at createChildren(file: node_modules/nativescript-vue/dist/index.js:5394:8)
at createElm(file: node_modules/nativescript-vue/dist/index.js:5295:8)
at patch(file: node_modules/nativescript-vue/dist/index.js:5818:6)
at Vue._update(file: node_modules/nativescript-vue/dist/index.js:4830:18)
at updateComponent(file: node_modules/nativescript-vue/dist/index.js:4951:9)
at get(file: node_modules/nativescript-vue/dist/index.js:2336:24)
at Watcher(file: node_modules/nativescript-vue/dist/index.js:2325:11)
at mountComponent(file: node_modules/nativescript-vue/dist/index.js:4958:2)
at push.../node_modules/nativescript-vue/dist/index.js.Vue.$mount(file: node_modules/nativescript-vue/dist/index.js:12536:9)
at init(file: node_modules/nativescript-vue/dist/index.js:4005:12)
at createComponent(file: node_modules/nativescript-vue/dist/index.js:5319:9)
at createElm(file: node_modules/nativescript-vue/dist/index.js:5266:8)
at patch(file: node_modules/nativescript-vue/dist/index.js:5818:6)
at Vue._update(file: node_modules/nativescript-vue/dist/index.js:4830:18)
at updateComponent(file:///app/vendor.js:11<…>
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Uncaught TypeError: Cannot read property 'setAttribute' of undefined
at
updateAttrs(file: node_modules/nativescript-vue/dist/index.js:6050:10)
at invokeCreateHooks(file: node_modules/nativescript-vue/dist/index.js:5410:22)
at createElm(file: node_modules/nativescript-vue/dist/index.js:5297:10)
at createChildren(file: node_modules/nativescript-vue/dist/index.js:5394:8)
at createElm(file: node_modules/nativescript-vue/dist/index.js:5295:8)
at patch(file: node_modules/nativescript-vue/dist/index.js:5818:6)
at Vue._update(file: node_modules/nativescript-vue/dist/index.js:4830:18)
at updateComponent(file: node_modules/nativescript-vue/dist/index.js:4951:9)
at get(file: node_modules/nativescript-vue/dist/index.js:2336:24)
at Watcher(file: node_modules/nativescript-vue/dist/index.js:2325:11)
at mountComponent(file: node_modules/nativescript-vue/dist/index.js:4958:2)
at push.../node_modules/nativescript-vue/dist/index.js.Vue.$mount(file: node_modules/nativescript-vue/dist/index.js:12536:9)
at init(file: node_modules/nativescript-vue/dist/index.js:4005:12)
at createComponent(file: node_modules/nativescript-vue/dist/index.js:5319:9)
at createElm(file: node_modules/nativescript-vue/dist/index.js:5266:8)
at patch(file: node_modules/nativescript-vue/dist/index.js:5818:6)
at Vue._update(file: node_modules/nativescript-vue/dist/index.js:4830:6<…>
```

In contrast to Android, the app crashes instead of elegantly displaying the error.

**To Reproduce**
`ns run adroind --bundle`

**Expected behavior**
For the app to build and run correctly as it did under NativeScript 6 and below.

**Additional context**
Happy to provide additional code snippets if helpful.

**Comment by lundtropic** [comment]
Issue caused by an outdated NativeScript plugin.
