### ISSUE TITLE
Project creation fails [NS 8.0.2]

### ISSUE THREAD

**Issue by Universi** [NativeScript/nativescript-cli#5531]
**Environment**
 - CLI: 8.0.2

```
$ tns doctor 
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 12.4.0 satisfies minimum required version 10.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 8.0.2 version and is up to date.
```

**Describe the bug**
```
(node:65010) ExperimentalWarning: The fs.promises API is experimental

> @nativescript/core@8.0.6 postinstall /Users/christophegarreau/Projects/NS/MiniPaints5/minipaints5/node_modules/@nativescript/core
> node cli-hooks/postinstall.js

/Users/christophegarreau/Projects/NS/MiniPaints5/minipaints5/node_modules/mkdirp/lib/mkdirp-manual.js:54
      throw er
      ^

Error: EACCES: permission denied, mkdir '/Users/christophegarreau/Projects/NS/MiniPaints5/minipaints5/hooks/before-checkForChanges'
    at Object.mkdirSync (fs.js:757:3)
    at mkdirpManualSync (/Users/christophegarreau/Projects/NS/MiniPaints5/minipaints5/node_modules/mkdirp/lib/mkdirp-manual.js:48:10)
    at mkdirpNativeSync (/Users/christophegarreau/Projects/NS/MiniPaints5/minipaints5/node_modules/mkdirp/lib/mkdirp-native.js:33:14)
    at Function.mkdirpSync [as sync] (/Users/christophegarreau/Projects/NS/MiniPaints5/minipaints5/node_modules/mkdirp/index.js:21:7)
    at /Users/christophegarreau/Projects/NS/MiniPaints5/minipaints5/node_modules/@nativescript/hook/index.js:94:14
    at /Users/christophegarreau/Projects/NS/MiniPaints5/minipaints5/node_modules/@nativescript/hook/index.js:78:7
    at Array.forEach (<anonymous>)
    at forEachHook (/Users/christophegarreau/Projects/NS/MiniPaints5/minipaints5/node_modules/@nativescript/hook/index.js:77:14)
    at postinstall (/Users/christophegarreau/Projects/NS/MiniPaints5/minipaints5/node_modules/@nativescript/hook/index.js:91:3)
    at Object.postinstall (/Users/christophegarreau/Projects/NS/MiniPaints5/minipaints5/node_modules/@nativescript/hook/index.js:7:14)
npm WARN @nativescript/webpack@5.0.0-beta.10 requires a peer of nativescript-vue-template-compiler@^2.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of @types/webpack@4.x but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of react-refresh@>=0.8.3 <0.10.0 but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of sockjs-client@^1.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of type-fest@^0.13.1 but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of webpack-dev-server@3.x but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of webpack-hot-middleware@2.x but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of webpack-plugin-serve@0.x || 1.x but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@11.0.1 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@11.0.1 requires a peer of node-sass@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.5 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.5 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nativescript/core@8.0.6 postinstall: `node cli-hooks/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @nativescript/core@8.0.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/christophegarreau/.npm/_logs/2021-05-24T18_37_24_212Z-debug.log
Command npm failed with exit code 1
```

**To Reproduce**
`sudo ns create minipaints5 --template @nativescript/template-blank-ts`

**Expected behavior**
Project creation (I have created NativeScript projects with NS 3, 4, 5 and 6, without ever having encountered this type of obstacle before).

**Comment by rigor789** [comment]
```
Error: EACCES: permission denied
```
Resolve filesystem issues - nothing the CLI or we can fix in this case. You should not need to run `sudo` for any of the NS commands unless your system permissions are really messed up.

**Comment by Universi** [comment]
@rigor789 So, the question is: why does `tns doctor` say "No issues were detected", when it is not able to create a project on my system (and when I think I respected the Setup Environment according to the NS 8 documentation)?

Under these conditions, I could create projects with NS 6 and previous, without this kind of issue.
Where does this sudden file system problem come from now?
Should I reinstall Node.js?

**Comment by Universi** [comment]
I resolved the filesystem permission, but why project creation gives all this WARNINGS:

```
# Let’s create a NativeScript app!

Answer the following questions to help us build the right app for you. (Note: you
can skip this prompt next time using the --template option, or the --ng, --react, --vue, --svelte, --ts, or --js flags.)

✔ First, which style of NativeScript project would you like to use: › Plain TypeScript

✔ Next, which template would you like to start from: › Hello World

> @nativescript/core@8.0.6 postinstall /Users/christophegarreau/Projects/NS/MiniPaints5/test2/node_modules/@nativescript/core
> node cli-hooks/postinstall.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @nativescript/webpack@5.0.0-beta.10 requires a peer of nativescript-vue-template-compiler@^2.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of @types/webpack@4.x but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of react-refresh@>=0.8.3 <0.10.0 but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of sockjs-client@^1.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of type-fest@^0.13.1 but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of webpack-dev-server@3.x but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of webpack-hot-middleware@2.x but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of webpack-plugin-serve@0.x || 1.x but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@11.0.1 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@11.0.1 requires a peer of node-sass@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.5 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.5 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

added 393 packages from 275 contributors and audited 393 packages in 11.652s
found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
[@nativescript/webpack] Initialized config.

Project test2 was successfully created.
```

while each missing peer dependency can't be installed:

```
$ npm install nativescript-vue-template-compiler@^2.8.1
npm ERR! code ETARGET
npm ERR! notarget No matching version found for testProject@0.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by Universi** [comment]
I resolved the filesystem issue, but the project creation gives ma all this warnings:

```
ns create test5

# Let’s create a NativeScript app!

Answer the following questions to help us build the right app for you. (Note: you
can skip this prompt next time using the --template option, or the --ng, --react, --vue, --svelte, --ts, or --js flags.)

✔ First, which style of NativeScript project would you like to use: › Plain TypeScript

✔ Next, which template would you like to start from: › Hello World

> @nativescript/core@8.0.6 postinstall /Users/christophegarreau/Projects/NS/MiniPaints5/test5/node_modules/@nativescript/core
> node cli-hooks/postinstall.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @nativescript/webpack@5.0.0-beta.10 requires a peer of nativescript-vue-template-compiler@^2.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of @types/webpack@4.x but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of react-refresh@>=0.8.3 <0.10.0 but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of sockjs-client@^1.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of type-fest@^0.13.1 but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of webpack-dev-server@3.x but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of webpack-hot-middleware@2.x but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of webpack-plugin-serve@0.x || 1.x but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@11.0.1 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@11.0.1 requires a peer of node-sass@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.5 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.5 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

added 393 packages from 275 contributors and audited 393 packages in 11.5s
found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
[@nativescript/webpack] Initialized config.

Project test5 was successfully created.
```

**Comment by rigor789** [comment]
Those warnings are fine to ignore, they come from npm, and some are related to `@nativescript/webpack` (it includes plugins for multiple flavors of NS like angular, react, vue etc. - and some peer dependencies are "missing" - but in reality they are just not required for some flavors... we are trying to come up with a neater solution to these dependencies during the webpack beta) - but the project has been created successfully, and should work fine.

**Comment by Universi** [comment]
Thank you so much for the quick response and sorry for my worries.
I'm preparing to migrate an NS6 application (present on the App Store and Google play) and I'm testing NS8 to make sure everything will be fine. I intend to rebuild the project little by little.
