### ISSUE TITLE
Facing issue While Running Nativescript project- Error: Cannot find connected devices.

### ISSUE THREAD

**Issue by harshal-khot08** [NativeScript/nativescript-cli#5543]
tns run android --log trace

* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
*                                                                                                                                               *
*  The "TRACE" log level might print some sensitive data like secrets or access tokens in request URLs. Be careful when you share this output.  *
*                                                                                                                                               *
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

Looking for project in 'E:\Android_app\digital-card'
Project directory is 'E:\Android_app\digital-card'.
Initializing project identifiers. Config:  {
  id: 'org.nativescript.digitalcard',
  appPath: 'src',
  appResourcesPath: 'App_Resources',
  android: { v8Flags: '--expose_gc', markingMode: 'none' }
}
Loading extensions.
Collecting system information...
System information:
{
  "platform": "win32",
  "shell": "C:\\Windows\\system32\\cmd.exe",
  "os": "Windows 10 Home Single Language 6.3.19041",
  "procArch": "x64",
  "nodeVer": "14.17.1",
  "npmVer": "6.14.13",
  "nodeGypVer": null,
  "nativeScriptCliVersion": "8.0.2",
  "gitVer": null,
  "dotNetVer": "4.8.04084",
  "javacVersion": "1.8.0_192",
  "javaVersion": "1.8.0_192",
  "javaPath": "C:\\Program Files\\AdoptOpenJDK\\jdk8u192-b12\\bin\\java.exe",
  "adbVer": "1.0.41",
  "androidInstalled": true,
  "monoVer": null,
  "gradleVer": null,
  "isAndroidSdkConfiguredCorrectly": true,
  "xcodeprojLocation": null,
  "itunesInstalled": false,
  "isCocoaPodsWorkingCorrectly": false,
  "isCocoaPodsUpdateRequired": false,
  "pythonInfo": null
}
Current CLI version:  8.0.2
Project dir from hooksArgs is: undefined.
Hooks directories: [ 'E:\\Android_app\\digital-card\\hooks' ]
BeforeHookName for command resolveCommand is before-resolveCommand
Project dir from hooksArgs is: undefined.
Hooks directories: [ 'E:\\Android_app\\digital-card\\hooks' ]
AfterHookName for command resolveCommand is after-resolveCommand
Starting watch on killswitch C:\Users\Harshal\AppData\Local\Temp\Harshal\KillSwitches\cli
Migration cache path is: C:\Users\Harshal\AppData\Roaming\.nativescript-cli\should-migrate-cache-8.0.2.json
Trying to handle SIGINT event. CLI overrides this behavior and does not allow handling SIGINT as this causes issues with Ctrl + C in terminal.
The stackTrace of the location trying to handle SIGINT is:
    at process.on (C:\Users\Harshal\AppData\Roaming\npm\node_modules\nativescript\lib\nativescript-cli.js:26:28)
    at C:\Users\Harshal\AppData\Roaming\npm\node_modules\nativescript\node_modules\signal-exit\index.js:128:15
    at Array.filter (<anonymous>)
    at load (C:\Users\Harshal\AppData\Roaming\npm\node_modules\nativescript\node_modules\signal-exit\index.js:126:21)
    at module.exports (C:\Users\Harshal\AppData\Roaming\npm\node_modules\nativescript\node_modules\signal-exit\index.js:36:5)
    at Object.<anonymous> (C:\Users\Harshal\AppData\Roaming\npm\node_modules\nativescript\node_modules\proper-lockfile\lib\lockfile.js:331:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
spawn: C:\Program Files\nodejs\node.exe "C:\Users\Harshal\AppData\Roaming\npm\node_modules\nativescript\lib\detached-processes\cleanup-process.js" "C:\Users\Harshal\AppData\Roaming\npm\node_modules\nativescript\lib\bootstrap.js"
Shasum of file E:\Android_app\digital-card\package.json is f9d2d0577c83e3d6e69835ea430b0777670fd402
Got cached result for shouldMigrate for platform: Android: false
Could not find an installed runtime, falling back to default runtimes
Could not find an installed runtime, falling back to default runtimes
Project dir from hooksArgs is: E:\Android_app\digital-card.
Hooks directories: [ 'E:\\Android_app\\digital-card\\hooks' ]
BeforeHookName for command checkEnvironment is before-checkEnvironment
Initializing analytics statuses.
Analytics statuses:  { TrackFeatureUsage: 'disabled', TrackExceptions: 'disabled' }
getInfos cacheConfig options: { forceCheck: undefined }  current info from cache:  [
  {
    message: 'Your ANDROID_HOME environment variable is set and points to correct directory.',
    platforms: [ 'Android' ],
    type: 'info'
  },
  {
    message: 'Your adb from the Android SDK is correctly installed.',
    platforms: [ 'Android' ],
    type: 'info'
  },
  {
    message: 'The Android SDK is installed.',
    platforms: [ 'Android' ],
    type: 'info'
  },
  {
    message: 'A compatible Android SDK for compilation is found.',
    platforms: [ 'Android' ],
    type: 'info'
  },
  {
    message: 'Javac is installed and is configured properly.',
    platforms: [ 'Android' ],
    type: 'info'
  },
  {
    message: 'The Java Development Kit (JDK) is installed and is configured properly.',
    platforms: [ 'Android' ],
    type: 'info'
  },
  {
    message: 'Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.',
    additionalInformation: '',
    platforms: [ 'iOS' ],
    type: 'info'
  }
]
Your ANDROID_HOME environment variable is set and points to correct directory.
Your adb from the Android SDK is correctly installed.
The Android SDK is installed.
A compatible Android SDK for compilation is found.
Javac is installed and is configured properly.
The Java Development Kit (JDK) is installed and is configured properly.
Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
Project dir from hooksArgs is: E:\Android_app\digital-card.
Hooks directories: [ 'E:\\Android_app\\digital-card\\hooks' ]
AfterHookName for command checkEnvironment is after-checkEnvironment
Selected targetSdk is: 30
Installed Android Targets are:  [ 'android-28', 'android-30' ]
Selected buildToolsVersion is: 30.0.3
Could not find an installed runtime, falling back to default runtimes
Validate options for platform: Android
Could not find an installed runtime, falling back to default runtimes
Searching for devices...
startLookingForDevices; platform is Android
Options for ios-device-discovery {
  platform: 'Android',
  shouldReturnImmediateResult: false,
  emulator: false,
  fullDiscovery: undefined
}
spawn: C:\Android\android-sdk\platform-tools\adb "start-server"
Result when throw error is false:
{ stdout: '', stderr: '', exitCode: 0 }
spawn: C:\Android\android-sdk\platform-tools\adb "devices"
spawn: C:\Android\android-sdk\platform-tools\adb "devices"
spawn: C:\Android\android-sdk\tools\bin\avdmanager.bat "list" "avds"
Error while trying to get InstallDir property for \Software\Oracle\VirtualBox. More info: ProcessUncleanExitError: QUERY command exited with code 1:

ERROR: The system was unable to find the specified registry key or value..
spawn: player 0
Configuration error for Genymotion { stdout: '', stderr: 'spawn player ENOENT', exitCode: 'ENOENT' }
No emulator image available for device identifier 'undefined'.
Cannot find connected devices.
Emulator start failed with: No emulator image available for device identifier 'undefined'.
To list currently connected devices and verify that the specified identifier exists, run 'tns device'.
To list available emulator images, run 'tns device <Platform> --available-devices'.
Error while initializing devicesService: Exception: Cannot find connected devices.
Emulator start failed with: No emulator image available for device identifier 'undefined'.
To list currently connected devices and verify that the specified identifier exists, run 'tns device'.
To list available emulator images, run 'tns device <Platform> --available-devices'.
Error: Cannot find connected devices.
Emulator start failed with: No emulator image available for device identifier 'undefined'.
To list currently connected devices and verify that the specified identifier exists, run 'tns device'.
To list available emulator images, run 'tns device <Platform> --available-devices'.
    at Errors.failWithOptions (C:\Users\Harshal\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:157:27)
    at Errors.fail (C:\Users\Harshal\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:130:21)
    at DevicesService.<anonymous> (C:\Users\Harshal\AppData\Roaming\npm\node_modules\nativescript\lib\common\mobile\mobile-core\devices-service.js:510:34)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Harshal\AppData\Roaming\npm\node_modules\nativescript\lib\common\mobile\mobile-core\devices-service.js:12:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by rigor789** [comment]
Do you have an emulator created inside Android Studio? Open it, and there's an "AVD Manager" where you can create one if necessary.

**Comment by janoshrubos** [comment]
Closing this issue due to inactivity. 
If this error is still relevant, feel free to open a new issue!
