### ISSUE TITLE
Error: Cannot find module 'webpack/lib/rules/DescriptionDataMatcherRulePlugin'

### ISSUE THREAD

**Issue by maziac** [NativeScript/nativescript-cli#5556]
tns info
✔ Component nativescript has 8.0.2 version and is up to date.
✔ Component @nativescript/core has 8.0.8 version and is up to date.
✔ Component @nativescript/ios has 8.0.0 version and is up to date.
✖ Component @nativescript/android is not installed.
 - XCode Version: 12.5.1
 - macOS: 11.4

**Describe the bug**
I followed the examples and successfully created an app  with 
~~~
tns create HelloWorld --template @nativescript/template-hello-world-ts
~~~

Then I tried to build it but get an error for web pack:
~~~
tns build ios
tns build ios
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

added 393 packages, and audited 394 packages in 13s

39 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Copying template files...
Platform ios successfully added. v8.0.0
Preparing project...
Error: Cannot find module 'webpack/lib/rules/DescriptionDataMatcherRulePlugin'
Require stack:
- /Volumes/SDDPCIE2TB/Projects/NativeScript/HelloWorld/node_modules/vue-loader/lib/plugin-webpack5.js
- /Volumes/SDDPCIE2TB/Projects/NativeScript/HelloWorld/node_modules/vue-loader/lib/plugin.js
- /Volumes/SDDPCIE2TB/Projects/NativeScript/HelloWorld/node_modules/vue-loader/lib/index.js
- /Volumes/SDDPCIE2TB/Projects/NativeScript/HelloWorld/node_modules/@nativescript/webpack/dist/configuration/vue.js
- /Volumes/SDDPCIE2TB/Projects/NativeScript/HelloWorld/node_modules/@nativescript/webpack/dist/configuration/index.js
- /Volumes/SDDPCIE2TB/Projects/NativeScript/HelloWorld/node_modules/@nativescript/webpack/dist/index.js
- /Volumes/SDDPCIE2TB/Projects/NativeScript/HelloWorld/webpack.config.js
- /Volumes/SDDPCIE2TB/Projects/NativeScript/HelloWorld/node_modules/@nativescript/webpack/dist/bin/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Volumes/SDDPCIE2TB/Projects/NativeScript/HelloWorld/node_modules/vue-loader/lib/plugin-webpack5.js:6:42)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Volumes/SDDPCIE2TB/Projects/NativeScript/HelloWorld/node_modules/vue-loader/lib/plugin-webpack5.js',
    '/Volumes/SDDPCIE2TB/Projects/NativeScript/HelloWorld/node_modules/vue-loader/lib/plugin.js',
    '/Volumes/SDDPCIE2TB/Projects/NativeScript/HelloWorld/node_modules/vue-loader/lib/index.js',
    '/Volumes/SDDPCIE2TB/Projects/NativeScript/HelloWorld/node_modules/@nativescript/webpack/dist/configuration/vue.js',
    '/Volumes/SDDPCIE2TB/Projects/NativeScript/HelloWorld/node_modules/@nativescript/webpack/dist/configuration/index.js',
    '/Volumes/SDDPCIE2TB/Projects/NativeScript/HelloWorld/node_modules/@nativescript/webpack/dist/index.js',
    '/Volumes/SDDPCIE2TB/Projects/NativeScript/HelloWorld/webpack.config.js',
    '/Volumes/SDDPCIE2TB/Projects/NativeScript/HelloWorld/node_modules/@nativescript/webpack/dist/bin/index.js'
  ]
}
No configuration!

~~~

**To Reproduce**
~~~
tns clean    
tns build ios
~~~

**Expected behavior**
No error

**Sample project**
~~~
tns create HelloWorld --template @nativescript/template-hello-world-ts
~~~

**Additional context**

**Comment by janoshrubos** [comment]
Could you please post your `package.json` and your `webpack.config.js` file?

**Comment by maziac** [comment]
Here they are:
[Archiv.zip](https://github.com/NativeScript/nativescript-cli/files/7122902/Archiv.zip)

**Comment by Fadarrizz** [comment]
Updating `nativescript-vue` to ^2.9.0 helped for me

**Comment by maziac** [comment]
Thanks very much that took me a step further.
I added 
~~~
"dependencies": {
	...
    "nativescript-vue": "^2.9.0"
  },
~~~

and I also had to add:
~~~
npm i nativescript-vue-template-compiler
~~~

The program is building now without errors.

However I still cannot run it in the iOS simulator.
It is missing app-root:
~~~
bob@macmini HelloWorld % tns run ios                             
Searching for devices...
Preparing project...
webpack is watching the files...
asset vendor.js 6.01 MiB [compared for emit] (name: vendor) (id hint: defaultVendor)
asset bundle.js 330 KiB [compared for emit] (name: bundle)
asset runtime.js 86.8 KiB [compared for emit] (name: runtime)
asset tns_modules/inspector_modules.js 1.25 KiB [compared for emit] (name: tns_modules/inspector_modules)
Entrypoint bundle 6.42 MiB = runtime.js 86.8 KiB vendor.js 6.01 MiB bundle.js 330 KiB
Entrypoint tns_modules/inspector_modules 6.1 MiB = runtime.js 86.8 KiB vendor.js 6.01 MiB tns_modules/inspector_modules.js 1.25 KiB
runtime modules 24.8 KiB 12 modules
orphan modules 356 bytes [orphan] 6 modules
modules by path ./node_modules/@nativescript/core/ 1.55 MiB 166 modules
modules by path ./node_modules/css-tree/ 317 KiB 109 modules
modules by path ./node_modules/source-map/lib/*.js 36.3 KiB 6 modules
modules by path ./node_modules/reduce-css-calc/dist/ 131 KiB 5 modules
modules by path ./node_modules/postcss-value-parser/lib/*.js 11.8 KiB 5 modules
modules by path ./node_modules/mdn-data/css/*.json 242 KiB 3 modules
modules by path ./app/ 122 KiB
  ./app/app.ts 3.36 KiB [built] [code generated]
  ./app/app.css 118 KiB [built] [code generated]
./node_modules/tslib/tslib.es6.js 10.5 KiB [built] [code generated]
external "~/package.json" 42 bytes [optional] [built] [code generated]
./node_modules/css-unit-converter/index.js 2.57 KiB [built] [code generated]
webpack 5.50.0 compiled successfully in 3324 ms
Webpack compilation complete. Watching for file changes.
Issues checking in progress...
Updating runtime package.json with configuration values...
Project successfully prepared (ios)
File change detected. Starting incremental webpack compilation...
assets by status 6.42 MiB [cached] 4 assets
Entrypoint bundle 6.42 MiB = runtime.js 86.8 KiB vendor.js 6.01 MiB bundle.js 330 KiB
Entrypoint tns_modules/inspector_modules 6.1 MiB = runtime.js 86.8 KiB vendor.js 6.01 MiB tns_modules/inspector_modules.js 1.25 KiB
cached modules 2.4 MiB (javascript) 24.8 KiB (runtime) [cached] 344 modules
webpack 5.50.0 compiled successfully in 196 ms
Webpack compilation complete. Watching for file changes.
Issues checking in progress...
Successfully transferred bundle.js on device 001DCBEA-431D-4731-AC54-15872B3B821B.
Successfully transferred package.json on device 001DCBEA-431D-4731-AC54-15872B3B821B.
Successfully transferred runtime.js on device 001DCBEA-431D-4731-AC54-15872B3B821B.
Successfully transferred tns_modules on device 001DCBEA-431D-4731-AC54-15872B3B821B.
Successfully transferred inspector_modules.js on device 001DCBEA-431D-4731-AC54-15872B3B821B.
Successfully transferred vendor.js on device 001DCBEA-431D-4731-AC54-15872B3B821B.
Restarting application on device 001DCBEA-431D-4731-AC54-15872B3B821B...
No issues found.
CONSOLE LOG: Loading inspector modules...
CONSOLE LOG: Finished loading inspector modules.
(RunningBoardServices) [com.apple.runningboard:connection] Identity resolved as application<org.nativescript.HelloWorld>
***** Fatal JavaScript exception - application has been terminated. *****
NativeScript encountered a fatal error: Uncaught Error: Failed to load component from module: app-root
at
loadInternal(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/ui/builder/index.js:104:0)
at createViewFromEntry(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/ui/builder/index.js:36:0)
at createRootView(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/application/index.ios.js:317:23)
at setWindowContent(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/application/index.ios.js:258:0)
at notifyAppStarted(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/application/index.ios.js:169:0)
at didFinishLaunchingWithOptions(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/application/index.ios.js:152:0)
at NotificationObserver.onReceive(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/application/index.ios.js:42:0)
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Uncaught Error: Failed to load component from module: app-root
at
loadInternal(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/ui/builder/index.js:104:0)
at createViewFromEntry(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/ui/builder/index.js:36:0)
at createRootView(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/application/index.ios.js:317:23)
at setWindowContent(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/application/index.ios.js:258:0)
at notifyAppStarted(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/application/index.ios.js:169:0)
at didFinishLaunchingWithOptions(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/application/index.ios.js:152:0)
at NotificationObserver.onReceive(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript/core/application/index.ios.js:42:0)
', reason: '(null)'
*** First throw call stack:
(
0   CoreFoundation                      0x00007fff20422fba __exceptionPreprocess + 242
1   libobjc.A.dylib                     0x00007fff20193ff5 objc_exception_throw + 48
2   NativeScript                        0x000000010816f914 _ZN3tns21NativeScriptException15OnUncaughtErrorEN2v85LocalINS1_7MessageEEENS2_INS1_5ValueEEE + 914
3   NativeScript                        0x00000001085cff65 _ZN2v88internal14MessageHandle<…>
~~~

**Comment by rigor789** [comment]
@maziac please push that project to a GitHub repo, seems something isn't quite right. You shouldn't need `nativescript-vue` nor `nativescript-vue-template-compiler` if you are not using Vue, and from the logs, seems like this is a ts project (`@nativescript/template-hello-world-ts`).

**Comment by maziac** [comment]
Seems the problem is gone now.
I did create a complete  new HelloWorld app with

~~~
ns create HelloWorld --template @nativescript/template-hello-world-ts
~~~

and then did a 

~~~
ns build ios 
ns run ios  
~~~

and it build and run without an error.

I guess the problem was that I uses tns instead of ns in the beginning.

Many thanks for your help.
