### ISSUE TITLE
gradlew Execution failed for task ':app:mergeDebugResources'. error=2, No such file or directory

### ISSUE THREAD

**Issue by Erudition** [NativeScript/nativescript-cli#5615]
### Issue Description

When I do `ns build android`, I get pretty far through the build until it crashes with this:

```shell
Execution failed for task ':app:mergeDebugResources'.
error=2, No such file or directory

72 actionable tasks: 2 executed, 70 up-to-date
Error: Command ./gradlew failed with exit code 1
    at Errors.failWithOptions (/home/adroit/Projects/Minder/node_modules/nativescript/lib/common/errors.js:157:27)
    at Errors.fail (/home/adroit/Projects/Minder/node_modules/nativescript/lib/common/errors.js:130:21)
    at GradleCommandService.<anonymous> (/home/adroit/Projects/Minder/node_modules/nativescript/lib/services/android/gradle-command-service.js:40:30)
    at Generator.throw (<anonymous>)
    at rejected (/home/adroit/Projects/Minder/node_modules/nativescript/lib/services/android/gradle-command-service.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

I've been debugging all day to get my environment right (I'm on Guix, so the pure environment doesn't have everything all the nativescript binaries might expect) but this one I have just not been able to get past.

The error message is cryptic, and the log output, even on level "trace" doesn't seem to show anything interesting.

Somehow, this gradle task just fails, and some file is not found.

### Reproduction

clone https://github.com/Erudition/Minder and `ns build android`

### Relevant log output (if applicable)

```shell
2022-01-07T22:58:33.665-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Snapshot inputs and outputs before executing task ':app:mergeDebugResources''
2022-01-07T22:58:33.665-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Snapshot inputs and outputs before executing task ':app:mergeDebugResources'' completed
2022-01-07T22:58:33.665-0600 [INFO] [org.gradle.internal.execution.steps.ResolveCachingStateStep] Caching disabled for task ':app:mergeDebugResources' because:
  Build cache is disabled
2022-01-07T22:58:33.665-0600 [DEBUG] [org.gradle.internal.execution.steps.SkipUpToDateStep] Determining if task ':app:mergeDebugResources' is up-to-date
2022-01-07T22:58:33.665-0600 [INFO] [org.gradle.internal.execution.steps.SkipUpToDateStep] Task ':app:mergeDebugResources' is not up-to-date because:
  Task has failed previously.
2022-01-07T22:58:33.665-0600 [DEBUG] [org.gradle.internal.execution.steps.CreateOutputsStep] Ensuring directory exists for property blameLogFolder at /home/adroit/Projects/Minder/platforms/android/app/build/intermediates/blame/res/debug
2022-01-07T22:58:33.665-0600 [DEBUG] [org.gradle.internal.execution.steps.CreateOutputsStep] Ensuring directory exists for property dataBindingLayoutInfoOutFolder at /home/adroit/Projects/Minder/platforms/android/app/build/intermediates/data_binding_layout_info_type_merge/debug/out
2022-01-07T22:58:33.665-0600 [DEBUG] [org.gradle.internal.execution.steps.CreateOutputsStep] Ensuring directory exists for property incrementalFolder at /home/adroit/Projects/Minder/platforms/android/app/build/intermediates/incremental/mergeDebugResources
2022-01-07T22:58:33.665-0600 [DEBUG] [org.gradle.internal.execution.steps.CreateOutputsStep] Ensuring directory exists for property outputDir at /home/adroit/Projects/Minder/platforms/android/app/build/intermediates/res/merged/debug
2022-01-07T22:58:33.665-0600 [INFO] [org.gradle.internal.execution.steps.ResolveInputChangesStep] The input changes require a full rebuild for incremental task ':app:mergeDebugResources'.
2022-01-07T22:58:33.666-0600 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':app:mergeDebugResources'.
2022-01-07T22:58:33.666-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Execute taskAction$gradle for :app:mergeDebugResources' started
2022-01-07T22:58:33.666-0600 [INFO] [org.gradle.api.Project] Unable do incremental execution: full task run
2022-01-07T22:58:33.666-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Resolve files of :app:debugRuntimeClasspath' started
2022-01-07T22:58:33.666-0600 [INFO] [org.gradle.api.internal.file.collections.DirectoryFileTree] file or directory '/home/adroit/Projects/Minder/customized-node-modules/nativescript-crypto/platforms/android', not found
2022-01-07T22:58:33.666-0600 [INFO] [org.gradle.api.internal.file.collections.DirectoryFileTree] file or directory '/home/adroit/Projects/Minder/node_modules/nativescript-dom-free/platforms/android', not found
2022-01-07T22:58:33.666-0600 [INFO] [org.gradle.api.internal.file.collections.DirectoryFileTree] file or directory '/home/adroit/Projects/Minder/node_modules/nativescript-nodeify/platforms/android', not found
2022-01-07T22:58:33.666-0600 [INFO] [org.gradle.api.internal.file.collections.DirectoryFileTree] file or directory '/home/adroit/Projects/Minder/node_modules/nativescript-randombytes/platforms/android', not found
2022-01-07T22:58:33.666-0600 [INFO] [org.gradle.api.internal.file.collections.DirectoryFileTree] file or directory '/home/adroit/Projects/Minder/node_modules/nativescript-theme-core/platforms/android', not found
2022-01-07T22:58:33.666-0600 [INFO] [org.gradle.api.internal.file.collections.DirectoryFileTree] file or directory '/home/adroit/Projects/Minder/node_modules/nativescript-toasty/platforms/android', not found
2022-01-07T22:58:33.666-0600 [INFO] [org.gradle.api.internal.file.collections.DirectoryFileTree] file or directory '/home/adroit/Projects/Minder/node_modules/nativescript-urlhandler/platforms/android', not found
2022-01-07T22:58:33.666-0600 [INFO] [org.gradle.api.internal.file.collections.DirectoryFileTree] file or directory '/home/adroit/Projects/Minder/node_modules/nativescript-node/platforms/android', not found
2022-01-07T22:58:33.666-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Resolve files of :app:debugRuntimeClasspath'
2022-01-07T22:58:33.666-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Resolve files of :app:debugRuntimeClasspath' completed
2022-01-07T22:58:33.668-0600 [DEBUG] [org.gradle.internal.component.model.LoggingAttributeMatchingExplanationBuilder] Candidate com.android.tools.build:aapt2:3.6.4-6197926 doesn't match attributes {artifactType=_internal-android-aapt2-binary}
2022-01-07T22:58:33.668-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Resolve files of :app:_internal_aapt2_binary' started
2022-01-07T22:58:33.668-0600 [INFO] [org.gradle.api.internal.artifacts.transform.TransformationStep] Transforming artifact aapt2-3.6.4-6197926-linux.jar (com.android.tools.build:aapt2:3.6.4-6197926) with Aapt2Extractor
2022-01-07T22:58:33.668-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Resolve files of :app:_internal_aapt2_binary'
2022-01-07T22:58:33.668-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Resolve files of :app:_internal_aapt2_binary' completed
2022-01-07T22:58:33.829-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'com.android.build.gradle.internal.tasks.Workers$ActionFacade' started
2022-01-07T22:58:33.830-0600 [INFO] [com.android.build.gradle.internal.dependency.AarResourcesCompilerTransform$Inject1] AAPT2 aapt2-3.6.4-6197926-linux Daemon #10: starting
2022-01-07T22:58:33.831-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'com.android.build.gradle.internal.tasks.Workers$ActionFacade' started
2022-01-07T22:58:33.831-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'com.android.build.gradle.internal.tasks.Workers$ActionFacade'
2022-01-07T22:58:33.832-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'com.android.build.gradle.internal.tasks.Workers$ActionFacade' started
2022-01-07T22:58:33.832-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'com.android.build.gradle.internal.tasks.Workers$ActionFacade' started
2022-01-07T22:58:33.832-0600 [INFO] [com.android.build.gradle.internal.dependency.AarResourcesCompilerTransform$Inject1] AAPT2 aapt2-3.6.4-6197926-linux Daemon #11: starting
2022-01-07T22:58:33.832-0600 [INFO] [com.android.build.gradle.internal.dependency.AarResourcesCompilerTransform$Inject1] AAPT2 aapt2-3.6.4-6197926-linux Daemon #12: starting
2022-01-07T22:58:33.833-0600 [INFO] [com.android.build.gradle.internal.dependency.AarResourcesCompilerTransform$Inject1] AAPT2 aapt2-3.6.4-6197926-linux Daemon #13: starting
2022-01-07T22:58:33.833-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'com.android.build.gradle.internal.tasks.Workers$ActionFacade' started
2022-01-07T22:58:33.834-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'com.android.build.gradle.internal.tasks.Workers$ActionFacade'
2022-01-07T22:58:33.834-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'com.android.build.gradle.internal.tasks.Workers$ActionFacade'
2022-01-07T22:58:33.834-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'com.android.build.gradle.internal.tasks.Workers$ActionFacade'
2022-01-07T22:58:33.834-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'com.android.build.gradle.internal.tasks.Workers$ActionFacade' started
2022-01-07T22:58:33.835-0600 [INFO] [com.android.build.gradle.internal.dependency.AarResourcesCompilerTransform$Inject1] AAPT2 aapt2-3.6.4-6197926-linux Daemon #14: starting
2022-01-07T22:58:33.835-0600 [INFO] [com.android.build.gradle.internal.dependency.AarResourcesCompilerTransform$Inject1] AAPT2 aapt2-3.6.4-6197926-linux Daemon #15: starting
2022-01-07T22:58:33.835-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'com.android.build.gradle.internal.tasks.Workers$ActionFacade' started
2022-01-07T22:58:33.835-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'com.android.build.gradle.internal.tasks.Workers$ActionFacade'
2022-01-07T22:58:33.836-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'com.android.build.gradle.internal.tasks.Workers$ActionFacade'
2022-01-07T22:58:33.836-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'com.android.build.gradle.internal.tasks.Workers$ActionFacade' started
2022-01-07T22:58:33.836-0600 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker for ':' Thread 11: released lock on :
2022-01-07T22:58:33.836-0600 [INFO] [com.android.build.gradle.internal.dependency.AarResourcesCompilerTransform$Inject1] AAPT2 aapt2-3.6.4-6197926-linux Daemon #16: starting
2022-01-07T22:58:33.836-0600 [INFO] [com.android.build.gradle.internal.dependency.AarResourcesCompilerTransform$Inject1] AAPT2 aapt2-3.6.4-6197926-linux Daemon #17: starting
2022-01-07T22:58:33.837-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'com.android.build.gradle.internal.tasks.Workers$ActionFacade'
2022-01-07T22:58:33.837-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'com.android.build.gradle.internal.tasks.Workers$ActionFacade'
2022-01-07T22:58:33.856-0600 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker for ':' Thread 11: acquired lock on :
2022-01-07T22:58:33.856-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Execute taskAction$gradle for :app:mergeDebugResources'
2022-01-07T22:58:33.857-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Execute taskAction$gradle for :app:mergeDebugResources' completed
2022-01-07T22:58:33.857-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Snapshot outputs after executing task ':app:mergeDebugResources'' started
2022-01-07T22:58:33.857-0600 [DEBUG] [org.gradle.api.internal.tasks.execution.DefaultTaskSnapshotter] Snapshotting property blameLogFolder (Output) for task ':app:mergeDebugResources'
2022-01-07T22:58:33.863-0600 [DEBUG] [org.gradle.api.internal.tasks.execution.DefaultTaskSnapshotter] Snapshotting property dataBindingLayoutInfoOutFolder (Output) for task ':app:mergeDebugResources'
2022-01-07T22:58:33.863-0600 [DEBUG] [org.gradle.api.internal.tasks.execution.DefaultTaskSnapshotter] Snapshotting property incrementalFolder (Output) for task ':app:mergeDebugResources'
2022-01-07T22:58:33.871-0600 [DEBUG] [org.gradle.api.internal.tasks.execution.DefaultTaskSnapshotter] Snapshotting property outputDir (Output) for task ':app:mergeDebugResources'
2022-01-07T22:58:33.871-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Snapshot outputs after executing task ':app:mergeDebugResources''
2022-01-07T22:58:33.871-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Snapshot outputs after executing task ':app:mergeDebugResources'' completed
2022-01-07T22:58:33.872-0600 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter] Removed task artifact state for task ':app:mergeDebugResources' from context.
2022-01-07T22:58:33.872-0600 [INFO] [com.android.build.gradle.internal.profile.RecordingBuildListener] Task :app:mergeDebugResources in app Finished
2022-01-07T22:58:33.872-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Task :app:mergeDebugResources'
2022-01-07T22:58:33.872-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Task :app:mergeDebugResources' completed
2022-01-07T22:58:33.872-0600 [INFO] [org.gradle.execution.plan.DefaultPlanExecutor] :app:mergeDebugResources (Thread[Execution worker for ':' Thread 11,5,main]) completed. Took 0.212 secs.
2022-01-07T22:58:33.872-0600 [DEBUG] [org.gradle.execution.plan.DefaultExecutionPlan] Node :app:mergeDebugResources failed
```

### Environment

```yaml
OS: Linux 5.14 undefined *(Guix)
CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
Shell: /gnu/store/87kif0bpf0anwbsaw0jvg8fyciw4sz67-bash-5.0.16/bin/bash
node: 14.16.0
npm: 6.14.11
nativescript: Not Found *(run locally from node_modules/.bin)

# android
java: 14.0.2
ndk: Not Found
apis: 28, 32
build_tools: 30.0.3, 32.0.0
system_images: 
  - android-28 | Google APIs Intel x86 Atom
  - android-28 | Google Play Intel x86 Atom

# ios
xcode: Not Found
cocoapods: Not Found
python: Not Found
python3: Not Found
ruby: Not Found
platforms: Not Found
```

### Dependencies

```json
"dependencies": {
  "@ionic/pwa-elements": "^1.3.0",
  "@nativescript/core": "~8.1.5",
  "assert": "^2.0.0",
  "ava": "^3.15.0",
  "browserify-zlib": "^0.2.0",
  "bufferutil": "^4.0.6",
  "circular-dependency-plugin": "^5.2.2",
  "console-browserify": "^1.2.0",
  "constants-browserify": "^1.0.0",
  "crypto-browserify": "^3.12.0",
  "events": "^3.3.0",
  "fastq": "^1.13.0",
  "https-browserify": "^1.0.0",
  "inherits": "^2.0.4",
  "iso-url": "^1.2.1",
  "libp2p": "^0.33.0",
  "libp2p-mdns": "^0.17.0",
  "libp2p-mplex": "^0.10.5",
  "libp2p-noise": "^4.0.0",
  "libp2p-tcp": "^0.17.2",
  "libp2p-webrtc-star": "^0.24.1",
  "libp2p-websockets": "^0.16.2",
  "multiaddr": "^10.0.1",
  "nativescript": "^8.1.5",
  "nativescript-crypto": "file:customized-node-modules/nativescript-crypto",
  "nativescript-dom-free": "^2.0.6",
  "nativescript-local-notifications": "file:customized-node-modules/nativescript-local-notifications/publish/package/nativescript-local-notifications-4.1.0.tgz",
  "nativescript-nodeify": "^0.8.0",
  "nativescript-randombytes": "^1.0.0",
  "nativescript-theme-core": "^1.0.6",
  "nativescript-toasty": "^2.0.1",
  "nativescript-urlhandler": "^1.3.0",
  "nativescript-wear-os": "^3.0.0",
  "node-http-xhr": "^1.3.4",
  "os-browserify": "^0.3.0",
  "path-browserify": "^1.0.1",
  "readable-stream": "^3.6.0",
  "sirv": "^1.0.19",
  "stream-browserify": "^3.0.0",
  "stream-http": "^3.2.0",
  "tape": "^5.4.0",
  "timers-browserify": "^2.0.12",
  "tty-browserify": "0.0.1",
  "utf-8-validate": "^5.0.8",
  "util": "^0.12.4",
  "vm-browserify": "^1.1.2",
  "whatwg-url": "^11.0.0",
  "xmldom": "^0.6.0"
},
"devDependencies": {
  "@nativescript/android": "8.1.1",
  "@nativescript/ios": "~8.1.0",
  "@nativescript/webpack": "~5.0.0",
  "elm-live": "^4.0.2",
  "elm-tooling": "^1.7.0"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/nativescript-cli/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by Erudition** [comment]
I still think this is a poor error message, and the details should be propagated, since there's no clue as to what file was trying to be accessed when encountering "No such file or directory". 

However, I wrote a script to run every executable file in ~/.gradle and patched all that gave that error (which is also a terrible error but it means the interpreter isn't found) to circumvent the issue. Unfortunately the gradle cache is rewritten every build. But still, the build succeeds now.
