### ISSUE TITLE
Fails to compile using JSC runtime on macOS 12.3

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/nativescript-cli#5658]
### Issue Description

The new CLI fails to compile a Hello World app using the JSC runtime

### Reproduction

1. tns create test-jsc
2. cd test-jsc
3. tns platform add ios@6.5.4
4. tns run ios

### Relevant log output (if applicable)

```shell
Updating runtime package.json with configuration values...
Project successfully prepared (ios)
Building project...
Xcode build...
2022-03-28 19:32:56.824 xcodebuild[3960:2389019] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-03-28 19:32:56.824 xcodebuild[3960:2389019] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
./.build_env_vars.sh: line 458: declare: UID: readonly variable
NSLD: Swift bridging header '*-Swift.h' not found under '/Users/peter/Library/Developer/Xcode/DerivedData/testjsc-aoupiijtimmxlacpjqcshdkkakwx/Build/Intermediates.noindex/testjsc.build/Debug-iphonesimulator/testjsc.build/Objects-normal/x86_64'
Generating metadata...~/Projects/test-jsc/platforms/ios/internal/metadata-generator/bin ~/Projects/test-jsc/platforms/ios
Python version: 2.7.18 (default, Mar 28 2022, 15:44:06) 
[GCC Apple LLVM 13.1.6 (clang-1316.0.21.2)]
Traceback (most recent call last):
  File "./build-step-metadata-generator.py", line 41, in <module>
    deployment_target_flag_name = env("DEPLOYMENT_TARGET_CLANG_FLAG_NAME")
  File "./build-step-metadata-generator.py", line 14, in env
    return os.environ[env_name]
  File "/Users/peter/.pyenv/versions/2.7.18/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'DEPLOYMENT_TARGET_CLANG_FLAG_NAME'
Command Ld failed with a nonzero exit code
note: Using new build system
note: Using codesigning identity override: 
note: Planning
note: Build preparation complete
note: Building targets in dependency order
** BUILD FAILED **
```

### Environment

```yaml
OS: macOS 12.3
CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
Shell: /bin/zsh
node: 14.16.0
npm: 8.5.4
nativescript: 8.2.3

# android
java: 1.8.0_282
ndk: Not Found
apis: 28, 29, 30, 31
build_tools: 28.0.3, 30.0.3
system_images: 
  - android-28 | Google Play Intel x86 Atom_64
  - android-30 | Google APIs Intel x86 Atom
  - android-30 | Google Play Intel x86 Atom
  - android-31 | Google Play Intel x86 Atom_64

# ios
xcode: 13.3/13E113
cocoapods: 1.11.3
python: 2.7.18
python3: 3.8.9
ruby: 2.7.5
platforms: 
  - DriverKit 21.4
  - iOS 15.4
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "~8.2.0",
  "@nativescript/theme": "~3.0.2"
},
"devDependencies": {
  "@nativescript/ios": "6.5.4",
  "@nativescript/types": "~8.2.0",
  "@nativescript/webpack": "~5.0.6",
  "typescript": "~4.5.5"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/nativescript-cli/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
Tracked in https://github.com/NativeScript/NativeScript/issues/9840
