### ISSUE TITLE
Android build error on windows with postcss-loader

### ISSUE THREAD

**Issue by rudaz-bp** [NativeScript/nativescript-cli#5720]
### Issue Description

For about 2 hours, i cannot no more run/build my nativescript application on Windows and getting de below error while using "ns run" or "ns build android" . This morning it works well and I did not change anything. It looks like there is an issue with postcss-loarder. On macos it is still possible to build the application, but it failed on Windows.

I try running ns clean and run again but sill have the same error.

Below the content of my app.android.css
`// Import common styles
@import "app-common";

// Place any CSS rules you want to apply only on Android here
`

Thank you for your help

### Reproduction

ns run --device {devicename}
tns build android --release ****

### Relevant log output (if applicable)

```shell
webpack is watching the files...
resolving "./app.scss" to "./app.android.scss"
assets by path *.js 7.8 MiB
  asset vendor.js 6.7 MiB [emitted] (name: vendor) (id hint: defaultVendor)
  asset bundle.js 1.01 MiB [emitted] (name: bundle)
  asset runtime.js 87.9 KiB [emitted] (name: runtime)
assets by path fonts/*.ttf 374 KiB
  asset fonts/fa-solid-900.ttf 204 KiB [emitted] [from: app/fonts/fa-solid-900.ttf] [copied]
  asset fonts/fa-brands-400.ttf 131 KiB [emitted] [from: app/fonts/fa-brands-400.ttf] [copied]
  asset fonts/fa-regular-400.ttf 39.1 KiB [emitted] [from: app/fonts/fa-regular-400.ttf] [copied]
Entrypoint bundle 7.8 MiB = runtime.js 87.9 KiB vendor.js 6.7 MiB bundle.js 1.01 MiB
runtime modules 25 KiB 12 modules
orphan modules 25.4 KiB [orphan] 8 modules
modules by path ./node_modules/ 2.53 MiB 352 modules
modules by path ./app/ 278 KiB
  optional modules 212 KiB [optional] 42 modules
  + 23 modules
external "~/package.json" 42 bytes [optional] [built] [code generated]

ERROR in ./app/app.android.scss
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
E:\Projects\inotest\node_modules\postcss-loader\node_modules\cosmiconfig\dist\index.js:63
  const config = metaConfig.config ?? {};
                                    ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (E:\Projects\inotest\node_modules\postcss-loader\dist\utils.js:18:20)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (E:\Projects\inotest\node_modules\postcss-loader\dist\index.js:12:14)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
 @ ./app/ sync \.(xml%7Cjs%7C(?<%21\.d\.)ts%7Cs?css)$ ./app.android.scss ./app.scss
 @ ./node_modules/@nativescript/webpack/dist/stubs/virtual-entry-typescript.js 3:16-103

webpack 5.76.2 compiled with 1 error in 6542 ms
Webpack compilation complete. Watching for file changes.
No errors found.
```

### Environment

```yaml
OS: Windows 10 10.0.19045
CPU: (8) x64 Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz
Shell: Not Found
node: 12.18.3
npm: 6.14.6
nativescript: Not Found

# android
java: Not Found
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: Not Found
cocoapods: Not Found
python: 3.7.2
python3: Not Found
ruby: Not Found
platforms: Not Found
```

### Dependencies

```json
"dependencies": {
  "@nativescript-community/ui-document-picker": "^1.1.12",
  "@nativescript-community/ui-material-bottom-navigation": "^7.0.40",
  "@nativescript-community/ui-material-tabs": "^7.0.40",
  "@nativescript/background-http": "^6.0.0",
  "@nativescript/camera": "^5.0.15",
  "@nativescript/core": "^8.4.7",
  "@nativescript/geolocation": "^8.1.0",
  "@nativescript/imagepicker": "^1.0.9",
  "@nativescript/localize": "^5.0.4",
  "@nativescript/theme": "^3.0.2",
  "nativescript-barcodescanner": "^4.1.2",
  "nativescript-exit": "^1.0.1"
},
"devDependencies": {
  "@nativescript/android": "8.4.0",
  "@nativescript/ios": "~8.4.0",
  "@nativescript/webpack": "~5.0.0",
  "sass": "~1.49.9",
  "tslint": "~6.1.3",
  "typescript": "~4.8.4"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/nativescript-cli/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rudaz-bp** [comment]
Hello everybody.

I notice that i was using an old version of nodejs. Updating nodejs to the latest version solve my issue.

Kind regards
