### ISSUE TITLE
Can't install nativescript-cli on ubuntu 15.04

### ISSUE THREAD

**Issue by oren** [NativeScript/nativescript-cli#833]
```
sudo apt-get install lib32bz2-1.0
E: Unable to locate package lib32bz2-1.0
E: Couldn't find any package by regex 'lib32bz2-1.0'
```

**Comment by teobugslayer** [comment]
Hi @oren,
What os are you using?

**Comment by oren** [comment]
Ubuntu 15.04

**Comment by teobugslayer** [comment]
I am on my phone and cannot check things up, but can you try simply omit installing this for the time being? I guess most of the command would work. also,  you may try searching for the correct name of this dependency. It existed in 64 bit Ubuntu and xubuntu last time I checked but it could have changed in the mean time.

**Comment by oren** [comment]
I will do that tomorrow. Thank you!

**Comment by oren** [comment]
I googled and found this solution but it didn't help:
```
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install libbz2-1.0:i386
```

```
sudo npm install nativescript -g --unsafe-perm

npm WARN deprecated byline@4.1.1: critical bug fixed in v4.2.0
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
 
> utf-8-validate@1.0.1 install /usr/lib/node_modules/nativescript/node_modules/utf-8-validate
> node ./build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
make: Entering directory '/usr/lib/node_modules/nativescript/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/usr/lib/node_modules/nativescript/node_modules/utf-8-validate/build'
Installed in `/usr/lib/node_modules/nativescript/node_modules/utf-8-validate/bin/linux-x64-v8-4.2/validation.node`
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
npm WARN excluding symbolic link docs/assets/ir_black.css -> ../../node_modules/highlight.js/src/styles/ir_black.css
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"2.5.0","npm":"2.13.2"})
 
> bufferutil@1.0.1 install /usr/lib/node_modules/nativescript/node_modules/bufferutil
> node ./build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
make: Entering directory '/usr/lib/node_modules/nativescript/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory '/usr/lib/node_modules/nativescript/node_modules/bufferutil/build'
Installed in `/usr/lib/node_modules/nativescript/node_modules/bufferutil/bin/linux-x64-v8-4.2/bufferutil.node`
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Resources -> Versions/Current/Resources
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Test Framework -> Versions/Current/Test Framework
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Versions/Current -> A
npm WARN excluding symbolic link docs/assets/ir_black.css -> ../../node_modules/highlight.js/src/styles/ir_black.css

> fibers@1.0.5 install /usr/lib/node_modules/nativescript/node_modules/fibers
> node ./build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
make: Entering directory '/usr/lib/node_modules/nativescript/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc: In function ‘v8::Handle<v8::Signature> uni::NewSignature(v8::Isolate*, v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)’:
../src/fibers.cc:132:54: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*&, v8::Handle<v8::FunctionTemplate>&, int&, v8::Handle<v8::FunctionTemplate>*&)’
   return Signature::New(isolate, receiver, argc, argv);
                                                      ^
../src/fibers.cc:132:54: note: candidate is:
In file included from /home/oren/.node-gyp/2.5.0/src/node.h:42:0,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/oren/.node-gyp/2.5.0/deps/v8/include/v8.h:4188:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/home/oren/.node-gyp/2.5.0/deps/v8/include/v8.h:4188:27: note:   candidate expects 2 arguments, 4 provided
../src/fibers.cc: In function ‘void uni::SetResourceConstraints(v8::Isolate*, v8::ResourceConstraints*)’:
../src/fibers.cc:140:3: error: ‘SetResourceConstraints’ is not a member of ‘v8’
   v8::SetResourceConstraints(isolate, constraints);
   ^
../src/fibers.cc:140:3: note: suggested alternative:
../src/fibers.cc:139:7: note:   ‘uni::SetResourceConstraints’
  void SetResourceConstraints(Isolate* isolate, ResourceConstraints* constraints) {
       ^
../src/fibers.cc: In function ‘v8::Handle<v8::Signature> uni::NewSignature(v8::Isolate*, v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)’:
../src/fibers.cc:133:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
fibers.target.mk:95: recipe for target 'Release/obj.target/fibers/src/fibers.o' failed
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory '/usr/lib/node_modules/nativescript/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-15-generic
gyp ERR! command "/usr/bin/iojs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /usr/lib/node_modules/nativescript/node_modules/fibers
gyp ERR! node -v v2.5.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
Build failed
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Resources -> Versions/Current/Resources
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Test Framework -> Versions/Current/Test Framework
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Versions/Current -> A
 
> ref@0.3.5 install /usr/lib/node_modules/nativescript/node_modules/ref
> node ./build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
make: Entering directory '/usr/lib/node_modules/nativescript/node_modules/ref/build'
  CXX(target) Release/obj.target/binding/src/binding.o
In file included from ../node_modules/nan/nan_new.h:181:0,
                 from ../node_modules/nan/nan.h:74,
                 from ../src/binding.cc:8:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBase<v8::Signature>::return_t NanIntern::Factory<v8::Signature>::New(NanIntern::Factory<v8::Signature>::FTH, int, NanIntern::Factory<v8::Signature>::FTH*)’:
../node_modules/nan/nan_implementation_12_inl.h:172:76: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, NanIntern::Factory<v8::Signature>::FTH&, int&, NanIntern::Factory<v8::Signature>::FTH*&)’
   return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
                                                                            ^
../node_modules/nan/nan_implementation_12_inl.h:172:76: note: candidate is:
In file included from /home/oren/.node-gyp/2.5.0/src/node.h:42:0,
                 from ../src/binding.cc:6:
/home/oren/.node-gyp/2.5.0/deps/v8/include/v8.h:4188:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/home/oren/.node-gyp/2.5.0/deps/v8/include/v8.h:4188:27: note:   candidate expects 2 arguments, 4 provided
binding.target.mk:88: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/usr/lib/node_modules/nativescript/node_modules/ref/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-15-generic
command "/usr/bin/iojs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/nativescript/node_modules/ref
gyp ERR! node -v v2.5.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
Build failed
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
 
> ws@0.4.32 install /usr/lib/node_modules/nativescript/node_modules/node-inspector/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/usr/lib/node_modules/nativescript/node_modules/node-inspector/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
bufferutil.target.mk:90: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: Leaving directory '/usr/lib/node_modules/nativescript/node_modules/node-inspector/node_modules/ws/build'
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
 
> ffi@1.2.7 install /usr/lib/node_modules/nativescript/node_modules/ffi
> node ./build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
make: Entering directory '/usr/lib/node_modules/nativescript/node_modules/ffi/build'
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
../deps/libffi/src/closures.c: In function ‘dlmmap_locked’:
../deps/libffi/src/closures.c:421:7: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
       ftruncate (execfd, offset);
       ^
../deps/libffi/src/closures.c:433:7: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
       ftruncate (execfd, offset);
       ^
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
../deps/libffi/src/x86/ffi64.c: In function ‘classify_argument’:
../deps/libffi/src/x86/ffi64.c:181:18: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
    FFI_ASSERT (0);
                  ^
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/unix64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/sysv.o
  AR(target) Release/obj.target/deps/libffi/libffi.a
  COPY Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
In file included from ../src/ffi.cc:3:0:
../src/ffi.h:3:0: warning: "__STDC_LIMIT_MACROS" redefined
 #define __STDC_LIMIT_MACROS true
 ^
In file included from /home/oren/.node-gyp/2.5.0/deps/v8/include/v8.h:19:0,
                 from /home/oren/.node-gyp/2.5.0/src/node.h:42,
                 from ../src/ffi.cc:1:
/usr/lib/gcc/x86_64-linux-gnu/4.9/include/stdint.h:5:0: note: this is the location of the previous definition
 #  define __STDC_LIMIT_MACROS
 ^
../src/ffi.cc: In static member function ‘static void FFI::FinishAsyncFFICall(uv_work_t*)’:
../src/ffi.cc:387:29: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/oren/.node-gyp/2.5.0/src/node.h:282): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
     FatalException(try_catch);
                             ^
  CXX(target) Release/obj.target/ffi_bindings/src/callback_info.o
In file included from ../src/callback_info.cc:8:0:
../src/ffi.h:3:0: warning: "__STDC_LIMIT_MACROS" redefined
 #define __STDC_LIMIT_MACROS true
 ^
In file included from /home/oren/.node-gyp/2.5.0/deps/v8/include/v8.h:19:0,
                 from /home/oren/.node-gyp/2.5.0/src/node.h:42,
                 from ../src/callback_info.cc:5:
/usr/lib/gcc/x86_64-linux-gnu/4.9/include/stdint.h:5:0: note: this is the location of the previous definition
 #  define __STDC_LIMIT_MACROS
 ^
../src/callback_info.cc: In static member function ‘static void CallbackInfo::DispatchToV8(callback_info*, void*, void**, bool)’:
../src/callback_info.cc:71:31: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/oren/.node-gyp/2.5.0/src/node.h:282): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
       FatalException(try_catch);
                               ^
In file included from ../src/callback_info.cc:8:0:
../src/callback_info.cc: In static member function ‘static void CallbackInfo::Callback(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/ffi.h:25:72: warning: ‘void NanThrowError(const char*, int)’ is deprecated (declared at ../node_modules/nan/nan.h:741) [-Wdeprecated-declarations]
 #define THROW_ERROR_EXCEPTION_WITH_STATUS_CODE(x, y) NanThrowError(x, y)
                                                                        ^
../src/callback_info.cc:139:12: note: in expansion of macro ‘THROW_ERROR_EXCEPTION_WITH_STATUS_CODE’
     return THROW_ERROR_EXCEPTION_WITH_STATUS_CODE("ffi_prep_closure() Returned Error", status);
            ^
  CXX(target) Release/obj.target/ffi_bindings/src/threaded_callback_invokation.o
In file included from ../src/threaded_callback_invokation.cc:2:0:
../src/ffi.h:3:0: warning: "__STDC_LIMIT_MACROS" redefined
 #define __STDC_LIMIT_MACROS true
 ^
In file included from /home/oren/.node-gyp/2.5.0/deps/v8/include/v8.h:19:0,
                 from /home/oren/.node-gyp/2.5.0/src/node.h:42,
                 from ../src/threaded_callback_invokation.cc:1:
/usr/lib/gcc/x86_64-linux-gnu/4.9/include/stdint.h:5:0: note: this is the location of the previous definition
 #  define __STDC_LIMIT_MACROS
 ^
  SOLINK_MODULE(target) Release/obj.target/ffi_bindings.node
  COPY Release/ffi_bindings.node
make: Leaving directory '/usr/lib/node_modules/nativescript/node_modules/ffi/build'
Installed in `/usr/lib/node_modules/nativescript/node_modules/ffi/bin/linux-x64-v8-4.2/ffi_bindings.node`
npm ERR! Linux 3.19.0-15-generic
npm ERR! argv "/usr/bin/iojs" "/usr/bin/npm" "install" "nativescript" "-g" "--unsafe-perm"
npm ERR! node v2.5.0
npm ERR! npm  v2.13.2
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

> nativescript@1.2.4 preuninstall /usr/lib/node_modules/nativescript
> node preuninstall.js

Failed to complete all pre-uninstall steps. 
{ [Error: Command failed: /bin/sh -c node bin/nativescript.js dev-preuninstall
module.js:338
    throw err;
          ^
Error: Cannot find module 'fibers/future'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/nativescript/lib/common/yok.js:27:14)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c node bin/nativescript.js dev-preuninstall' }

npm ERR! Please include the following file with any support request:
npm ERR!     /home/oren/npm-debug.log
```

**Comment by teobugslayer** [comment]
Hello @oren,

Judging from this message: 
> npm ERR! node v2.5.0

you are using IO.js 2.5. NativeScript CLi does not work with it due to incompatibilities of our C++ dependencies. Consider changing to node.js 0.12 or 0.10. The good news is that we are working on supporting io.js 3.1 and up but I cannot give a time frame in which we will be ready.

**Comment by oren** [comment]
thank you. i'll try downgrading to 0.12.
