### ISSUE TITLE
javac version is not getting properly extracted in case of open jdk systems

### ISSUE THREAD

**Issue by anshulguleria** [NativeScript/nativescript-cli#936]
`tns --version` = 1.3.0

In case of openjdk java `javac -version` command has different output.

```
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
javac 1.8.0_45-internal
```

thus `/^javac (.*)/i` regex won't work.
And it was causing error in `tns doctor` command.

Log for `tns doctor --log trace`:
```
Exec uname -a 
 stdout: Linux developer 3.19.0-28-generic #30-Ubuntu SMP Mon Aug 31 15:52:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
 
 stderr: 
Exec npm -v 
 stdout: 2.11.3
 
 stderr: 
spawn: java -version
Exec ant -version 
 stdout: Apache Ant(TM) version 1.9.4 compiled on January 27 2015
 
 stderr: Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 

Exec node-gyp -v 
 stdout:  
 stderr: /bin/sh: 1: node-gyp: not found

Exec adb version 
 stdout: Android Debug Bridge version 1.0.31
 
 stderr: 
Exec android -h 
 stdout: 
       Usage:
       android [global options] action [action options]
       Global options:
  -s --silent     : Silent mode, shows errors only.
  -v --verbose    : Verbose mode, shows errors, warnings and all messages.
     --clear-cache: Clear the SDK Manager repository manifest cache.
  -h --help       : Help on a specific command.

                                                                    Valid
                                                                    actions
                                                                    are
                                                                    composed
                                                                    of a verb
                                                                    and an
                                                                    optional
                                                                    direct
                                                                    object:
-    sdk              : Displays the SDK Manager window.
-    avd              : Displays the AVD Manager window.
-   list              : Lists existing targets or virtual devices.
-   list avd          : Lists existing Android Virtual Devices.
-   list target       : Lists existing targets.
-   list device       : Lists existing devices.
-   list sdk          : Lists remote SDK repository.
- create avd          : Creates a new Android Virtual Device.
-   move avd          : Moves or renames an Android Virtual Device.
- delete avd          : Deletes an Android Virtual Device.
- update avd          : Updates an Android Virtual Device to match the folders
                        of a new SDK.
- create project      : Creates a new Android project.
- update project      : Updates an Android project (must already have an
                        AndroidManifest.xml).
- create test-project : Creates a new Android project for a test package.
- update test-project : Updates the Android project for a test package (must
                        already have an AndroidManifest.xml).
- create lib-project  : Creates a new Android library project.
- update lib-project  : Updates an Android library project (must already have
                        an AndroidManifest.xml).
- create uitest-project: Creates a new UI test project.
- update adb          : Updates adb to support the USB devices declared in the
                        SDK add-ons.
- update sdk          : Updates the SDK by suggesting new platforms to install
                        if available.
 
 stderr: Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 

Exec mono --version 
 stdout:  
 stderr: /bin/sh: 1: mono: not found

Exec git --version 
 stdout: git version 2.1.4
 
 stderr: 
Exec gradle -v 
 stdout: 
------------------------------------------------------------
Gradle 2.7
------------------------------------------------------------

Build time:   2015-09-14 07:26:16 UTC
Build number: none
Revision:     c41505168da69fb0650f4e31c9e01b50ffc97893

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_45-internal (Oracle Corporation 25.45-b02)
OS:           Linux 3.19.0-28-generic amd64

 
 stderr: Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 

Exec javac -version 
 stdout:  
 stderr: Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
javac 1.8.0_45-internal

TypeError: Cannot read property '1' of null
    at FiberFuture.Future.wait (/home/ban/.nvm/versions/node/v0.12.7/lib/node_modules/nativescript/node_modules/fibers/future.js:535:15)
    at /home/ban/.nvm/versions/node/v0.12.7/lib/node_modules/nativescript/lib/nativescript-cli.js:17:45
    - - - - -
    at SysInfo.getSysInfo (/home/ban/.nvm/versions/node/v0.12.7/lib/node_modules/nativescript/lib/common/sysinfo.js:63:56)
    at /home/ban/.nvm/versions/node/v0.12.7/lib/node_modules/nativescript/lib/common/dispatchers.js:21:46
    at Function.settle (/home/ban/.nvm/versions/node/v0.12.7/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/home/ban/.nvm/versions/node/v0.12.7/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /home/ban/.nvm/versions/node/v0.12.7/lib/node_modules/nativescript/lib/nativescript-cli.js:17:45
```

**Comment by teobugslayer** [comment]
The fix is in master. We must cherry pick it in release for 1.3.1
